huggingface/accelerate

- src/accelerate/big_modeling.py
Fixes https://github.com/huggingface/transformers/issues/24540 and the failing test: https://github.com/huggingface/accelerate/actions/runs/5396594202/jobs/9800396637
Currently on the main branch loading a quantized model on a single GPU fails:
```python
from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer
import torch
model_path="facebook/opt-350m"
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True, load_in_8bit=True, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_path)
input_text = "Describe the solar system."
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("cuda")
outputs = model.generate(input_ids, max_length=100) …
```
> [`BigModeling`] Add missing check for quantized models

- .github/workflows/integration_tests.yml
Transformers removed support for 3.7 today. Until we decide if Accelerate should do something similar, this PR changes the workflow to use 3.8 for the integration tests
> Bump integration python version tests

- src/accelerate/utils/launch.py
Ross gave a wonderful tip:
> You can avoid this if you explicitly specify the rdzv backend with `localhost:0`
So for us, we can tell the user they can specify it to `0`, and the next port will be used.
> Also hint at using the next port directly

- docker/accelerate-cpu/Dockerfile
Bumps the cpu python version of the docker image to 3.8 as well (GPU was already there)
> docker cpu py version

- src/accelerate/big_modeling.py
Fixes a silent bug regarding buffers that are not in the state dict of the model and when using quantized models. Currently the following snippet fails:
```python
from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer
import torch
model_path="ybelkada/gpt2-xl-8bit"
config = AutoConfig.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path, load_in_8bit=True)
tokenizer = AutoTokenizer.from_pretrained(model_path)
input_text = "Describe the solar system."
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("cuda")
outputs = model.generate(input_ids, max_length=10)
print(tokenizer.decode(outputs[0]))
```
With the following error:
```bash
File "/home/younes_huggingface_co/code/transformers/src/transformers/models/gpt2/modeling_gpt2. …
```
> [`BigModeling`] Final fix for dispatch int8 and fp4 models

- src/accelerate/utils/modeling.py
This PR removes the dependency on `safetensors` when people uses the method `save_model` from `Accelerator` even when the attribute `safe_serialization` was set to `False`
> remove safetensor dep on shard_checkpoint

- src/accelerate/accelerator.py
1. DeepSpeed version check wasn't happening before an import which requires versions above or equal to it. 
2. This PR changes the place of such import so that the version error is raised appropriately. 
3. Fixes https://huggingface.slack.com/archives/C02CH2YP4EQ/p1687909933322059
> change the import place to avoid import error

- docs/source/package_reference/accelerator.md
This PR adds the `save_model` method in the `Accelerator` documentation.
> replace save funct in doc

- docs/source/_toctree.yml
- docs/source/usage_guides/big_modeling.md
This PR modifies replaces the example in big model inference documentation so that we use a model that is not from the transformers library. Tested the new example in this [colab](https://colab.research.google.com/drive/1Mj6YOrETdrCzLWjEBjpC-pt1DvquMEW0?usp=sharing).
> Doc big model inference

- src/accelerate/accelerator.py
- src/accelerate/utils/modeling.py
- tests/test_quantization.py
This PR fixes the bnb tests that did not pass the Accelerate nightly single_gpu and multi_gpu test. I added decorators to function that should only be run on multi_gpu. I also fixed the 8-bit serialization tests because of the new version of bnb (check this PR for more [details](https://github.com/huggingface/transformers/pull/24416))
> fix bnb tests

- src/accelerate/utils/modeling.py
This PR fixes a bug introduced in this [PR](https://github.com/huggingface/accelerate/pull/1626). The following test `tests/bnb/test_4bit.py::Bnb4bitTestMultiGpu::test_multi_gpu_loading` in `transformers` library fails because the model is not dispatched on multiple gpus when using` device_map='balanced'.` This behavior happens because I forgot to remove the duplicated class `CustomDtype` (both in dataclass and modeling). Hence, we were not able to get the right size occupied by the 4-bit module in `dtype_byte_size`, resulting in an unbalanced device_map.
> Fix 4bit test

- examples/README.md
This PR updates the readme in exmaples, when using fp16(mixed-precision), we should pass in `--mixed_precision fp16` rather than `--fp16`
If you run `nlp_examle.py` with `--fp16`
```python
python ./nlp_example.py --fp16
```
will get the following error message:
```text
usage: nlp_example.py [-h] [--mixed_precision {no,fp16,bf16,fp8}] [--cpu]
nlp_example.py: error: unrecognized arguments: --fp16
```
@sgugger
> update readme in examples

- .github/workflows/quality.yml
- src/accelerate/accelerator.py
When quality checks fail, provides a clear error in the job summary, as seen here: https://github.com/huggingface/accelerate/actions/runs/5509213335
> Quality check failed. Please ensure the right dependency versions are installed with 'pip install -e .[quality]' and rerun 'make style; make quality;'
Many users have issues with knowing what to do or how to install with it, so this is one solution I have in mind, otherwise go as far as a github bot that points to the different job summaries and their statuses/errors that automatically gets updated each push. As github doesn't just let you go "Details" and automatically see the summary
> Improve quality errors

- docs/source/usage_guides/quantization.md
- src/accelerate/hooks.py
- src/accelerate/utils/bnb.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/modeling.py
- tests/test_quantization.py
This PR makes offload on cpu/disk possible with 8-bit models, thus saving even more memory. Previously, we did not quantize the modules on cpu/disk and the modules weights stayed at full precision. With cpu/disk offlaod, we offload the quantized weight to cpu/disk and move them back to gpu when needed using hooks. This should work out of the box with `device_map="auto"` but we make the user specify `enable_offload=True` to be sure that he knows what he's doing. Furthermore, no modification is needed on `bitsandbytes` library. 
The input weights (`weights_location`) can be quantized or not. If the weights are not quantized, we will first quantize them before offloading them to the cpu/disk. If we don't want to quantize a module, the user should add it in `skip_modules` arg. 
PS: 4-bit …
> Add offload for 8-bit model

- docs/source/usage_guides/tracking.md
Updates the Tracking doc to use `project_dir` instead of the deprecated `logging_dir` parameter as mentioned [here](https://github.com/huggingface/diffusers/pull/3924#issuecomment-1617703691). Let me know if I've interpreted this correctly! 🤗
> [docs] project_dir parameter update

- tests/test_accelerator.py
- tests/test_big_modeling.py
Noticed some tests in Accelerator that fail when bnb isn't available, rather than use the conditional check for if it is when running the slow tests locally
> Skip tests when bnb isn't available

- src/accelerate/accelerator.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_utils.py
- src/accelerate/commands/config/default.py
- src/accelerate/commands/env.py
- src/accelerate/commands/launch.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/launch.py
- src/accelerate/utils/memory.py
- src/accelerate/utils/operations.py
- src/accelerate/utils/random.py
According to the review of the previous PR([see](https://github.com/huggingface/transformers/pull/22644)), if i want to use Ascend NPUs to train 🤗 Transformers models, the support should be added in Accelerate first and then will come in the Trainer for free. 
This PR will support Ascend NPU accelerator：
1. Sample config after running the accelerate config command:
```text
deepspeed_config: {}
distributed_type: multi-NPU
downcast_bf16: 'no'
fsdp_config: {}
main_process_ip: null
main_process_port: null
mixed_precision: 'no'
num_processes: 8
use_cpu: false
```
2. run `nlp_example.py` with NPUs.
```bash
time accelerate launch  nlp_example.py
```
compare with A100
| Device            | …
> Add Ascend NPU accelerator support

- tests/test_quantization.py
This PR adds a decorator to a test that should require multi gpu. Otherwise, it will fail during the nightly single_gpu test.
> Fix bnb test by adding multi_gpu decorator

- docs/source/usage_guides/quantization.md
This PR updates the version of bitsandbytes required for the tutorial since we fixed the [issue](https://github.com/huggingface/accelerate/pull/1679) with the serialization of 8bit model.
> fix bnb version

- src/accelerate/data_loader.py
Second part of a followup from https://github.com/huggingface/accelerate/pull/1709, given a dataloader never really should change its remainder after iterating, the remainder isn't re-set after the end of an `__iter__`, nor is it recalculated *during* an `__iter__`. Instead we check for the default (`-1`), then recalculate.
> Remove duplicate code and check the remainder only once

- docs/source/usage_guides/quantization.md
- src/accelerate/utils/bnb.py
This PR fixes an issue when people quantize transformers model with the quantization api from accelerate and convert them into peft model for training. In order to fix this issue, we need to add the attributes  `model.is_loaded_in_4bit` and `model.is_loaded_in_8bit`. However, as indicated by the docs, the user should use the transformers integration of bnb when using transformers model. I've also updated the training section of the doc. 
related issue #1713
> add compatibility with peft

- src/accelerate/test_utils/scripts/test_script.py
Solves #1722 by changing the test to：
- Properly give us an extra remainder/odd one
Verified on (2, 4, 8)xA100
> fix failing test on 8GPU

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/test_sync.py
This PR is a suggestion for a solution for the following observation regarding torch's DDP behaviour using `no_sync`:
Here’s the example from the docs (uses forward-backward)
```python
ddp = torch.nn.parallel.DistributedDataParallel(model, pg)
with ddp.no_sync():
ddp(input).backward()  # no synchronization, accumulate grads
ddp(another_input).backward()  # synchronize grads
```
Let’s separate forward from backward. It seems like `no_sync` doesn't affect backward(), it must wrap the forward() call instead.
```python
ddp = torch.nn.parallel.DistributedDataParallel(model, pg)
with ddp.no_sync(): # forward under no_sync -> works
loss = ddp(input) 
loss.backward() # no synchronization, accumulate grads
ddp(another_input).backward()  # synchronize grads
```
```python
ddp = …
```
> Better control over DDP's `no_sync`

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
This small PR allow one to use both DP and PP for fast inference of large models on larger nodes.
Here is how this can be done on a 8 GPUs with a model which requires 2 GPUs to be loaded:
- run accelerate with 4 processes => GPU 0, 1, 2, 3 will have a process with DP
- setup max_memory on each process to use the first GPU + a second GPU in the remaining four GPUs (4, 5, 6, 7)
To be able to do that with the current transformers/accelerate we only need to make sure `get_balanced_memory` can handle non contiguous list of GPUs which this PR does.
Here is a working examples of doing DP=4 + PP=2 for Falcon 40B on a node with 8 A100 for instance:
[Not shown: start accelerate on the node with 4 processes - could also with done with 2 process and we'd get DP=2 + PP=4]
```
from accelerate import …
```
> Make balanced memory able to work with non continguous GPUs ids

- src/accelerate/hooks.py
In the __repr__ method of the AlignDevicesHook class, the class name was incorrectly written as "AlignDeviceHook" instead of "AlignDevicesHook". This PR corrects this typo.
Thank you!
> Fixed typo in __repr__ of AlignDevicesHook

- docs/source/package_reference/utilities.md
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/other.py
- tests/test_kwargs_handlers.py
[https://github.com/huggingface/accelerate/blob/653ba110d31c86d3527bb88bf6209441c176ce11/src/accelerate/accelerator.py#L1423-L1427](https://github.com/huggingface/accelerate/blob/653ba110d31c86d3527bb88bf6209441c176ce11/src/accelerate/accelerator.py#L1423-L1427)
Before this patch, `self.state.dynamo_plugin.to_kwargs()` in above code always results in `{}` if torch.compile kwargs are set through environment variables. This behaviour is used by transformers:
[https://github.com/huggingface/transformers/blob/66fd3a8d626a32989f4569260db32785c6cbf42a/src/transformers/training_args.py#L1375-L1382](https://github.com/huggingface/transformers/blob/66fd3a8d626a32989f4569260db32785c6cbf42a/src/transformers/training_args.py#L1375-L1382)
In this patch, we fix it by unset all data in os.environ when …
> fix KwargsHandler.to_kwargs not working with os.environ initialization in __post_init__

- src/accelerate/commands/config/cluster.py
It's possible to end up in a situation following the prompts where `num_machines == 1`, `num_processes == 1`, and `distributed_type == DistributedType.MULTI_GPU` if you select "multi-GPU" to the first question. This PR adds a check and raises the right error if done. Helps https://github.com/huggingface/accelerate/issues/1743
(Don't review until tomorrow 😉 )
> Check for misconfiguration of single node & single GPU

- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/fsdp_utils.py
1. Fixes `load_result` never being passed when using FSDP in Trainer
2. Fixes https://github.com/huggingface/transformers/issues/24874
3. In torch nightlies they have removed the support for `ignored_parameters`, updating the same.
> Fix FSDP related issues

- src/accelerate/accelerator.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/other.py
1. If the model is already an instance of FSDP, bypass the warning and additional FSDP preparation logic. This is to enable PR https://github.com/huggingface/transformers/pull/24980 which Fixes https://github.com/huggingface/transformers/issues/24724
2. allow usage of _no_split_modules to simplify UX when using FSDP. Fixes https://github.com/huggingface/transformers/issues/24568 via https://github.com/huggingface/transformers/pull/24980
3. `extract_from_parallel` how unwraps FSDP models too but these will lead to FSDP issues if there are modules as part of the global FSDP unit as the parameters of those modules won't be gathered if one isn't calling global FSDP wrapper's forward call. This is wrt issue https://github.com/huggingface/diffusers/issues/4037
> FSDP enhancements and fixes

- src/accelerate/accelerator.py
This happens occasionally when you run the merge test with multi-gpu. Here is the log of a failure ci-test link:
https://github.com/huggingface/accelerate/actions/runs/5601414096/job/15173828704#step:4:1472
The code caused failure is mainly from [https://github.com/huggingface/accelerate/blob/a2d8f540c3ab37c8f84d616be1300a0572b69cf8/src/accelerate/accelerator.py#L2580-L2585](https://github.com/huggingface/accelerate/blob/a2d8f540c3ab37c8f84d616be1300a0572b69cf8/src/accelerate/accelerator.py#L2580-L2585)
In some test (e.g. tests/test_state_checkpointing.py::CheckpointTest::test_map_location) and using multi-gpu environment, multi process would check whether output_dir is created. If one process A runs very fast and finishes making dir in L2585 above, another process B runs very slow and …
> Fix check failure in Accelerator.save_state using multi-gpu

- src/accelerate/utils/modeling.py
This PR fixes some errors when user-provided `max_memory` argument in `infer_auto_device_map` is not in expected order or contains unexpected devices. 
- [Add argument-checking for max_memory](https://github.com/huggingface/accelerate/commit/301c034ac935509b2b6c706fa47de997c0aab20a)
- [Sort the user-provided max_memory keys in gpu-cpu-disk order](https://github.com/huggingface/accelerate/commit/f84ac36bcda4525f6bbc1596770453e34923ee29)
- [Fixed the bug that adds "disk" to gpus if it is provided in max_memory argument](https://github.com/huggingface/accelerate/commit/394d937fc344bae9e7a370cd4b200948a22736cd)
For some large models that I tested,  using device_map="auto" might still lead to OOM problem( and I'd like to look into it soon). So we need to explicitly call `infer_auto_device_map` …
> Fix error when max_memory argument is in unexpected order

- src/accelerate/utils/imports.py
With the upcoming major version of Aim, package structure and SDK will change without providing backwards compatibility.
In order to make sure nothing fails on the HF accelerate side, modified the `is_aim_available()` check to return True value only for Aim versions 3.x, by adding the availability check for `aim.sdk` sub-package.
> Change is_aim_available() function to not match aim >= 4.0.0

- src/accelerate/accelerator.py
This PR updates ``Accelerator.accumulate()`` so that users can pass in multiple models into the context manager for skipping gradient sync (by calling ``no_sync()``)
> Support wrapping multiple models in Accelerator.accumulate()

- src/accelerate/test_utils/scripts/test_ops.py
- src/accelerate/utils/operations.py
Solves https://github.com/huggingface/transformers/issues/25076
Solves https://github.com/huggingface/accelerate/issues/1764
We need to ensure tensors are `contiguous` before gathering, else torch will raise an error.
> Contigous on gather

- src/accelerate/utils/fsdp_utils.py
**Overview**
This PR fixes `load_fsdp_optimizer` and passes `test_checkpointing` in the FSDP unit tests.
```
@staticmethod
def optim_state_dict_to_load(
model: torch.nn.Module,
optim: torch.optim.Optimizer,
optim_state_dict: Dict[str, Any],
is_named_optimizer: bool = False,
load_directly: bool = False,
group: Optional[dist.ProcessGroup] = None,
) -> Dict[str, Any]:
```
[code pointer](https://github.com/pytorch/pytorch/blob/29f856e3e02cea6b608167555719c907a80fb135/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1810-L1818)
To support both the old and new arg orders, this passes to `optim_state_dict_to_load()` using kwargs. (See [here](https://github.com/pytorch/pytorch/commit/580b4702bc862dbce386312900db985df58428c0#diff-ffc1ad1876fbf03d814108f6f2f5950a99281b47e0fd77597745f10dc99add8 …
> [FSDP] Fix `load_fsdp_optimizer`

- src/accelerate/utils/modeling.py
This PR fixes OOM problem in the case of 1 GPU and device_map="auto", by reserving 10% memory for buffer(e.g. , storing the text embeddings). Manually setting max_memory or device_map will override this change. 
This is a patch to `get_balanced_memory()` in the case of `num_devices==1`.
The OOM problem happens for some LLMs, such as chatglm, llama, etc. 
Hope it's acceptable.
> reserve 10% GPU in `get_balanced_memory` to avoid OOM

- src/accelerate/tracking.py
Minor fix to allow users to resume from a previous run on wandb. Example use case: if one uses a custom `config` with  `wandb` for tracking as follows:
`accelerator.init_trackers(project_name=args.wandb_project, config=args, init_kwargs=wandb_init_kwargs)`
I might want to resume from the same `wandb` run using the `resume`  argument 
(Docs: https://docs.wandb.ai/guides/runs/resuming) 
Resuming by just passing the `resume` argument with `wandb_init_kwargs` as `{"wandb": {"resume": True, "allow_val_change": True}}` does not work if I have changed the `config` parameter above (Say a "checkpoint_path" key).  leading to the following error:
`ConfigError: Attempted to change value of key "checkpoint_path" from None to test_ckpt_path If you really want to do this, pass allow_val_change=True to …
> Allow users to resume from previous wandb runs with allow_val_change 

- src/accelerate/accelerator.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- tests/test_multigpu.py
Solves https://github.com/huggingface/accelerate/issues/1802 by raising an error if a user tries doing `.prepare()` on a model that contains a device map and we are in something other than `Distributed.NO
> Detect device map auto and raise a helpful error when trying to not use model parallelism

- src/accelerate/big_modeling.py
- tests/test_big_modeling.py
This PR wrap `to` and `cuda` method when we dispatch a model on multiple devices. We send a send a warning when these methods are called as they should not move the model for inference/training. We also give a better error message when the user tries to move a model that has some modules offloaded to cpu or disk.
> add warning when using to and cuda

- setup.py
- src/accelerate/utils/bnb.py
- tests/test_accelerator.py
`bitsandbytes` will always initialize CUDA on import as it's designed to be imported/ran from the CLI. As a result this makes it fully incompatible with the `notebook_launcher`. To try and mitigate this, I've moved all of the import statements to be inside the functions that require the items to use them. Not the cleanest solution, but as this behavior has been consistent in bnb for many versions I don't believe this is likely to change in the future, so we need to adapt for it as a result. 
Solves https://github.com/huggingface/accelerate/issues/1807
> Fix bnb import

- docs/source/usage_guides/quantization.md
- src/accelerate/utils/bnb.py
`load_and_quantize_model` [has an arg](https://github.com/huggingface/accelerate/blob/v0.21.0/src/accelerate/utils/bnb.py#L52) `bnb_quantization_config`, but slightly different versions of this were listed in the docs and docstrings.
> Update docs and docstrings to match `load_and_quantize_model` arg

- src/accelerate/test_utils/scripts/test_notebook.py
- tests/test_accelerator.py
Writes a better test that doesn't depend on the order the test is called in for us to check torch cuda (why main has been failing). Verified by removing the hack of having it go first and test via `pytest -sv tests/test_accelerator.py` on a multi-GPU machine. 
Helpful tip: if for whatever reason you care about the execution of a test, send it to a new test `.py` file in `test_utils/scripts` to run off of an isolated new process cc @SunMarc @BenjaminBossan
> Better test

- src/accelerate/accelerator.py
Tuple comparison in Python is a slightly cleaner way to check that the major/minor is >= 8.9.
> Minor idiomatic change for fp8 check.

- src/accelerate/big_modeling.py
- tests/test_big_modeling.py
> Use device as context manager for init_on_device

- src/accelerate/utils/modeling.py
For our arc intel gpus, there is an issue where if cpu is present in the device map (which it is by default from get_max_memory)  , it will flag an error in ipex (during device_map =balanced or auto) as ipex expects no 'cpu' type in its arc gpu memory initialization. This fix  is exclusively for our gpus .
@sgugger @muellerzr
> Ipex bug fix for device properties in modelling

- src/accelerate/utils/other.py
- tests/test_accelerator.py
Using `accelerator.unwrap_model(model, keep_fp32_wrapper=False)` results in a defective `forward` method. This bug was (probably) introduced in PR #872. I could reproduce it with current main, v0.21 and v0.20.
This PR provides a bugfix and tests for the regression.
> FIX: Bug with unwrap_model and keep_fp32_wrapper=False

- src/accelerate/accelerator.py
Currently `verify_device_map`, which is called during `Accelerator.prepare` only checks if there is an attribute `hf_device_map` in any of the submodules. However, it does not check the contents of the device map itself. In case of trivial device map with only one element this will prevent user from training a model in distributed mode, while the model would in fact work perfectly fine as it is not spread across many devices.
I've made a small change to the function, so now it will **only** return True if any of the child modules has `hf_device_map` **and** this map has more than one entry.
> Fix verify_device_map

- src/accelerate/accelerator.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/dataclasses.py
1. Enables this PR https://github.com/huggingface/transformers/pull/25107. All explanation is in that PR.
> support for ram efficient loading of model with FSDP

- src/accelerate/big_modeling.py
This PR fixes the `dispatch` function for quantized model. Only bnb model needs to have hooks in a single gpu setup. For other quantization methods such as GPTQ, we don't need that.
> fix dispatch for quantized model

- docs/source/package_reference/accelerator.md
- src/accelerate/accelerator.py
1. Fixes https://github.com/huggingface/accelerate/issues/1865
> remove casting to FP32 when saving state dict

- .github/ISSUE_TEMPLATE/bug-report.yml
As noted in https://github.com/huggingface/accelerate/issues/1870, this PR adds a link to the forums for users choosing the bug report template, enticing them to post there first:
> Include a note to the forums in the bug report

- src/accelerate/hooks.py
Fixes #1869. This PR fixes the `detach_hook` function from `AlignDevicesHook` class so that we can call `.detach_hook()` on a `SequentialHook` object where one of the hooks is an `AlignDevicesHook` object.
> fix detach_hook

- src/accelerate/accelerator.py
This PR fulfills https://github.com/huggingface/accelerate/issues/1368#issuecomment-1689817806 by letting users set `ACCELERATE_BYPASS_DEVICE_MAP="true"` as an environmental variable so that if users wish to try an experimental approach at TP as described in the issue thread, they can.
> Enable power users to bypass device_map="auto" training block

- docs/source/package_reference/cli.md
- setup.py
- src/accelerate/commands/accelerate_cli.py
- src/accelerate/commands/estimate.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/other.py
- tests/test_cli.py
This PR introduces a new CLI command: `accelerate estimate-memory`, which will utilize the `meta` device to calculate the total vRAM needed for big model inference, the entire model, and training for a particular model and a variety of precision formats. This also does so *without needing to download model weights*.
Users of accelerate, and MLE's in general who want to know how big of a model they can fit on their system
Many individuals have asked for a way to figure out just what size of a model they can perform big model inference on, the size of a model to fit on their system in general, and for training. As a result, this PR finally fulfills this, using much of the memory-calculating logic already existing in accelerate
Currently this supports `transformers` and `timm`, in the future …
> Introduce model memory estimator

- docs/source/usage_guides/explore.md
Now that accelerate has an official hub org, updates the docs to include it.
Note: the old URL will always redirect to the new one, so prior doc versions will not break
> Update with new url for explore

- src/accelerate/commands/estimate.py
Small enhancement to let a token be passed in. This doesn't matter from the CLI side, we still require the user login via `huggingface-cli`, this is just for the front-end gradio demo
> Enable a token to be used

- setup.py
- src/accelerate/commands/estimate.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- tests/test_cli.py
As the hub is meant to be the foundational library for every lib in the hf ecosystem, adds `huggingface_hub` as a core dep on Accelerate since we have need for it now with the model estimation tool.
> Add hub as core dep

- docs/source/usage_guides/model_size_estimator.md
- src/accelerate/commands/estimate.py
Just some final nits and cleaning on the model util and doc, specifying that after testing the real vs estimated values, we're off by at most a few % (further tests to be done on this), showing `bert-base-cased` as an example of this.
> Final nits on model util

- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
Add FSDP `activation_checkpointing` option. It's already well supported in the native pytorch training code. 
Please see the details about the FSDP activation chekpointing [here](https://pytorch.org/blog/scaling-multimodal-foundation-models-in-torchmultimodal-with-pytorch-distributed/#activation-checkpointing).
Also, I observed the improvement in training performance for the large LLM models (e.g., LLAMA 70B) as compared to  existing `gradient_checkpointing` option.
> Add FSDP activation checkpointing feature

- src/accelerate/utils/dataclasses.py
@pacman100 we have multiple failing tests, stemming from https://github.com/huggingface/accelerate/pull/1894 + related, especially when working off `pypi`. should we skip these tests, if (one) of the fixes in this PR is deemed unnecessary? We also fail on integration tests with pypi as well: https://github.com/huggingface/accelerate/actions/runs/6000691481/job/16273604914
> Solve at least one failing test

- src/accelerate/state.py
- src/accelerate/utils/constants.py
Deepspeed has exposed  support to different backends .So for using deepspeed through accelerate on xpus, the ccl backend is required. Also mpich support was added in deepspeed before (by me) so that can be added too for multinode. 
@sgugger @muellerzr
> Deepspeed integration for XPU/ccl

- .github/workflows/integration_tests.yml
- .github/workflows/self_hosted_integration_tests.yml
This PR in transformers (https://github.com/huggingface/transformers/pull/25077) makes the pypi version of transformers incompatible with the git-version of the tests. As a result, this PR skips their integration tests (but keeps github). Will be re-added in the next release.
Failing merge tests
> Skip pypi transformers until release

- .github/workflows/build-docker-images-release.yml
- .github/workflows/build_docker_images.yml
- .github/workflows/self_hosted_integration_tests.yml
- docker/accelerate-gpu/Dockerfile
Docker image workflows have been broken for the last few months silently, it comes from the workflow we use for it. Instead now we just manually upload it using the repository secrets, and I've confirmed this works and runs without issue. 
cc @LysandreJik @BenjaminBossan
> Fix docker images

- src/accelerate/accelerator.py
- src/accelerate/utils/deepspeed.py
- tests/deepspeed/test_deepspeed.py
1. Add support for deepspeed optimizer and custom scheduler
2. Fixing the lr scheduler not being saved by passing them to the DeepSpeed engineer for all schedulers that are instances of LRScheduler.
3. Added related tests
> Add support for deepspeed optimizer and custom scheduler

- src/accelerate/commands/config/config_args.py
- tests/test_cli.py
- tests/test_configs/invalid_keys.yaml
This PR introduces a better error when loading the YAML file in by letting the user know what errors were actually present. 
Helps relieve the confusion when getting errors such as:
```python
ClusterConfig.__init__() got an unexpected keyword argument 'myargument'
```
And instead results with:
```python
Unknown keys in the config file: ['myargument'], please try upgrading your `accelerate` version or remove them.
```
Anyone in the community is free to review the PR once the tests have passed. Feel free …
> Check for invalid keys

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
Fixes #1933 . We make sure that in case `num_devices = 0`, we return `max_memory` as it is.
> clean num devices

- src/accelerate/tracking.py
This PR protect the tensorflow dependency, so that we import tensorflow only when it is needed ! This should speed-up the import by ~2s. See similar PR for [transformers](https://github.com/huggingface/transformers/pull/26106#issuecomment-1715318226). 
To get the dashboard : 
```py
pip install tuna
python -X importtime -c "import accelerate" 2> accelerate-import-profile.log
tuna accelerate-import-profile.log
```
cc @younesbelkada
> Protect tensorflow dependency

- src/accelerate/utils/other.py
- tests/test_utils.py
Resolves #1832
This fixes a bug in `patch_environment` that currently leads to pre-existing items being deleted completely from the environment variables, when they were temporarily modified by `patch_environment`, once the context has finished. Now, the env vars are restored to their previous values.
@muellerzr
> FIX: patch_environment restores pre-existing environment variables when finished

- src/accelerate/accelerator.py
- src/accelerate/tracking.py
- src/accelerate/utils/other.py
This PR guards slower imports better, namely the trackers and especially `deepspeed` across the framework.
Alternative to https://github.com/huggingface/accelerate/pull/1961, unless we decide that it's getting too repetitive and we want a wrapper 
Resolves https://github.com/huggingface/accelerate/issues/1952
Before, with DeepSpeed installed too:
After:  …
> Better guards for slow imports

- docs/source/concept_guides/deferring_execution.md
- examples/by_feature/early_stopping.py
- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/test_script.py
- tests/test_examples.py
This PR adds two new functions to `Accelerator`: `set_breakpoint` and `check_breakpoint` based on https://discuss.pytorch.org/t/how-to-use-break-in-distributeddataparallel-training/88296/7
https://discuss.huggingface.co/t/early-stopping-for-eval-loss-causes-timeout/51349
When doing early stopping in DDP, if each process has a specific conditional that it can check, where it may not be synchronized across all of them, a `break` can happen on process 0 but not on process 1. As a result this will cause the code to hang indefinitely until a timeout occurs. 
To address that this PR introduces a new `set` and `check` breakpoint API, which should be used in-tandem with such conditionals to ensure that the breakpoint will be reached. This API can be used on any distributed type, not just …
> Introduce breakpoint API

- src/accelerate/accelerator.py
1. Fixes https://github.com/huggingface/accelerate/issues/1889
> fix torch compile with FSDP

- src/accelerate/accelerator.py
shutil.rmtree might throw errors if called on multiply processes. Remove checkpoints only on main process
> Remove checkpoints only on main process

- src/accelerate/hooks.py
- tests/test_big_modeling.py
Fixes #1835 where a model dispatched with `dispatch_model` was unable to be properly copied with `copy.deepcopy`. Specifically, the copied model would incorrectly still reference the align device hook forward function of the original model, rather than its own forward function. This PR includes a fix to this issue as well as a test to validate the fix.
@SunMarc @sgugger
> Fix model copy after `dispatch_model`

- src/accelerate/accelerator.py
- tests/test_state_checkpointing.py
Resolves #1983
Note: I basically duplicated an existing test 99% to check for this bug. My reasoning was that duplication is better for this test than abstracting it. LMK if you prefer to abstract it instead.
> FIX: Automatic checkpoint path inference issue

- examples/by_feature/deepspeed_with_config_support.py
Fixes skipping first batches for the DeepSpeed example. Same changes as #1466 
cc @muellerzr @pacman100
> Fix skip first batch for deepspeed example

- src/accelerate/commands/config/config_utils.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/launch.py
- tests/test_kwargs_handlers.py
#What does this PR do ?
This PR fixes #1977. We updated the list of backend for torch dynamo by the one displayed on the pytorch [website](https://pytorch.org/docs/stable/dynamo/get-started.html). This was not done when we bumped the version of `torch` to `torch > 2.0` when we use torch dynamo.
Here's the list of supported backend for my setup when checking the global variable from torch:
`['dynamo_minifier_backend', 'dynamo_accuracy_minifier_backend', 'cudagraphs', 'eager', 'ts', 'aot_eager', 'aot_eager_decomp_partition', 'aot_ts', 'inductor', 'ipex', 'nvprims_nvfuser', 'nvprims_aten', 'aot_ts_nvfuser', 'onnxrt', 'torchxla_trivial', 'torchxla_trace_once', 'aot_torchxla_trivial', 'aot_torchxla_trace_once', 'tvm']`
For information, here is the list of available backends using …
> update torch_dynamo backends

- src/accelerate/utils/dataclasses.py
Adds sync state for fsdp loading on rank 0 -> broadcasted to other xpu ranks. 
Links to #1777 
cc @pacman100 @muellerzr
> Sync states for xpu fsdp

- src/accelerate/checkpointing.py
Fixes issue where `save_on_each_node` was included on the gradscaler saving, which needs to be done on each worker individually not on each node.
Failing nightly test
> Fix save on each node

- src/accelerate/utils/operations.py
torch 1.13 introduced publicly `all_gather_into_tensor` (before this was `_all_gather_base`) which is a much more memory efficient version of gather. One thing to note mentioned in the PR [here](https://github.com/pytorch/pytorch/pull/85686) is they did not have this be the base of `gather`, since it handles uneven inputs automatically. Since Accelerate does this separately and checks, we can safely use this API. [Original DeepSpeed PR I discovered showing this](https://github.com/microsoft/DeepSpeed/pull/4282)
For a general idea of just how much memory can be stored, I ran a small simple test:
```python
import time
import torch
from accelerate import PartialState
from accelerate.utils import gather
def convert_bytes(size):
"Converts `size` from bytes to the largest possible unit"
for x …
```
> Reduce memory by using `all_gather_into_tensor`

- .github/workflows/self_hosted_integration_tests.yml
Fixes issue finding the last latest release from github for transformers, need a better way to search for it in case what happened last time happens again, where a release was made but not a *release branch*. This method will grab all actual existing tags and search for the latest one made/release.
Failing pypi integration tests on main. See [here](https://github.com/huggingface/accelerate/actions/runs/6484993725) for an example completed run
Anyone in the community is free to review the PR once the …
> Fix integration CI

- docs/source/usage_guides/fsdp.md
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
1. Make fsdp ram efficient loading optional. Certain models are having issues when handling `meta` devices during pre-trained model loading. Fixes https://github.com/huggingface/accelerate/issues/1948 and https://github.com/huggingface/accelerate/issues/2031 by making the ram efficient loading optional.
> Make fsdp ram efficient loading optional

- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/external_deps/test_metrics.py
Ensures that if `drop_last=True`, the default remainder for the `GradientState` is utilized since we are just dropping the non-fitting batch anyways instead.
closes https://github.com/huggingface/accelerate/issues/2007
@BenjaminBossan @LysandreJik
> Let drop_last modify `gather_for_metrics`

- src/accelerate/data_loader.py
This PR mimics `transformers` implementation for the `IterableDatasetShard` by bringing over the ability for it to have a defined `len` and allow for epoch-based training rather than number of batches.
fixes https://github.com/huggingface/accelerate/issues/2023
@BenjaminBossan @LysandreJik
> Let iterable dataset shard have a length if implemented

- src/accelerate/accelerator.py
- src/accelerate/logging.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/other.py
- tests/test_utils.py
See #1929
On Linux with kernel version < 5.5, issues with hanging processes have been reported. It is not clear how to fix the issue, so instead we warn the user that they may encounter problems.
As logging requires an initialized `PartialState`, the actual check happens at the end of `Accelerator.__init__`.
In a similar vein, the docstring of `get_logger` has been adjusted to first initialize the `Accelerator`, as it is not working as currently shown.
@muellerzr
> Warn when kernel version is too low on Linux

- src/accelerate/checkpointing.py
We should only save/load the sampler if it's an iterable dataset shard, and if we use our custom sampler. Otherwise pulling from the batch sampler and loading it is more nuanced. For the sake of the release, let's focus on just the new sampler. If users report that they can't reproduce trainings on batch samplers (or if we test and find we can't), then we can pivot after.
Failing test on main that caught this …
> Fix failing test on main

- src/accelerate/big_modeling.py
This PR adds a warning if there is any parameters on the meta device because of the offloading.
> Add logs offloading

- .github/workflows/build-docker-images-release.yml
- .github/workflows/build_docker_images.yml
- .github/workflows/nightly.yml
- .github/workflows/run_merge_tests.yml
- .github/workflows/self_hosted_integration_tests.yml
CI is red when merging because new runners contain the same tags, but are not setup for our CI yet (and as a result, will completely fail). This PR keeps us on the old CI system for now until we are ready to migrate
> CRITICAL: fix failing ci

- src/accelerate/accelerator.py
- src/accelerate/utils/transformer_engine.py
Doing `.copy()` like we were before leads to a *huge* memory leak during `fp8`, and also putting the model on CUDA *after* converting the layers can reduce some memory.
Example benchmark:
Model: `"meta-llama/Llama-2-7b-hf"`
Note: on FP8 weights are in bf16 beforehand
**Before fix**:
Memory in FP32: 25.23 GB
Memory on BF16: 12.61 GB
Memory on FP8: **37.23 GB** <- Warning sign that something is amiss!
**After fix**:
Memory on FP8:
1. Doing `.cuda()` before (current implementation in `.prepare()`): **12.87 GB**
2. Doing `.cuda()` after: **12.61 GB**
(Finally) fixes https://github.com/huggingface/accelerate/issues/1430
[here are tips on …
> Fix memory leak in fp8 causing OOM (and potentially 3x vRAM usage)

- src/accelerate/data_loader.py
Because at the end of the day the trainer will always use a `DispatchDataLoader` (even in the case of num_gpus == 1), it needs to be able to set the random seed properly for the sampler. The solution is to just always use the `SeedableRandomSampler`. While our tests (in accelerate)do not fail, they don't account for if the base case is `DispatchDataLoader` (`Trainer` tests).
members/contributors who may be …
> Always use SeedableRandomSampler

- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_script.py
Properly sets `SeedableRandomSampler` as the main sampler to be replaced if the user passed in `RandomSampler`. We need this always/should use it always.
Also fixes a missing `set_epoch` at the end of the `__iter__`.
> Make SeedableRandomSampler the default always

- src/accelerate/utils/operations.py
Add explicit error message in case of empty dictionary received. Details are in #2108.
Fixes #2108
> Add explicit error if empty batch received

- docs/source/package_reference/utilities.md
- src/accelerate/data_loader.py
- src/accelerate/utils/random.py
This PR introduces `ACCELERATE_SEED` as part of `set_seed`. Doing so will allow for the custom random samplers to rely on it for setting the seed, rather than the generator (as this can lead to imperfect issues). Solves related trainer test failures.
[Internal slack thread](https://huggingface.slack.com/archives/C01NE71C4F7/p1699294942410279)
@LysandreJik …
> Allow for ACCELERATE_SEED env var

- src/accelerate/utils/dataclasses.py
Adds sync state for fsdp loading on rank 0 -> broadcasted to other npu ranks.
cc @pacman100 @statelesshz @muellerzr 
Fixes #2085
> Sync states for npu fsdp

- src/accelerate/checkpointing.py
- src/accelerate/utils/other.py
We only care if the model is saved in `safetensors`, general objects should never be if registered.. As a result makes `save` follow the same notion as `Accelerator.save` where `safe_serialization` is `False` by default. It can remain true for `save_model` and `save_state` however. 
Fixes https://github.com/huggingface/accelerate/issues/2135
> Leave native `save` as `False`

- src/accelerate/utils/modeling.py
- tests/test_quantization.py
This PR fixes the `retie_parameters` function. The issue is that we were making the assumption that the first elem of the tied_params was the param to tie. This should solves the BNB tests that are failing on the CI because we switched to safetensors.
> fix retie_parameters

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/other.py
- tests/test_utils.py
We need to deal with shared memory scenarios when saving with `safetensors` and a model. Since the `safetensor` version relies on passing the *entire model* instead of the state dict directly, [see here](https://github.com/huggingface/safetensors/blob/main/bindings/python/py_src/safetensors/torch.py#L130), to deal with this, for now a raw copy/paste of the code is done instead to remove duplicate names.
(All `state_dict` in torch are `OrderedDict`, hence the check)
Two failures on the transformers CI …
> Deal with shared memory scenarios

- examples/README.md
I had hard time figuring out how to run on multi-node configuration with the given instructions.
It looked like no configuration file argument is required and accelerate will find the generated configuration automatically.
Just few more phrases are needed.
@muellerzr , @pacman100
> specify config file path on README

- src/accelerate/utils/other.py
THis fixes the safetensors saving in case the `state_dict` contains other object (e.g. str). In that case, we can't use `.contiguous()` as it only works for `Tensor`
> Fix safetensors contiguous

- src/accelerate/utils/other.py
- tests/test_accelerator.py
- tests/test_cli.py
This PR fixes a series of tests:
* `test_save_load_model`: `parameterized` requires tuples *specifically*, it cannot be a list
* `test_cli`: Some gated nits were needed
@SunMarc
> Fix more tests

- docs/source/usage_guides/gradient_accumulation.md
Adds a note in the docs about how during DDP the model will synchronize on the last step through the dataloader at the end, and how if this is a behavior not wanted it can be avoided.
Fixes https://github.com/huggingface/accelerate/issues/1847
> Add note about GradientState being in-sync with the dataloader by default

- .github/workflows/integration_tests.yml
- .github/workflows/self_hosted_integration_tests.yml
Adds trainer integration tests (the examples) to our test suite since they test both the `Trainer` and the `Accelerator`
> Add examples to tests

- docs/source/usage_guides/tracking.md
- examples/by_feature/deepspeed_with_config_support.py
- examples/by_feature/megatron_lm_gpt_pretraining.py
- setup.py
- src/accelerate/test_utils/testing.py
- src/accelerate/tracking.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- tests/test_examples.py
- tests/test_tracking.py
Adds a [DVCLive](https://dvc.org/doc/dvclive) tracker. DVCLive is a logger for [DVC](https://dvc.org), which version data, models, metrics, etc. and keeps them connected to your Git repo. They can then be visualized in several different interfaces.
A [PR](https://github.com/huggingface/transformers/pull/27352) was recently merged to add a logger to `transformers`, and this PR adds support for `accelerate`.
@muellerzr From what I can tell, it looks like you would be the relevant reviewer. Please feel free to redirect …
> Adds dvclive tracker

- src/accelerate/utils/launch.py
Currently, `main_process_port` availability is checked on all the deepspeed launchers (for multi_node senario), but this check is only necessary for main launcher whose machine rank is 0.
- DeepSpeed: @pacman100
- Command Line Interface: @muellerzr
> check port availability only in main deepspeed/torchrun launcher

- src/accelerate/launchers.py
- src/accelerate/test_utils/scripts/test_notebook.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/environment.py
- tests/test_multigpu.py
Since this is a **very** common issue, adds a check in `notebook_launcher` for specific libraries that are *known* to cause issues (such as starting CUDA forks *on import*). 
Fixes https://github.com/huggingface/accelerate/issues/2148
@BenjaminBossan @SunMarc
> Add warning for problematic libraries

- src/accelerate/logging.py
- src/accelerate/tracking.py
Same solution as https://github.com/huggingface/transformers/pull/27608, warn when failing trying to log non-scalars as metrics. Makes failing tests pass
@SunMarc
> Apply DVC warning to Accelerate

- src/accelerate/utils/operations.py
This PR adds a new explicit error when a user tries to call `.gather()` in a GPU scenario and the device of the passed in tensor != the device in `PartialState` (aka CUDA). Avoids users getting err:
```python
File "/home/student/Experiemnts/MultiLabelClassification_LLMs/.mlc/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2897, in all_gather_into_tensor
return honor_type(
File "/home/student/Experiemnts/MultiLabelClassification_LLMs/.mlc/lib/python3.10/site-packages/accelerate/utils/operations.py", line 83, in honor_type
return type(obj)(generator)
File "/home/student/Experiemnts/MultiLabelClassification_LLMs/.mlc/lib/python3.10/site-packages/accelerate/utils/operations.py", line 112, in <genexpr>
recursively_apply(
File …
```
> Better error when device mismatches when calling gather() on CUDA

- src/accelerate/state.py
1. Allow deepspeed without distributed launcher. Fixes https://github.com/huggingface/transformers/issues/27770
> Allow deepspeed without distributed launcher

- src/accelerate/accelerator.py
This PR is adding missing whitespace in the assert messages.
> add missing whitespace

- src/accelerate/utils/operations.py
Related to #2180 . There can be an alternate design as (cc @muellerzr  Let me know your thoughts.) :
```python
if state.device.type != tensor.device.type :
if state.device.type=="cuda:"
<print error>
elif ......<logic for other devices>
<print error>
```
> Add  allgather check for xpu

- src/accelerate/launchers.py
- src/accelerate/state.py
- src/accelerate/utils/environment.py
Similar to prior work done in https://github.com/huggingface/accelerate/pull/2195, I noticed when using the `notebook_launcher` this would need to be done here as well. Rather than having the user manually set these values themselves, modifies the check to include a torch-save version of checking GPU names (by just calling `nvidia-smi` under the hood). …
> Check notebook launcher for 3090+

- src/accelerate/utils/tqdm.py
Fix the condition on when to disable the tqdm output
> fix tqdm wrapper to print when process id ==0

- src/accelerate/utils/modeling.py
There are cases when we don't want to merge all the keys in a device map based on module grouping, and the order is *very* important (such as knowing what layer to split a model on based on the first instance of another device 👀 )
This PR flags doing so as optional as a result, leaving clean as the default. 
@SunMarc
> Make cleaning optional for device map

- src/accelerate/data_loader.py
Currently, running `accelerate test` on TPU fails with error:
```
stderr: concurrent.futures.process._RemoteTraceback:
stderr: """
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
stderr:     r = call_item.fn(*call_item.args, **call_item.kwargs)
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/ansible/.venv/lib/python3.8/site-packages/torch_xla/runtime.py", line 87, in wrapper
stderr:     return fn(*args, **kwargs) …
```
> Fix MpDeviceLoaderWrapper not having attribute batch_sampler

- src/accelerate/utils/modeling.py
- src/accelerate/utils/other.py
This PR addresses the final issue raised by @poedator here: https://github.com/huggingface/transformers/pull/26037#issuecomment-1855421796 
In fact, there is a corner case when users pass `device_map="cuda"` since the device will be initialized without the index argument, leading the check `elif value is not None or torch.device(device) != module._parameters[tensor_name].device:` to pass whereas it should fail. 
I propose a simple approach where we define a new utils function `check_device_same` that effectively checks whether two devices are the same and deals with the corner case if one of the device that we want to check do not have the attribute `index`. 
cc @SunMarc @muellerzr
> [`Big-Modeling`] Harmonize device check to handle corner cases

- src/accelerate/tracking.py
This PR aims to add `log_images` function to aim tracker for better integration between accelerate and aim.
Below is a simple file to check the integration result:
```python
import numpy as np
from PIL import Image
def main():
accelerator = accelerate.Accelerator(
project_dir="runs/test_aim_images",
log_with=["aim"],
)
accelerator.init_trackers(project_name="test aim images")
for cur_iter in range(0, 10):
image_grid = Image.fromarray(np.random.randint(0, 255, size=(256, 256, 3), dtype=np.uint8))
for tracker in accelerator.trackers:
if tracker.name == "aim":
tracker.log_images(
{"test_image": (image_grid, f"iter: {cur_iter}")}, step=cur_iter + 1
)
accelerator.end_training()
if __name__ == "__main__":
main()
```
After running the sample code, users can open aim with `aim …
> Support `log_images` for aim tracker

- docs/source/_toctree.yml
- docs/source/concept_guides/low_precision_training.md
- docs/source/package_reference/utilities.md
- docs/source/usage_guides/low_precision_training.md
- examples/nlp_example.py
- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/environment.py
- src/accelerate/utils/imports.py
This PR introduces an additional backend for FP8 support through [MS-AMP](https://github.com/Azure/MS-AMP/tree/main) which has shown to decrease memory when using FP8 precision while maintaining accuracy
Individuals training with FP8 (H100/4090's, etc)
https://github.com/Azure/MS-AMP/issues/128
Two new arguments were added to the `FP8RecipeKwargs`:
* `backend` (`str`): Whether a user should use MS-AMP or TE (transformerengine). Uses `MS-AMP` by default.
* `optimization_level` (`str`), should be one of `"O1"` or `"O2"`. `"O3"` is for DeepSpeed and we need to wait for them to update to v0.9.3 of deepspeed to match what Accelerate supports
General guideline to optimization levels:
* O1: Weight gradients and `all_reduce` communications are done in fp8, reducing GPU
memory usage and …
> Integrate MS-AMP Support for FP8 as a seperate backend

- tests/deepspeed/test_deepspeed.py
- tests/fsdp/test_fsdp.py
Part of https://github.com/huggingface/accelerate/issues/2122
cc @muellerzr
> device agnostic deepspeed&fsdp testing

- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
https://github.com/huggingface/accelerate/pull/2123 introduced device agnostic testing, but it didn't account for the fact our testing suite relies on never spawning any CUDA processes explicitly until a test is fully called. Replaces all calls to `torch.cuda.is_available()` with our equivalent check that doesn't rely on touching `torch.cuda` (and causing issues with the `notebook_launcher`
The other failing test on main
Anyone in the community is free to review the PR once the tests have passed. Feel …
> Solve CUDA issues

- .github/workflows/self_hosted_integration_tests.yml
Autopicking up DVC in the env leads to very annoying DVC issues related to git configs for the trainer specifically. Since these tests are already ran nightly on the trainer side this PR just disables them in Accelerate locally by uninstalling yet another problematic tracker during tests. 
The failing tests on main. 
@SunMarc
> Uninstall DVC in the Trainer tests

- src/accelerate/utils/modeling.py
As pointed by @fxmarty [here](https://github.com/huggingface/accelerate/pull/2116#discussion_r1415338368), we need to check if the `device_map` is `None` or not before using `check_tied_parameters_on_same_device`.
> Add condition before using `check_tied_parameters_on_same_device`

- docs/source/usage_guides/deepspeed.md
When ported to Accelerate from Transformers the Deepspeed docs about `auto`-values didn't make it. This is very important information. How would a user otherwise know what those values get set to?
This PR adds the 3 critical ones, but more work is needed to explain which is which.
The original document had a very detailed section for each entry, explaining each `auto` 
https://huggingface.co/docs/transformers/main/en/main_classes/deepspeed
but for some reason Accelerate chose not to document any of it - which is super odd. It's already documented - why not just copy it as is?
But bottom line is that there are 2 types of auto-values:
1. sync the value with the CLI args or defaults
2. set the value based on the model's parameters
So perhaps a new `Auto Values` section can be added that just …
> [deepspeed docs] auto-values aren't being covered

- src/accelerate/utils/transformer_engine.py
1. When `linear` layers in the model are replaced with Transformer-Engine's linear layers, the weights of the latter should be replaced with the weights of the former (currently, it's the other way around).
2. Adding TE's `TransformerLayer` to `has_transformer_engine_layers` function to allow the case when larger chunks of modules could be replaced (`TransformerLayer` could replace `LlamaDecoderLayer` in this case)
@muellerzr, could you pls take a look? Thanks!
> Fixes bug in swapping weights when replacing with Transformer-Engine layers

- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/utils/operations.py
breakpoint API in test_script.py currently fails on TPU. This PR is intended to fix it:
- `xm.all_reduce("sum", cloned_tensor, scale)` doesn't do an in-place update so a return value should be used to get the value after the all_reduce.
- Run https://github.com/huggingface/accelerate/blob/b0528392c83c1d7afb823d87abb94a924f7f69b1/src/accelerate/test_utils/scripts/test_script.py#L605-L606 not just on the main process but on all processes.
Fixes [# (issue)](https://github.com/huggingface/accelerate/issues/2247)
Anyone in …
> Fix breakpoint API in test_script.py on TPU.

- src/accelerate/big_modeling.py
This PR adds a warning that device_map should not be left as `None` when using the `init_empty_weights` context,
as dispatch won't be called in this case.
At the moment, pytorch prints warning that tensors can't be copied from meta device, but that's difficult to trace back to this.
Note: I've also tried to fix the broken link to designing a device map but not sure if this works - the doc preview didn't work for me (--html incompatible with my installed node version).
Anyone in the community is free to review the PR …
> Update docs: Add warning for device_map=None for load_checkpoint_and_dispatch

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/external_deps/test_performance.py
- tests/deepspeed/test_deepspeed.py
1. Revert a change from https://github.com/huggingface/accelerate/pull/1909 causing a regression in behaviour from version 0.22 to version 0.23
Details about the Regression: 
Accelerate caused regression:
Deepspeed 0.12.6, accelerate 0.22.0 works,
Deepspeed 0.12.6, accelerate 0.23.0 regresses
As you can see the learning is much slower on multi-gpu ds setup as compared to 1 gpu:
red is 1 gpu w/ either accelerate version
blue  is 2 gpus w/ accelerate 0.23.0
green is 2 gpus w/ accelerate 0.22.0
Reason: The changes of this PR https://github.com/huggingface/accelerate/pull/1909/files
This PR reverts the LR scheduler related changes. I have run all the slow tests of Trainer to make sure this revert doesn't impact trainer's DeepSpeed integration.
> Fix DeepSpeed related regression

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_script.py
This PR disables the seedable random sampler by default. While yes it can make user results *fully reproducible*, it has a questionable degradation in quality which outweighs its benefits. It can be enabled explicitly in the `Accelerator`. 
Fixes https://github.com/huggingface/accelerate/issues/2268
Fixes https://github.com/huggingface/accelerate/issues/2208 …
> Bring old seed technique back

- src/accelerate/utils/modeling.py
adding `"Params4bit"` to the list of bnb classes in set_module_tensor_to_device(). 
It looks like this class was originally named "FP4Params", but later renamed to "Params4bit", and it was not reflected in accelerate.  See https://github.com/huggingface/accelerate/issues/2250 for discovery details.
This issue was not affecting anything until recently, but as of today (possibly due to some other changes) this breaks 4-bit bnb serialization tests in transformers.
I left `"FP4Params"` intact in case there are compatibility issues with some older bnb version.
tagging @younesbelkada, @SunMarc @TimDettmers @Titus-von-Koeller
> `Params4bit` added to bnb classes in set_module_tensor_to_device()

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
As per title, thanks to @giuseppe5 & @nickfraser notice.
On main currently, the detection of `tied_param_goups` and `tied_params` is wrong as e.g. if we have a group `["compute.weight", "compute.weight_submodule.parameter"]` and we are currently treating the parameter `compute.weight`, `tied_param_goups` will wrongfully be empty as `all(name in k for k in tied_group)` is True.
This result in an error in this example:
```python
import torch
class SubModule(torch.nn.Module):
def __init__(self, ref_to_parameter):
super().__init__()
self.parameter = ref_to_parameter
def forward(self, x):
return self.x + torch.max(self.parameter)
class LinearModuleAndSubModule(torch.nn.Linear):
def __init__(self, in_features, out_features):
super().__init__(in_features, out_features) …
```
> Fix infer_auto_device_map when tied weights share the same prefix name

- src/accelerate/data_loader.py
This PR raise an error when the user tries to use batches of different sizes with `dispatch_batches=True`. This arg is set to `True` when using an `IterableDataset`. 
Solves [26548](https://github.com/huggingface/transformers/issues/26548). See this [comment](https://github.com/huggingface/transformers/issues/26548#issuecomment-1885798533) for more details.
> Raise error when using batches of different sizes with `dispatch_batches=True`

- src/accelerate/big_modeling.py
This PR convert the model.hf_device_map to dict for better usage (make copy paste easier, better front ).
For ref,  the `device_map` was changed from dict to OrderedDict through this [PR](https://github.com/huggingface/accelerate/pull/2233).
> Convert model.hf_device_map back to Dict

- src/accelerate/commands/estimate.py
The model memory space would have issues if an API token was passed because it *also* needs to be passed when we grab the config 🤦‍♂️ 
@SunMarc
> Fix model memory issue

- src/accelerate/commands/launch.py
- src/accelerate/state.py
- src/accelerate/utils/environment.py
My research was a bit off, the 3090's can still do P2P from what this user reports, so I adjusted the limit to only happen on 40* series.
Fixes https://github.com/huggingface/accelerate/issues/2328
@SunMarc
> Disable P2P in *just* the 4000 series

- src/accelerate/big_modeling.py
- src/accelerate/hooks.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/other.py
- tests/test_big_modeling.py
@Giuseppe5 noticed that `dispatch_model` does not preserve tied weights during its call, although `retie_parameters` as the end so the end model dispatched model preserves tied weights.
This results in possible large memory spike during `dispatch_model` in case many weights are tied. The core issue in `init_hook` and `set_module_tensor_to_device` is:
```python
import torch
import torch.nn as nn
from collections import OrderedDict
model = nn.Sequential(
OrderedDict(
[
("linear0", nn.Linear(4, 4)),
("linear1", nn.Linear(6, 6)),
("linear2", nn.Linear(4, 4)),
("linear3", nn.Linear(6, 6)),
]
)
)
model.linear2.weight = model.linear0.weight
model.linear2.bias = model.linear0.bias
old_value0 = getattr(model.linear0, "weight")
old_value2 = getattr(model.linear2, "weight")
print("on cpu linear0:", …
```
> Avoid duplicating memory for tied weights in `dispatch_model`, and in forward with offloading 

- src/accelerate/commands/config/cluster.py
Currently, no DeepSpeed option is shown to users when multi-XPU is selected. This PR adds support for XPU. 
On NV GPU, the question "Do you want to use DeepSpeed? [yes/NO]:" comes before "Do you want to use FullyShardedDataParallel? [yes/NO]:". The same user experience should apply for XPU. 
@muellerzr @pacman100
> Show DeepSpeed option when multi-XPU is selected in `accelerate config`

- src/accelerate/state.py
- Fixes issue https://github.com/huggingface/accelerate/issues/2340 fort both deepspeed path and none-deepspeed path 
- Adds the missing `LOCAL_WORLD_SIZE` environment variable
> FIX: add oneCCL environment variable for non-MPI launcher (accelerate launch)

- examples/by_feature/megatron_lm_gpt_pretraining.py
If no `block_size` is explicitly passed, and the tokenizer happens to have a `model_max_length` of less than 1024, the current example will produce a bad `block_size`. With this change, we only cap `block_size` to 1024 if `tokenizer.model_max_length` is actually greater than 1024.
Tagging @pacman100 / @sgugger as the authors of the surrounding code.
> Fix `block_size` picking in `megatron_lm_gpt_pretraining` example.

- src/accelerate/utils/dataclasses.py
Fix the usage of `FP8RecipeKwargs`
@muellerzr
> bugfix to allow usage of TE or MSAMP in `FP8RecipeKwargs`

- src/accelerate/hooks.py
- tests/test_hooks.py
It appears to be illegal to modify the forward method of a `GraphModuleImpl` instance, PyTorch rather favors modifying the class method (https://github.com/pytorch/pytorch/blob/c3780010a58a84920335296ee5f091a0db18259f/torch/fx/graph_module.py#L708-L723) though it is unclear why the behavior would be different.
Just modifying the class instance forward method results in a frozen forward call - despite modifying the graph (as in the test).
@Giuseppe5 and @nickfraser found this bug. cc @jamesr66a as this was quite a tricky one.
> `add_hook_to_module` and `remove_hook_from_module` compatibility with fx.GraphModule

- src/accelerate/inference.py
- src/accelerate/test_utils/scripts/external_deps/test_pippy.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/operations.py
- tests/test_utils.py
This PR allows for dynamic batch padding by finding and duplicating the last item in the batch before concating everything. 
Current issue:
* `PiPPy` has issues with batch inference on GPT-2, will talk to the pippy folks about this
@SunMarc
> Allow for dynamic batch padding

- src/accelerate/utils/__init__.py
- src/accelerate/utils/fsdp_utils.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/modeling.py
- See related PR in `transformers` for motivation: https://github.com/huggingface/transformers/pull/28297
- Adds the ability to only save/load PEFT weights for `save_fsdp_model` and `load_fsdp_model`
- The `adapter_only` parameter (default off) controls whether only the PEFT weights will be saved.
> Add `adapter_only` option to `save_fsdp_model` and `load_fsdp_model` to only save/load PEFT weights

- setup.py
See https://github.com/huggingface/transformers/pull/28785 - torch 2.2.0 was pushed to pypi and broke the CI. We pinned the version in Transformers, but because it installs accelerate from `main` at the end of the other installations, we need to pin the version in `accelerate` as well, or the `accelerate` installation upgrades to `torch 2.2.0` regardless.
> Pin Torch version to <2.2.0

- src/accelerate/utils/environment.py
[PEP-632](https://peps.python.org/pep-0632/) deprecated use of distutils, which are now completely removed in Python 3.12+. environment.py still uses distutils.spawn to detect full path of nvidia-smi executable for GPU detection. 
This PR replaces deprecated distutils.spawn with supported shutils.which to ensure conpatibility with Python 3.12+
Code path impacted is windows-only and requires Nvidia GPU, so not a good candidate for automated tests.
Fixes #2379 
@muellerzr
> Address PIP-632 deprecation of distutils

- Makefile
Pytest released a new version that broke our CI because:
>  Files and directories are now collected in alphabetical order jointly, unless changed by a plugin. Previously, files were collected before directories. See below for an example.
The failures were coming from deepspeed being the first one being ran instead of later on. This PR change `make test` to run in the following order:
```make
test:
$(MAKE) test_core
$(MAKE) test_cli
$(MAKE) test_big_modeling
$(MAKE) test_deepspeed
$(MAKE) test_fsdp
```
Instead of the prior:
```make
python -m pytest -s -v ./tests/ --ignore=./tests/test_examples.py $(if $(IS_GITHUB_CI),--report-log "$(PYTORCH_VERSION)_all.log",)
```
> Fix CI due to pytest

- src/accelerate/big_modeling.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/operations.py
With `device_map = {"xpu": "16GB", "cpu": "32GB"}` on an Intel XPU, it will complain about 
```
Device xpu is not recognized, available devices are integers(for GPU/XPU), 'mps', 'cpu' and 'disk'"
```
but you cannot just put 0 as device, or it will treat 0 as CUDA device, then complains again that torch is not compiled with CUDA enabled.
You will need safetensors >= 0.4.2 if using safetensors files (https://github.com/huggingface/safetensors/pull/428).
Anyone in the community is free to review the PR once the tests …
> Fix XPU inference

- src/accelerate/utils/modeling.py
Hello, I'm trying using accelerate to offload a large model (https://huggingface.co/TheBloke/WizardCoder-33B-V1.1-GPTQ) to CPU, with following code (requires https://github.com/huggingface/accelerate/pull/2383 if using Intel GPU, and https://github.com/huggingface/transformers/pull/28755):
```python
import datetime
import torch
import intel_extension_for_pytorch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
model_id = "/mnt/external2/LLMs/WizardCoder-33B-V1.1-GPTQ"
tokenizer = AutoTokenizer.from_pretrained(model_id)
pipe = pipeline("text-generation", model=model_id, model_kwargs={"torch_dtype": torch.bfloat16, "device_map": "auto", "max_memory": {0: "16GB", "cpu": "128GB"}, "offload_buffers": True})
print(str(pipe.model.hf_device_map)) …
```
> Fix the size of int and bool type when computing module size

- CONTRIBUTING.md
- Makefile
- pyproject.toml
- setup.py
- src/accelerate/utils/megatron_lm.py
- tests/test_tracking.py
This PR replaces Black formatting with `ruff format`, following in the footsteps of https://github.com/huggingface/transformers/pull/27144 and https://github.com/huggingface/diffusers/pull/5841.
Tagging @sgugger as the author of https://github.com/huggingface/accelerate/pull/1046 that last touched Ruff configuration.
> Use Ruff for formatting too

- docs/source/usage_guides/fsdp.md
1. States an important detail when using `fsdp_cpu_ram_efficient_loading`.
2. Adds a section with a mapping between FSDP sharding strategies and DeepSpeed ZeRO Stages.
> Update FSDP docs

- docs/source/usage_guides/distributed_inference.md
- src/accelerate/inference.py
- src/accelerate/test_utils/scripts/test_ops.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/operations.py
This PR makes it so that after running pippy inference, the outputs are gathered and returned on each GPU at the end. This does incur a comms call so this can be disabled if users want to keep it on the last GPU only
@SunMarc @kwen2501
> Make output end up on all GPUs at the end

- docs/source/usage_guides/distributed_inference.md
- examples/inference/README.md
- examples/inference/bert.py
- examples/inference/gpt2.py
- examples/inference/llama.py
- examples/inference/requirements.txt
- examples/inference/t5.py
- setup.py
- tests/test_examples.py
Since pippy 0.2.0 is out, adds it as a test dep. Also migrates the examples from the example repo to Accelerate and updates the relevant docs. 
Should be merged after https://github.com/huggingface/accelerate/pull/2423
@SunMarc @kwen2501
> Migrate pippy examples over and run tests

- tests/test_multigpu.py
With the command `pytest test_multigpu.py` on my NV A100 device, I got a failed test for `test_distributed_data_loop`. Based on the code, I think it is intended to use 2 processes instead of the available device number. 
I also change the `require_multi_device` to `require_multi_gpu`, because `cuda_visible_devices=0,1` reveals that this test can only be applied to GPU. 
Pls have a review, thanks!
@muellerzr or @pacman100
> [FIX] fix the wrong `nproc_per_node` in the multi gpu test  

- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
Fixes a few things with the fp8 integration since the merger of msamp:
* Couldn't just use the accelerate configuration and leave the defaults, as the mixed precision wasn't set yet for when we check to build a recipe handler default
* explicitly makes the backend te as the default (hit the dataclass not liking this w/o it being passed in)
* some fixes to allow users to pass in either `backend="te"` or `backend="TE"`
> Fix fp8 things

- src/accelerate/commands/estimate.py
Looks like something changed in the backend somewhere and we don't raise errors when having invalid models/metadata. This alleviates this and makes the old test pass. 
@SunMarc
> Fix model metadata issue check

- docker/accelerate-gpu/Dockerfile
PiPPy requires 3.9, fixes more test failures
> Use py 3.9

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_script.py
TL;DR the chunk for modifying the seedable sampler/adding it needs to be done *after* the new dataloader has been made. Otherwise we just modify the one we're getting rid of 😓 
Closes https://github.com/huggingface/accelerate/issues/2333
```
Original: tensor([ 6, 15, 22,  2, 10, 19,  3, 18, 12, 23, 21, 20,  7, 11, 16,  0,  4, 12,
7, 22,  9,  6,  5, 20, 10, 23,  1, 11, 17,  2, 14, 15, 11, 19, 13, 17,
8, 14,  1, 10,  3, 15, 18, 12, 22, 16, 21,  5], device='cuda:0')
New: tensor([ 8, 12, 11, 19,  7,  1, 10,  2, 23, 20, 18,  9, 17, 13, 22,  3, 21,  6,
19,  3,  2,  5,  1, 13, 14, 15, 11,  7, 18, 10,  4, 20,  7,  5,  0, 21,
23,  8, 10,  1, 17,  6, 11, 13, 18,  2, 12, 20], device='cuda:0')
```
> Fix seedable sampler logic and expound docs

- src/accelerate/hooks.py
Keep this variable as a set, since some people may call `post_forward` multiple times.
Having it reset as `None` is breaking in the sense that `post_forward` may be called multiple times before, while it can not anymore on main.
Context: https://github.com/huggingface/optimum-amd/pull/62
> Fix tied_pointers_to_remove type

- tests/deepspeed/test_deepspeed.py
- tests/fsdp/test_fsdp.py
- tests/test_accelerator.py
- tests/test_big_modeling.py
- tests/test_cli.py
- tests/test_data_loader.py
- tests/test_examples.py
- tests/test_hooks.py
- tests/test_kwargs_handlers.py
- tests/test_memory_utils.py
- tests/test_modeling_utils.py
- tests/test_offload.py
- tests/test_optimizer.py
- tests/test_quantization.py
- tests/test_state_checkpointing.py
- tests/test_tracking.py
- tests/test_utils.py
This PR makes the assertions used in the test suite [more idiomatic for Pytest](https://docs.pytest.org/en/stable/how-to/assert.html).
Idiomatic assertions are rewritten by Pytest, making debugging much easier.
Namely, I did a first pass using [codemod-unittest-to-pytest-asserts](https://github.com/akx/codemod-unittest-to-pytest-asserts), followed by some `ast-grep` powered fixes, followed up with some manual fixes to make things neater still.
Sibling of https://github.com/huggingface/trl/pull/1301.
I don't have easy access to hardware suitable for running all tests locally (Apple Silicon 😄), but the tests I could run seem to pass, so here's hoping CI agrees!
[documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs) …
> Make test assertions more idiomatic

- src/accelerate/utils/operations.py
- tests/test_utils.py
`torch.compile` breaks when using `hasattr` but succeeds when using `isinstance(torch.Tensor)`.  This commit short-circuits the `hasattr` call for `torch.Tensor`s if possible.
Note: `is_npu_available` is also not torch.compile compatible due to (1) lru_cache and (2) importlib checks, so I've moved it into the try block, catching the AssertionError instead.
- Core parts of the library: @muellerzr @BenjaminBossan
> Prefer `is_torch_tensor` over `hasattr` for torch.compile.

- src/accelerate/big_modeling.py
This PR fixes the wraper around .to() method when we dispatch the model. We were displaying this warning even when the user was not moving the model but casting the model to a specific dtype for example. cc @sayakpaul 
Fixes one of the issues in this PR https://github.com/huggingface/diffusers/pull/6857
> Fix warning when dispatching model 

- src/accelerate/inference.py
The CV models test showed a failure when `args` is defined but `kwargs` are none (why only them, unsure as gpt2 didn't face this, but I digress). This check makes sure that the padding is only checked for if the value is not `None` (otherwise we get an error about how we can't run it w/o a tensor-like item)
Failing test on main
@SunMarc
> Check for None

- setup.py
Fixes the pytest version.
We're getting errors such as this one:
https://github.com/huggingface/accelerate/actions/runs/7958684877/job/21725397566?pr=2450
> Fix the pytest version to be less than 8.0.1

- pyproject.toml
- src/accelerate/accelerator.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/tracking.py
- src/accelerate/utils/other.py
- tests/test_kwargs_handlers.py
- tests/test_utils.py
* Configures Ruff to prevent `os.getenv` and `os.setenv`; there should be one way to manage the env, and `os.environ` was used more.
* `clear_environment()` didn't actually clear environment variables, it just assigned a new `os.environ` proxy dictionary.
* The environment management context managers wouldn't clean up after themselves if the inner block raised.
* There was another suspect place where cleanup code after `yield` is not wrapped; marked that as a TODO (@muellerzr seems to have touched that function last)) …
> Context manager fixes

- src/accelerate/accelerator.py
- src/accelerate/commands/config/config_utils.py
- src/accelerate/utils/imports.py
#2176 replaces the `TPU` device type with `XLA`, letting us use GPUs with `accelerate` now :confetti_ball: 
This PR fixes some issues that pop up on TPU after that PR:
- Don't check the `xm.xla_device` in `is_torch_xla_available`. Calling `xm.xla_device` before `xmp.spawn` causes issues. This causes `torch_xla` to initialize the runtime parent process, reserving some space on GPU that can't be used by the child processes and causing TPU workloads to outright crash (message below).
- Fix menu of options in `accelerate config` to offer `XLA` as an option. Selecting `TPU` causes an error because that device type no longer exists.
- Allow bf16 mixed precision on TPU. Matches old behavior before #2176.
Currently, running `accelerate` on TPU causes this crash due to the first issue:
```
... …
```
> Fix TPU with new `XLA` device type

- src/accelerate/utils/memory.py
This PR updates the `release_memory` function to also free mps memory if we have a mps backend. 
Thx to [Datamance](https://github.com/Datamance) for letting us know ! See related [issue](https://github.com/huggingface/transformers/issues/27181#issuecomment-1958902144).
> Free mps memory

- src/accelerate/state.py
Inspired by the newly added test `test_fsdp.py`, I found that Accelerator's default distributed type is NO on XPU with the following approach, while on NV GPU it is FSDP: 
```bash
$ export ACCELERATE_USE_FSDP="true"
$ export MASTER_ADDR="localhost"
$ export MASTER_PORT="10999"
$ export RANK="0"
$ export LOCAL_RANK="0"
$ export WORLD_SIZE="1"
$ python
>>> from accelerate.accelerator import Accelerator
>>> accelerator = Accelerator()
>>> accelerator.state.distributed_type
<DistributedType.NO: 'NO'>
>>> accelerator.state.distributed_type
<DistributedType.FSDP: 'FSDP'>
```
The reason lies at [this ](https://github.com/faaany/accelerate/blob/main/src/accelerate/state.py#L254) line: currently, MUTLI_XPU/MULTI_CPU is detected by `WORLD_SIZE`, while on NPU or GPU, it is detected by `LOCAL_RANK` …
> [FIX] allow `Accelerator` to detect distributed type from the "LOCAL_RANK" env variable for XPU 

- src/accelerate/commands/test.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/other.py
- tests/deepspeed/test_deepspeed.py
- tests/fsdp/test_fsdp.py
- tests/test_cli.py
- tests/test_examples.py
- tests/test_grad_sync.py
- tests/test_metrics.py
- tests/test_multigpu.py
- tests/test_tpu.py
`subprocess` requires strings, it cannot use paths. Since the helper introduced in https://github.com/huggingface/accelerate/pull/2446 doesn't handle anything externally-facing and is just for testing, and a *vast majority of our tests* require `subprocess`, this PR makes it return a string instead and casts it back to a Path object if applicable. 
Fixes failures on main (and soon-to-be nightlies)
members/contributors who may …
> Fix CI tests due to pathlib issues

- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- tests/fsdp/test_fsdp.py
- tests/test_cli.py
- tests/test_examples.py
- tests/test_grad_sync.py
- tests/test_kwargs_handlers.py
- tests/test_metrics.py
- tests/test_multigpu.py
- tests/test_state_checkpointing.py
As `accelerate launch` sets up various environmental variables for users on systems that can freeze tests (e.g. 4090 people) this PR migrates all tests to use `accelerate launch` instead by making a `LaunchTestCase` with a helper to generate the right command arguments. 
This should be inherited and used if any test case wants to run something that would be ran using `torchrun`/`accelerate launch`/etc
members/contributors who …
> Remove all cases of torchrun in tests and centralize as `accelerate launch`

- docs/source/usage_guides/big_modeling.md
This PR fixes a small typo in the big model inference docs.
> Fix link typo

- src/accelerate/utils/environment.py
Makes the docstring for `are_libraries_initialized` correct (and type signature)
Fixes https://github.com/huggingface/accelerate/issues/2386
@SunMarc
> Docstring fixup

- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/modeling.py
This PR adds the custom dtype INT2 what will be useful to calculate the memory required for 2bits model for quanto.
> add custom dtype INT2

- docs/source/_toctree.yml
- docs/source/basic_tutorials/execution.md
- docs/source/basic_tutorials/migration.md
- docs/source/basic_tutorials/tpu.md
- docs/source/quicktour.md
This PR updates the Quicktour to focus more on the library's core offerings:
➕ organizes the Quicktour around the three main features: unified launcher, `Accelerator` class, and Big Model Inference
➕ new tutorials for Execution process and TPU training
➕ adds save Transformer models from Accelerator API page to same section with saving/loading models in Add Accelerate to your code tutorial
➕ adds `on_local_main_process`, `on_main_process`, `on_process`, and `on_local_process` from Accelerator API page to the Execution process docs
➖ removes the "Common modifications of the base case" section because all these different scenarios can be overwhelming for a new user and because it is not necessarily needed to help users start quickly. These sections will be integrated as a part of the …
> [docs] Quicktour

- .github/workflows/test.yml
- Makefile
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- tests/test_cli.py
- tests/test_examples.py
- tests/test_hub_status.py
- tests/test_multigpu.py
Adds a decorator to the test utils that will skip tests if we find the Hub is down automatically to avoid red CI in the case of an outtage
> Check if hub down

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
Fix 0MiB bug converting from string to int 
https://github.com/oobabooga/text-generation-webui/issues/4193
```
02:06:45-485003 INFO     Loading "mistralai_Mistral-7B-Instruct-v0.2"
{'low_cpu_mem_usage': True, 'trust_remote_code': False, 'torch_dtype': torch.float16, 'use_safetensors': None, 'device_map': 'auto', 'max_memory': {0: '6070MiB', 1: '6070MiB', 2: '6070MiB', 3: '6070MiB', 4: '6070MiB', 5: '6070MiB', 6: '0MiB', 7: '0MiB', 'cpu': '99GiB'}}
02:06:49-501273 ERROR    Failed to load the model.
File "/mnt/nvme/workspace/text-generation-webui/modules/ui_model_menu.py", line 242, in load_model_wrapper
shared.model, shared.tokenizer = load_model(selected_model, loader)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fixed 0MiB bug in convert_file_size_to_int

- src/accelerate/utils/modeling.py
This PR fixes the case where we have buffers in the `modules_to_treat` and we are at the point where we need to choose between split/not split the buffer. 
Fixes an issue in our CI with llama because of the `causal_mask` buffer cc @ArthurZucker
> Fix edge case in infer_auto_device_map when dealing with buffers

- Makefile
- benchmarks/measures_util.py
- examples/inference/bert.py
- examples/inference/gpt2.py
- examples/inference/t5.py
- examples/multigpu_remote_launcher.py
- pyproject.toml
- src/accelerate/__init__.py
- src/accelerate/commands/__init__.py
- src/accelerate/commands/menu/__init__.py
- src/accelerate/commands/menu/keymap.py
- src/accelerate/commands/menu/selection_menu.py
- src/accelerate/inference.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/scripts/__init__.py
- src/accelerate/test_utils/scripts/external_deps/__init__.py
- src/accelerate/test_utils/scripts/external_deps/test_checkpointing.py
- src/accelerate/test_utils/scripts/external_deps/test_metrics.py
- src/accelerate/test_utils/scripts/test_cli.py
- src/accelerate/test_utils/scripts/test_notebook.py
- src/accelerate/utils/__init__.py
- tests/deepspeed/test_deepspeed.py
- tests/test_accelerator.py
- tests/test_sagemaker.py
- tests/xla_spawn.py
- utils/log_reports.py
- utils/stale.py
This PR adds a rule to the `ruff` formatter that allows for checking the presence of a copyright notice at the top of the file, adds said copyrights with the right year (file was introduced), and also fixes a few lint things I found when running on 0.3.0 (note I'm not unpinning 0.3.0, and verified that these rules etc still work on 0.2.1)
> Add copyright + some ruff lint things

- src/accelerate/utils/imports.py
`PYTORCH_NVML_BASED_CUDA_CHECK=1` will tell PyTorch to use an NVML-based check when determining how many devices are available. That's useful for preventing CUDA initialization when calling `torch.cuda.is_available()`. 
`accelerate.utils.imports.is_cuda_available()` will set that env var and delete it afterwards. This is bad because that env var may be available, so deleting it after the function is called can lead to bugs. We ([Modal](https://modal.com/)) set that env var in some workloads. Calling this function breaks some user programs.
We can restore that env var its previous state after calling this function but I think that it is better to, instead of manipulating that env var, call the torch utility `_device_count_nvml` directly. What do you think?
@muellerzr tagging you because …
> Don't manage `PYTORCH_NVML_BASED_CUDA_CHECK` when calling `accelerate.utils.imports.is_cuda_available()`

- src/accelerate/utils/modeling.py
For quanto compatibility with lower bit quantization, we need to check for QBitsTensor class too. 
Related [PR](https://github.com/huggingface/accelerate/pull/2481).
> Quanto compatibility with QBitsTensor

- src/accelerate/commands/test.py
- tests/deepspeed/test_deepspeed.py
- tests/fsdp/test_fsdp.py
- tests/test_cli.py
- tests/test_grad_sync.py
- tests/test_kwargs_handlers.py
- tests/test_metrics.py
- tests/test_multigpu.py
- tests/test_state_checkpointing.py
- tests/test_tpu.py
- tests/test_tracking.py
Subprocess execution calls had a copy-pasted `env=os.environ.copy()` tacked onto them.
When `env=None`, quoth the docs for `subprocess.run`:
> If env is not `None`, it must be a mapping that defines the environment variables for the new process; these are used **instead of the default behavior of inheriting the current process’ environment.**
, emphasis mine.
Unless someone expects `execute_subprocess_async()` to modify the `env` passed in, these are all unnecessary copy-paste. If `execute_subprocess_async()` is expected to modify it, then we can add ```if env is None: env = os.environ.copy()` within it.
Sibling of #2446.
[here are tips on formatting …
```
> Remove unnecessary `env=os.environ.copy()`s

- src/accelerate/commands/accelerate_cli.py
- src/accelerate/commands/estimate.py
- src/accelerate/commands/launch.py
- src/accelerate/commands/utils.py
- tests/test_cli.py
Alternative approach to https://github.com/huggingface/accelerate/pull/2525
This PR adds a pinch of magic for users that are used to doing `--a-b` with arguments that pass-through to things such as `torchrun`, accelerate can process those if we have them defined ourselves already.
E.g. a user can do:
```bash
accelerate launch --no_python --multi_gpu --num_processes 8 --monitor_interval=1 ./trampoline.sh python3 -c "print('hello')"
```
**OR**:
```bash
accelerate launch --no-python --multi-gpu --num-processes 8 --monitor-interval=1 ./trampoline.sh python3 -c "print('hello')"
```
Fulfills some of https://github.com/huggingface/accelerate/issues/2241
[here …
> Enable using dash or underscore for CLI args

- src/accelerate/utils/dataclasses.py
[pytorch/torchdynamo](https://github.com/pytorch/torchdynamo ) has moved to [pytorch/pytorch](https://github.com/pytorch/pytorch/tree/main/torch/_dynamo) and relevant doc is now at https://pytorch.org/docs/stable/torch.compiler.html.
This µPR updates the link in the `DynamoBackend` docstring to save you one click :).
@muellerzr
> Update link to dynamo/compile doc

- src/accelerate/big_modeling.py
- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
Hello, I'm trying using `accelerate` to offload a large model (https://huggingface.co/TheBloke/WizardCoder-33B-V1.1-GPTQ) to CPU, with following code (requires https://github.com/huggingface/accelerate/pull/2383 if using Intel GPU, and https://github.com/huggingface/transformers/pull/28755):
```python
import datetime
import torch
import intel_extension_for_pytorch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
model_id = "/mnt/external2/LLMs/WizardCoder-33B-V1.1-GPTQ"
tokenizer = AutoTokenizer.from_pretrained(model_id)
pipe = pipeline("text-generation", model=model_id, model_kwargs={"torch_dtype": torch.bfloat16, "device_map": "auto", "max_memory": {0: "16GB", "cpu": "128GB"}})
#pipe = pipeline("text-generation", model=model_id, …
```
> Check if the buffers fit GPU memory after device map auto inferred

- docs/source/concept_guides/gradient_synchronization.md
- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/test_sync.py
- src/accelerate/utils/dataclasses.py
Fixes https://github.com/huggingface/transformers/issues/29425
This PR adds in logic to allow `no_sync` to be disabled in `accelerate`, in particular, so that memory can be saved whilst performing FSDP training. See details in the above linked issue.
- Introduced new  argument `GradientAccumulationPlugin.sync_each_batch`, when set will cause gradients to be synced each data batch, regardless of what the setting of `gradient_accumulation_steps` is.
- Introduced a `force` flag into `_do_sync`. This flag is set to `True` during `accumulate`, if `GradientAccumulationPlugin.sync_each_batch` has been configured to `True. 
- Updated tests `tests/test_grad_sync.py::SyncScheduler::test_gradient_sync_gpu_mult` and `test_gradient_sync_gpu`.
- update test utilities `test_gradient_accumulation` and …
> Allow Gradients to be Synced Each Data Batch While Performing Gradient Accumulation

- src/accelerate/utils/dataclasses.py
- tests/fsdp/test_fsdp.py
1. Update FSDP mixed precision setter to enable fsdp+qlora. When using quantization storage datatype as `float32`, the MixedPrecision policy should use `float32` but with autocasting enabled. This PR supports this. 
2. It adds `override` argument to force update the mixed precision policy.
3. It adds `buffer_autocast` argument to support casting buffers to `float32` which can be important for RoPE layer which gives incorrect results when cast to lower precision especially with longer context lengths.
> Update FSDP mixed precision setter to enable fsdp+qlora

- .github/workflows/integration_tests.yml
- .github/workflows/test.yml
Opts for using `uv` instead of `pip install` for the github CI. It's so fast that we don't need to cache anymore, fun fact.
Total time: 
Before: **14m 15s** (~10min on a second commit), taken from https://github.com/huggingface/accelerate/actions/runs/8231938776
After: **6m 30s**, taken from https://github.com/huggingface/accelerate/actions/runs/8238343827
As you can see, *much* of our time is spent on caching (both download and upload of `n` workers, github doesn't like that bandwidth cost)
Anyone in the community is …
> Use uv instead of pip install for github CI

- src/accelerate/data_loader.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
Fixes https://github.com/huggingface/accelerate/issues/2479
- This PR fix the dataloader test: The same test `accelerate test` succeeds on TPU v4 but fails on v2/v3. The reason why it fails on TPU v2/v3 is multithreading. TPU v2/v3 involves multithreading: there are 4 processes and 8 TPU devices on the TPU v3-8, and each process spawns 2 threads for each device respectively. However TPU v4 and further TPU generations doesn't use multithreading. On TPU v2/v3, due to multithreading, we need to explicitly set the seed on each thread. Otherwise, each thread will permute the dataset indices in a different way and therefore generate the duplicate indices as shown in the gh issue. This PR explicitly set the `generator` for each thread and fix the test failure.
- This PR also fix a …
> Fix test_script.py on TPU v2/v3

- src/accelerate/big_modeling.py
This PR adds a message for users with RTX 4000 when using multi-gpu inference with device_map. 
Maybe we can do a better check by looking at the driver version but I need to dig into that a little bit. 
Needed [here](https://github.com/huggingface/diffusers/pull/6857) 
cc @sayakpaul
> Add log message for RTX 4000 series when performing multi-gpu inference with device_map

- src/accelerate/commands/launch.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/environment.py
- tests/test_utils.py
This PR improves the deepspeed env file generation by making sure any bad flags include a warning that they are being strict. 
```
Avoid trailing newline and avoid writing some other characters that would break reading in this file.
DeepSpeed [code](https://github.com/microsoft/DeepSpeed/blob/688239e3f24f7ba11d3fe90bbe9670b7a61e5440/deepspeed/launcher/runner.py#L560) that reads from this file is naive and thus requires strict narrowing of legal key=value lines.
```
- [] Did you make sure to update the documentation with your changes? Here are the
[here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-doc …
> Improve deepspeed env gen

- docs/source/package_reference/accelerator.md
Adds missing functions like `gather_object` which is in a separate file `accelerate/utils/operations.py` rather than the main `accelerate/accelerator.py`. This results in `gather_object` not being documented because the `[[autodoc]]` tag couldn't find it in `accelerate/accelerator.py`.
> [docs] Missing functions from API

- docs/source/package_reference/utilities.md
- src/accelerate/state.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/environment.py
- tests/test_accelerator.py
@stas00 pointed out that the affinity check was being done *every time `PartialState()` was called*. This refactors it into a stateful call when users do `set_numa_affinity`.
This is cached because this check is taxing on the CPU briefly. 
If users want to override it, they can use `accelerate.utils.environment.override_numa_affinity` themselves.
Example usage:
```python
from accelerate.utils import set_numa_affinity
set_numa_affinity(0)
```
Anyone in the community is free to review the PR once the tests have passed. …
> Refactor affinity and make it stateful

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
Up to now, `load_checkpoint_in_model` would behave differently when the checkpoint to be loaded has unexpected keys compared to the model state_dict keys.
With `device_map=None` input, we are currently not erroring out, while with `device_map` not None, we are erroring out.
This PR aligns the behavior of both, defaulting to `strict=False`, and logs the unloaded keys.
> Fix `load_checkpoint_in_model` behavior when unexpected keys are in the checkpoint

- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
- tests/test_accelerator.py
This PR is the second half of solving https://github.com/huggingface/accelerate/issues/2564
The issue boils down to:
1. The user defines a `PartialState`/creates an `Accelerator`
2. The user then calls `_reset_state()` themselves
3. The user then calls subsequent functions in `Accelerator`.
That instance will still point to our reset/broken `PartialState`, and so a better error needs to be raised that contextualizes what's going on early:
```python
File "/home/zach/test.py", line 11, in <module>
_ = accelerator.prepare(model)
File "/home/zach/accelerate/accelerate/src/accelerate/accelerator.py", line 1230, in prepare
if self.distributed_type == DistributedType.DEEPSPEED:
File "/home/zach/accelerate/accelerate/src/accelerate/accelerator.py", line 515, in …
```
> Guard stateful objects

- src/accelerate/state.py
These merge conflicts are getting *fun*, but it's nice to see more people wanting better uses of `PartialState`!
In this one we explicitly discuss how to use `InitProcessGroupKwargs` with the `PartialState`, which is needed if you want to modify the init outside the `Accelerator`
Closes https://github.com/huggingface/accelerate/issues/2587
> Expound PartialState docstring

- src/accelerate/state.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/environment.py
- tests/deepspeed/test_deepspeed.py
This PR does a *huge* refactor of the `PartialState` device setup to make it easier for new backends to get added, ease the maintenance burden, and centralizes the code based on topics
* When adding a new device, `set_device()` should be updated to include the new backend to be used and calling it
* `_prepare_backend` will handle setting `self.backend` and bringing in any imports that are needed for injecting/monkeypatching (such as `torch_ccl`)
Anyone in the community is free to review the PR once the tests have …
> Refactor PartialState and AcceleratorState

- src/accelerate/utils/other.py
- tests/test_utils.py
There are cases when we need to unwrap *far more* than just what is done natively in Accelerate, such as when we have TPUs/SPMD.
This PR expands `extract_model_from_parallel` to support situations such as using XLA's `FSDPv2`.
Alternative to https://github.com/huggingface/transformers/pull/29780, which we can upstream to transformers by just using `recursive=True` …
> Allow for force unwrapping

- src/accelerate/state.py
This existed before the refactor, but we are missing parenthesis around one of the calls to `is_xpu_available`
Fixes https://github.com/huggingface/accelerate/issues/2637
> Parenthesis on xpu_available

- src/accelerate/big_modeling.py
- src/accelerate/utils/operations.py
The following code fails on XPU:
```python
import torch
import requests
from PIL import Image
from transformers import Blip2ForConditionalGeneration, Blip2Processor
def prepare_img():
url = "https://huggingface.co/hf-internal-testing/blip-test-image/resolve/main/demo.jpg"
image = Image.open(requests.get(url, stream=True).raw)
return image
processor = Blip2Processor.from_pretrained("Salesforce/blip2-flan-t5-xl")
device_map = {
"query_tokens": 0,
"vision_model": 0,
"language_model": 1,
"language_projection": 0,
"qformer": 0,
}
model = Blip2ForConditionalGeneration.from_pretrained(
"Salesforce/blip2-flan-t5-xl", torch_dtype=torch.float16, device_map=device_map
)
image = prepare_img()
inputs = processor(images=image, return_tensors="pt").to("xpu:0", dtype=torch.float16)
predictions = …
```
> add third-party device prefix to `execution_device`  

- src/accelerate/big_modeling.py
This PR adds the strict arg in `load_checkpoint_and_dispatch`. We need this since this [PR](https://github.com/huggingface/accelerate/pull/2588) introduced a breaking change in the way to error out when the keys in the checkpoint state_dict do not match the keys of the model's state_dict. 
Fixes https://github.com/huggingface/accelerate/issues/2640#issuecomment-2045579806 cc @yiyixuxu 
maybe worth doing a patch @muellerzr ? There are other issues in diffusers so let's wait a bit if we indeed do a patch.
> add strict arg to load_checkpoint_and_dispatch

- src/accelerate/utils/dataclasses.py
**PR Description**:
Fixes the data type of `is_train_batch_min` in `DeepSpeedPlugin` from `str` to `bool`, ensuring correct usage as a boolean flag.
**Fixes**: N/A
**Tests**: Existing tests apply; no new tests needed.
**Documentation**: Not affected.
> Fix `is_train_batch_min` type in DeepSpeedPlugin

- examples/by_feature/deepspeed_with_config_support.py
- examples/by_feature/megatron_lm_gpt_pretraining.py
- examples/requirements.txt
`Repository` is a deprecated feature in `huggingface_hub`. It is more robust to use the HTTP-based methods from `HfApi` instead. [Here is a doc page explaining why it's better](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http). Main reasons are 1. don't need to clone a repo to push files 2. faster upload speed 3. don't need git/git+lfs configured locally.
`transformers` switched to use `HfApi` is all their training scripts in Aug 23' (see https://github.com/huggingface/transformers/pull/25095) without breaking. Let's do the same for `accelerate`!
**Disclaimer:** I did not test those changes myself. Should be fine though.
Similar PRs: https://github.com/huggingface/peft/pull/1641 https://github.com/huggingface/parler-tts/pull/18
> Don't use deprecated `Repository` anymore

- src/accelerate/state.py
Hi @muellerzr . This PR fixed the backend assignment. It avoids confusing backend checks and distributed_type checks. We should assign distributed_type by env first and then decide whether to assign backend.
Do you know how to add a proper test to avoid this issue? Please let me know, and I will add it : )
> fix backend check

- src/accelerate/state.py
We are using accelerate's megatron plugin on the NPU.
Specifically, there are two scenarios:
1. After we `import torch_npu`, `torch.cuda.is_available()` is False, which is the `MULTI_NPU` branch.
2. When we `import transfer_to_npu from torch_npu.contrib`, `torch.cuda.is_available()` is True, which is the `MULTI_GPU` branch.
Therefore, in fact, accelerate's megatron plugin supports both `MULTI_GPU` and `MULTI_NPU` scenarios.
> Megatron plugin can support NPU

- docs/source/usage_guides/deepspeed.md
- src/accelerate/accelerator.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/launch.py
- tests/deepspeed/test_deepspeed.py
1. Changes to support MoEs with DeepSpeed. For DS Z3 to work properly without hanging, one needs to follow this https://github.com/microsoft/DeepSpeed/pull/5008 so that DeepSpeed doesn't split the MOE layers further which can be called in different orders depending on inputs leading to invalid traces as well as hangs during reduce_scatter calls when an expert is unused on 1 rank but used on the other.
2. This PR enables this via new config argument `deepspeed_moe_layer_cls_names`. An example of config is given below:
```
compute_environment: LOCAL_MACHINE                                                                                                                                           
debug: false …
```
> Handle MoE models with DeepSpeed

- src/accelerate/utils/tqdm.py
- tests/test_utils.py
This PR is a follow-up to https://github.com/huggingface/accelerate/pull/2654, specifically it:
1. Writes a new test to check that the deprecation is flagged
2. Changes the logic slightly to check if users are passing in `disable` explicitly as a kwarg. We should be respecting this if so
@SunMarc or @BenjaminBossan
> Deprecate tqdm args + slight logic tweaks

- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_distributed_data_loop.py
1. Fix the rng states of sampler's generator to be synchronized for correct sharding of dataset across GPUs
Example:
1. Code:
```
import torch
from torch.utils.data import default_collate,default_convert, Dataset, DataLoader, BatchSampler, RandomSampler, SequentialSampler
import numpy
from accelerate import Accelerator
from accelerate.utils import set_seed
from accelerate.utils.random import synchronize_rng_state
from accelerate.utils.dataclasses import DistributedType, RNGType
import os
import sys
import platform
class MyDataset(Dataset):
def __len__(self):
return 22
def __getitem__(self, index):
squeeze = False
if isinstance(index, int):
index = [index]
squeeze = True
elif isinstance(index, slice):
index = list(range(*index.indices(self.size)))
else:
index = …
```
> Fix the rng states of sampler's generator to be synchronized for correct sharding of dataset across GPUs

- src/accelerate/accelerator.py
- src/accelerate/utils/imports.py
This PR fixes the support of AMP with mps. It was never supported in the first place. When this [PR](https://github.com/pytorch/pytorch/pull/99272) from pytorch gets merged, we can revert this PR. However, one can safely load a model in bf16 or fp16 with mps device with the latest torch. 
Fixes https://github.com/huggingface/accelerate/issues/2693
> Block AMP for MPS device 

- docs/source/quicktour.md
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/utils/dataclasses.py
Currently, it seems that even with pinned memory enabled on the dataloader, iterating over the dataloader causes a cudaStreamSynchronize call:
This is a devastating hit to performance if you are trying to overlap any other asynchronous transfers with your computations (such as offloading optimizer/EMA states), since it appears to be waiting for all async transfers to complete before continuing.
Setting these operations to be non-blocking, as well as using pinned memory for the dataloader, gets rid of the offending call:
(the timescale is very different here, this one is a fraction of a millisecond whereas the previous screenshot highlights a period of roughly one entire second)
With this, the tensors should only get forcibly synced when they are about to be used, and other non-blocking …
> Change dataloader send_to_device calls to non-blocking

- src/accelerate/accelerator.py
This PR fixes a bug that users who want to perform multi-gpu training with bnb gets when the first gpu is not used. In this [PR](https://github.com/huggingface/accelerate/pull/1155), you see that we did not allow multi-gpu training before and [all the code after](https://github.com/huggingface/accelerate/pull/1155/files#:~:text=current_device_index%20%3D%20list,.device%3A) that assume that we are in a single gpu setup. Since then, we added the possibility to perform multi-gpu training using naive PP. However, the logic after the multi-gpu check stayed the same as you can see on [main](https://github.com/huggingface/accelerate/blob/6af157ea93dfbace1db88b0fdc7dfb568dfdd5a5/src/accelerate/accelerator.py#L1393) . A quick fix would be to just add an elif statement. 
Fixes …
> fix bnb multi gpu training

- docs/source/quicktour.md
- src/accelerate/accelerator.py
This Pr makes `gather_for_metrics` more flexible when it comes to tensors. We introduce `use_gather_object` flag that enable users to gather object even if the input data is composed of tensors only. This is useful in the case the tensors have different sizes and we don't wanna end up padding all tensors to the same shape/size as it might be a bit complicated afterwards. Note that this is not very efficient for tensors on GPU. Also, we make sure that we do not adjust the sample when we are not in distributed setup. 
cc [qubvel](https://github.com/qubvel) could you try your use case by setting `use_gather_object = True` ? 
Fixes https://github.com/huggingface/transformers/issues/30357
```python
import torch
import random
from torch.utils.data import DataLoader, Dataset
from accelerate …
```
> allow gather_for_metrics to be more flexible

- docs/source/_toctree.yml
- docs/source/concept_guides/fsdp_and_deepspeed.md
- docs/source/package_reference/cli.md
- src/accelerate/accelerator.py
This PR address the issues identified in #2624, whereby differences were found between how DeepSpeed (DS) and FSDP handle the sharded parameters during mixed precision. To address this we have:
- added logic in `accelerate.prepare` to upcast the FSDP sharded paramaters, if it has been detected that:
1. mixed precision has been activated, and,
2. the sharded parameters are in low precision.
- added concept guide to clarify to how DS and FSDP handles mixed precision. Also to inform that 🤗  Accelerate will upcast FSDP sharded weights.
- added warning to inform user, that if the weights were upcasted, then this will affect the precision in which the checkpoint will be saved. 
In addition to the above, we also:
- int the above mentioned concept guide, clarified the equivalences between DS and …
> Add Upcasting for FSDP in Mixed Precision. Add Concept Guide for FSPD and DeepSpeed. 

- .github/workflows/build-docker-images-release.yml
- .github/workflows/build_docker_images.yml
- .github/workflows/nightly.yml
- .github/workflows/run_merge_tests.yml
- .github/workflows/self_hosted_integration_tests.yml
- docker/README.md
- docker/accelerate-gpu-deepspeed/Dockerfile
- setup.py
Deepspeed has required python v3.10, which is above our minimum. To keep with our 3.9 requirement, this PR adds a new docker image specific for deepspeed with the required tags
Should fix our tests on main
New tag added: `huggingface/accelerate:gpu-deepspeed`
@pacman100
> Segment out a deepspeed docker image

- examples/by_feature/cross_validation.py
- src/accelerate/accelerator.py
- tests/test_accelerator.py
Tweaks `Accelerator.free_memory` to take in `*objects` and return `*objects`. This is because we need to fully replace the values, doing just `del` doesn't *actually* help as much as it should. 
Solves https://github.com/huggingface/accelerate/issues/2715, graph:
Solves https://github.com/huggingface/transformers/issues/28178
(Weird read, I know, I think it's because they delay the reading of the computer for a few seconds). But I think because the graphs are identical that's **good**
Anyone in the community is free …
> Fixup `free_memory` to deal with garbage collection

- src/accelerate/checkpointing.py
- src/accelerate/data_loader.py
This PR fixes an issue with sampler serialization. The sampler do not necessarily have a sampler attribute. I think this is only the case when the sampler is a `SeedableRandomSampler`. To fix the issue, we create a getter and setter function to get the sample of the dataloader. 
You need to use num_processes >= 2 :
```python 
from typing import Iterator
from torch.utils.data import IterableDataset,DataLoader
from accelerate import Accelerator, DataLoaderConfiguration
class FooSet(IterableDataset):
def __iter__(self) -> Iterator:
for i in range(100):
yield i
dset = FooSet()
dloader = DataLoader(dset, batch_size=1)
dataloader_config = DataLoaderConfiguration(dispatch_batches=False, split_batches=False)
ac = Accelerator(
dataloader_config = dataloader_config
)
dloader = ac.prepare(dloader) …
```
> fix sampler serialization

- docs/source/concept_guides/fsdp_and_deepspeed.md
- docs/source/package_reference/deepspeed.md
- docs/source/usage_guides/deepspeed.md
- docs/source/usage_guides/fsdp.md
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/launch.py
Address @stas00's comments that was omitted when we merged  #2674 
@stas00 @muellerzr
> Fix Documentation in FSDP and DeepSpeed Concept Guide

- src/accelerate/utils/dataclasses.py
Fixes the data type of offload device in `DeepSpeedPlugin` from `bool` to `str`.
N/A
> Fix deepspeed offload device type

- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- tests/test_accelerator.py
- tests/test_multigpu.py
Fixes the following on our red CI:
* We need to run `gc.collect()` and `torch.cuda.empty_cache()` on the memory test to make sure a full good reset state is present
* Missing some `@require` on the pippy tests
@SunMarc
> Fix tests on main

- src/accelerate/commands/launch.py
This pull request aims to enable the `accelerate launch` to redirect std streams into log files. 
When I am using torchrun to launch the training scripts, I am able to use --log-dir and --tee to redirect all streams into log files to help debugging. But when I use `accelerate launch`, even though the backend launcher is torchrun, I was unable to achieve that. Thus I would like to add a `--log-dir/--log_dir` argument near the `--tee` argument to improving the logging capability of `accelerate launch`. It's just a few lines of code but it does make debugging much easier when running multi-node training.
Thanks!
[here are tips on formatting …
> Add feature to allow redirecting std streams into log files when using torchrun as the launcher. 

- src/accelerate/utils/modeling.py
In the current implementation of the library, when deploying tensor operations across multiple GPU devices, the program attempts to initialize a tensor on each device and get maximum available memory. 
```
def get_max_memory(max_memory: Optional[Dict[Union[int, str], Union[int, str]]] = None):
...
for i in range(torch.cuda.device_count()):
_ = torch.tensor([0], device=i)
max_memory = {i: torch.cuda.mem_get_info(i)[0] for i in range(torch.cuda.device_count())}
```
However, this approach leads to an error and terminates the program if it encounters a GPU that is unavailable(memory fully occupied or device damaged). 
For example, this error will occur when one of the devices is fully occupied:
```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at …
```
> Update modeling.py by adding try-catch section to skip the unavailable devices

- src/accelerate/logging.py
- tests/test_logging.py
Fixes #2114
Currently, `accelerate.logging` does not correctly log the *user* call site of log functions such as `.log()` and `.info()`. Consider the following example modified from issue #2114:
```python
import logging
from accelerate import Accelerator
from accelerate.logging import get_logger
from rich.logging import RichHandler
logger = get_logger(__name__)
if __name__ == "__main__":
accelerator = Accelerator()
logging.basicConfig(
format="%(filename)s:%(name)s:%(lineno)s - %(message)s",
datefmt="%m/%d %H:%M:%S",
level=logging.INFO,
handlers=[RichHandler(show_time=True, show_level=True, show_path=True)],
)
logger.info("Test")
```
In its current state, the above script shows something like
```
05/01 19:26:22 INFO     logging.py:__main__:61 - Test
```
The calling site of the logging …
> Fix stacklevel in `logging` to log the actual user call site (instead of the call site inside the logger wrapper) of log functions

- src/accelerate/state.py
This PR corrects the environment variable check for `DistributedType.MULTI_CPU` in `accelerate/state.py`. Previously, the variable `OMP_NUM_THREADS` was duplicated. This update ensures that only one variable exists.
> Fix duplicate environment variable check in multi-cpu condition

- src/accelerate/commands/launch.py
- src/accelerate/state.py
Hi @muellerzr 
This PR fixed the cpu num threads set. We should set a default value if the env parameter `OMP_NUM_THREADS` is not set.
Besides, we should keep `OMP_NUM_THREADS` instead of replacing it in `launch.py`. Could you pls review it? Thx!
> fix cpu omp num threads set

- src/accelerate/utils/dataclasses.py
Enables sharded CPU resuming when using FSDP and CPU offloading is enabled
For people potentially googling:
This solves the issue where you could hit a CUDA out-of-memory (CUDA OOM) issue when resuming checkpoints as it would try to load everything onto the GPU, when instead we need to offload on CPU
@pacman100
> Enable sharded cpu resume

- src/accelerate/utils/modeling.py
When I try to inference deepseek-v2 with transformers:
```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
model_name = "deepseek-ai/DeepSeek-V2"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
max_memory = {i: "75GB" for i in range(8)}
model = AutoModelForCausalLM.from_pretrained(model_name, trust_remote_code=True, device_map="sequential", torch_dtype=torch.bfloat16, max_memory=max_memory, attn_implementation="eager")
model.generation_config = GenerationConfig.from_pretrained(model_name)
model.generation_config.pad_token_id = model.generation_config.eos_token_id
text = "An attention function can be described as mapping a query and a set of key-value pairs to an output, where the query, keys, values, and …
```
> optimize get_module_leaves speed

- src/accelerate/utils/modeling.py
This PR fixes a small edge case when we compute the leaves of a model introduced in this [PR](https://github.com/huggingface/accelerate/pull/2756) . This should solves the failing test in our CI.
> Fix small edge case in get_module_leaves

- tests/deepspeed/test_deepspeed.py
This PR skips the deepspeed test since it started failing with deepspeed > 0.12.6. This is most probably an issue on deepspeed side cc @pacman100. Let's make sure to not forget about this test :/ .
> Skip deepspeed test

- tests/test_big_modeling.py
This PR skips a flaky test. Not sure why it happens but the `data_ptr() `of `compute2.weight` is sometimes the same of `compute1.weight.` Hence it is using the same value as compute1 through self.tied_params_map and we get an assert error. I checked that the values are not the same but it gives the same address. This does not happen on my local machine and it passes sometimes on the CI. Maybe an issue with the hardware. We should have enough coverage with `test_dispatch_model_tied_weights_memory_with_nested_offload_cpu`, so I think it's fine if we skip it. 
cc @fxmarty
> Skip tied weights disk offload test

- src/accelerate/utils/fsdp_utils.py
Fixes: https://github.com/huggingface/transformers/issues/30908
As per title - I propose a simple fix as a follow up of https://github.com/huggingface/accelerate/pull/2772 in order to make `accelerate` happy for users with earlier torch versions. Currently when trying to import anything from accelerate using torch < 2.3.0 it fails
```bash
import torch.distributed.checkpoint.format_utils as dist_cp_format_utils
ModuleNotFoundError: No module named 'torch.distributed.checkpoint.format_utils'
```
cc @muellerzr
> FIX / FSDP : Guard fsdp utils for earlier PyTorch versions

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/megatron_lm.py
#2390 
I want to use accelerate with megatron, and I do many changes in nvidia's megatron framework.
But when I use MegatronLMPlugin, it is using huggingface's megatron and it is not maintaining now. 
This pr upgrades huggingface's megatron to nvidia's megatron, so we will don't need to maintain huggingface's megatron. And I can also use my changes in nvidia's megatron framework.
By the way, we will use `pip install --no-use-pep517 -e .` to install nvidia's megatron.
> Upgrade huggingface's megatron to nvidia's megatron when use MegatronLMPlugin

- tests/test_cli.py
https://github.com/huggingface/transformers/commit/0ae789e04330e15a90e34cd723c851a8ab8d7ec5#diff-a48ba7f6444ca4954a58f1ac3e66c7941a2bbc4615649d56b182aeac8cc36d9c introduced `_no_split_modules` to the Bert config in the last release...which caused our tests to fail because the largest layer group is now the embeddings!
Changes the tests to reflect this behavior (since it's actually what we want)
Fixes failing tests on main + nightlies
Anyone in the community is free to review the PR once the tests have passed. Feel …
> Fixup CLI test

- docs/source/basic_tutorials/notebook.md
- src/accelerate/launchers.py
- src/accelerate/test_utils/scripts/test_notebook.py
This PR enhances the `notebook_launcher` function by adding support for elastic launch, enabling fault tolerance. Previously, elastic launch was only supported when using the `accelerate` or `torchrun` CLI command. With this update, users can now launch custom training loops with elastic capabilities directly from a Python script.
The implementation draws on most of the launching code from [PyTorch's launcher API](https://github.com/pytorch/pytorch/blob/91bf952d10e9524a9b078900d9807efa5d252f5c/torch/distributed/launcher/api.py). Variable names and default values are chosen to align with Accelerate CLI standards.
Key features introduced:
- Parameters such as `rdzv_backend`, `rdzv_endpoint`, `rdzv_conf`, `rdzv_id`, `max_restarts`, and `monitor_interval` are added to `notebook_launcher`.
- …
> Add Elastic Launch Support to `notebook_launcher`

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/test_sync.py
As pointed  @Nightmare-n [here](https://github.com/huggingface/transformers/issues/29425#issuecomment-2116574203), the fix of [#29425](https://github.com/huggingface/transformers/issues/29425) was incorrect all this while, due to a misunderstanding of how `sync_gradients` is used to signal also [optimizer step](https://github.com/huggingface/accelerate/blob/main/src/accelerate/optimizer.py#L153).
**Tested On mistralai/Mixtral-8x7B-Instruct-v0.1**:
1. `torch =  2.2.0` , regressed changes to `accelerate = 0.28` (because latest `accelerate` does not support old torch
2. `torch = 2.3` with this PR
In both cases we observed the similar effect of the grad accumulation working on this new fix; the results shown below is from case 1.
Fixes …
> Fix Wrong use of sync_gradients used to implement sync_each_batch 

- tests/test_tracking.py
This PR fixes the comet ml test that is failing on the CI. The issue is that there is a breaking change in their latest version. The payload structure is not the same anymore: 
old version: 
`'{"payload":{"local_timestamp":1716817708970,"log_other":{"key":"my_text","val":"some_value"},"message_id":20},"type":"ws_msg"}'`
new version:
`'{"payload":{"key":"my_text","message_id":20,"value":"some_value"},"type":"log_other"}'`
This seems intentional on comet-ml side, so O'm fixing how we parse the results.
> fix comet ml test

- src/accelerate/utils/modeling.py
This PR removes the outdated and unnecessary code of xpu device check in the following code snippet
```python
if (
d != "cpu"
and (torch.device(d).type == "xpu" or torch.xpu.get_device_properties(d).dev_type == "gpu")
)
```
The reasons are 
- If torch.xpu.get_device_properties(d) works, torch.device(d).type will always be "xpu"
- If torch.device(d).type == "xpu", `d` will definitively not be "cpu"
`torch.device(d).type == "xpu"` is enough to check xpu device just like the case in MLU and  NPU.
@SunMarc and @muellerzr
> Remove out-dated xpu device check code in `get_balanced_memory`

- docs/source/usage_guides/deepspeed.md
- src/accelerate/accelerator.py
- tests/deepspeed/test_deepspeed.py
This PR changes the `zero_optimization.stage3_prefetch_bucket_size` config value to be an integer. With the impending Pydantic v2 update in DeepSpeed, we run into validation errors if the value is a float. The [documentation](https://www.deepspeed.ai/docs/config-json/) states that this value should be an integer.
cc @muellerzr
> Fix DeepSpeed config validation error by changing `stage3_prefetch_bucket_size` value to an integer 

- src/accelerate/test_utils/testing.py
@stas00 and Nikita (sorry don't know your gh handle!) and I were investigating why `accelerate launch` is *so slow* during tests.
Turns out pytorch isn't respecting the `monitor_interval` default of 0.1 for *some reason* and it's being set to 5 seconds instead. So, magically do that and the `test_multigpu.py` is sped up by 30% (`33.40s` -> `23.29s`) and `test_core` was sped up by 25% (`102.23s (0:01:42)` -> `76.94s (0:01:16)`
Anyone in the community is free to review the PR once the tests have passed. …
> Improve test speeds by up to 30% in multi-gpu settings

- docs/source/concept_guides/fsdp_and_deepspeed.md
> doc: fix link

- src/accelerate/utils/fsdp_utils.py
If the merge save_dir does not exist, the accelerate merge-weight will crash after a long time (Weights already merged in memory)
```
$ accelerate merge-weights checkpoint-2000/pytorch_model_fsdp_0/ checkpoint-2000-merged-weight
File "/home/jobuser/.local/bin/accelerate", line 8, in <module>
sys.exit(main())
File "/home/jobuser/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
args.func(args)
File "/home/jobuser/.local/lib/python3.10/site-packages/accelerate/commands/merge.py", line 27, in merge_command
merge_fsdp_weights(
File "/home/jobuser/.local/lib/python3.10/site-packages/accelerate/utils/fsdp_utils.py", line 270, in merge_fsdp_weights
save_path = _distributed_checkpoint_to_merged_weights(checkpoint_dir, …
```
> Auto create dir when merging FSDP weights

- src/accelerate/accelerator.py
- src/accelerate/utils/imports.py
Fixes: https://github.com/huggingface/transformers/issues/31237
XPU backend is available in the stock PyTorch starting from version 2.4 [1]. This commit extends huggingface accelerate to support XPU from both IPEX and the stock pytorch. IPEX is being tried first.
Raising this PR as WIP and Draft to facilitate further discussion around XPU backend enabling in huggingface and be able to communicate observed XPU issues back to PyTorch.
[1] https://github.com/pytorch/pytorch/issues/114842
@EikanWang, @fengyuan14, @guangyey, @jgong5, @kding1, @sywangyi
> xpu: support xpu backend from stock pytorch (>=2.4)

- src/accelerate/utils/imports.py
That's a follow up to cleanup the code in npu and mlu paths. Noted here: https://github.com/huggingface/accelerate/pull/2825#discussion_r1638310778
`import torch` is actually done file-wise and is not needed: https://github.com/huggingface/accelerate/blob/3b5a00e048f4393398d8ea8c4f468857f595f039/src/accelerate/utils/imports.py#L21
**CAVEAT:** I don't have HW to verify npu and mlu paths with tests.
CC: @SunMarc, @muellerzr
> Drop torch re-imports in npu and mlu paths

- src/accelerate/commands/merge.py
The new accelerate merge-weights should default use safetensors format. However, it is using bin format.
```
$ accelerate merge-weights checkpoint-2000/pytorch_model_fsdp_0/ checkpoint-2000-merged-weight
$ ls checkpoint-2000-merged-weight
pytorch_model.bin
```
After this change it is now `model.safetensors`
@muellerzr 
> Default FSDP weights merge to safetensors

- tests/test_tracking.py
This PR fixes the following failed test:
```bash
(accelerate) root@150f3b602a91:/workspace/code# python -m pytest -rA -k "ClearMLTest" tests
============================================================ test session starts =============================================================
platform linux -- Python 3.9.19, pytest-8.0.0, pluggy-1.5.0
rootdir: /workspace/code
plugins: subtests-0.12.1, xdist-3.6.1, hydra-core-1.3.2, anyio-4.2.0
collected 334 items / 329 deselected / 5 selected                                                                                            
tests/test_tracking.py FFFFF                                                                                                           [100%]
================================================================== FAILURES …
```
> [tests] fix bug in `test_tracking.ClearMLTest`

- tests/test_big_modeling.py
- tests/test_hooks.py
Below is the rest result for `tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_with_hook` on XPU:
```bash
===================================================== test session starts =====================================================
platform linux -- Python 3.9.0, pytest-8.0.0, pluggy-1.5.0
rootdir: /home/fanli/workspace/accelerate
plugins: subtests-0.12.1, excel-1.6.0, env-1.1.3, xdist-3.6.1
collected 1 item                                                                                                              
tests/test_big_modeling.py F                                                                                            [100%]
========================================================== FAILURES =========================================================== …
```
> [tests] use `torch_device` instead of `0` for device check 

- src/accelerate/test_utils/scripts/external_deps/test_zero3_integration.py
```bash
python -m pytest -rA -k "test_zero3_integration" tests/deepspeed
```
The command above gives the following error: 
```bash
E           Traceback (most recent call last):
E             File "/home/fanli/workspace/accelerate/src/accelerate/test_utils/scripts/external_deps/test_zero3_integration.py", line 52, in <module>
E               main()
E             File "/home/fanli/workspace/accelerate/src/accelerate/test_utils/scripts/external_deps/test_zero3_integration.py", line 48, in main
E               init_torch_dist_then_launch_deepspeed()
E             File "/home/fanli/workspace/accelerate/src/accelerate/test_utils/scripts/external_deps/test_zero3_integration.py", line 30, in init_torch_dist_then_launch_deepspeed
E …
```
> [tests] enable XPU backend for `test_zero3_integration`

- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
This PR adds support to checkpoint the `step`(internal step tracker) value while calling `Accelerator.save_state` and also makes appropriate changes to `Accelerator.load_state` to support the loading of the saved `step`.
Fixes #2702 
@muellerzr
> Support saving and loading of step while saving and loading state

- src/accelerate/launchers.py
- src/accelerate/utils/constants.py
This PR addresses an issue with the `notebook_launcher` in the `accelerate` library, where the inclusion of the `log_line_prefix_template` argument in the `LaunchConfig` instantiation leads to a `TypeError` in certain PyTorch versions. By making this argument optional, we ensure compatibility across all supported PyTorch versions.
The `notebook_launcher` function in the `accelerate` library currently includes a `log_line_prefix_template` argument when creating a `LaunchConfig` instance. However, this argument is not supported in some versions of PyTorch, resulting in a `TypeError`. To maintain compatibility with all supported versions of PyTorch, this PR makes the inclusion of the `log_line_prefix_template` argument conditional.
- Added a `log_line_prefix_template` parameter to the …
> Make `log_line_prefix_template` Optional in Elastic Launcher for Backward Compatibility

- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- tests/test_utils.py
`test_dynamo` works on xpu, but fails because it requires extra installation of the triton library. This PR adds the `require_triton` test marker and make `test_dynamo` device-agnostic.
> add `require_triton` and enable `test_dynamo` work on xpu

- src/accelerate/test_utils/testing.py
- src/accelerate/utils/memory.py
- src/accelerate/utils/modeling.py
This PR introduces 2 updates:
1. adds new `clear_device_cache` function in memory.py to replace repetitive code. This also adds check for mps devices in  function `find_executable_batch_size`. This feature was tested with tests/test_memory_utils.py, which had bug.
2. fixes bug in `get_backend` function where function's 3rd outputs must be callable object. This bug caused failures in tests/test_memory_utils.py on MacOS. …
> Fix get_backend bug and add clear_device_cache function

- src/accelerate/utils/memory.py
https://github.com/huggingface/accelerate/pull/2857 introduced using `gc.collect()` as part of the `clear_device_cache`. This is *very* slow to do and increases the time to load models exponentially when using `device_map="auto"` (e.g. `llama-3-8B` went from 6.663s to 37.535s).
This PR adds a `garbage_collection` flag which is `False` by default.
Fixes https://github.com/huggingface/accelerate/issues/2911
members/contributors …
> Fix slowdown on init with `device_map="auto"`

- src/accelerate/commands/launch.py
Fixes a bug in the `accelerate launch` command which enables `multi_gpu` even with `num_processes` being set to 1.
https://github.com/huggingface/accelerate/issues/2920
> fix: bug where mulit_gpu was being set and warning being printed even with num_processes=1

- src/accelerate/utils/fsdp_utils.py
This PR expounds the error messages given when passing in a checkpoint directory, specifying if model or optimizer FSDP directories were found.
Each of these have `pytorch_model_fsdp_0` and `optimizer_0` for folders, so we can check for their existence and direct the user on what to do.
Fixes https://github.com/huggingface/accelerate/issues/2848
@SunMarc
> Better error when a bad directory is given for weight merging

- setup.py
There is no `huggingface_hub` version in setup.py. It can lead to errors in some installations:
```
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
File "/root/miniconda3/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module> 
from .accelerator import Accelerator
File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 34, in <module>
from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```
`split_torch_state_dict_into_shards` was added in [0.21.0](https://github.com/huggingface/huggingface_hub/releases/tag/v0.21.0) version of …
> Add huggingface_hub version to setup.py

- src/accelerate/checkpointing.py
- tests/test_accelerator.py
I would run into problems with PyTorch's _load_state_dict_ complaining about missing keys. These keys belonged to shared tensors. These shared keys are intentionally omitted by the safetensors library. To load a model correctly, one has to use safetensor's _load_model_ function instead of the default _load_state_dict_ function (described [here](https://huggingface.co/docs/safetensors/torch_shared_tensors)). This was previously not done when using the _load_state_ function of the _Accelerator_.
I think this issue might be relevant as they also report problems when loading with _accelerator.load_state_.
https://github.com/huggingface/accelerate/issues/2155
[documentation …
> Correct loading of models with shared tensors when using accelerator.load_state()

- .github/workflows/test.yml
This PR corrects the CI workflow to ensure that the minimum specified PyTorch version (1.10.0) is installed when the `matrix.pytorch-version` is set to `minimum`. Previously, the installation condition incorrectly referenced `matrix.test-kind`, leading to the installation of the latest PyTorch version instead.
- Corrected the conditional check for installing PyTorch 1.10.0 by changing `matrix.test-kind` to `matrix.pytorch-version`.
```yaml
if [[ ${{ matrix.test-kind }} = minimum ]]; then pip install torch==1.10.0; fi
```
```yaml
if [[ ${{ matrix.pytorch-version }} = minimum ]]; then pip install torch==1.10.0; fi
```
This change ensures that the CI workflow correctly installs PyTorch 1.10.0 when the `matrix.pytorch-version` is set to `minimum`. This avoids any inconsistencies and ensures …
> Hotfix PyTorch Version Installation in CI Workflow for Minimum Version Matrix

- src/accelerate/state.py
This PR deletes some CCL environment variable setting. With versions updating of software stack, current torch-CCL don't recommend manually setting these CCL env vars like 'CCL_LOCAL_SIZE', 'CCL_LOCAL_RANK' or 'CCL_PROCESS_LAUNCHER'.
And  `os.environ.get("LOCAL_WORLD_SIZE", "1")
os.environ.get("LOCAL_RANK", "0")`
may not get the correct value. For example, when run fine-tuning with deepspeed on multiple gpus, it will get wrong value and pass them to torchCCL comm backend, which will result in crash.
> delete CCL env var setting

- src/accelerate/utils/modeling.py
This PR adds the `torch.float8_e4m3fn` in `dtype_byte_size` function, so that we can calculate the memory required for this specific datatype
> Add `torch.float8_e4m3fn` format `dtype_byte_size`

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
This PR fixes compatibility for bitsandbytes `Params4bit` and `set_module_tensor_to_device`.
Related: https://github.com/bitsandbytes-foundation/bitsandbytes/pull/1279
@muellerzr @SunMarc
> Properly handle Params4bit in set_module_tensor_to_device

- setup.py
Fixes #2939
Changes made in `accelerate` PR https://github.com/huggingface/accelerate/pull/2875 require passing the arg `device` into `safetensors.torch.load_model`. This was not supported until after the `safetensors` PR https://github.com/huggingface/safetensors/pull/449 which is contained starting from release `v0.4.3`
Note: `conda` does not contain this release yet.
> Require safetensors>=0.4.3

- src/accelerate/accelerator.py
Fixes https://github.com/huggingface/accelerate/issues/2958
There are more details and a repro case in the issue above - it appears the `unwrap` args is unused when getting the state dict and running FSDP, which seems to cause shared pointers/tied weights to behave inconsistently.
> Enable Unwrapping for Model State Dicts (FSDP)

- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
To not break prior releases, checks if `step` exists in our checkpoint to try and load it in.
Fixes https://github.com/huggingface/accelerate/issues/2923
> Explicit check for `step` when loading the state

- src/accelerate/big_modeling.py
Fixes #2996
This fixes a typo on a warning string [(link to the line)](https://github.com/huggingface/accelerate/blob/d982751aecc020a58a5583473eabe8d281f5f114/src/accelerate/big_modeling.py#L437).
Typo: "Some parameters are on the meta device device" -> "Some parameters are on the meta **device**"
- Big modeling: @SunMarc
> Fix typo on warning str: "on the meta device device" -> "on the meta device"

- src/accelerate/data_loader.py
At present, when using the resume_from_checkpoint feature in the Transformers Trainer, it results in an error because `skip_first_batches` does not support `MpDeviceLoaderWrapper` of `XLA`. This PR supports this feature.
@muellerzr
> Support skip_first_batches for XLA

- src/accelerate/hooks.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/memory.py
This PR clears the memory in `CpuOffload` after we offload the previous module to the `cpu` ( used a lot in `cpu_offload_with_hook` ). This helps a lot with cpu offloading in diffusers as this is more efficient with the VRAM usage.
cc @sayakpaul
> clear memory after offload

- src/accelerate/state.py
- src/accelerate/utils/dataclasses.py
- tests/fsdp/test_fsdp.py
This PR removes the need to lock the user into using `accelerate launch` when using FSDP + accelerate. Instead, the user can now fully create a `FullyShardedDataParallelPlugin` manually.
Users of accelerate who want the flexibility of FSDP without needing `accelerate launch`
Closes https://github.com/huggingface/accelerate/issues/2973
Limiting users to using global variables long-term is not good because it hides much of what's going on in the env, with no way to pull them down easily.
A user can now use `FullyShardedDataParallelPlugin` manually:
```python
from accelerate import FullyShardedDataParallelPlugin
plugin = FullyShardedDataParallelPlugin(
strategy="FULL_SHARD"
)
```
This was an entire refactor to the internals of the dataclass, allowing for every variable to be passed in, new …
> Make env variables optional for FSDP

- docs/source/package_reference/fsdp.md
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/fsdp_utils.py
- tests/fsdp/test_fsdp.py
Enables users to quickly do:
```python
from accelerate.utils import enable_fsdp_ram_efficient_loading
enable_fsdp_ram_efficient_loading()
model = AutoModel.from_*
```
(Also some tests got commented out when I was toying with things, hence the odd diff)
@BenjaminBossan 
Note that we have `self.ram_efficient_loading` in the FSDP Plugin. For clarity it should …
> Add small util to enable FSDP offloading quickly

- src/accelerate/commands/launch.py
When a distributed run is launched with `accelerate launch myscript.py` under the hood it launches mpirun. 
The logic that sets the num_of_threads_per_process for good OOB performance relies on the environment variables that are yet unassigned because mpirun is called after the environment variables are read.
```
local_size = get_int_from_env(
["MPI_LOCALNRANKS", "OMPI_COMM_WORLD_LOCAL_SIZE", "MV2_COMM_WORLD_LOCAL_SIZE"],
max(args.num_processes/args.num_machines,1)
)
threads_per_process = int(psutil.cpu_count(logical=False) / local_size)
```
https://github.com/huggingface/accelerate/blob/cd5698bb324352a80a2a2b5d8bfccf495e14bf6b/src/accelerate/commands/launch.py#L1063 
The solution is to calculate the rank per node assuming total number of processes are equally distributed across the …
> fix default value for rank size in cpu threads_per_process assignment logic

- src/accelerate/accelerator.py
With the latest version of torch, when we use multi-gpu, torch will trigger a warning asking us to call `destoy_process_group()`. This PR fixes this by adding that in end_training method. Note that this function needs to be called on all process. 
For trackers, we are already only executing the methods on the main process. See [here](https://github.com/huggingface/accelerate/blob/851cf3435135d4be28a7569e61fb7c9466d68291/src/accelerate/tracking.py#L108). So it should be safe to remove the on_main_process decorator in the end_training method. 
However, I see for [WandBTracker](https://github.com/huggingface/accelerate/blob/851cf3435135d4be28a7569e61fb7c9466d68291/src/accelerate/tracking.py#L289) that `main_process_only = False`. Is there a specific reason @muellerzr ?
> destroy process group in `end_training`

- docs/source/concept_guides/low_precision_training.md
- docs/source/usage_guides/low_precision_training.md
- src/accelerate/commands/config/cluster.py
- src/accelerate/utils/dataclasses.py
Per the NVIDIA team, we should be using HYBRID for training, E4M3 during inference. As a result, tweaks the default to be HYBRID
> Tweak defaults for quantized-typed FP8 TE weights

- src/accelerate/accelerator.py
- src/accelerate/utils/constants.py
- src/accelerate/utils/other.py
The current version check doesn't actually do what it's meant to, as `2.1.0a` gets parsed as LT for `2.1.0`, making it impossible to do FSDP properly for MS-AMP rn.
*Technically* this is true, but it works so we can adjust this. 
> Fix torch version check

- README.md
- docs/source/quicktour.md
- examples/README.md
- examples/config_yaml_templates/README.md
- examples/config_yaml_templates/deepspeed.yaml
- examples/config_yaml_templates/fp8.yaml
- examples/config_yaml_templates/fsdp.yaml
- examples/config_yaml_templates/multi_gpu.yaml
- examples/config_yaml_templates/multi_node.yaml
- examples/config_yaml_templates/run_me.py
- examples/config_yaml_templates/single_gpu.yaml
- src/accelerate/commands/config/config_args.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/launch.py
This PR introduces a config zoo to the repo, showcasing a number of "template" config files users can use. 
This PR also tweaks how the config yamls are read, so we can simplify certain configurations better, relying on inferred (but valid) parameters, which our CLI already does.
E.g. this is a full, complete, valid config yaml for single-gpu bf16 training:
```yaml
distributed_type: "NO"
mixed_precision: "bf16"
```
Anyone in the community is free to review the PR once the tests have passed. Feel free …
> Improve config handling and add a zoo

- src/accelerate/data_loader.py
- tests/test_data_loader.py
https://github.com/huggingface/accelerate/issues/3011
- Core parts of the library: @BenjaminBossan
> Fix batch_sampler maybe None error

- src/accelerate/data_loader.py
- tests/test_data_loader.py
Following #3039, decouples `prepare_data_loader()` (and all DataLoader classes/mixins in `data_loader.py`) from relying on `AcceleratorState` (and by extension, a properly initialized `Accelerator`), instead relying on `PartialState`. Fixes and extends tests in `test_data_loader.py` to validate both the non-Accelerator and decoupled workflows.
The benefit of this is that now folks can use `prepare_data_loader` and the nice features it provides (`put_on_device`, `split_batches`) without restructuring the rest of their training code around `Accelerator`. 
[here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writ …
> Decouple `prepare_data_loader()` from Accelerator

- CONTRIBUTING.md
CONTRIBUTING.md has developers only install quality dependencies (`black, hf-doc-builder, ruff`) rather than full set of testing dependencies. Since the documentation requires folks run tests anyway, update instructions to install `dev` dependencies.
Not sure if this is overkill (and we just want `pytest` / `parameterized` as specified with the `test_prod` target).
@muellerzr
> Update CONTRIBUTING.md Setup Instructions

- examples/slurm/fsdp_config.yaml
- examples/slurm/submit_multinode_fsdp.sh
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
This PR adds a new SLURM example specifically for when users want to specify an `accelerate` config yaml in addition to regular launching. This is *specifically* useful as generally SLURM resources are dynamically created/set in SLURM, such as:
```
export LAUNCHER="accelerate launch \
--num_processes $((SLURM_NNODES * GPUS_PER_NODE)) \
--num_machines $SLURM_NNODES \
--rdzv_backend c10d \
--main_process_ip $head_node_ip \
--main_process_port 29500 \
"
```
However since we only care about these values, this PR shows how you can also pass in a config yaml (if it's stored somewhere locally/on a shared FS):
```
export LAUNCHER="accelerate launch \
--config ${ACCELERATE_DIR}/examples/slurm/fsdp_config.yaml \
--num_processes $((SLURM_NNODES * GPUS_PER_NODE)) \
--num_machines $SLURM_NNODES \ …
```
> Add a SLURM example with minimal config

- .github/workflows/build-docker-images-release.yml
- .github/workflows/build_docker_images.yml
- benchmarks/fp8/README.md
- docker/README.md
This PR adds FP8 benchmarking docker images. They are tagged as `huggingface/accelerate-gpu-fp8-transformerengine` + `-release`/`-nightly`. 
Also noticed that the deepspeed images weren't ever being built, so changes that/fixes it. 
> Add FP8 docker images

- src/accelerate/utils/transformer_engine.py
- tests/test_imports.py
Fix a circular import when multiple package involves, including `deepspeed`, `apex`, `transformer_engine`, `onnx`.
A simple repro can be built based on ngc:
```Dockerfile
FROM nvcr.io/nvidia/pytorch:24.07-py3
RUN pip install onnxruntime-training deepspeed transformers[torch]
RUN python -c 'import transformers.integrations.deepspeed, deepspeed; deepspeed.runtime'
```
<details>
<summary>full `pip list`</summary>
```root@2555f18fb655:/pwd# pip list
Package                   Version
------------------------- -------------------------
absl-py                   2.1.0
accelerate                0.33.0
aiohttp                   3.9.5
aiosignal                 1.3.1
annotated-types           0.7.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
asciitree                 0.3.3 …
```
> Do not import `transformer_engine` on import

- src/accelerate/optimizer.py
the new duck-typing approach in https://github.com/huggingface/transformers/pull/30079 is causing build failures over there, because of the path through accelerate
```
/usr/local/lib/python3.10/site-packages/transformers/trainer.py:3448: in training_step
self.optimizer.train()
/usr/local/lib/python3.10/site-packages/accelerate/optimizer.py:128: in train
return self.optimizer.train()
E   AttributeError: 'AdamW' object has no attribute 'train'
```
we need to replicate that logic here, ensuring this code path is safe to call for all optimizers
cc @amyeroberts @muellerzr @winglian https://github.com/huggingface/accelerate/pull/2631
> use duck-typing to ensure underlying optimizer supports schedulefree hooks

- src/accelerate/data_loader.py
in transformers' trainer.py, when using xla resume, the data_iterator used during resumption is different from the original data_iterator. It is necessary to use set_epoch with the current epoch value: https://github.com/huggingface/transformers/blob/3bf6dd8aa141ff6bebd579649e9d0ba8bf5d03db/src/transformers/trainer.py#L2264. However accelerator adds an additional wrapper for xla: MpDeviceLoaderWrapper, which does not have a set_epoch method, this leads to incorrect epoch value and data being used in subsequent training (the random seed in the data loader's sampler is related to the epoch value). To resolve this issue, we add a set_epoch method to MpDeviceLoaderWrapper.
[documentation …
> add set_epoch for MpDeviceLoaderWrapper

- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- tests/test_cli.py
As title states, subprocess is slow. Each time we call it adds a whole second or so to the testing suite. This PR removes that (when save/applicable) from our testing suite, and instead does a 1:1 replacement by capturing the `stdout` instead of a func (said func being the equivalent `accelerate.commands.X`. 
Total CPU CI time:
```
Before: 2m53s
After: 2m36s
```
For specific areas:
* `TpuConfigTester`: (10x reduction)
```
Before: 10.77s
After: 0.95s
```
* `AccelerateLauncherTester` (50% reduction)
```
Before: 13.46s
After: 6.99s
```
[here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-d …
> Speed up tests by shaving off subprocess when not needed

- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/external_deps/test_pippy.py
- tests/test_data_loader.py
- tests/test_examples.py
Fixes our variety of failing tests on `main`.
Namely:
* removes `StatefulDataloader` from `skip_batch_sampler` stuff. There is no need since the dataloader can resume itself, so we don't want users to do so by accident imo. 
* Tweaks the `pippy` tests to deal with the changes, and adds one for bert (at this time, we can't support vision models, and they dropped support for encoder/decoder)
* RIP SD v1-5
members/contributors …
> Remove `skip_first_batches` support for StatefulDataloader and fix all the tests

- src/accelerate/utils/dataclasses.py
- tests/fsdp/test_fsdp.py
Recent release broke FSDP for models like llama that define a set of layers to split by. It'd parse the string as a tuple of characters instead. This PR fixes it + adjusts the tests to be more strict (tests bert and llama for auto wrap policy)
Fixes critical issue of FSDP being broken on the release. 
@SunMarc
> Fix FSDP auto_wrap using characters instead of full str for layers

- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_distributed_data_loop.py
- tests/test_accelerator.py
- tests/test_data_loader.py
Fixes #3070
This PR contains the following:
1. Cleanup the dynamic class resolution of DataLoaderAdapter a bit. Instead of performing dynamic class overriding in `__init__`, we instead override the property to pass through the base dataloader's class.
*Note:* This means `isinstance(obj, DataLoaderAdapter)` breaks. However, since `DataLoaderAdapter` was introduced very recently, it's very unlikely this will break anything, since there [shouldn't](https://www.hyrumslaw.com/) be any reason why existing downstream code would be checking this.
2. Implement `__reduce__` in DataLoaderAdapter subclasses to allow pickling of these classes, despite the `__class__` override. This implementation just repasses the object's init arguments and `__dict__` back into the constructor.
3. Some cleanup in …
> Allow DataLoaderAdapter subclasses to be pickled by implementing `__reduce__`

- src/accelerate/utils/dataclasses.py
- tests/fsdp/test_fsdp.py
0.34.0 removed the ability to set the state_dict_type on the fly, which I had assumed was fine, however I wasn't aware that users typically will:
* Use `SHARDED_STATE_DICT` for checkpoints
* Use `FULL_STATE_DICT` for the final model
As a result, brings it back and documents the desired behavior
Fixes https://github.com/huggingface/accelerate/issues/3072
@SunMarc
> Re-enable setting state dict type

- src/accelerate/utils/modeling.py
As discussed internally in https://huggingface.slack.com/archives/C068ZAHJZCZ/p1725454261264919
From the Diffusers-TorchAO experimentation, when modeling components are quantized and sequential cpu offloading is enabled, we get the following error:
<details>
<summary> Traceback </summary>
```
File "/home/aryan/work/diffusers/dump10.py", line 228, in <module>
pipe.enable_sequential_cpu_offload()
File "/home/aryan/work/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1104, in enable_sequential_cpu_offload
cpu_offload(model, device, offload_buffers=offload_buffers)
File "/raid/aryan/nightly-venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 204, in cpu_offload
attach_align_device_hook(
File …
```
> Support sequential cpu offloading with torchao quantized tensors

- src/accelerate/utils/imports.py
- src/accelerate/utils/memory.py
- src/accelerate/utils/modeling.py
This PR introduces the new API for get xpu available memory. Below is an example of before and after:
```python
from transformers import AutoModelForSeq2SeqLM
model = AutoModelForSeq2SeqLM.from_pretrained("bigscience/T0pp", device_map="auto")
print(model.hf_device_map)
```
Before
```python
{'': 'cpu'}
```
After
```python
{'shared': 0, 'decoder.embed_tokens': 0, 'encoder.embed_tokens': 0, 'encoder.block.0': 0, 'encoder.block.1': 0, 'encoder.block.2': 0, 'encoder.block.3': 0, 'encoder.block.4': 0, 'encoder.block.5': 0, 'encoder.block.6': 1, 'encoder.block.7': 1, 'encoder.block.8': 1, 'encoder.block.9': 1, 'encoder.block.10': 1, 'encoder.block.11': 1, 'encoder.block.12': 1, 'encoder.block.13': 1, 'encoder.block.14': 2, 'encoder.block.15': 2, 'encoder.block.16': 2, 'encoder.block.17': 2, …
```
> use the correct available memory API for XPU

- src/accelerate/hooks.py
it fixes `skip_keys` to be actually used by the big modelling forward hooks.
previously `skip_keys` would not be propagated to nested modules (idk what level of nesting but some level), && kwargs that were supposed to be skipped would just be transferred to other devices by `send_to_device` anyway.
* there is no open issue for this as far as i know
* there is no documentation change needed for this because this just fixes something the docs say is supposed to work
* no it's a 2 line change
- Big modeling: @SunMarc
> fix `skip_keys` usage in forward hooks

- benchmarks/fp8/ddp.py
- benchmarks/fp8/distrib_deepspeed.py
- benchmarks/fp8/fsdp.py
- benchmarks/fp8/non_distributed.py
- examples/config_yaml_templates/run_me.py
- pyproject.toml
- setup.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/environment.py
- src/accelerate/utils/fsdp_utils.py
- src/accelerate/utils/memory.py
- tests/deepspeed/test_deepspeed.py
Currently used version, 0.2.1, is quite old at this point.
Not a lot needed to be changed:
- Change ruff version in `setup.py`
- Remove deprecated `ignore-init-module-imports` option for ruff
- Type comparison should use `is not` and not `!=`
- Use f-string instead of `%` formatting
- Some line wrapping and empty lines
> MAINT: Upgrade ruff to v0.6.4

- src/accelerate/utils/dataclasses.py
Fixes #3100 by adding docstring to the `DataLoaderConfiguration` class.
> [docs] DataLoaderConfiguration docstring

- .github/workflows/stale.yml
See https://github.com/huggingface/peft/pull/2061 for the equivalent PR in PEFT.
This restores the functionality of the stale bot after permissions for the token have been limited. The action still shows errors for PEFT but the bot appears to work fine.
> MAINT: Permission for GH token in stale.yml

- docs/source/usage_guides/distributed_inference.md
Solves broken doc image by offloading it to the 🤗 Hub
@stevhliu
> Update image ref for docs

- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
Adds missing docstrings for more classes.
> [docs] More docstrings

- tests/test_examples.py
- tests/test_multigpu.py
XPU doesn't support pippy yet. So we should skip the pippy-related tests for now.   
@muellerzr @SunMarc
> [tests] skip pippy tests for XPU 

- src/accelerate/test_utils/scripts/external_deps/test_ds_multiple_model.py
- tests/deepspeed/test_deepspeed_multiple_model.py
Fixes failures on DS tests wrt multiple models. 
TL;DR:
1. Need to remember to call `AcceleratorState.reset_state()` when we want to do things in concurrent different configurations (such as the multiple ds model configuration tests that actually do things)
2. Still need `patch_environment` to properly setup everything, otherwise we end up with failures when running the entire DS suite at once. 
Fixes our tests & deepspeeds PR's from failing
Anyone in the community is free to review the PR once the tests have passed. …
> Fixup multiple model DS tests

- src/accelerate/utils/__init__.py
- src/accelerate/utils/constants.py
- src/accelerate/utils/dataclasses.py
This PR adds support for `XPU` and `MTIA` profiler activities in `accelerate.utils.dataclasses.ProfileKwargs` based on the installed PyTorch version. These activities are included conditionally depending on whether the current PyTorch version supports them (`XPU` in 2.4.0 and `MTIA` in 2.1.0).
Fixes #3128 
- Added `XPU_PROFILING_AVAILABLE_PYTORCH_VERSION` and `MITA_PROFILING_AVAILABLE_PYTORCH_VERSION` constants to `constants.py`.
- Updated `ProfileKwargs._get_profiler_activity` to conditionally include `XPU` and `MTIA` activities based on PyTorch version.
[here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#wr …
> 🐛 [HotFix] Handle Profiler Activities Based on PyTorch Version

- src/accelerate/accelerator.py
- src/accelerate/state.py
When model is loaded across multiple devices, fine-tuning on XPU crashes with the message:
```bash
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, xpu:0 and xpu:3! (when checking argument for argument mat2 in method wrapper_XPU__bmm)
```
The reason is that the whole model is moved back to `xpu:0` in the `_prepare_ipex_or_xpu` method. After the fix, fine-tuning works. 
@SunMarc and @muellerzr
> only move model to device when model is in cpu and target device is xpu

- src/accelerate/accelerator.py
causes bug in the case of is_musa_available()
> typo of "scalar" instead of "scaler"

- .github/workflows/stale.yml
Continuation of #3102.
The equivalent PR in PEFT (https://github.com/huggingface/peft/pull/2064) was successful to restore stale bot function to PRs as well. Hence also making the same change for accelerate.
> MNT Permission for PRs for GH token in stale.yml

- src/accelerate/utils/operations.py
- tests/test_utils.py
Fixes #3113 by explicitly checking and handling padding on negative dimensions for `accelerate.utils.pad_across_processes`.
Adds tests for handling valid and out-of-bounds negative dimensions.
@muellerzr @BenjaminBossan @SunMarc
> Handle negative values for `dim` input in `pad_across_processes`

- examples/inference/distributed/florence2.py
This PR adds a distributed inference example for Florence-2.
#3078 
Based on https://gist.github.com/sayakpaul/dfb26d6562b62ba8c2f613dc912a28a8#file-generate_captions_multigpu-py and https://gist.github.com/sayakpaul/cfaebd221820d7b43fae638b4dfa01ba
- `nodesplitter=None` in `wds.WebDataset` seems to be an important implementation detail, by default I'm getting `ValueError: you need to add an explicit nodesplitter to your input pipeline for multi-node training`, with `wds.split_by_node` only 1 GPU is utilized and the script hangs.
- Similarly `empty_check=False` avoids the need to set num_workers to less than or equal to the number of shards, otherwise: `ValueError: No samples found in dataset; perhaps you have fewer shards than workers.`
- We have to convert `BatchFeature` to dict: …
> Florence2 distributed inference example

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/utils/dataclasses.py
Adds in the ability to pass in a `data_seed` when using the `seedable_random_sampler`. Alternative to https://github.com/huggingface/accelerate/pull/3130
Essentially all we *really* want to do is make sure that the `initial_seed` in the `SeedableRandomSampler` can be changed to not be the same as the one used by torch. so as a result, adds it to the `DataLoaderConfiguration` class
members/contributors who may …
> POC: Allow for a `data_seed`

- examples/inference/distributed/distributed_speech_generation.py
This PR adds a distributed speech data generation example using facebook/mms-tts-eng
https://github.com/huggingface/accelerate/issues/3078
- Tested it on two t4 GPUs 
- For two gpu 
- Generating Pokemon descriptions: 100%|██████████| 52/52 [00:26<00:00,  1.99it/s]
- For one gpu 
- Generating Pokemon descriptions: 100%|██████████| 105/105 [00:50<00:00,  2.07it/s]
- The example was tested using a very small dataset. If you'd like me to experiment with a different dataset, please let me know!
@sayakpaul
> Adding multi gpu speech generation

- src/accelerate/accelerator.py
- tests/deepspeed/test_deepspeed.py
Related: https://github.com/microsoft/DeepSpeed/pull/6502
> support torch dynamo for deepspeed>=0.14.4

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/external_deps/test_performance.py
- tests/deepspeed/test_deepspeed.py
When `save_model` is called under Zero3 only a single rank has all of the parameters. As a result `Accelerator.save_model` will throw an error under zero3 saying `'NoneType' object has no attribute 'items'` because in this case the `state_dict` of the model on non-0-ranks won't exist. 
Fixes https://github.com/huggingface/accelerate/issues/2985
@SunMarc @BenjaminBossan
> Fixup Zero3 + `save_model`

- docs/source/package_reference/utilities.md
- src/accelerate/checkpointing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/other.py
Sets `weights_only=True` by default when using `torch.save()` for all compatible objects:
* Model weights
* Optimizer states
* DataLoader states
* Scheduler states
The only one that we can't do right now are the random states, since the numpy random states will raise an exception if we add the right classes for safe loading:
```
File "/home/zach/work/accelerate/test.py", line 24, in <module>
_ = load(p / "r2.pkl", weights_only=True)
File "/home/zach/work/accelerate/src/accelerate/utils/other.py", line 245, in load
loaded_obj = torch.load(f, map_location=map_location, **kwargs)
File "/home/zach/miniconda3/envs/accelerate/lib/python3.10/site-packages/torch/serialization.py", line 1096, in load
raise pickle.UnpicklingError(_get_wo_message(str(e))) from None …
```
> Trigger `weights_only=True` by default for all compatible objects

- src/accelerate/utils/memory.py
This PR fixed the version check bug introduced in #3076. Below are the verified results with ipex "2.5.10+gitad5c117":
```bash
from accelerate.utils.memory import get_xpu_available_memory
mem = get_xpu_available_memory(1)
print(mem)
```
@muellerzr
> fix version check bug in `get_xpu_available_memory`

- src/accelerate/accelerator.py
Hi @SunMarc , this PR enables cpu bnb model distributed finetune by removing check index because we don't need index in cpu device. Please review it. Thanks!
> enable cpu bnb distributed lora finetune

- docs/source/package_reference/big_modeling.md
- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
- tests/test_utils.py
* Add a `has_offloaded_params` utility function which returns `True` iff there is an `AlignDevicesHook` with offloading enabled
* Prepare for other utility functions to be implemented in future PRs
* Implement utility function in `accelerate.utils.modeling`, exposed through `accelerate.utils`
* Replace repeat code use in `accelerate.utils.modeling` and `accelerate.accelerator` with newly added function
<details><summary>test_has_offloaded_params.py</summary>
```python3
import torch
from accelerate.utils import has_offloaded_params
from accelerate.hooks import attach_align_device_hook
from accelerate.big_modeling import cpu_offload_with_hook
class ModelForTest(torch.nn.Module):
def __init__(self):
super().__init__()
self.linear1 = torch.nn.Linear(3, 4)
self.batchnorm = …
```
> [Utils] `has_offloaded_params`

- src/accelerate/accelerator.py
What does this PR do?
---
Hi, I am a beginner to `huggingface/accelerate` and have learned a lot from the repo. However, I find a possible spelling mistake in `src/accelerate/accelerate.py:1255`.
Could you please examine this comment again to confirm whether this is an error?
---
P.S. I am also a beginner to contributing to open source project (maybe also to English communication). Could you please let me know if this PR violate some conventions in this community? I will appreciate it!
> docs: fix a wrong word in comment in src/accelerate/accelerate.py:1255

- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/megatron_lm.py
I have adapted the Megatron-LM plugin code to version 0.8.0 or higher.
Same setup as before, but now Megatron-LM is using `core_r0.8.0`.
- Core parts of the library: @muellerzr @BenjaminBossan @SunMarc+
> update Megatron-LM plugin code to version 0.8.0 or higher.

- src/accelerate/utils/dataclasses.py
- tests/deepspeed/test_deepspeed.py
Fixes instances of `transformers.deepspeed` that were broken with the deprecation in transformers 4.46.0 released earlier today.  Updates those to use `transformers.integrations.deepspeed` since this is where those have been moved.
- DeepSpeed: @muellerzr
> Update transformers.deepspeed references from transformers 4.46.0 release

- src/accelerate/accelerator.py
Last time in #3133, I introduced the check to only move the model when the model is on "cpu". But this doesn't take the `torch.nn.module` Model into account, e.g. 
```python
from accelerate import Accelerator, DDPCommunicationHookType, DistributedDataParallelKwargs
from torch.utils.data import DataLoader, TensorDataset
import torch
class MyModel(torch.nn.Module):
def __init__(self):
super().__init__()
self.layer = torch.nn.Linear(10, 10)
def forward(self, x):
return self.layer(x)
data = torch.randn(100, 10)
targets = torch.randint(0, 10, (100,))
dataset = TensorDataset(data, targets)
criterion = torch.nn.CrossEntropyLoss()
ddp_kwargs = DistributedDataParallelKwargs(comm_hook=DDPCommunicationHookType.FP16)
accelerator = Accelerator(kwargs_handlers=[ddp_kwargs])
model = MyModel()
optimizer …
```
> take `torch.nn.Module` model into account when moving to device  

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/fsdp_utils.py
Currently in `FullyShardedDataParallelPlugin`, the `param_init_fn` [is set when sync_module_states=True](https://github.com/huggingface/accelerate/blob/6f79b63b865a33b92a3f1c9e2562b88ee7a4d89d/src/accelerate/utils/dataclasses.py#L1699). This is required by `FSDP` to initialize the shards (i.e. rank > 0) params in a [variety of situations](https://github.com/pytorch/pytorch/blob/8321eec009c8c79145ebccd51fdfc336e5f8b848/torch/distributed/fsdp/_init_utils.py#L588-L603), including the important one where the parameter was on `torch.device("meta")` because `low_cpu_mem_mode` was used. 
However `FullyShardedDataParallelPlugin.param_init_fn` is now set to 
```python
self.param_init_fn = lambda x: x.to_empty(device=device, recurse=False)
```
which causes problems when there are tied weights. …
> Models With Tied Weights Need Re-Tieing After FSDP Param Init

- src/accelerate/big_modeling.py
- src/accelerate/utils/imports.py
This PR relax the condition that 4-bit bnb models needs to have a hook to work. It is not necessary as we can move the 4-bit model since bnb 0.43.2.
cc @sayakpaul
> remove hook for bnb 4-bit 

- docs/source/basic_tutorials/troubleshooting.md
- src/accelerate/utils/memory.py
Currently, the `find_executable_batch_size` only works on CUDA and CPU. This PR adds the XPU support for this. 
@muellerzr
> enable `find_executable_batch_size` on XPU

- src/accelerate/utils/fsdp_utils.py
Address the issue pointed out by @enesmsahin  on #3154
@muellerzr @enesmsahin
> take care of case when "_tied_weights_keys" is not an attribute

- src/accelerate/data_loader.py
- tests/test_data_loader.py
When training with the `transformers` Trainer or related (Sentence Transformers, SpanMarker, SetFit, etc.), `set_epoch` is called on the dataloader. This is propagated down to the `dataloader.batch_sampler.sampler` if that has a `set_epoch` , but not to `dataloader.batch_sampler`.
This prevents epoch-specific generator seeding in custom batch samplers, such as the ones that are common in Sentence Transformers: https://sbert.net/docs/package_reference/sentence_transformer/sampler.html
See also https://github.com/UKPLab/sentence-transformers/issues/3069 by @antigregory which showed that `set_epoch` in my Batch Samplers is not called like I expected them to be.
[documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), …
> [`data_loader`] Optionally also propagate set_epoch to batch sampler

- docs/source/usage_guides/profiler.md
- docs/source/usage_guides/quantization.md
`pip install bitsandbytes` doesn't work on non-cuda devices, e.g. CPU or XPU. So I add a comment for that. 
@muellerzr
> [docs] add instruction to install bnb on non-cuda devices

- src/accelerate/utils/other.py
We've been getting this warning:
>   /fsx/qgallouedec/miniconda3/envs/trl/lib/python3.11/site-packages/accelerate/utils/other.py:220: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.multiarray.
np.core.multiarray._reconstruct,
[documentation guidelines](https://github.com/huggingface/accelerate/tree/main/doc …
> Use `numpy._core` instead of `numpy.core`

- src/accelerate/accelerator.py
`Accelerator` doesn't allow for explicitly passing in `TorchDynamoPlugin`. This is needed since the `TrainingArguments` can pass in a `mode` (and I want to try and remove all env vars from the `Trainer`)
@SunMarc @BenjaminBossan
> Allow for full dynamo config passed to Accelerator

- docs/source/package_reference/utilities.md
- src/accelerate/utils/__init__.py
- src/accelerate/utils/environment.py
- tests/test_utils.py
In some circumstances, calling certain classes or functions can result in accelerate env vars being set and not being cleaned up afterwards. As an example, when calling:
`TrainingArguments(fp16=True, ...)`
The following env var will be set:
`ACCELERATE_MIXED_PRECISION=fp16`
This can affect subsequent code, since the env var takes precedence over `TrainingArguments(fp16=False)`. This is especially relevant for unit testing, where we want to avoid the individual tests to have side effects on one another. Decorate the unit test function or whole class with this decorator to ensure that after each test, the env vars are cleaned up. This works for both `unittest.TestCase` and normal classes (pytest) and standalone functions; it also works when decorating the parent class and in conjunction …
> [WIP] FEAT Decorator to purge accelerate env vars

- src/accelerate/commands/config/cluster.py
When using `accelerate config` to configure params on XPU, it shows "What GPU(s) (by id)..." rather than "What XPU(s) (by id)..." as shown below:
```bash
In which compute environment are you running?
This machine                                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                                                        
multi-XPU                                                                                                                                   
How many different machines will you …
```
> use XPU instead of GPU in the `accelerate config` prompt text

- docs/source/basic_tutorials/troubleshooting.md
I think the terminology of set_breakpoint and check_breakpoint has become set_trigger and check_trigger.
@muellerzr
> Replaced set/check breakpoint with set/check trigger in the troubleshooting documentation

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/deepspeed.py
For DeepSpeed optimizer offloading, select the appropriate optimizer based on the original optimizer class.
- DeepSpeed: @muellerzr
- Core parts of the library: @muellerzr @BenjaminBossan @SunMarc
> Select the DeepSpeedCPUOptimizer based on the original optimizer class.

- src/accelerate/hooks.py
- tests/test_accelerator.py
We ran into this issue when try to load [VPTQ](https://github.com/microsoft/VPTQ/tree/main)  models by multiple devices, the `VQLinear` layer has embending as its sub-module. This function should move all constant buffers/parameters to the corresponding devices from Meta device.
So `add_hook_to_module` should pass `preload_module_classes` to the next recursive calling for the nested modules.
https://github.com/microsoft/VPTQ/blob/ac7258f461e214ca705f5895513f314576750528/vptq/layers/vqlinear.py#L160C18-L160C18
This PR is to fix https://github.com/huggingface/accelerate/issues/3060
- Big modeling: @SunMarc
> Fix: Resolve #3060, `preload_module_classes` is lost for nested modules

- docs/source/concept_guides/performance.md
The current `set-seed` in documentation only includes the cuda part, which is out-dated. This PR updates it with the current implementation.
@muellerzr
> [docs] update set-seed

- src/accelerate/utils/modeling.py
Add npu support in `load_state_dict` when device_map value is an integer, since torch.device(0) defaults to cuda
> fix load_state_dict for npu

- src/accelerate/utils/modeling.py
> correct the return statement of _init_infer_auto_device_map

- docs/source/usage_guides/gradient_accumulation.md
- examples/by_feature/gradient_accumulation_for_autoregressive_models.py
- src/accelerate/test_utils/training.py
- tests/test_examples.py
Following the recent [highlights](https://huggingface.co/blog/gradient_accumulation) on how gradient accumulation with the cross-entropy loss is usually off, it could be great to have it mentioned in the doc. I've thus added some code and explanation of it in the gradient accumulation page.
cc @SunMarc and @muellerzr, let me know what you think of it or if I can make this any clearer!
> Give example on how to handle gradient accumulation with cross-entropy

- src/accelerate/utils/memory.py
`torch.xpu.mem_get_info` API is available starting from PyTorch 2.6 (and in nightly `2.6.0.dev20241206+xpu` or later). To work properly this method requires PyTorch built with the SYCL runtime which supports API to query device memory stats. If not available, exception will be raised.
Requires: https://github.com/pytorch/pytorch/pull/141230
Fixes: #2929
Fixes: https://github.com/huggingface/transformers/issues/31922
CC: @muellerzr @SunMarc
> Use torch.xpu.mem_get_info for XPU

- src/accelerate/accelerator.py
- src/accelerate/utils/other.py
- tests/test_accelerator.py
- tests/test_utils.py
This PR fixes the unexpected behavior of `Accelerator.unwrap_model` (Issue https://github.com/huggingface/accelerate/issues/3281). Right now, if the model is wrapped in both distributed wrapper (e.g. `DistributedDataParallel` or `DeepSpeedEngine`) and compiled module (`OptimizedModule`) it only unwraps the distributed module. This behavior arises from the following code in L80 of `utils/others.py`: https://github.com/huggingface/accelerate/blob/cb8b7c637a8588668c52bd306f9b2828f69d9585/src/accelerate/utils/other.py#L80
Instead of checking for compiled model both **before and after** unwrapping distributed wrapper, the current code only checks for compilation before unwrapping the distributed wrapper. If the model is wrapped in both, `is_compiled` will be set to `False` and won't unwrap the …
> Add `keep_torch_compile` param to `unwrap_model` and `extract_model_from_parallel` for distributed compiled model.

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
Fixes #3308
This PR fixes the check in get_module_size_with_ties used to determine the module to which a tied parameter belongs. This is done by checking that the name of the tied parameter starts with module name plus ".".
The previous check (`n in tied_param`) was not returning the expected results in models with a ModuleList, where the contained modules have a tied parameter. I added a unit test covering this situation.
cc @BenjaminBossan
> Ensure that tied parameter is children of module

- docs/source/basic_tutorials/install.md
- docs/source/usage_guides/mps.md
- docs/source/usage_guides/sagemaker.md
- setup.py
- src/accelerate/accelerator.py
- src/accelerate/big_modeling.py
- src/accelerate/commands/launch.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/operations.py
- src/accelerate/utils/other.py
- tests/fsdp/test_fsdp.py
- tests/test_big_modeling.py
- tests/test_utils.py
Drops torch<2 support
@BenjaminBossan @SunMarc
> Bye bye torch <2

- src/accelerate/commands/launch.py
- src/accelerate/launchers.py
- tests/xla_spawn.py
This should fix some issues that have been hit by the torch xla team when testing in CI.
Fixes #3304 
@muellerzr 
Also CC @tengyifei for visibility.
> feat(tpu): remove nprocs from xla.spawn

- tests/test_big_modeling.py
This PR fixes some tests that started to fail because of transformers (maybe related to either generate or attention ? It was working with v4.44 for example). I changed a bit the test to make it more robust.
> Fix offload generate tests

- tests/test_accelerator.py
This PR enables 1 cuda-only case on non-cuda hardware accelerators. Below is the test result on XPU: 
```bash
================================================= short test summary info ==================================================
PASSED tests/test_accelerator.py::AcceleratorTester::test_nested_hook
======================================= 1 passed, 417 deselected, 1 warning in 5.53s =======================================
```
cc @SunMarc and @muellerzr
> [tests] make cuda-only test case device-agnostic

- src/accelerate/utils/deepspeed.py
with latest bitsandbytes:
```
[rank1]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/accelerate/utils/deepspeed.py", line 53, in map_pytorch_optim_to_deepspeed                                                                                                        
[rank1]:     is_adaw = isinstance(optimizer, (bnb_opt.AdamW, bnb_opt.AdamW32bit)) and optimizer.optim_bits == 32                                                                                                                                             
[rank1]:                                                                              ^^^^^^^^^^^^^^^^^^^^ …
```
> latest bnb no longer has optim_args attribute on optimizer

- src/accelerate/utils/modeling.py
There was a breaking change made in TorchAO v0.7.0, where `layout_tensor` was made an internal private attribute and `tensor_impl` was added as another parameter.
This causes sequential offloading implementation to break in Diffusers: https://github.com/huggingface/diffusers/issues/10470
@SunMarc
> Fix for offloading when using TorchAO >= 0.7.0

- src/accelerate/data_loader.py
The test below
```bash
pytest -rA tests/test_accelerator.py::AcceleratorTester::test_save_model_with_stateful_dataloader_use_safetensors_num_workers_0_dispatch_batches
```
gives the following error:
```bash
self = <accelerate.data_loader.DataLoaderDispatcher object at 0x7efdf9399ed0>
dataset = <torch.utils.data.dataset.TensorDataset object at 0x7efdf9398a90>, use_stateful_dataloader = True
batch_sampler = <torch.utils.data.sampler.BatchSampler object at 0x7efdf9398760>
kwargs = {'collate_fn': <function default_collate at 0x7efecb76bd00>, 'in_order': True, 'multiprocessing_context': None, 'num_workers': 0, ...}
StatefulDataLoader = <class 'torchdata.stateful_dataloader.stateful_dataloader.StatefulDataLoader'>
def __init__(self, dataset, use_stateful_dataloader=False, batch_sampler=None, …
```
> add torchdata version check to avoid "in_order" error

- src/accelerate/data_loader.py
This fixes tests/test_data_loader.py::StatefulDataLoaderTester tests which started to fail after 828aae4:
```
FAILED tests/test_data_loader.py::StatefulDataLoaderTester::test_dataloader_dispatcher_state_dict_num_workers_0 - KeyError: 'in_order'
FAILED tests/test_data_loader.py::StatefulDataLoaderTester::test_dataloader_dispatcher_state_dict_num_workers_2 - KeyError: 'in_order'
FAILED tests/test_data_loader.py::StatefulDataLoaderTester::test_dataloader_inheritance - KeyError: 'in_order'
FAILED tests/test_data_loader.py::StatefulDataLoaderTester::test_dataloader_state_dict_num_workers_0 - KeyError: 'in_order'
FAILED tests/test_data_loader.py::StatefulDataLoaderTester::test_dataloader_state_dict_num_workers_2 - KeyError: 'in_order'
FAILED …
```
> dataloader: check that in_order is in kwargs before trying to drop it

- tests/test_modeling_utils.py
The below test works on XPU, and it should also work on other hardware accelerators:
```bash
===================================================================== PASSES ======================================================================
============================================================= short test summary info =============================================================
PASSED tests/test_modeling_utils.py::ModelingUtilsTester::test_get_balanced_memory
```
> [tests] make cuda-only test work on other hardware accelerators

- tests/test_kwargs_handlers.py
- tests/test_optimizer.py
Both test cases work on XPU now. Below are the rest results:
```bash
===================================================================== PASSES ======================================================================
============================================================= short test summary info =============================================================
PASSED tests/test_optimizer.py::OptimizerTester::test_accelerated_optimizer_step_was_skipped
========================================================== PASSES ===========================================================
================================================== short test summary info ==================================================
PASSED tests/test_kwargs_handlers.py::KwargsHandlerTester::test_grad_scaler_kwargs …
```
> [tests] remove `require_non_xpu` test markers

- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
- src/accelerate/commands/env.py
- src/accelerate/hooks.py
- src/accelerate/utils/dataclasses.py
We have already supported MUSA backend  since [v0.33.0](https://github.com/huggingface/accelerate/releases/tag/v0.33.0), and accelerate have supported more functionalities, like FSDP, of which MUSA backend doesn't included.
This PR just make MUSA backend adapted with all these features.
cc @SunMarc @muellerzr
> Support more functionalities for MUSA backend

- src/accelerate/commands/estimate.py
Fixes https://github.com/huggingface/accelerate/issues/3379
This PR fixes the estimate memory command as it gave wrong results when `torch_dtype` is specified in the config we are loading.
> fix torch_dtype in estimate memory

- examples/cv_example.py
As the title suggests, this PR updates the code for seed setting in `cv_example.py`. The current code only applies for cuda device.
cc @SunMarc and @muellerzr
> [examples] upgrade code for seed setting  

- docs/source/usage_guides/quantization.md
- src/accelerate/utils/bnb.py
When going through the following code example in `Model quantization` doc, the below code returns error that no GPU is found. This PR can fixes this error. 
```bash
from accelerate import init_empty_weights
from mingpt.model import GPT
import torch
model_config = GPT.get_default_config()
model_config.model_type = 'gpt2-xl'
model_config.vocab_size = 50257
model_config.block_size = 1024
with init_empty_weights():
empty_model = GPT(model_config)
from huggingface_hub import snapshot_download
weights_location = snapshot_download(repo_id="marcsun13/gpt2-xl-linear-sharded")
from accelerate.utils import BnbQuantizationConfig
bnb_quantization_config = BnbQuantizationConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_use_double_quant=True, bnb_4bit_quant_type="nf4")
from …
```
> add xpu check in `get_quantized_model_device_map`

- benchmarks/fp8/torchao/Dockerfile
- benchmarks/fp8/torchao/README.md
- benchmarks/fp8/torchao/ddp.py
- benchmarks/fp8/torchao/distrib_deepspeed.py
- benchmarks/fp8/torchao/fp8_utils.py
- benchmarks/fp8/torchao/fsdp.py
- benchmarks/fp8/torchao/non_distributed.py
- benchmarks/fp8/transformer_engine/distrib_deepspeed.py
- docs/source/usage_guides/low_precision_training.md
- src/accelerate/accelerator.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/ao.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- tests/__init__.py
- tests/test_fp8.py
This PR is the start of incorporating [torchao](https://github.com/pytorch/ao/tree/main/torchao/float8) float8 training into Accelerate. 
It does so by refactoring the backend to be more modular as more FP8 backends come out, and adds new benchmarking tests for it.
Current status of benchmarks:
* Single GPU :heavy_check_mark: 
* DDP: :heavy_check_mark: 
* FSDP: :heavy_check_mark: 
* DeepSpeed: :heavy_check_mark: 
Also need to work on a testing suite. 
Anyone in the community is free to review the PR …
> Torchao float8 training

- docs/source/usage_guides/distributed_inference.md
minor optimization: both `torch.float16` need torch to be imported. 
cc @SunMarc and @muellerzr
> [docs] add the missing `import torch`

- docs/source/usage_guides/low_precision_training.md
> minor doc fixes

- src/accelerate/data_loader.py
Replaces calls to
```python
torch.Generator()
```
with
```python
torch.Generator(device=torch.get_default_device())
```
in [`src/accelerate/data_loader.py`](src/accelerate/data_loader.py).
Prior to this fix, I was seeing:
<details closed><summary>🐛 <b>Bug</b>:</summary>
```python
File /lus/flare/projects/datascience/foremans/projects/argonne-lcf/AuroraGPT/venvs/aurora_nre_models_frameworks-2024.2.1_u1/lib/python3.10/site-packages/accelerate/data_loader.py:99, in SeedableRandomSampler.__iter__(self)
97 # print("Setting seed at epoch", self.epoch, seed)
98 self.generator.manual_seed(seed)
---> 99 yield from super().__iter__()
100 self.set_epoch(self.epoch + 1)
File /opt/aurora/24.180.3/frameworks/aurora_nre_models_frameworks-2024.2.1_u1/lib/python3.10/site-packages/torch/utils/data/sampler.p …
```
> fix: Add `device=torch.get_default_device()` in `torch.Generator`s

- setup.py
- src/accelerate/test_utils/testing.py
- src/accelerate/tracking.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- tests/test_tracking.py
Add `log_artifact`, `log_artifacts` and `log_figure` capabilities to the MLflowTracker.
When using `Accelerator` for training, the MLFlowTracker did not offer logs to artifact(s) and figures, which are fully implemented at MLFlow. With this PR, those functionalities are now available at MLFlowTracker as well.
Fixes #2070 
@muellerzr @BenjaminBossan @SunMarc
> Add `log_artifact`, `log_artifacts` and `log_figure` capabilities to the MLflowTracker.

- docs/source/usage_guides/deepspeed.md
- src/accelerate/commands/launch.py
- src/accelerate/utils/constants.py
- src/accelerate/utils/launch.py
Allows the use of the no_ssh option in DeepSpeed (https://www.deepspeed.ai/getting-started/#launching-without-passwordless-ssh) which is helpful in restricted network environments / HPC clusters to use srun/mpirun instead of setting up passwordless SSH.
@muellerzr
> feat: Add no_ssh and slurm multinode launcher options for deepspeed

- src/accelerate/big_modeling.py
- src/accelerate/hooks.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/operations.py
remove device index workaround on xpu since it supports integer device index as cuda now
this can fix https://github.com/huggingface/accelerate/issues/3402, this issue is brought by inconsistent device key(integer(x) vs string("xpu:x")).
- blip, dab_detr and vilt can pass
- roberta fail, but CUDA fail w/ same log, so it's another issue, may open another PR to fix
> remove device index workaround on xpu since xpu supports integer device index as cuda now

- src/accelerate/hooks.py
Fixes: #3402
The #3448 is a better way to fix the reported #3402, but the fix is XPU specific (as well as 3402 to be fair). I do worry that the issue might still exists for accelerators other than cuda and xpu which got aligned behavior after 3448. I don't have a way to verify that however. So, I am rebasing this PR and leave that to maintainers and users/developers of non-cuda/xpu devices to take it from here if needed. Better way however might be to aligned behavior of these accelerators on pytorch side and then make a fix similar to 3448.
CC: @SunMarc @faaany @zucchini-nlp
> Fix device KeyError in tied_params_map

- src/accelerate/data_loader.py
- tests/test_data_loader.py
Fixes #3398 
The initial state of the new generator was always the same, whatever the seed passed to `accelerate.utils.set_seed`. This PR makes sure that we get reproducible results but different numbers for different seeds passed to `set_seed`. This is already the case when multi GPU is disabled because generator is None (see https://github.com/pytorch/pytorch/blob/main/torch/utils/data/sampler.py#L170).
Before adding a test, I will wait for a first reviewer to confirm this is OK, I am not yet very familiar with accelerate.
Maybe the same should be done for https://github.com/huggingface/accelerate/blob/main/src/accelerate/data_loader.py#L1184 where the seed is set to 42 and thus will always produce the same number whatever the first global initial seed passed to `set_seed`
Pull Request …
> Fix seeding of new generator for multi GPU

- src/accelerate/utils/modeling.py
Fix get_balanced_memory for MPS.
This also fixes a failure in test_get_balanced_memory:
```
assert {0: 215, 1: 300} == {0: 300, 1: 300}
[...]
tests/test_modeling_utils.py:871: AssertionError
```
> Fix get_balanced_memory for MPS

- src/accelerate/state.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
xccl distributed backend is available for XPU device backend starting from torch 2.7 (requires torch built with `USE_XCCL=1 USE_C10D_XCCL=1`).
This change is verified with the following Transformers tests:
* `tests/extended/test_trainer_ext.py`
* `tests/trainer/test_trainer_distributed.py`
This commit does not impact IPEX which currently remains using custom distributed backend.
CC: @muellerzr
> xpu: enable xccl distributed backend

- examples/by_feature/cross_validation.py
- pyproject.toml
- src/accelerate/big_modeling.py
- src/accelerate/checkpointing.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/env.py
- src/accelerate/commands/estimate.py
- src/accelerate/commands/menu/input.py
- src/accelerate/data_loader.py
- src/accelerate/hooks.py
- src/accelerate/inference.py
- src/accelerate/state.py
- src/accelerate/test_utils/examples.py
- src/accelerate/test_utils/scripts/test_distributed_data_loop.py
- src/accelerate/test_utils/testing.py
- src/accelerate/tracking.py
- src/accelerate/utils/ao.py
- src/accelerate/utils/bnb.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/environment.py
- src/accelerate/utils/launch.py
- src/accelerate/utils/megatron_lm.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/offload.py
- src/accelerate/utils/operations.py
- src/accelerate/utils/other.py
- src/accelerate/utils/random.py
- tests/test_modeling_utils.py
Use Python 3.9 as base version for ruff.
> Update ruff target-version to py39 and apply more fixes

- docs/source/usage_guides/low_precision_training.md
Hi there!
To fix a teeny-tiny typo in `low_precision_training` guide.
> Fix a tiny typo in `low_precision_training` guide

- src/accelerate/utils/memory.py
- src/accelerate/utils/modeling.py
This PR fixes the tied weights check as `tie_word_embeddings` is only for the decoder part of a model. So for multimodal model, we need to get the decoder config and not the global config. The issue with the global config is that `tie_word_embeddings` is set to `True` by default.
> Fix check_tied_parameters_in_config for multimodal models

- src/accelerate/commands/config/cluster.py
Fixes https://github.com/huggingface/accelerate/issues/3489 
`override_linear_precision` is incorrectly set when using `accelerate config`
> Fix fp8 deepspeed config

- src/accelerate/commands/launch.py
I got the following error when running a deepspeed test case:
```bash
_________________________________ DeepSpeedConfigIntegration.test_train_multiple_models _________________________________
self = <test_deepspeed_multiple_model.DeepSpeedConfigIntegration testMethod=test_train_multiple_models>
@run_first
@require_huggingface_suite
@require_multi_device
@slow
def test_train_multiple_models(self):
self.test_file_path = self.test_scripts_folder / "test_ds_multiple_model.py"
args = ["--num_processes=2", "--num_machines=1", str(self.test_file_path)]
args = self.parser.parse_args(args)
>       launch_command(args)
tests/deepspeed/test_deepspeed_multiple_model.py:183: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> fix warning error

- .github/workflows/build_docker_images.yml
- .github/workflows/fp8_runner.yml
- benchmarks/fp8/transformer_engine/Dockerfile
- setup.py
This PR adds in running TE/FP8 tests through our dedicated CI runner for said tests. 
Also tweaks the docker image to allow for us to request which CUDA NVIDIA image we use (so we can get the latest TE version of the month). By default it builds with the prior month's image (so we always build off of the "latest-ish" release.
@SunMarc @S1ro1
> Add FP8 runners + tweak building FP8 image

- src/accelerate/test_utils/testing.py
With #3457 this introduces another bug in our CI, where it fails on nightly runners for `TPIntegrationPlugin` on `ValueError("... requires transformers version 4.52.0...")` due to the version of `transformers` on that runner being old (viz [here](https://github.com/huggingface/accelerate/actions/runs/14459958612)). I believe this fail also introduces further unrelated fail, so this should be handled.
> Fix: require transformers version for tp tests

- .github/workflows/build-docker-images-release.yml
- .github/workflows/build_and_run_tests.yml
- .github/workflows/integration_tests.yml
- .github/workflows/quality.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- .github/workflows/test_imports.yml
Fix cache service that is making our CI fail by upgrading the related github action to the latest version
Related https://github.com/actions/setup-python/issues/1085
> Fix cache issue by upgrading github actions version 

- src/accelerate/utils/launch.py
When trying to get FP8 training to work, i was confused by the error message (as the docs say that FP8 via torchao is supported as well). 
`is_fp8_available` tests for all 3 FP8 methods, so the error message should also state all FP8 options :). 
- [X ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
@muellerzr @zach-huggingface
> Add torchao to FP8 error message

- src/accelerate/utils/ao.py
This PR protects better the import as it initializes cuda somehow, breaking the notebook launcher. This was not pick-up by the CI as it requires to install torchao
Fixes https://github.com/huggingface/accelerate/issues/3524
Thanks for the report @jmurph1
To reproduce with the following script or one of our tests:
`CUDA_VISIBLE_DEVICES=0,1 pytest tests/test_cli.py::AccelerateLauncherTester::test_notebook_launcher -s -vvvv`
```python 
from accelerate import notebook_launcher, Accelerator
def dummy_fn():
import os
accelerator = Accelerator()
print(f"Dummy function started in process {os.environ.get('LOCAL_RANK', 0)}.")
import time
time.sleep(5)
print(f"Dummy function finished in process {os.environ.get('LOCAL_RANK', 0)}.")
print("Calling notebook_launcher...")
try: …
```
> Fix unwanted cuda init due to torchao

- docs/source/concept_guides/internal_mechanism.md
This PR changes a documentation link that was not correct. Now, you should be able to access `docs/source/package_reference/torch_wrappers.md` from `docs/source/concept_guides/internal_mechanism.md`, solving the link error in [this page](https://huggingface.co/docs/accelerate/concept_guides/internal_mechanism).
Now, at least in GitHub, the link works.
Fixes #3506
@SunMarc, as he commented on the issue.
1. Go to the file that contained the error in my fork and my branch: …
> Solve link error in internal_mechanism documentation (#3506)

- src/accelerate/utils/fsdp_utils.py
- src/accelerate/utils/modeling.py
This PR fixes the spike first found in #3474. Providing some numerics below:
Loss parity between `cpu_ram_efficient_loading=true/false`
[wandb link](https://wandb.ai/siro/PR3482?nw=nwusersiro)
Memory snapshots:
(The discrepancy between new/baseline in the semi-big rectangle appearing first/in the middle is caused by difference in order of evaluation - top-level first vs bottom-level first)
cc @SunMarc @zach-huggingface 
Possibly moving `get_non_persistent_buffer_fqns` and making it `private` could be an upgrade, this function is quite specific to this use-case.
> [FSDP2] Fix memory spike with `cpu_ram_efficient_loading=True`

- docs/source/usage_guides/ipex.md
- src/accelerate/accelerator.py
Fixes #3516.
Fixes the logic in `accelerator._prepare_ipex` such that:
- Multiple `nn.Module` objects can now be prepared in parallel, without silent failures.
- An error is raised if a user attempts to prepare a combination that is non-trivial to infer (e.g., two modules and two optimizers at the same time).
- A cautionary note and a suggested workaround for this limitation (due to `intel-extension-for-pytorch`) is added to the documentation.
@yao-matrix @BenjaminBossan @SunMarc @zach-huggingface
> Fix logic in `accelerator.prepare` + IPEX for 2+ `nn.Models` and/or `optim.Optimizers`

- .github/workflows/test.yml
- tests/test_load_checkpoint_and_dispatch_with_broadcast.py
Fixes CI. Pytorch 3.7 with python < 3.10 requires `importlib_metadata` to be installed. This can be removed when switching to 3.10.
> Fix CI due to missing package 

- src/accelerate/launchers.py
This change enhances the TPU autodetection logic in notebook_launcher and remove call of device_count() before xmp.spawn for avoiding earlier devices initialising for passing check on torch_xla._XLAC._xla_runtime_is_initialized().
- Added a check for PJRT_DEVICE == "TPU" when TPU_NAME is undefined.
- Removed calls to torch_xla.device_count() before xmp.spawn because it initialised devices.
Fixes [#3358](https://github.com/huggingface/accelerate/issues/3358)
@BenjaminBossan @SunMarc @zach-huggingface
> fix notebook_launcher for Colab TPU compatibility.

- src/accelerate/utils/launch.py
- src/accelerate/utils/other.py
- tests/test_launch.py
This PR implements support for port 0 auto-selection in multi-GPU environments (`prepare_multi_gpu_env()`). The documentation already mentions that setting port to 0 will automatically select the next available port, but this functionality wasn't actually implemented in the code.
When `main_process_port` is set to `0`, the code now:
- Automatically finds an available port through socket binding
- Updates relevant arguments (`master_port`, `rdzv_endpoint`) with the selected port
- Provides a more seamless experience for users working in environments where specific ports might be occupied
@SunMarc @zach-huggingface - This relates to the Command Line Interface and distributed training functionality.
> add support for port 0 auto-selection in multi-GPU environments

- src/accelerate/utils/dataclasses.py
Makes environment variable and dataclass consistent for `cpu_ram_efficient_loading`. Currently, there's an inconsistency when the FSDP plugin is initialized in a standalone fashion: the `cpu_ram_efficient_loading` flag can be set to `True` but if the user doesn't use `accelerate launch` , then the environment variable `FSDP_CPU_RAM_EFFICIENT_LOADING` would not be set. This environment variable is actually used by transformers to initialize parameters efficiently in the process group (See: https://github.com/huggingface/accelerate/issues/2100#issuecomment-1822330625 for details on how this happens)
I can see a previous PR #2998 that tried to make  all env vars optional, but looks like this was left. 
[documentation …
> [FSDP] Make env var and dataclass flag consistent for `cpu_ram_efficient_loading` 

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/fsdp_utils.py
Adds a utility function to strip the `_orig_mod.` prefix that gets added by torch.compile when fixing the optimizer in fsdp2. Fixes #3554.
CC @S1ro1
> canonicalize optimized names before fixing optimizer in fdsp2

- docs/source/usage_guides/deepspeed.md
The deepspeed config path in the deepspeed doc is not up-to-date. This PR updates it.
> [docs] update deepspeed config path

- src/accelerate/utils/fsdp_utils.py
Earlier PR https://github.com/huggingface/accelerate/pull/3560 broke FSDP2 for non-compiled models due to omitted keys from the `named_params` dict. This change fixes the mistake in the if-replace logic, by conditionally stripping the "_orig_mod." prefix only when it's present as intended.
Fixes https://github.com/huggingface/accelerate/issues/3554
-  [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
@S1ro1, @SunMarc
> preserve parameter keys when removing  prefix

- src/accelerate/utils/dataclasses.py
Modified the logic for setting `self.dynamic` to explicitly preserve `None` when the `USE_DYNAMIC` environment variable is not set, aligning with the behavior described in the PyTorch documentation for torch.compile (https://docs.pytorch.org/stable/generated/torch.compile.html). The documentation notes that `dynamic=None` has distinct semantics from `dynamic=False`, where `None` indicates a different configuration state. Previously, the code defaulted to `False` when the environment variable was unset, which could lead to incorrect behavior.
[here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-document …
> Update dynamic env handling to preserve None when USE_DYNAMIC is unset

- src/accelerate/utils/operations.py
There is a bug related to INT64 collectives in oneCCL on XPU. This bug will be fixed in PyTorch-2.9. However, this bug impacts many code examples when running in distributed mode, e.g., below are the predicted labels of `nlp_examples.py`:
```bash
=========tensor([                   1,                    0,                    0,
1,                    0,                    1,
1,                    1,                    1,
1,                    1,                    0,
0,                    1,                    1,
0,                    1,                    0,
1,                    0,                    0,
1,                    0,                    1,
1,                    0,                    1,
1,                    1,                    1,
0,                    1, -4763119552675512320, …
```
> add a `synchronize` call for xpu in `_gpu_gather`

- src/accelerate/state.py
Supersedes https://github.com/huggingface/accelerate/pull/3544
> set backend correctly for CUDA+FSDP2+cpu-offload

- tests/test_big_modeling.py
- tests/test_quantization.py
> enable test_dispatch_model_tied_weights_memory_with_nested_offload_cpu on xpu

- src/accelerate/state.py
- src/accelerate/utils/imports.py
`torch_ccl` supports `torch < 1.12` and now torch already evolve to 2.7, time to say goodbye.
> goodbye torch_ccl

- src/accelerate/utils/launch.py
This PR adds support for the `--standalone` mode in Accelerate, addressing [issue #3175](https://github.com/huggingface/accelerate/issues/3175) and building upon the work in [PR #3501 by @hellobiondi](https://github.com/huggingface/accelerate/pull/3501).
While the documentation notes that setting the port to `0` will automatically select an available port, this PR leverages the built-in `--standalone` functionality from [torch.distributed.run](https://github.com/pytorch/pytorch/blob/9785b32189583abb4cc2e369389575568e384a68/torch/distributed/run.py#L451-L458) and propagates the argument to the underlying `torch.distributed.run` launcher without raising a connection error, reducing the likelihood of port conflicts when running multiple distributed jobs on the same machine ([see …
> Add support for standalone mode when default port is occupied on single node

- src/accelerate/utils/modeling.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> Resolve logger warnings

- src/accelerate/utils/launch.py
Don't know why it assigns `CCL_WORKER_COUNT` only when machine> 1 because 1 CPU machine can also run distributed training or Tensor Parallelism.
I also added KMP params to get better performance on CPU.
With this PR we can run transformers TP model and got 40% speed-up on Intel 4th Gen Xeon.
The accelerate config is :
```
debug: false
distributed_type: MULTI_CPU
downcast_bf16: 'no'
enable_cpu_affinity: false
ipex_config:
ipex: false
mixed_precision: 'no'
mpirun_config:
mpirun_ccl: '1'
mpirun_hostfile: /home/jiqingfe/hostfile
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: true
```
The script is as follows
`accelerate …
> Set ccl and KMP param in simple launch

- src/accelerate/utils/fsdp_utils.py
@SunMarc @IlyasMoutawwakil i searched the `accelerate` code base, and this is the only place which uses `torch.cuda.device`, so I suppose it's safe to change to its device-agnostic `torch.device`, pls help review, thx.
> change to use torch.device

- src/accelerate/test_utils/scripts/external_deps/test_pippy.py
- tests/test_fp8.py
- tests/test_multigpu.py
torchao has xpu support since 0.11.0, so enable torchao cases. ALL cases passed.
enable pippy cases on XPU, ALL passed.
@SunMarc , pls help review.
Till now, all existing accelerate ut cases which are valid on XPU are enabled, thx very much @SunMarc @IlyasMoutawwakil for your great support!
> enable torchao and pippy test cases on XPU

- .github/workflows/gaudi1.yml
- .github/workflows/gaudi3_scheduled.yml
- tests/test_compile.py
- tests/test_load_checkpoint_and_dispatch_with_broadcast.py
> Update Gaudi Runners

- src/accelerate/accelerator.py
- src/accelerate/state.py
> better handle FP8 with and without deepspeed

- src/accelerate/commands/launch.py
A similar issue to PR #3541 remains for the TPU launcher. With this, we avoid prematurely initializing the XLA runtime.
```bash
accelerate launch <script>
```
currently fails. This fixes it. Tested on gcloud v6e TPUs.
@SunMarc @zach-huggingface
> Remove device_count for TPU launcher to avoid initializing runtime

- src/accelerate/utils/modeling.py
> Add fp8_e5m2 support in `dtype_byte_size`

- examples/fsdp2/fsdp2_fp8.py
Very small PR, doesn't change anything functionality-wise, I just got bit by LLM generated code and my lack of attention and was passing labels even though they were shifted. Explicitly pass shifted labels now, doesn't change ANYTHING in the benchmark.
> Fix: correct labels for fsdp2 examples

- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/dataclasses.py
There's a mismatch between when the launcher is used and when simple en vars are passed.
If I run with accelerate launcher, the fp8_format defaults (and env var is overriden) to e4m3, which is not what the dataclass defaults to.
> Add support for e5e2 and default to hybrid when launcher is used

- docs/source/usage_guides/gradient_accumulation.md
This PR fixes a few typos in the `docs/source/usage_guides/gradient_accumulation.md` file.
Changes:
- `adjustements` -> `adjustments`
- `unnecesary` -> `unnecessary`
- `shoud` -> `should`
> Docs: Fix typos in gradient accumulation guide

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/other.py
A rather tiny PR, "fixes" or more likely errors properly on an issue introduced in #3628. The issue is that DDP doesn't work if model has DTensors which it has if it was loaded with device_map="auto" (it applies TP). Now we properly raise an Error.
Snippet to test:
```python
from transformers import AutoModelForCausalLM
from accelerate import Accelerator
model_id = "NousResearch/Hermes-3-Llama-3.1-8B"
accelerator = Accelerator()
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto")
model = accelerator.prepare(model)
```
Before: 
`[rank0]: AssertionError: found no DeviceMesh from dtensor args for c10d.broadcast_.default!`
After:
`[rank0]: ValueError: Your model contains `DTensor` parameters, which is incompatible with DDP. Maybe you loaded your model with …
> Fix: properly error when DDP + Dtensor model

- examples/by_feature/profiler.py
- src/accelerate/launchers.py
- tests/deepspeed/test_deepspeed_gradient_accumulation.py
1. enable xpu for launcher -> validated
2. expand cuda only ds uts to xpu -> all 3 passed
3. expand profiler example to xpu -> validated
@SunMarc , pls help review, thx.
> xpu enablement on left cases 

- benchmarks/fp8/transformer_engine/Dockerfile
- examples/config_yaml_templates/fp8.yaml
- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/launch.py
- tests/test_fp8.py
It looks like the [current fp8 tests are not passing](https://github.com/huggingface/accelerate/actions/workflows/fp8_runner.yml), this PR slightly refactors these tests and makes a few fixes to get them to pass.
It also adds (and fixes) new tests that ensure FP8 functionality can be configured entirely from an accelerate config yaml in the cases where the user doesn't have the ability to change how the `Accelerator()` object is created. This currently seems broken, since you need to be able to pass a `kwargs_handlers` to choose the FP8 backend. With the `transformers.Trainer` class, for instance, the `Accelerator()` object is created under-the-hood, so this should enable FP8 training with that class simply by changing the accelerator config yaml.
to it if that's the …
> Fix FP8 tests, enable FP8 to be used without direct `Accelerator()` configuring

- src/accelerate/tracking.py
Pass config during wandb.init() in offline mode instead of using
config.update() 
Fixes #3607 
similar [https://github.com/huggingface/transformers/issues/38968](https://github.com/huggingface/transformers/issues/38968)
@SunMarc
> fix: wandb config not saved in offline mode

- src/accelerate/data_loader.py
in the code:
```
dataloader_iter = self.base_dataloader.__iter__()
try:
current_batch = next(dataloader_iter)
except StopIteration:
yield
```
If the base dataloader is empty then the exception is raised but `yield` yields nothing.
This at the time of:
```
if self.device is not None:
current_batch = send_to_device(current_batch, self.device, non_blocking=self._non_blocking)
```
would lead to uncaught exception like:
File "/root/rl-swarm/.venv/lib/python3.10/site-packages/accelerate/data_loader.py", line 575, in iter
current_batch = send_to_device(current_batch, self.device, non_blocking=self._non_blocking)
UnboundLocalError: local variable 'current_batch' referenced before assignment because `current_batch` was never assigned because `next(dataloader_iter)` returned with exception …
> accelerate/data_loader.py: do not yield if the base_dataloader is empty

- examples/fsdp2/README.md
- examples/fsdp2/nd_parallel.py
- examples/fsdp2/nd_parallel_prepared_device_mesh.py
- examples/fsdp2/utils.py
- src/accelerate/__init__.py
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/parallelism_config.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/external_deps/test_performance.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/fsdp_utils.py
- src/accelerate/utils/modeling.py
- tests/test_dataclasses.py
Building on #3651
Dependencies:
cc @S1ro1 
> Parallelism config + TP + HSDP +  BYODM (Bring Your Own Device Mesh)

- src/accelerate/accelerator.py
This PR adds a @property method  for simply get parallelism rank in HF Accelerate.
Motivation:
- To make it easier to retrieve the process rank in Distributed Learning using Accelerate.
Changes:
- Added `rank` property in accelerator.py
This PR is from issue #3702 with S1ro1.
Let me know if there’s anything I should improve. 
Thanks a lot for giving opportunity for this amazing PJ!
> Add Parallelism getter property to Accelerator class

- src/accelerate/accelerator.py
If we only had TP specified, the training would probably be still correct, though the optimizer/dataloader wouldn't be accelerator prepared (in some cases). This was and is a rare case, as pure TP is not fully supported yet anyway. Though this PR fixes atleast this.
> Fix: prepare works even if nothing except tp specified (rare)

- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/utils/dataclasses.py
```yaml
env:
ACCELERATE_USE_FSDP: true
FSDP_VERSION: 2
FSDP_RESHARD_AFTER_FORWARD: true
FSDP_STATE_DICT_TYPE: "FULL_STATE_DICT"
FSDP_AUTO_WRAP_POLICY: "TRANSFORMER_BASED_WRAP"
FSDP_CPU_RAM_EFFICIENT_LOADING: false
FSDP_ACTIVATION_CHECKPOINTING: false
```
When passing `ACCELERATE_USE_FSDP: true` in the YAML config file and running the script, the `os.environ.get("ACCELERATE_USE_FSDP", "false") == "true"` condition in Accelerate does not activate FSDP due to receiving the value `"True"` (with uppercase "T").
To prevent this issue, all string values obtained via `os.environ.get` should be converted to lowercase using `.lower()`.
[here are tips on …
> Fix: Ensure environment variable values are case-insensitive in Accelerate

- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/launch.py
- tests/test_configs/latest_fsdp.yaml
For FSDP, there is an option to indicate [`ignored_modules`](https://docs.pytorch.org/docs/stable/fsdp.html), which should be a list of modules are ignored by FSDP. Even though this argument was supported in accelerate, it was not very usable:
1. Listing all modules can tricky, especially with something like PEFT, where the whole model is wrapped and thus the module structure changes.
2. When configuring this argument, accelerate takes a detour via environment variables. These can only be strings. Therefore, passing a list of modules is not feasible.
Moreover, I noticed that the environment variable for `ignored_modules` was not even set, so configuring this argument didn't even work.
**Don't merge yet** This PR is lacking tests. I would be happy for pointers on how to add those.
When …
> ENH: Allow FSDP ignored modules to be regex

- src/accelerate/accelerator.py
With change in #3700 where we default to None, passing 1 as tp_size would result in env vars not being read.
> Fix: tp size wouldn't read from env

- src/accelerate/accelerator.py
- src/accelerate/parallelism_config.py
- src/accelerate/state.py
- src/accelerate/utils/launch.py
Since we moved `ParallelismConfig` to AcceleratorState, it should be fine to remove that in `PartialState`. Trainer in transformers actually reset `PartialState` so we shouldn't keep it there as we can't reconstruct if we don't create global var.
Apart from that, we don't initialize `parallelismconfig` if it is not passed or we didn't set any env var.
> Remove `ParallelismConfig` from `PartialState`

- src/accelerate/hooks.py
- tests/test_hooks.py
Added optimisation to not attempt to move devices if already on that the device. This is more noticeable in large step iterations on diffusion loops when the **pre_forward** can get called many times
Possibly the there is a better way than using **next()** and noticed it's possibly to set the **prev_module_hook** to invalid object so added an additional check. Glad for any feedback to improve. Or perhaps there's an even better way.
Issue was not as bad as I initially thought. But from speaking with maintainers there was some smaller gains found.  Mainly noticeable in large loops
https://github.com/huggingface/diffusers/issues/11872
[here …
> feature: CpuOffload pre_forward don't attempt to move if already on device

- src/accelerate/parallelism_config.py
- tests/test_dataclasses.py
This PR fixes an issue with an import related to device_mesh as it requires to have torch 2.2.0.
> Protect import for device_mesh 

- src/accelerate/state.py
To avoid this warning
```
/fsx/qgallouedec/miniconda3/envs/trl/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:4631: UserWarning: No device id is provided via `init_process_group` or `barrier `. Using the current device set by the user. 
warnings.warn(  # warn only once
```
when using
```python
PartialState().main_process_first()
```
> Specify device_ids in torch.distributed.barrier for PartialState

- src/accelerate/accelerator.py
In FSDP2, the model(`FSDPModule`) does not have `no_sync()` and instead calls  `model.set_requires_gradient_sync(False)`  to turn off gradient synchronization. See at [torch.distributed.fsdp.FSDPModule.set_requires_gradient_sync](https://docs.pytorch.org/docs/stable/distributed.fsdp.fully_shard.html#torch.distributed.fsdp.FSDPModule.set_requires_gradient_sync)
> fix: model.set_requires_gradient_sync(False) should be called to turn off gradient synchronization in FSDP2

- tests/test_cli.py
Tiny fix, #3753 fixes a typo in error message that in return makes this test fail.
> Fix: typo makes tests fail

- tests/test_hooks.py
```
pytest -rA tests/test_hooks.py::HooksModelTester::test_cpu_offload_hook_moves_model
pytest -rA tests/test_hooks.py::HooksModelTester::test_cpu_offload_hook_with_prev_module
```
both pass w/ this PR.
@S1ro1, pls help review, thx very much.
> enable 2 model hook ut cases on XPU

- src/accelerate/utils/operations.py
```python
from transformers.modeling_outputs import CausalLMOutputWithPast
from accelerate.utils import convert_to_fp32
import torch
lm_output = CausalLMOutputWithPast(logits=torch.ones(2, 3, 4))
print(convert_to_fp32(lm_output))
```
before:
```
CausalLMOutputWithPast(loss={'logits': tensor([[[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]],
[[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]]])}, logits=tensor([[[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]],
[[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]]]), past_key_values=None, hidden_states=None, attentions=None)
```
after
```
CausalLMOutputWithPast(loss=None, logits=tensor([[[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]],
[[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]]]), past_key_values=None, …
```
> fix: correct dictionary unpacking in recursively_apply function

- src/accelerate/accelerator.py
refactor: Use  `with`  in Accelerator.autocast()instead of ` __enter__()` and` __exit__()` for more elegant style.
> refactor: Use  `with`  in Accelerator.autocast()instead of ` __enter__()` and` __exit__()` for more elegant style.

- setup.py
This PR removes mlflow from the setup so that we don't test it anymore. The tests are failing because we are installing a very old version due to conflicting dependencies.
> remove mlflow from testing 

- src/accelerate/utils/operations.py
Reverts huggingface/accelerate#3766
This was not the correct fix and the issue was with `ModelOutput` from transformers. I will fix this in transformers
> Revert "fix: correct dictionary unpacking in recursively_apply function"

- src/accelerate/utils/modeling.py
Fix `disk_offload()` api causing `torch.cuda.empty_cache()` to be called when the module origin device is `cpu` and offloaded to `meta` (disk).  
Secondarily this also resolves a performance issue as `torch.cuda.empty_cache()` is slow and calling it with no effect in a forwardig env where modules are dynamically (manually) offloaded is suboptimal. 
```py
model: TritonV2QuantLinear  (P=0 B=2.25M) [cpu | mixed[int32, float16] | ~8.32MB]
buffer: g_idx  shape=(2048,) dtype=int32 device=cpu ~8.00KB
buffer: scales  shape=(16, 8192) dtype=float16 device=cpu ~256.00KB
buffer: qweight  shape=(256, 8192) dtype=int32 device=cpu ~8.00MB
buffer: qzeros  shape=(16, 1024) dtype=int32 device=cpu ~64.00KB
```
Given above nn.Module (linear) which is on `cpu` and following this call, I did not expect …
> Fix (skip) cuda cache flush when origin device is `cpu` and offloaded to `meta`
