huggingface/accelerate

- README.md
Changes `glue_example` to `nlp_example` as that's the name of the script.
> Fix example name in README

- README.md
> Fix typos and tighten grammar in README

- docs/source/internal.rst
- docs/source/quicktour.rst
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/test_script.py
- src/accelerate/utils.py
Currently, the RNG synchronization at the beginning of each epoch is done very broadly, which means the potential data augmentation is done the same way on each process. While this is probably not hurting a big deal unless the underlying dataset isn't very big, there is a way to use local RNG with `torch.Generator` introduced in PyTorch 1.6.
This PR enables this by default and leaves some flexibility to the user to set the RNGs they want to synchronize (among torch, cuda, xla and local generator).
> More flexible RNG synchronization

- src/accelerate/utils.py
As pointed out in #12, users may have some non-Tensor objects in their dataloaders, which is perfectly fine. `accelerate` should not error on those when trying to send a batch on the proper device but just do a noop.
Fixes #12
> Don't error on non-Tensors objects in move to device

- docs/source/index.rst
- docs/source/kwargs.rst
- examples/cv_example.py
- examples/nlp_example.py
- src/accelerate/__init__.py
- src/accelerate/accelerator.py
- src/accelerate/kwargs_handlers.py
- src/accelerate/optimizer.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- tests/test_kwargs_handlers.py
This PR introduces a new argument in the main `Accelerator` class called `kwargs_handlers` which can take a list of config-like objects to customize how the `DistributedDataParallel` or `GradScaler` are created.
For instance, to activate `find_unused_parameters = True`, one would create the `Accelerator` like this:
```
from accelerate import Accelerator, DistributedDataParallelKwargs
ddp_handler = DistributedDataParallelKwargs(find_unused_parameters=True)
accelerator = Accelerator(kwargs_handlers=[ddp_handler])
```
`kwargs_handlers` takes the list of all `KwargsHandler`s desired by the user, to make the API easily scalable to more objects we want to make customizable by the users.
Fixes #11
> Add KwargsHandlers

- src/accelerate/commands/config.py
This PR adds support and defaults toward a YAML config while retaining backward compatibility: it's possible to pass along a json config file and if a default JSON config was created by the user, it will still be used.
However new configs created will default to the YAML format.
> Add YAML config support

- docs/source/quicktour.rst
- src/accelerate/accelerator.py
- src/accelerate/commands/launch.py
- src/accelerate/utils.py
- tests/test_multigpu.py
This PR solves the problem of having predictions of different sizes across processes (for instance when doing padding to the maximum length of a batch) that can't be gathered (the script will hang).
To do this it introduces a new method called `pad_across_processes` that will pad a tensor (or nested list/tuple/dict of tensors) to the maximum length across processes on a given dimension.
> Add utility to pad tensor across processes to max length

- src/accelerate/utils.py
The `size` used inside the `pad_across_processes` function was wrong, this PR fixes that.
> Use proper size

- src/accelerate/commands/config/config_args.py
#17 introduced a breaking change since it requires configs to now have a `"compute_environment"` field. This is fixed by re-running `accelerate config` but we can also be nice to the user and make sure it works for old configs as well :-)
This PR does that.
> Add defaults for compute_environmnent

- README.md
- docs/source/index.rst
- docs/source/quicktour.rst
This PR adds the diff styling to the examples in the index of the documentation and indents all the code in the README/this index by two to make everything align properly.
> Cleaner diffs in README and index

- examples/README.md
- Changed `fb16` -> `fp16`.
- Minor capitalisation fix.
> Fix typos in examples README

- src/accelerate/commands/config/config_args.py
When testing the key dictionary for `"compute_environment"`, the result gotten from the config file is a string, so it needs to be compared with an `==` to the enum value.
> Fix load from config

- src/accelerate/commands/config/cluster.py
Remove indent from https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/config/cluster.py, led to undefined num_processes when using TPU.
> fix cluster.py indent error

- src/accelerate/commands/launch.py
Some of the defaults from the config (like the number of machines used for training) were not properly passed along to the launcher. This PR fixes that.
Fixes #37
> Set all defaults from config in launcher

- src/accelerate/optimizer.py
This PR adds support for the keyword argument `set_to_none` in `AcceleratedOptimizer.zero_grad`, with a version check as PyTorch only introduced it in v1.7.0.
Fixes #42
> Add `set_to_none` to AcceleratedOptimizer.zero_grad

- src/accelerate/commands/config/cluster.py
This PR fixes how the port information provided by the user in `accelerate config` is stored. Previously, it was erasing the IP address of the main process.
Fixes #49
> Fix port in config creation

- README.md
- docs/source/launcher.rst
This PR adds references in the main README and in the documentation to an example of notebook that can be used to fine-tune an NLP model on TPU in Colab.
cc @philschmid
> Add notebook/colab example

- README.md
- docs/source/launcher.rst
- docs/source/quicktour.rst
- src/accelerate/notebook_launcher.py
- src/accelerate/utils.py
This PR adds support for multi-GPU training in the `notebook_launcher` and cleans a bit the API.
The same constraints as for TPU are applicable: no defining `accelerator` outside of the training function **and** CUDA has to be uninitiliazed until inside the trainnig function or the forking process is not happy.
Fixes #36
> Support for multi-GPU in notebook_launcher

- README.md
- src/accelerate/accelerator.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_utils.py
- src/accelerate/state.py
- src/accelerate/utils.py
Possible fix for https://github.com/huggingface/accelerate/issues/32
> Add distributed multi-node cpu only support (MULTI_CPU)

- src/accelerate/optimizer.py
- src/accelerate/utils.py
- tests/test_utils.py
This PR adds support for namedtuples in inputs/outputs of models and dataloaders.
There is sadly no direct check to know if a Python object is a namedtuple, and nametuple can't be instantiated from a generator like regular tuples and lists, the generator needs to be unpacked. Sadly list and tuples don't want that kind of unpacking, so I had to add a utility function that does the distinction depending on the type of object received.
Fixes #65
> Honor namedtuples in inputs/outputs

- src/accelerate/notebook_launcher.py
`notebook_launcher()` will cause the flag `in_colab_or_kaggle` false if runs in kaggle notebook with TPU v3-8 on. The bug will lead the TPU v3-8 starts failed. Changed the sequence of `if` in notebook_launcher.py lines 45-48 to keep TPU is available in kaggle when calling `notebook_launcher()`.
> TPU not available in kaggle

- src/accelerate/notebook_launcher.py
This PR fixes an issue reported on the [forums](https://discuss.huggingface.co/t/missing-positional-arguments-when-try-to-use-multiple-gpus-with-accelerator/6112): basically the `args` are not passed along to the multiprocess call when using several GPUs. This fixes it.
> Pass args in notebook_launcher for multi-GPU

- src/accelerate/commands/config/config_args.py
When I run `accelerate test`, I get this error:
```
File ".../bin/accelerate-launch", line 33, in <module>
sys.exit(load_entry_point('accelerate', 'console_scripts', 'accelerate-launch')())
File ".../accelerate/src/accelerate/commands/launch.py", line 319, in main
launch_command(args)
File ".../accelerate/src/accelerate/commands/launch.py", line 285, in launch_command
defaults = load_config_from_file(args.config_file)
File ".../accelerate/src/accelerate/commands/config/config_args.py", line 43, in load_config_from_file
with open(config_file, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'None'
```
Looks like this command (executed by `accelerate test`)
`Running:  accelerate-launch --config_file=None …
> Fix `accelerate test` with no config file

- src/accelerate/accelerator.py
This PR adds a `free_memory` to the `Accelerator` class, to free memory between two different trainings. This cleans up the internal list to the optimizers, but we will also add other objects stored in the future (for instance #82 adds a reference to the model for deespeed).
Fixes #84
> Add Accelerator.free_memory

- src/accelerate/accelerator.py
This feature is useful when downloading or processing data. 
Example
```python
accelerator = Accelerator() 
cache_fname = Path("cache.txt") 
with accelerator.main_process_first():  ## or accelerator.local_main_process_first()
if cache_fname.exists(): 
data = cache_fname.read_text() # Load from cache 
else:
data = "data" # Time consuming operation 
cache_fname.write_text(data)  # Cache the data
```
This syntaxis is much more concise and contributes with more semantic than the older one:
```python
if not accelerator.is_main_process:  # or is_local_main_process
accelerator.wait_for_everybody()
if cache_fname.exists(): 
data = cache_fname.read_text() # Load from cache 
else:
data = "data" # Time consuming operation 
cache_fname.write_text(data)  # Cache the data
if …
```
> [Feature] Add context manager to allow main process first.

- src/accelerate/accelerator.py
- src/accelerate/deepspeed_utils.py
This PR allows the use of all keyword arguments for the `backward` method.
Fixes #103
> Pass along kwargs to backward

- src/accelerate/notebook_launcher.py
The `start_processes` function introduced with the `notebook_launcher` requires torch 1.5.0, this PR moves the import to avoid having an import error.
> Fix import error for torch 1.4.0

- src/accelerate/accelerator.py
As mentioned in #113, the `unscale_gradients` method of `Accelerator` is unscaling the wrapped optimizer and not the inner one, which results in gradients being unscaled twice.
This PR fixes that.
Fixes #113
> Unwrap optimizer before unscaling

- src/accelerate/data_loader.py
As pointed out by #119, the dataloader length is incorrect when `split_batches=True` (even if the length of the iterator is the right one). This PR fixes that by fixing the length of the batch sampler used.
> Fix DataLoader length when split_batches=True

- src/accelerate/optimizer.py
The `device_placement` was not initialized in the `OptimWrapper` init, this PR fixes that.
Fixes #126
> Fix `OptimWrapper` init

- docs/source/quicktour.rst
- src/accelerate/accelerator.py
- src/accelerate/utils.py
As was pointed out in #101, there is currently a bug in mixed precision training: the outputs are properly computed in mixed precision but are returned in FP16, and the loss computation is not inside a `torch.cuda.amp.autocast` context manager so is executed in full FP16, which is generally unstable (especially for softmax).
This was not discovered with Transformers models as the loss is computed inside the model, which is generally a better idea if one wants to use mixed precision with Accelerate.
To fix the problem, this PR:
- automatically converts the outputs of the model to FP32 so that the loss is executed in full precision (generally a better idea)
- adds a context manager `accelerator.autocast` for more complex loss functions that should be executed in mixed precision (as with all …
> Fix fp16 by converting outputs back to FP32

- docs/source/quicktour.rst
- src/accelerate/accelerator.py
- src/accelerate/deepspeed_utils.py
- src/accelerate/optimizer.py
This PR adds a property to check whether or not the optimizer step was skipped in Mixed Precision or DeepSpeed training. This is not necessary to use in most cases, but could be important if there are not many training steps.
> Add optimizer not stepped property

- src/accelerate/utils.py
The details about this PR is [huggingface/transformers:#13232](https://github.com/huggingface/transformers/issues/13232)
I test the official example scripts: https://github.com/huggingface/transformers/examples/pytorch/translation/run_translation_no_trainer.py 
when using `fp16` mode via the `accelerate` repo.
However, it has been corrupted as follows:
I checked the `outputs.loss` and found it is a `dict` object with keys `dict_keys(['loss', 'logits', 'past_key_values', 'encoder_last_hidden_state'])`.
I tracked the problem to this function：`convert_to_fp32` in `accelerate/utils.py`
```python
def convert_to_fp32(tensor):
if isinstance(tensor, (list, tuple)):
return honor_type(tensor, (convert_to_fp32(t) for t in tensor))
elif isinstance(tensor, dict):
return type(tensor)({k: …
```
> fix fp16 covert back to fp32 for issue: unsupported operand type(s) for /: 'dict' and 'int'

- docs/source/quicktour.rst
- src/accelerate/commands/config/__init__.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/test.py
I think the default config is in `.yaml` format not in `.json`. Was a bit confused when reading the docs.
> [Docs] Machine config is yaml not json

- src/accelerate/utils.py
Similar to how it's done in `transformers`, I think we should always allow untested optimizers, e.g. for AdamW.
See: https://github.com/huggingface/transformers/blob/b6ddb08a664565848c4741e0ff949a4d12989e83/src/transformers/deepspeed.py#L342
cc @stas00 @vasudevgupta7
> [DeepSpeed] allow untested optimizers deepspeed

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/test_script.py
- src/accelerate/utils.py
This PR adds a new API called central dataloader. The main concept is that the dataloader passed along to the `accelerator.prepare` method will behave like this: they will only be iterated on the main process, which will then dispatch the batches on all the other processes.
This solves two different problems:
- it makes sure all processes have the same underlying data (a feat usually achieved by synchronizing random number generators) when there is some random events out of the script control that can change the data: for instance we are streaming a dataset and there could be timeouts on some of the processes but not all
- when using an IterableDataset, it avoids iterating through (and thus processing) the data number of processes times, which saves CPU resources and make sure the GPUs …
> Central dataloader

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
This PR changes the default of `dispatch_batches` to None, so that it becomes more dynamic:
- for `IterableDataset` it will then default to `True`
- for other datasets, it will keep the old default of `False`
This is because the option is really better and safer for `IterableDataset` (cc @lvwerra )
> Dynamic default for `dispatch_batches`

- src/accelerate/utils.py
Currently, when fp_16 = True is set in the Accelerator, the model returns a bool, so I fixed it based on #172.
> fix bug #172

- src/accelerate/data_loader.py
Currently, the `DispatchDataLoader` object as the same length as the underlying dataloader, even if it will return 8 times less batches.
> Fix length of DispatchDataLoader

- src/accelerate/utils.py
- tests/test_utils.py
By mistake, the refactor in #164 introduced a bug in `send_to_device` and made it error when non-tensor data is passed. This PR fixes that.
Fixes #176
> Fix send_to_device with non-tensor data

- src/accelerate/utils.py
- tests/test_utils.py
Currently, all the reclusive utility functions defined in the `utils` module handle nested lists and dictionaries of a base type (usually tensors) but not `UserDict`, which is not considered an instance of `dict`.
This cause problems with the `BatchEncoding` type in Transformers (which is a `UserDict` so is not considered a subclass of `dict`) as pointed out by #178. This PR addresses that issue.
Fixes #178
> Handle UserDict in all utils

- src/accelerate/utils.py
As discussed in #179, it's enough to use `collections.abc.Mapping` to handle both the `dict` and the `UserDict` types in the codebase. This PR addresses that.
> Use collections.abc.Mapping to handle both the dict and the UserDict types

- docs/source/index.rst
Both `accelerator` or `Accelerator` would do the trick, but `accelerate` won't since we never import it and even we do, the `backward()` method doesn't exist in `accelerate`.
> fix typo in code snippet

- src/accelerate/accelerator.py
The lines 152--154 in `accelerator.py` have the risk of causing `AttributeError: 'Accelerator' object has no attribute 'rng_types'` (ex. line 392 in `accelerator.py`)
So this PR:
- Define `self.rng_types` in advance.
> fix rng_types in accelerator

- examples/nlp_example.py
- src/accelerate/accelerator.py
- src/accelerate/kwargs_handlers.py
- src/accelerate/state.py
As pointed out it #223, users sometimes need to customize some of the kwargs of the `init_process_group` method of the torch distributed package. This PR enables that.
Fixes #223
> Add customization point for init_process_group kwargs

- src/accelerate/accelerator.py
I am trying to do some prompt tuning with deepspeed+accelerate, and by default, when using deepspeed, all model parameters are updated. Instead, I'd like to only update the ones that I put in the original optimizer.
> make deepspeed optimizer match parameters of passed optimizer

- setup.py
Upgrades the `accelerate` library quality tool `black` to use the first stable release of `black`, version 22.0.
> Upgrade black to version ~=22.0

- src/accelerate/commands/launch.py
A few notes:
- I have tested the various configurations of `simple_launcher()` locally, but not the others.
- I did not add any pytest tests.
- There is a bit of repetition in the spots that check for when both flags are set together. This could be done in the sanity check section before a specific launcher is called, or it could be omitted entirely since the error would hopefully be obvious, but I thought the best solution was to just do it where the flags are used.
- I ran `black` but it changed a lot of unrelated code, so I undid that.
- It's kind of a niche feature so I didn't bother adding anything to the .rst docs.
I'm happy to take feedback on these notes or any other comments.
> Add launch flags --module and --no_python (#256)

- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/launchers.py
- src/accelerate/state.py
- src/accelerate/utils.py
This PR adds a field in the config to only use CPU even if GPUs are available. It also simplifies the state initialization using that new flag.
Fixes #261
> Add a flag to use CPU only in the config

- src/accelerate/state.py
- src/accelerate/test_utils/test_script.py
- src/accelerate/utils.py
This PR includes basic fixes to the DeepSpeed integration to make sure the base `accelerate test` passes.
The main issue is that the primitive such as gather/broadcast were behaving in DeepSpeed like in single-process mode.
> Basic fixes for DeepSpeed

- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
- src/accelerate/utils.py
- tests/test_state_checkpointing.py
Closes https://github.com/huggingface/accelerate/issues/171
This PR adds in two functions, `Accelerator.save_state` and `Accelerator.load_state`, which will go through and checkpoint the current state of everything accelerator touches.
I've included a testing script, but this needs to be properly turned into a test, as currently it is just a script with a bunch of asserts. I have tested successfully on:
- Single GPU
- Single CPU
- Multi-GPU
> Add in checkpointing capability

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
`torch.distributed` does not have `broadcast_object_list` until v1.8.0 and above, so we can't use the `DispatchDataLoader` for versions smaller than this. This PR adapts the defaults and raises proper ImportError.
This was reported on the [forums](https://discuss.huggingface.co/t/why-my-accelerate-just-doesnt-work/15409)
> Don't use dispatch_batches when torch is < 1.8.0

- Makefile
- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
- src/accelerate/utils.py
- tests/test_state_checkpointing.py
Introduces a `register_for_checkpointing` function, as well as two save/loading functions for those registered objects. 
Would like an initial review for if I'm on the right track 😄
> Implementation of saving and loading custom states

- src/accelerate/test_utils/test_script.py
- src/accelerate/utils.py
- tests/test_utils.py
Solves issue #273
As discussed in the issue, the solution is to use a class instead of a
closure to achieve the same result.
I created an alias `convert_outputs_to_fp32` = `ConvertOutputsToFp32` so
that importing `convert_outputs_to_fp32` can still be imported.
Alternatively, I could remove the alias and change import to use
`ConvertOutputsToFp32` directly, but this may break backwards
compatibility. Or I could name the class `convert_outputs_to_fp32` because
it acts like a function.
Regarding the testing, I added a check to `test_script.py` for the model
trained with `mixed_precision='fp16'`. Locally, this test could not trigger
the error in the issue because the forward method is never replaced. I
believe this is because `AcceleratorState` detects that my machine can't
perform fp16 …
> Make accelerated model with AMP possible to pickle

- CONTRIBUTING.md
- README.md
- docs/source/installation.mdx
I don't change at docs files, but also have old references to `master` branch at `docs/source/installation.mdx`. I should also update the docs?
> replace texts and link (master -> main)

- src/accelerate/accelerator.py
This PR passes along the execution info expected by the `__exit__` of any context manager.
We were previously able to get around that because PyTorch had written the signature of thier autocast `__exit__` as `*args`, but they updated it to the normal `exc_type, exc_value, exc_tb` in v1.11.
Fixes #281
> Pass along execution info to the exit of autocast

- src/accelerate/checkpointing.py
This PR makes sure we load the model and optimizer state dicts (in the `load_state` method) on the CPU. Otherwise, those might be tensors that are on GPU 0 (since `save_state` only saves on process 0), which may result in an OOM: at some point we may have the optimizer state properly loaded on GPU 0 (by process 0) but also loaded a second time in GPU 0 by process 1 during `load_state_dict`, so twice that size on poor GPU 0.
> Load model and optimizet states on CPU to void OOMs

- examples/nlp_example.py
Datasets v2 seems to have removed `rename_column_` so this PR adapts the example to run with it.
> Fix example for datasets v2

- src/accelerate/commands/launch.py
The default in `mixed_precision` for the launch command should be `None`, otherwise the config value is not used. Thanks @nbroad1881 for reporting the bug!
> Leave default as None in `mixed_precision` for launch command

- src/accelerate/test_utils/testing.py
- tests/test_tracking.py
Cleans up the tests in trackers to better utilize mocking, tmpdir's, and make wandb like us.
(It didn't like if we removed the original logging dir, but doesn't complain when we just wipe everything inside it and keep writing to it!)
> Create new TestCase classes and clean up W&B tests

- src/accelerate/tracking.py
- tests/test_tracking.py
Found out comet also has an offline mode. Parsing their bits was trivial, we're just checking the messenger log here to pick up that the right values got stored.
Now we're fully tested 😄 
Key bits:
Slight behavioral differences between online vs offline for Comet:
- We use an `OfflineExperiment` rather than `Experiment`
Probably wouldn't be a bad idea to update the docs with this as well, basically stating if you are wanting to use comet offline to log, you should make those changes.
> Write tests for comet_ml

- src/accelerate/accelerator.py
When mixed precision is set to no or bf16 with DeepSpeed, everything fails in Accelerate becasue the deepspeed config as no "fp16" key. This PR fixes that.
Fixes #302
> Fix training in DeepSpeed

- README.md
- docs/source/quicktour.mdx
- src/accelerate/commands/launch.py
This way a user doesn't have to add a `local_rank` argument in their script.
> Use --no_local_rank for DeepSpeed launch

- src/accelerate/commands/config/cluster.py
- tests/test_tracking.py
- Change CPU param to use `convert_yes_no_to_bool` in the CLI Config
- Changes the logic for W&B `.log` tests to be `assertTrue` and "str" in `output`
- Fixes an undocumented issue where the Accelerate Config CPU param expected a boolean argument, but it was phrased in a way where it seemed like yes/no could be passed in [forums post](https://discuss.huggingface.co/t/accelerate-on-1-gpu/16617)
- Noticed that the CI seemed to be slightly unstable with the W&B log parsing (unsurprising), so rather than a `self.assertEqual` I opted for a `self.assertTrue` and runs an `in` check, since we only care that the value itself is in the log, with potentially a little bit of noise
> Fix Accelerate CLI CPU option + small fix for W&B tests

- examples/README.md
- examples/by_feature/README.md
- examples/by_feature/checkpointing.py
- examples/by_feature/tracking.py
- examples/cv_example.py
To jump ahead of a similar problem in Transformers currently, this PR adds additional example scripts for `Accelerate` features individually, and provides a framework for how to write a new script when some new feature is added.
Each new script is based on the original `nlp_example.py` script, and adds *one* single capability to each one. This is then documented in the `README.md` in `examples/by_feature`.
- Users of Accelerate and Transformers
We received feedback recently that the current example scripts in `transformers` are becoming too bulky, and I especially noticed this in the `complete_nlp_example.py` script. As more features get added, the logic will get exponentially worse to navigate as time goes by
- Potentially we should test these scripts similar to how we do in …
> Refactor Examples by Feature

- src/accelerate/accelerator.py
I noticed that my training using the deepspeed integration in accelerate had some strange behavior, the number of iterations per epoch didn't go down as I increased number of GPUs. Also loss wasn't converging as expected.
After a bunch of debugging, I found that `_prepare_deepspeed(...)` doesn't appear to call `_prepare_one(...)` properly. It calls without setting `first_pass=True`, which means that `prepare_one(...)` skips wrapping the DataLoaders... defeating the whole point
I added logging to my training flow to print out `len(data_loader)` after `accelerator.prepare(...)` is called. 
I validated that with this fix, the length is divided by the number of processes, as expected.
> Fix DataLoader sharding for deepspeed in accelerate

- src/accelerate/accelerator.py
- src/accelerate/tracking.py
- src/accelerate/utils.py
- tests/test_tracking.py
This PR refactors much of the logic when it comes to how Trackers are initialized and checked inside of `Accelerate`
- Users of Accelerate who want to use W&B, TensorBoard, etc and want clear errors as to what went wrong
I noticed that users were finding it confusing as to why a `logging_dir` must always be passed in when using `"all"`, and this was because of `TensorBoard` requiring a logging directory.
On top of this, the current logic to check if a tracker can be added is a heap of spaghetti code that isn't maintainable. 
When users forget to pass in a `logging_dir` to `Accelerate.__init__` and a particular tracker needs them, an error is now raised stating:
```
Logging with `TensorBoardTracker` requires a `logging_dir` to be passed in.
```
Each `GeneralTracker` implementation now …
> Refactor Tracker logic and write guards for logging_dir

- examples/by_feature/README.md
- examples/by_feature/cross_validation.py
- src/accelerate/test_utils/testing.py
- tests/test_examples.py
This adds an example to `examples/by_feature` for performing Cross Validation with `Accelerate`. 
Along with this, since we cannot run Cross-Validation well on 4 examples (our test sample dataset), I have elected to move the bits over from `transformers` so we can have `slow` tests. The CV examples run under slow, and take quite a bit (even on GPU, a minute). Ideally I should come up with a better solution for this, but I think for now if it is the only one it is not the end of the world.
This also implements the "skip_example" feature mentioned in my previous PR for making sure all aspects of a test are implemented in `complete_*_example.py`, since cross-validation is too niche for that.
Users of Accelerate, especially Kagglers, who want to perform Cross Validation with Accelerate and …
> Create Cross-Validation example

- src/accelerate/accelerator.py
This PR introduces `Accelerator.clear`, an alias for `Accelerator.free_memory`. The reasoning for this addition is a user may be wanting to destroy all of the stored items in Accelerate, and they may instinctively search for a "clear" function.
They may dig for a bit until they see that `free_memory` is what they should call, so this pr helps to aid that workflow style and expectation.
(This PR is 100% opinionated ;) )
> Create alias for Accelerator.free_memory

- docs/source/tracking.mdx
In some code examples `Accelerate` was imported from `accelerate` instead of `Accelerator` .
> fix typo in docs of accelerate tracking

- examples/by_feature/checkpointing.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- src/accelerate/test_utils/testing.py
- tests/test_examples.py
This PR fixes a number of bugs currently present in the save/load examples
Closes https://github.com/huggingface/accelerate/issues/322
As I was exploring solving 322 and writing tests, I was noticing that some behaviors weren't *quite* behaving how I would have expected them to. 
It also didn't make logical sense to me that if we resume at epoch 1, the numbering starts at epoch 0 again (and thus, our checkpoint saves do as well!). So, that behavior had to change slightly.
> Fixup all checkpointing examples

- src/accelerate/commands/config/config_args.py
If an existing config does not have anything on FSDP (as will be the case for most users since the future just went out) there is currently an error in the launcher that the config has a `None` `fsdp_config`. This PR takes care of this by making sure all dicts attributes of the config are initialized in the post_init.
cc @pacman100 for information.
> Fix default config dicts

- src/accelerate/test_utils/testing.py
- tests/test_tracking.py
Refactors `TestCase` decorators to use `unittest.skipUnless` to simplify the logic greatly.
Solves import bug with `comet_ml` on `test_tracking.py`
Introduces requires decorators for `comet_ml` and `wandb`
> Clean up tests + fix import

- src/accelerate/memory_utils.py
- tests/test_memory_utils.py
Makes sure that if zero is reached when finding the batch size, we raise an error stating no batch size will fit
> Add guards for batch size finder

- src/accelerate/memory_utils.py
- tests/test_memory_utils.py
Raising any error if it doesn't relate to CUDA OOM was removed in https://github.com/huggingface/accelerate/pull/334, this adds it back. 
Otherwise this would result in an infinite loop constantly reducing a bs of 0
> Patchfix infinite loop in bs finder

- examples/by_feature/tracking.py
- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
- src/accelerate/logging.py
- src/accelerate/tracking.py
- tests/test_state_checkpointing.py
Adds a new `LoggerAdapter` and a `get_logger` helper to help aid with printing logs repeatedly when in multiprocess
Users were reporting that the logs can confuse them with the actions actually occuring (such as logging multiple times a model was saved even though it only happened once).
Rather than an onslaught of if statements, this PR takes the simpler approach of creating an Adapter that will do the check for us. 
By default it will only log to the main processor, but if all processes should log just pass `main_process_only=False` (see examples below) 
Loggers in Accelerate now accept a `main_process_only` kwarg
```python
from accelerate.logging import get_logger
logger = get_logger("my_logger")
logger.info("My message!")
logger.info("My message!", main_process_only=True) …
```
> Introduce multiprocess logger

- src/accelerate/commands/config/cluster.py
This slightly tweaks the question asking how many devices the user will be using when running `accelerate config`
Closes https://github.com/huggingface/accelerate/issues/338
Stating the number of processes is very general, and I as well found it a bit confusing until I learned that just means number of GPUs, CPUs, etc that will be the **main training device**. As a result, PR proposes changing it from:
```
How many processes in total will you use? [1]
```
To:
```
How many devices should be used for (potentially) distributed training? [1:]
```
> Improve num_processes question in CLI

- src/accelerate/commands/launch.py
- src/accelerate/utils/versions.py
- Checks for the right launcher based on the torch version
- Adds `num_cpu_threads_per_process` and sets it to env to get rid of torchrun warning. Default is torchrun default
> Handle deprication errors in launch

- src/accelerate/launchers.py
Fixing a minor typo, `num_process=...`  -->  `num_processes=...` in the error message when `num_processes` is `None` for `notebook_launcher`.
> Fix minor typo in `notebook_launcher` error message

- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- src/accelerate/tracking.py
- tests/test_examples.py
- tests/test_tracking.py
1. When dictionary of metrics is provided to the accelerate tracker, tensorboard wasn't able to log it. Example with dict of metrics is in this transformers script [run_glue_no_trainer.py](https://github.com/huggingface/transformers/blob/9f16a1cc13029c37fd3b7713d0edb743a8a86e39/examples/pytorch/text-classification/run_glue_no_trainer.py#L541). Fixed support for dictionary of int/float metrics 
2. Fixing examples so that run is created only for the main process else wandb will create num_processes runs with no data.
3. comet-ml logging wasn't helpful as everything was being logged in others `log_others`. No plots were being created. Fixing it to be able to get plots for metrics using `log_metric` and `log_metrics`.
Post these changes, below are the plots for the …
> fix tracking

- docs/source/internal.mdx
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/other.py
This PR adds a `write_basic_config` file that will write a barebones config file automatically setting the GPU's to be the maximum GPUs available (or CPU), and takes in one param for mixed precision
Folks who want to avoid running `accelerate config` and for tests that need to be ran with `accelerate launch`.
Along with a request in the fastai integration https://github.com/fastai/fastai/pull/3646, I was working on fixing up the tests we currently run and was noticing some frustration when trying to setup and configure them to be launched on multi gpu. 
Adds a `write_basic_config` config to `test_utils/testing.py`, that should be used in tests but users can optionally use it to setup a basic configuration if wanted. It **will not** override an already setup configuration.
```python
from …
```
> Add a utility for writing a barebones config file

- src/accelerate/accelerator.py
Fixes #369
1. Fixes the deepspeed model saving in Zero Stage-3. This saves the model in 16-bit precision by first gathering all the parameters across processes onto main process  to get complete state dict.  A point to note  - this is expensive in time and memory.
> fix deepspeed model saving

- examples/by_feature/checkpointing.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- src/accelerate/test_utils/training.py
- tests/test_examples.py
This PR refactors all the example tests to use `accelerate launch` to be ran, adjusting any testing logic that needs to be done to compensate for this. Mostly changing the accelerate.print mocks to use string matching instead based on stdout from `subprocess.run`
In order to have our tests be ran on more than one GPU, the tests needed to be refactored to allow for the `accelerate launch` command to be used via subprocess rather than calling it in python directly. 
All of the example scripts now contain a small snippet denoting that a particular import is only used for testing, and should be ignored
`mocked_dataloaders` was migrated to the test utils.
> Refactor tests to use accelerate launch

- src/accelerate/commands/launch.py
1. In DeepSpeed Zero Stage-1, the offload_optimizer was not present in accelerate config and as such was being set to "None" whereas the deepspeed expects it to "none"
> fix deepspeed zero stage-1

- src/accelerate/utils/imports.py
We are having issues in the tests of Transformers where there is a folder called `deepspeed` containing test files for DeepSpeed.
That folder gets interpreted as the "DeepSpeed" package by Accelerate, which then tries to import things.
This PR fixes that by making the test for `deepspeed` more robust (like we have for Datasets in Transformers).
> Better check for deepspeed availability

- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
- src/accelerate/utils/offload.py
This PR refactors some parts of `load_checkpoint_in_model` as independent utils, so we can re-use them in Transformers.
> Refactor some parts of `load_checkpoint_in_model`  in utils

- examples/cv_example.py
Fixes small config typo in the CV example, should be `mixed_precision` and not `mix_precision`
> Fix typo in cv example

- .github/workflows/build-docker-images.yml
- docker/accelerate-cpu/Dockerfile
- docker/accelerate-gpu/Dockerfile
This PR adds a workflow to publish two docker containers nightly: 
- [huggingface/accelerate-cpu](https://hub.docker.com/r/huggingface/accelerate-cpu)
- [huggingface/accelerate-gpu](https://hub.docker.com/r/huggingface/accelerate-gpu)
These will eventually be up-streamed and used in our nightly tests for testing multigpu, gpu, etc. 
I also modified the Dockerfile slightly to add a different end-user when launching the docker container for security reasons.
> Build Docker Images nightly

- src/accelerate/hooks.py
While testing the `dispatch_model` features in [this PR](https://github.com/huggingface/transformers/pull/17401) I hit some edge case for model parallelism: when a submodule of a given model is never actually called in the forward pass (like the `h` of the GPT-2 model which is a module list which is iterated on in the forward but not directly called) the inputs aren't necessarily moved to the right device.
This PR adds a hook in all submodules to just move those inputs to the device, which fix this issue.
> Better dispatch for submodules

- setup.py
This PR adds `packaging>=20.0` to the project requirements, which is the same pin as in [transformers](https://github.com/huggingface/transformers/blob/main/setup.py#L132)
Closes https://github.com/huggingface/accelerate/issues/393
Current installations from source fail due to the `packaging` package needing to be installed in both accelerator.py and versions.py in huggingface/accelerate
> Add packaging to requirements

- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- tests/test_examples.py
1. Train loss being logged wasn't normalized and as such wasn't intuitive to understand. This also made it difficult to compare train loss between different tools such as comparing train loss from Trainer with that of Accelerate. This PR normalizes the train_loss per epoch to make is more intuitive and comparable.
> improve train loss metric logged in examples

- src/accelerate/test_utils/testing.py
- tests/test_examples.py
This PR fixes one of the example tests that would fail due to saving by step and the slight differences between on a single GPU vs multiple GPU's. 
Currently the example tests will fail when in a multi-gpu, this fixes it.
> Fix CUDA examples tests

- .github/workflows/build-docker-images.yml
- .github/workflows/nightly.yml
- .github/workflows/test.yml
- docker/accelerate-cpu/Dockerfile
- docker/accelerate-gpu/Dockerfile
- setup.py
- src/accelerate/test_utils/training.py
- tests/test_examples.py
**Should be merged after**:
* #407 
* #408 
* #409 
This PR adds nightly runners that will test on a GPU and multi-GPU, and runs all slow tests. In total it should take somewhere between 5-10 minutes to run (depending on whether a cache of a Docker image needed to be downloaded beforehand)
We currently have no runners for testing CUDA and multi-GPU tests, or slow tests on the CI. As a result there were **many** undiscovered errors and bugs that needed to be solved. This PR ensures that we can trust the quality of our code and know when we have issues on platforms other than on the CPU.
Currently they are running nightly, a different workflow will handle when pushes to main occur that I will work on later next week.
> Introduce nightly runners

- .github/workflows/on-merge.yml
This PR adds a similar workflow to the nightly tests, that will run tests for Accelerate post a commit to main. The main difference is we do not run the slow tests so that if multiple PR's are accepted in rapid succession (or pushes to main in general), the queue is not hanging for ages to let everyone through. But, it is rapid enough to where if a push to main did break something in CUDA, we are made aware of it.
> Introduce post-merge runners

- .github/workflows/test.yml
- examples/README.md
- examples/by_feature/checkpointing.py
- examples/by_feature/cross_validation.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- examples/complete_nlp_example.py
- examples/nlp_example.py
- setup.py
This PR switches all example scripts to use `evaluate` instead of `datasets` for the metric computation. cc @lvwerra
> Switch to evaluate for metrics

- .github/workflows/test.yml
- Makefile
This PR speeds up the time for the github CI tests to pass by ~2.5x through a few basic optimizations:
Four new test conditionals were added to the `Makefile` based on groupings of how each example test needs to be ran, and how their topics relate to each other:  
- `test_example_differences`: The quick method that checks if the .py files are missing any parts in the examples/ dir
- `test_checkpoint_step`: tests relating to checkpoint by step and load checkpoint by step
- `test_checkpoint_epoch`: tests relating to checkpoint by epoch and loading checkpoint by epoch
- `test_rest`: Everything that did not fall under the previous three
By using these two specific actions, we can speed up the time it takes to setup the python environment, cache the pip installation, and also cache the model …
> Speedup main CI

- .github/workflows/nightly.yml
- .github/workflows/on-merge.yml
- .github/workflows/quality.yml
- .github/workflows/test.yml
- docker/accelerate-cpu/Dockerfile
- docker/accelerate-gpu/Dockerfile
- setup.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- tests/test_big_modeling.py
- tests/test_tracking.py
This PR upgrades the minimum py version to 3.7 and fixes all tests related to the upgrade. TensorFlow was also removed as a side dep for CUDA reasons.
> Push out python 3.6 + fix all tests related to the upgrade

- .github/workflows/nightly.yml
This PR enables the slow tests to be ran as part of the nightly builds. These seem to have gotten fixed during https://github.com/huggingface/accelerate/pull/420 as shown in https://github.com/huggingface/accelerate/runs/6697809890?check_suite_focus=true
(Failure in that runner is unrelated to the slow tests, and the multi-gpu one ran before the new docker image was out).
Finally stabilized our full CI test suite outside TPUs ❤️
> Enable slow tests during nightly

- .github/workflows/check_dependencies.yml
- setup.py
Noticed that when merged, the Docker images couldn't be made (failed here: https://github.com/huggingface/accelerate/actions/runs/2449927979).
This PR makes the runner inherit the repository secrets safely (documented [here](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) in step 3)
Shown success is here: https://github.com/huggingface/accelerate/actions/runs/2450268127
( @ydshieh mostly so you're aware of such a behavior, I didn't know about it 😄 )
> Fix secrets in Docker workflow

- src/accelerate/accelerator.py
1. Check was happening after the point of using FSDP functionality. Fixed it t be before using any FSDP functionality
2.  Issue  #436  would not happen because a value error would be raised specifying that FSDP requires PyTorch nightlies.
> fix fsdp PyTorch version dependency

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/test_utils/scripts/test_sync.py
- src/accelerate/utils/launch.py
- src/accelerate/utils/modeling.py
- tests/test_tpu.py
- tests/xla_spawn.py
- Make `prepare_model` use [`MpModelWrapper`](https://pytorch.org/xla/master/index.html#torch_xla.distributed.xla_multiprocessing.MpModelWrapper) to distribute the model across all devices efficiently when used
- Changes `prepare_dataloader` to create an [`MpDeviceLoader`](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L171) allowing for the dataloaders to be more efficient. 
- Changes `DataLoaderShard` to no longer do `xm.mark_step`, `MpDeviceLoader` will handle this for us. Instead if on TPU we set the device as `None` in `prepare_dataloader` letting `MpDeviceLoader` take over with the `device` when needed. 
- Allow for FP16 and BF16 precision types on the TPU via AcceleratorState since they are now supported
- Users of TPUs
We currently have a …
> Revamp TPU internals to be more efficient

- setup.py
This PR adds `psutil` as a dependency as it's required by the big model inference files.
Fixes #444
> Add psutil as depenedency

- src/accelerate/big_modeling.py
- src/accelerate/hooks.py
- tests/test_big_modeling.py
This PR deals with models with unused submodules combined with offload (on CPU and disk). By unused submodules, we mean a something like the `ModuleWithUnusedSubModules` introduced in the test file in this PR: a module that defines a submodule, but does not call it during its forward, just does some operations using its weights.
Currently, the offload will fail for such modules because the weights are fetched in a pre-forward hook and the forward method is never called. This PR fixes that by introducing a new argument named `load_all_weights_classes` (if you have any better suggestion, please let me know as I'm not super happy with this name) which contains the name of such submodules used (like `no_split_module_classes` contains the names of the modules that shouldn't be split across …
> Offload and modules with unused submodules

- src/accelerate/utils/imports.py
This PR fixes a situation where `torch_xla` is installed but a TPU device isn't present. 
This originally would cause the import to pass, even though a TPU device isn't found. Instead we combine this with a quick `xm.xla_device()`, that raises a `RuntimeError` if not on a TPU.
I've tested this on a CPU and TPU version of Colab. 
cc @sgugger
> Better checks for if a TPU device exists

- examples/by_feature/gradient_accumulation.py
Solves https://github.com/huggingface/accelerate/issues/435 by changing the conditional to `!=`, stepping at the right time.
> Fix right conditional to stepping

- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
This PR adds a guard if the user tries to pass a different `mixed_precision` or `cpu` flag to `Accelerator()` after the `AcceleratorState` has been initialized once.
Users of Accelerate
Currently if a modification is attempted to be made, it gets ignored leaving the user confused as to why they passed in a new mixed precision type, or told the Accelerator to run on the CPU, when in actually it has not due to the AcceleratorState being built once. 
Nothing
A new `_check_initialized` function has been included in the `AcceleratorState` that fills a clear string template of what they tried to do, why they cannot do it, and how to achieve their desired behavior.
> Raise a clear warning if a user tries to modify the AcceleratorState

- .github/workflows/check_dependencies.yml
- .github/workflows/on-merge.yml
Currently slow runner tests don't show up on the commit to main as they're triggered separately, making it hard to realize when they fail. This PR makes the on-merge ci (aka the slow runner) reusable and has `check_dependencies` trigger it at the very end. This lets the commit SHA/message be linked and it will show up in the merge history with a checkmark or x if there was a failure. 
Some git specifics:
If you combine an `if: always()` with a `needs: {workflow}`, it will wait until `{workflow}` finishes running and then will always run.
> Link CI slow runners to the commit

- docs/source/internal.mdx
- src/accelerate/utils/imports.py
This PR adds the following to the documentation:
- `is_bf16_available`
- `is_torch_version`
- `is_tpu_available`
My motivation for this is while they're mildly small utility functions, they have more usecases than just being used internally. Especially the `is_bf16_available`, as pytorch's own check isn't shown in their general documentation so many people did not even know it existed!
I'm 50/50 on if we want to show `is_torch_version`, but bare minimum `is_tpu_available` and `is_bf16_available` are a must IMO as they have different underlying checks than just "is this package installed"
> Expose some is_*_available utils in docs

- setup.py
Adds docbuilder to the setup.py similar to transformers. 
I could put it also in the `docs` subsection as well, but as we're mimicking it twice I'd rather we wait until doc-specific dependencies are needed, then it may be a good idea to have a `deps_list` util similar to that of `transformers`. For now though I think that's unnecessary.
> Add docbuilder to setup.py

- docs/source/_toctree.yml
- docs/source/internal.mdx
- docs/source/utilities.mdx
- src/accelerate/utils/dataclasses.py
This PR refactors the docs with a "General Utilities" landing page, that includes more of what exists in `accelerate.utils`. This was made with the belief of improving and exposing more in the docs that a user (and potentially power user) may want to find and/or see what is available to be used.
> Refactor Utility Documentation

- examples/by_feature/fsdp_with_peak_mem_tracking.py
- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
1. PyTorch has renamed `default_auto_wrap_policy` to `size_based_auto_wrap_policy`. This PR updates the same.
> fixing fsdp autowrap functionality

- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/multi_process_metrics.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- src/accelerate/accelerator.py
https://github.com/huggingface/accelerate/issues/366
> add use_distributed property

- docs/source/accelerator.mdx
- docs/source/internal.mdx
- examples/by_feature/gradient_accumulation.py
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/optimizer.py
- src/accelerate/scheduler.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_sync.py
- tests/test_grad_sync.py
- tests/test_kwargs_handlers.py
This PR adds:
- An `accelerator.accumulate` context manager that will allow for gradient accumulation automatically without the user having to change **any** code. Simply throw your code under it and call everything as normal. Accelerate will handle properly stepping the scheduler, optimizer, and zeroing.
- A new `_set_state` function to `AcceleratorState` to give the state knowledge of if gradients should be utilized and the optimizer/schedulers should be stepped. This is done internally and the user should never ever need to perform this. As a precautionary only state keys that need to be set in *this* PR have been added. A follow up will likely include the mixed precision.
- Lets `backward` handle the gradient accumulation division since it's tied to the `Accelerator` now
- …
> Introduce automatic gradient accumulation wrapper + fix a few test issues

- docs/source/internal.mdx
- src/accelerate/data_loader.py
1. A requirement was to get resulting batch size post `accelerator.prepare` call. Adding `total_batch_size` to provide the resulting batch_size across devices.
```python
my_dataloader = accelerator.prepare(my_dataloader)
accelerator.print(f"The resulting batch_size across devices is {my_dataloader.total_batch_size}")
```
> update dataloader wrappers to have `total_batch_size` attribute

- examples/by_feature/gradient_accumulation.py
- src/accelerate/optimizer.py
- src/accelerate/scheduler.py
Doesn't divide the number of steps in the scheduler since Accelerate handles it
> Fix scheduler in gradient accumulation example

- examples/requirements.txt
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/config/sagemaker.py
- src/accelerate/commands/launch.py
- src/accelerate/state.py
- src/accelerate/utils/constants.py
1. Fixes bugs in the current SageMaker support to get it working properly using the latest HF DLC
2. Adds `DATA_PARALLEL` support. Run `accelerate config` and answer the questions and choose `DATA_PARALLEL` for SageMaker Distribution Type. Sample config below with `XXXXX` values being AWS account specific.
```bash
base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
distributed_type: DATA_PARALLEL
ec2_instance_type: ml.p3.16xlarge
iam_role_name: XXXXX
mixed_precision: fp16
profile: XXXXX
py_version: py38
pytorch_version: 1.10.2
region: us-east-1
transformers_version: 4.17.0
use_cpu: false
```
After above config, just run the below command to run the official NLP example:
```bash
cd acceelerate/examples
accelerate launch complete_nlp_example.py
``` …
> SageMaker DP Support

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_sync.py
This PR implements gradient accumulation support for dispatched dataloaders and rewrites the tests for testing all combinations of dispatched dataloaders + split batches
> Make gradient accumulation work with dispatched dataloaders

- Makefile
- benchmarks/README.md
- benchmarks/big_model_inference.py
- benchmarks/measures_util.py
This PR adds a benchmark script to the repository showing the speed of the big model inference using Accelerate on several big models. The goal is to compare it to other libraries to show the strengths and weaknesses of each.
I have just run the benchmark on my machine for now. Sharing this script will make it easier to tests other kinds of setups!
> Add benchmarks

- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/constants.py
Fixes issue #498 
1. Fixes deepspeed multinode launcher support. It uses `hostfile` as specified in the Official DeepSpeed documentation [Resource Configuration (multi-node)](https://www.deepspeed.ai/getting-started/#resource-configuration-multi-node)
```
DeepSpeed configures multi-node compute resources with hostfiles that
are compatible with [OpenMPI](https://www.open-mpi.org/) and [Horovod](https://github.com/horovod/horovod). 
A hostfile is a list of hostnames (or SSH aliases), which are machines accessible via passwordless SSH,
and slot counts, which specify the number of GPUs available on the system
```
An example of a `hostfile` is given below:
```
localhost slots=2
brutasse slots=2
```
2. Example of the accelerate env after answering `accelerate config` questionnaire:
```
- …
```
> fixing deepspeed multi-node launcher

- docs/source/big_modeling.mdx
This PR is a first step to address some pain points @stas00 encountered with Accelerate when trying to design a more efficient `device_map`. This documentation will then be extended when we add support for more string values to `device_map` (like "balanced").
> Add more documentation for device maps computations

- src/accelerate/accelerator.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
- src/accelerate/state.py
This PR adds downcasting support for bf16 on TPUs. Per the XLA docs:
* By default both torch.float and torch.double are torch.float on TPUs.
* If `XLA_USE_BF16` is set, then `torch.float` and `torch.double` are both `bfloat16` on TPUs.
* If `XLA_DOWNCAST_BF16` is set, then `torch.float` is `bfloat16` on TPUs and `torch.double` is `float32` on TPUs.
> Add support for downcasting bf16 on TPUs

- docs/source/big_modeling.mdx
- src/accelerate/big_modeling.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
This PR adds an new option to `device_map` creation, to have something that balances the GPUs when several are available and their combined space is bigger than the model size. This then permits users to handle a batch size greater than 1.
Since there is no downside, this balanced way becomes the new "auto" behavior. The user can still get the old behavior with the "sequential" option and can also use "balanced" for the balanced way (in case auto becomes something different in the future). There is also "blanced_low_0" when we want to minimize the weights on GPU 0 if it's used for generation (cc @stas00 )
@younesbelkada This was something you requested so cc-ing you here.
TODO:
> Add balanced option for auto device map creation

- src/accelerate/accelerator.py
- src/accelerate/tracking.py
- tests/test_tracking.py
This PR lets kwargs be trickled down into each tracker's `__init__` and `log` method. Example:
```python
kwargs = {"wandb":{"name":"some_name", "tags":["tag_a","tag_b"]}}
accelerator.init_trackers("run_name", init_kwargs=kwargs)
```
> Allow for kwargs to be passed to trackers

- docs/source/quicktour.mdx
- examples/by_feature/checkpointing.py
- examples/by_feature/cross_validation.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/gradient_accumulation.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- examples/cv_example.py
- examples/nlp_example.py
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/state.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/scripts/test_metrics.py
- tests/test_metrics.py
This PR adds a new function to `Accelerator` called `gather_for_metrics`, which assists with calculating the right metric in distributed setups
Users of accelerate that want to ensure that their reported metrics are fully accurate
To assist with making sure all the batches have the right batch size, Accelerate will pad the length on the last batch to be duplicates of the last sample. These need to be dropped when calculating the final metrics on the last batch, and currently it looks something like:
```python
if accelerator.use_distributed:
if step == len(eval_dataloader) - 1:
predictions = predictions[: len(eval_dataloader.dataset) - samples_seen]
references = references[: len(eval_dataloader.dataset) - samples_seen]
else:
samples_seen += references.shape[0]
```
This PR adds a new …
> Add a gather_for_metrics capability

- .github/workflows/test.yml
- Makefile
- setup.py
- src/accelerate/test_utils/scripts/test_metrics.py
Adds a production stage to the CI so that barebones testing without any added dependencies can be checked on the git ci first to ensure that trickle-down breakages cannot occur. 
Specifically breaks down the `big_modeling` into its own ci matrix and adds a `core` to the matrix
Also removes unused evaluate test since it adds a dep to the main library. Not wondering if it'd be good for us soon to leave `test_script` in the main lib but migrate out all the other test scripts that might want or need external deps to a seperate folder at some point
> Add production testing + fix failing CI

- .github/workflows/on-merge.yml
- .github/workflows/test.yml
- docker/accelerate-cpu/Dockerfile
- docker/accelerate-gpu/Dockerfile
- setup.py
Super tiny nit, but keeps it inline with how transformers has their extras setup for tests. Mostly so I don't have to keep digging to see if I need to do `pip install -e .[tests]` `pip install -e .[testing]` `pip install -e .[test]` when bouncing back and forth between testing transformers and accelerate
> Rename test extras to testing

- src/accelerate/commands/launch.py
Creates good defaults for unconfigured `accelerate launch` usage so that the user doesn't have to think much on it. (and actually support not needing to do `accelerate config` again)
> Create good defaults in `accelerate launch`

- src/accelerate/accelerator.py
checkpointing not saving model weights if calling `accelerator.prepare_model` instead of `accelerator.prepare`
resolves issue: https://github.com/huggingface/accelerate/issues/555
> fix: saving model weights

- src/accelerate/commands/launch.py
Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>
> set default num_cpu_threads_per_process to improve oob performance

- .gitignore
- tests/test_examples.py
Actually fixes the multi-gpu examples, also added the `wandb` folder to the gitignore since it may be run when testing the tracking and create a `wandb` folder in the repo.
> Fix tests, add wandb to gitignore

- examples/by_feature/checkpointing.py
- examples/by_feature/cross_validation.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/gradient_accumulation.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- examples/cv_example.py
- examples/nlp_example.py
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_metrics.py
Solves https://github.com/huggingface/accelerate/issues/575 by completely changing how we check for the number of samples to drop. Instead uses modulo to learn how many extra samples there are initially, allowing us to simplify the logic.
> Fix gather_for_metrics

- examples/by_feature/checkpointing.py
- examples/by_feature/cross_validation.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/gradient_accumulation.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- examples/cv_example.py
- examples/nlp_example.py
- src/accelerate/accelerator.py
- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- tests/test_metrics.py
Raises an err since there's still a number of bugs we're discovering with this implementation.
Related discussions:
https://github.com/huggingface/accelerate/issues/575
https://github.com/huggingface/accelerate/pull/578
> Skip and raise NotImplementedError for gather_for_metrics for now

- examples/by_feature/checkpointing.py
- examples/by_feature/cross_validation.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/gradient_accumulation.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- examples/complete_nlp_example.py
- examples/nlp_example.py
Adds usage of `main_process_first` when calling `map()` in the examples
> Use main_process_first in examples

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
This PR adds a couple of fixes to the balanced device map API, as using it on small models has given me a couple of errors.
- First the GPU 0 should also have the buffer (contrarily to the initial implementation) because it always saves memory for the largest layer inside `infer_auto_device_map` (so if we don't give it the buffer, we end up with way less on the GPU 0).
- Then we need to give extra room on the last GPU to avoid accidental CPU offload if one or two parameters end up without device at the end. The easiest way is just to leave it with the max memory.
> Small fixes for balanced device maps

- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_sync.py
This PR fixes the dispatch dataloader which was a bit broken by the recent refactors. It's untested (since it requires a multiGPU setup) but will be in the new evaluation testing @muellerzr will add soon.
> Fix DispatchDataloader

- docs/source/usage_guides/tracking.mdx
- setup.py
- src/accelerate/accelerator.py
- src/accelerate/tracking.py
- tests/test_tracking.py
This PR introduces a method to the Accelerator that lets you grab a tracker's internal run if some custom code with it is wanted to be ran
Closes https://github.com/huggingface/accelerate/issues/592
There are needs when using `wandb` for example to access and toy with the `run`, such as stated in #592. Currently you need to index into the trackers, hope you find the right one, and then in the case of wandb call `run.run` which is a bit convoluted. 
Adds a new `Accelerator.get_tracker` method. To get a tracker you should pass in the corresponding string to the `.name` attribute
Trackers now have a new abstract property of `tracker` which should be used to return the internal tracking mechanism normal users would expect to interact with.
```python
accelerator = Accelerator(log_with="wandb") …
```
> Shorthand way to grab a tracker

- docs/source/concept_guides/training_tpu.mdx
- docs/source/quicktour.mdx
- docs/source/usage_guides/big_modeling.mdx
- docs/source/usage_guides/checkpoint.mdx
- docs/source/usage_guides/deepspeed.mdx
- docs/source/usage_guides/tracking.mdx
Ran a spell checker on the docs ahead of our next release, and fixed some third person -> second in the deepspeed tutorial
> Fix some typos + wordings

- src/accelerate/tracking.py
Fix the "AttributeError: 'Run' object has no attribute 'run'" error caused by the redundant `.run` in `WandBTracker`.
> Remove redundant `.run` in `WandBTracker`.

- src/accelerate/utils/modeling.py
This PR fixes a small "pre-bug" where in some very niche cases model buffers are saved in `int`, `uint` or `bool`. Therefore sometimes there is no need to cast their `dtype` to the desired `dtype` and we want to keep them in their native `dtype`.
I don't know if this is relevant but I ran `tests/test_big_modeling.py` slow tests to make sure this does not break anything on a multi-GPU setup (2x Tesla T4 16GB)
cc @sgugger @muellerzr
> Correct dtype casting

- tests/deepspeed/test_deepspeed.py
- tests/fsdp/test_fsdp.py
1. Disabling DeepSpeed and FSDP tests that are overwhelming the RAM of the CI instance running slow tests (Mostly CPU offload related tests). Now, `make test` passes end to end. Below is the report of the tests run on an instance with specifications matching the self hosted runners. 
[report_multi_gpu_tests.txt](https://github.com/huggingface/accelerate/files/9259282/report_multi_gpu_tests.txt)
> fixing deepspeed slow tests issue

- .github/workflows/nightly.yml
- Makefile
- tests/deepspeed/test_deepspeed.py
Fixes the DeepSpeed CI on the runner by just separating out the integration tests to be ran in a later python process, avoiding the lockup and issues.
Passed CI can be seen here on multi-gpu: https://github.com/huggingface/accelerate/actions/runs/2819545133
> Fix DeepSpeed CI

- examples/README.md
From here: https://github.com/huggingface/community-events/tree/main/huggan/pytorch
> Added GANs example to examples

- src/accelerate/commands/launch.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/constants.py
- src/accelerate/utils/launch.py
This PR removes the subprocess parts of the `multi_gpu` launcher code and replaces it with raw torchrun. This reduces the number of subprocesses had (2 to 1, just torchrun's), and lets us actually get a readable stack trace now that isn't overwhelmed with subprocess bits (so we can play with them now! 🥳 )
Users of Accelerate
Old stack traces were very hard to read and parse through, especially to play with since it's a double-nesting of subprocess. Now only one instance of subprocess is used, leaving us with the following new stack trace example:
```bash
(base) zach_mueller_huggingface_co@zach-multi-gpu:~/accelerate/examples$ accelerate launch nlp_example.py 
The following values were not passed to `accelerate launch` and had defaults used instead:
`--num_cpu_threads_per_process` was set …
```
> Fully remove `subprocess` from the multi-gpu launcher

- src/accelerate/commands/launch.py
- src/accelerate/state.py
1. setting env variable "PYTORCH_ENABLE_MPS_FALLBACK" = "1" when using `mps` 
2. Warning which strongly recommends users to use PyTorch nightly (1.13.dev...) as per the issue https://github.com/pytorch/pytorch/issues/82707
> M1 mps fixes

- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- src/accelerate/state.py
1. `with_tracking` was failing for complete example scripts with error `/ in name of the run` (logs/complete_... was being used as run). This fixes it.
2. A minor fix in printing accelerate state's mixed precision
> minor tracker fixes for complete* examples

- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
Sets `torchrun` to be the only way to run multi-node, and adds a `rdvz_endpoint` param during config setup.
> Use torchrun for multinode

- src/accelerate/accelerator.py
While on distributed setup the `accelerator.init_trackers()` method initializes multiple runs of the tracker on all processes. It should be initialized on the main process. Added a `@on_main_process` decorator to achieve the expected behavior.
@muellerzr @sgugger
> make `init_trackers` to launch on main process

- examples/by_feature/deepspeed_with_config_support.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
Made the changes as discussed in [this PR](https://github.com/huggingface/accelerate/pull/642#issuecomment-1220651885).
@muellerzr
> remove check for main process for trackers initialization

- src/accelerate/tracking.py
This PR saves the hyperparameters in a YAML file for Tensorboard tracker. By default, the HParams dashboard currently requires at least one hparam and at least one metric defined in the hparams configuration but since we have no metric, the hyperparameters will be stored in a YAML file . The changes have been implemented in `tracking.py`.
> Saving hyperparams in yaml file for Tensorboard for #521

- src/accelerate/tracking.py
Solves https://github.com/huggingface/accelerate/issues/650 by making the loggers use debug rather than info, to keep them quiet.
> Use debug for loggers

- src/accelerate/accelerator.py
- src/accelerate/logging.py
- src/accelerate/scheduler.py
- src/accelerate/state.py
This PR fixes a few nits in the docstrings (such as the Attributes issue discussed awhile ago in more places), as well as adds a few examples to places where users could get confused on the usage, or it is not extremely straightforward to use from the documentation. 
These specific cases are ones where numerous issues have been opened, asking how to use the specific item. 
This helps us document it in two places: the official documentation/tutorials for folks who need more information, and the docstring for folks who do not and just need the boilerplate.
> Improve docstrings and add examples where it makes sense

- src/accelerate/utils/imports.py
Mimics https://github.com/huggingface/transformers/pull/18777/ and caches the result of `is_tpu_available()`
> Cache torch_tpu check

- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
Solves a few lasting issues with the `torchrun` migration. Noteably:
- When doing multinode on the same network, it would just hang forever. 
- Defaults were not being set properly and overriden for `same_network`
- `node_rank` needs to be an `int`, not a string
> Fix multi-node issues from launch

- src/accelerate/tracking.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
Adds support for [Aim](https://github.com/aimhubio/aim)
cc @gorarakelyan to make sure it all seems alright with you! I thought about an easy `set_context` func but since our trackers all work off an abstract base class, seemed easier to just leave it as a kwarg. Let me know if there's something I seem to have missed! (Based this off my no-accelerate training script I wrote)
`Accelerator` will automatically only log on the main process and initialize the trackers on the main process, hence why there isn't any special "Are we on the main process" things in this PR.
> Add aim tracker for accelerate

- src/accelerate/accelerator.py
- src/accelerate/commands/launch.py
1. Addresses feature request of https://discuss.huggingface.co/t/when-using-deepspeed-why-do-i-need-to-pass-dataloaders-to-the-accelerator-prepare/22432/2
2. Addresses issue of https://discuss.huggingface.co/t/deepspeed-deepspeed-config-file-path-is-lowered-case/22464/2
3. As deepspeed handles loss scaling by gradient_accumulation_steps in its `backward`,  fixing the related  bug.
> deepspeed enhancements and fixes

- src/accelerate/commands/launch.py
1. Resolves #677 
Run below example script with additional torchrun elastic params as below:
```bash
accelerate launch --max_restarts=10 --rdzv_conf="timeout=10" examples/nlp_example.py 
```
> adding torchrun elastic params

- src/accelerate/data_loader.py
This PR fixes the dead loop reported in #678. The `skip` part is some old code that wasn't updated in the last refactor of this dataloader, so should be removed altogether as it will create infinite loops as is.
> Fix skip in dispatch dataloaders

- src/accelerate/utils/random.py
1. `synchronize_rng_state` now is cognizant of FSDP.
> rng state sync for FSDP

- docs/source/usage_guides/mps.mdx
- src/accelerate/launchers.py
1. Fixes #692 . 
Running [accelerate_examples/simple_nlp_example.ipynb](https://github.com/huggingface/notebooks/blob/main/examples/accelerate_examples/simple_nlp_example.ipynb) now runs on Mac Apple Silicon when available as shown below.
> Fixing support for Apple Silicon GPU in `notebook_launcher`

- src/accelerate/data_loader.py
1. Fixes #679. PR #687 introduced support for custom samplers that are batch_samplers (e.g., my_awesome_sampler=BatchSampler()) but it had the following issues
a. Default collating was failing, I had to tweak the collate_fn which isn't a good experience for the user.
b. Duplicate samples were being yielded and `gather_for_metrics` wasn't removing ending excess samples.
With the changes in this PR, I am running below `dataloader_checks.py` script with the following command. Results are as per expectations.
```bash
accelerate launch --multi_gpu --num_processes 2 --num_machines 1 dataloader_checks.py
```
dataloader_checks.py: Builds upon the nice MRE given by @etiennebeaulac
```python
import torch
from torch.utils.data import default_collate, Dataset, DataLoader, BatchSampler, RandomSampler, …
```
> fixing rng sync when using custom sampler and batch_sampler

- src/accelerate/big_modeling.py
`init_empty_weights` actually construct tensors in `cpu` and then moves them to `meta`. Instead we propose to construct tensors in `meta` device directly by overriding default constructors. This is inspired from https://github.com/microsoft/DeepSpeed/blob/c199edac8210e730acfd004c6e2bc3a98c0db903/deepspeed/utils/init_on_device.py This results in a faster loading mechanism with using the `init_empty_weights` context manager.
Additionally we override loading mechanism to return empty dictionary as there's no reason to read the checkpoint since everything is in `meta` (This is a hack as `map_location="meta"` doesn't work yet). Not sure if that's considered too hacky to be integrated inside `accelerate`
Running the following gets accelerated:
```python
from timeit import timeit
from accelerate …
```
> Improve `init_empty_weights` to override tensor constructor

- src/accelerate/accelerator.py
1. Override DeepSpeed `grad_acc_steps` from `accelerator` obj when they aren't same.
> override DeepSpeed `grad_acc_steps` from `accelerator` obj

- tests/test_tracking.py
Small readability refactor in `tests/test_tracking.py`
`key_occurance` -> `key_occurrence`
grep'd the rest of the project to ensure no other references exist...
> refactor(tests): `key_occurrence` fixup

- src/accelerate/hooks.py
Cleanups in `src/accelerate/hooks.py`
- `deached` -> `detached`
- `defauts` -> `defaults`
Confirmed with grep that these issues are exclusive to `hooks.py`
> docs: `hooks` readability improvements

- docs/source/usage_guides/sagemaker.mdx
- examples/README.md
- src/accelerate/commands/config/sagemaker.py
1. Adding AWS Sagemaker examples to accelerate/examples README.md file.
2. Help users correctly leverage it going forward as it is at times not clear.  (issue #706 ).
> sagemaker fixes and improvements

- src/accelerate/accelerator.py
- src/accelerate/big_modeling.py
- src/accelerate/tracking.py
- src/accelerate/utils/modeling.py
One-off readability fix-ups in `src/accelerate/*.py`
Grew to a few one-off's when grep'ing to check for more occurrences... 
Seemed reasonable to put these together in a PR. 
Fixes:
- `devicement_placement` -> `device_placement`
- `intialize` -> `initialize`
- `pyton` -> `python`
- `avoig` -> `avoid`
> refactor(accelerate): readability improvements

- src/accelerate/accelerator.py
Adds some more type hints and docs to functions I've noticed the one-off user has used before so it's documented (but also documents the best practice). 
Also felt like having the type annotations on `unwrap_model` eases a bit more into what exactly it *can* unwrap, let me know if we should use the fully qualified types (I imagine so) and how that would be annotated to fit in the 150ish char limit we have (e.g. newline for each type?)
> More docstring nits

- src/accelerate/accelerator.py
This PR lets the user customize whether device_placement should be `True` or `False` for the different objects passed along to prepare. This feature was requested in #624
Fixes #624
> Allow custom device placements for different objects

- src/accelerate/accelerator.py
Adjusts the docstring to specify that only models whose gradients will be utilized should be passed through accelerator.prepare
> Specify gradients in model preparation

- src/accelerate/data_loader.py
There was a lasting `_iterate_samples_seen` that was unnoticed until https://github.com/huggingface/accelerate/issues/723
> Fix regression issue on iterate_samples_seen

- src/accelerate/commands/launch.py
As pointed out in #717, the current default for `num_processes` erases the value set by the config, which we don't want. This PR fixes that.
> Fix default for num processes

- .github/workflows/build-docker-images-release.yml
- .github/workflows/build-docker-images.yml
Introduces a workflow that releases a docker image based on when a Github release has been made. It will pull the version id from the setup.py and that state
Relevant gh docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
Tested this on a separate branch using the current dev version. 
CPU tag can be seen here: https://hub.docker.com/r/huggingface/accelerate-cpu/tags
GPU tag can be seen here: https://hub.docker.com/r/huggingface/accelerate-gpu/tags
FFT, should we just merge these two release workflows together and check if 'dev' is in the version to automatically tag the `latest` tag? Or maybe just publish the prerelease tags? WDYT?
> Build and Release docker images on a release

- src/accelerate/scheduler.py
- tests/test_scheduler.py
Turns out the logic for one-cycle on the scheduler was backwards so `step` was never called.
Fixes https://github.com/huggingface/accelerate/issues/690 and adds some tests
> Fix issue with one-cycle logic

- .github/ISSUE_TEMPLATE/bug-report.yml
Same as in Transformers, it irks em to see the bug label auto-added whenever a user files an issue, since lots of them are just questions or issues within the user's code and not a bug in the library.
> Remove auto-bug label in issue template

- docs/source/_toctree.yml
- docs/source/usage_guides/training_zoo.mdx
Adds a non-exhaustive example zoo to the docs, which also includes a few examples from popular integrations
> Add an example zoo to the documentation

- docs/source/usage_guides/memory.mdx
- examples/by_feature/memory.py
Fixes a memory leak in the memory example. The `accelerator` should be the only one defined out of the loop, and `accelerator.free_memory()` should be the first thing called in the loop. This way all memory is actually freed and lingering references can be wiped.
> Fix memory leak

- docs/source/usage_guides/training_zoo.mdx
- examples/by_feature/automatic_gradient_accumulation.py
- tests/test_examples.py
Showcases how to perform automatic gradient accumulation, similar to a popular feature that was toted by MosaicML awhile back.
The initial batch size starts at 256 to guarantee a CUDA OOM and the user can observe the print statement showing the new number of steps and batch size
> Auto grad accum example

- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
I'm not sure why `PYTHONPATH` is set to python executable here as it expects dirs and not files:
https://github.com/huggingface/accelerate/pull/514/files#r987305929
but regardless accelerate shouldn't hijack `PYTHONPATH` 
This PR extends the `PYTHONPATH` instead if it was preset.
Thank you
> [ds launcher] un-hijack PYTHONPATH

- src/accelerate/utils/modeling.py
This is needed to allow to use the "device_map" for models that have `nn.Parameter` at the top level, such as the safety checker of `diffusers`: https://github.com/huggingface/diffusers/pull/772/files#r990269773
> [Device map] nn.Parameter don't have children

- docs/source/index.mdx
This PR replaces the absolute paths in the landing page tiles with relative ones so that one can test navigation both locally in and in future PRs (see [here](https://moon-ci-docs.huggingface.co/docs/accelerate/pr_747/en/index) for an example PR where the links don't work).
I encountered this while working on the `optimum` docs and figured I'd fix it elsewhere too :)
Internal Slack thread: https://huggingface.slack.com/archives/C02GLJ5S0E9/p1665129710176619
> Use HTML relative paths for tiles

- src/accelerate/commands/launch.py
Modifies the default cpu_threads_per_process to be 1, and then if training on CPU then we adjust the number of threads based on an optimization to use them all. 
The need for this fix is there was not much of a want to have a high utilization on the CPU when training on GPUs, and when there was a performance gain wasn't really found. As a result we're limiting the tuning in this way to CPU-bound only training.
> Change num_cpu_threads_per_process default

- src/accelerate/utils/imports.py
We just noticed the new Megatron support in Accelerate (https://github.com/huggingface/accelerate/pull/667). This is great! :slightly_smiling_face:
Unfortunately, I think this PR has broken our transformers and accelerate unit tests in DeepSpeed. Several of our unit tests depend on megatron==1.1.5 which is the version of [Megatron-DeepSpeed](https://github.com/microsoft/megatron-deepspeed). It appears this feature in accelerate requires megatron 2.2.0+ and we are seeing errors in our CI when megatron 1.1.5 is installed. This PR aims at addressing this issue.
https://github.com/microsoft/DeepSpeed/actions/runs/3244132853/jobs/5319868166#step:6:958
/cc @pacman100, @sgugger
> ensure megatron is 2.2.0+

- src/accelerate/accelerator.py
Like the title says. Fixes #760. 
There is [just such a check](https://github.com/pytorch/pytorch/blob/13cff2ee8ea1d7aea2ad201cbd77ebe2b9a29d25/torch/nn/parallel/distributed.py#L550-L555) in DistributedDataParallel, which I do the opposite of.
I would like to add a test so that this feature doesn't regress, but it's not clear to me how to add a test.
I could add a module with only buffers and add it to the `prepare()` call on line 78, then check that the device is the accelerator's device.
https://github.com/huggingface/accelerate/blob/693d46826e32507376d44f99967df4710886c984/tests/test_kwargs_handlers.py#L73-L79
> Only wrap modules in DDP if they require grad

- docs/source/usage_guides/megatron_lm.mdx
- examples/by_feature/megatron_lm_gpt_pretraining.py
1. Maintaining 🤗 fork of Megatron-LM: https://github.com/huggingface/Megatron-LM. Updating docs to directly install from it instead of the current long process. 
2. wandb was resulting in the below error when doing `accelerator.end_training()` with Megatron-LM. On commenting those 2 lines, everything works properly.  For Megatron-LM, the main process is the last rank as that will have loss from the last pipeline stage, this might be behaving weirdly with closing the wandb connection using `run.finish`. Commenting it for now.
```
envs/ml/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 187, in get_stream
stream = self._streams[stream_id]
KeyError: '26ll3a5t'
```
3. Minor megatron-lm docs fixes to make output logs in sync with the config and args
> updating docs to use fork of megatron-lm and minor example/docs fix

- src/accelerate/big_modeling.py
- src/accelerate/hooks.py
- tests/test_hooks.py
Solves https://github.com/huggingface/accelerate/issues/767.
Moves the AlignDevicesHook with `io_same_device` from `accelerate.cpu_offload` and `accelerate.disk_offload` to before the `attach_align_device_hook`.
That way we can keep the changes on forward method for the whole module without deleting the hook we want to keep: the one with execution device and configurations on how to move the tensors between devices.
> Move io_same_device hook to before attach_align_device hook on cpu_offload and disk_offload.

- .github/workflows/run_merge_tests.yml
- .github/workflows/test.yml
- Makefile
- src/accelerate/commands/launch.py
- src/accelerate/test_utils/scripts/test_cli.py
- tests/test_cli.py
- tests/test_configs/0_11_0.yaml
- tests/test_configs/0_12_0.yaml
- tests/test_configs/README.md
- tests/test_configs/latest.yaml
This PR introduces a subset of tests for checking `accelerate launch` and in turn `accelerate config`, and solves a bug I found during testing
Users have pointed out that we're not quite doing a good enough job with backwards compatibility checks on config yamls. To ensure these can be caught new tests are added to run a simple script using `accelerate launch` with no configuration file or specific configuration files
Nothing
`tests/test_configs` should contain (at *least*) the last 2 major versions of Accelerate plus the latest version, which are direct outputs from `accelerate config`. Since these tests take so fast to execute, I think it's fine if this just contains the last 5 or 6 configs until we are comfortable. 
As part of PR review, maintainers should be aware of any changes to …
> Regression cli tests

- tests/test_tracking.py
Completely redo's the wandb tests to run a single experiment that then checks that init and the logs worked fine. Uses a new processing system the wandb team shared with me that is **infinitely** more reliable and we can successfully parse from repeatedly without trouble
> Fix flakey wandb test

- src/accelerate/data_loader.py
- tests/test_data_loader.py
This is the first PR to deal with #684 and begins the work of allowing the data loaders not to loop back at the beginning when there is non-even number of samples compared to the number of processes.
It introduces a new argument (that will eventually trickle down all the way up to the Accelerator main class) `even_batches` that can be set to `False`, in which case each process will see a different number of batches.
In this PR, we focus on the `BatchSamplerShard`.
> Allow BatchSamplerShard to not even out batches

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
Will add accelerate tests for that asap. 
For the mean time, 
The last device is not left with `max_memory`. This cause the `test_model_parallelism` to fail in transformers.
> fix transformers tests

- src/accelerate/data_loader.py
1. Fixes #786 
Example script for testing the updated code:
```python 
import torch
from torch.utils.data import default_collate,default_convert, Dataset, DataLoader, BatchSampler, RandomSampler, SequentialSampler
import numpy
from accelerate import Accelerator
from accelerate.utils import set_seed
from accelerate.utils.random import synchronize_rng_state
from accelerate.utils.dataclasses import DistributedType, RNGType
import os
import sys
import platform
class MyDataset(Dataset):
def __len__(self):
return 22
def __getitem__(self, index):
squeeze = False
if isinstance(index, int):
index = [index]
squeeze = True
elif isinstance(index, slice):
index = list(range(*index.indices(self.size)))
else:
index = list(index)
batch = [{"index": i, "label": i % 2, …
```
> separate dataloader generator from sampler generator

- src/accelerate/utils/modeling.py
This PR adds `list(model._buffers)` inside `modules_to_treat` when computing the `auto_device_map`. This scenario occured when I tried to add `accelerate` support for `BART`-like models when the [`final_logits_bias` is registered as a buffer and is different than a `uint` type](https://github.com/huggingface/transformers/blob/76296569266fbc238defbe68d06ad720b3a544e3/src/transformers/models/bart/modeling_bart.py#L1286). It seems that we need to assign a device to this buffer. 
The other solution is to "force-ignore" the buffer in `check_device_map` [here](https://github.com/huggingface/accelerate/blob/a5525406fcba79523fc5edf1051360e15447ef6a/src/accelerate/utils/modeling.py#L577) since the tensors that are in `model._buffers` are stored in the state_dict. 
cc @sgugger @muellerzr 
slow …
> Consider top-level buffers when computing `infer_auto_device_map` 

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_distributed_data_loop.py
- tests/test_multigpu.py
This PR enables the option of configuring the Accelerator to disable prepared DataLoaders ensuring that an even number of batches are observed across all processes. 
This continues the work described in: https://github.com/huggingface/accelerate/issues/684
> Add `even_batches` keyword to Accelerator

- src/accelerate/utils/offload.py
- tests/test_offload.py
When we end up with weights offloaded on CPU and disk, there is a little bug in the function that extracts the CPU state dict. In the added tests, it would catch the submodules beginning like the one passed (so `a.10` because `a.1` is in the list).
> Fix extraction of state dict in offload

- src/accelerate/commands/accelerate_cli.py
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/env.py
- src/accelerate/commands/pod.py
- tests/test_cli.py
- tests/test_configs/latest.yaml
- tests/test_samples/test_command_file.sh
This PR introduces a new command `accelerate pod-config` which will first ask the user for commands they wish to run across all TPU nodes in a GCP TPU cluster, before then running all of them in along with installing `accelerate` if specified
Part of https://github.com/huggingface/accelerate/issues/501
When dealing with TPU pods, they need to have initial configurations across all of their processes with all the main data being available there and initial setups. This provides an easy tool to do so without having the user need to enter their own startup script, and can be run at any point in time.
Adds a new `accelerate pod-config` command which can accept both a bash script of commands to run at once, or an unlimited amount of regular commands passed in
Configs now store both types of …
> Introduce a pod-config command

- src/accelerate/commands/launch.py
This PR refactors the `launch` CLI to make their arguments infinitely more readable and organizes it in such a way that users can quickly get arguments to their specific needs without having to comb through a million options. We do this two different ways
Argparse allows for [ArgumentGrouping](https://docs.python.org/3/library/argparse.html#argument-groups) which we should utilize much more. This allows for much cleaner renderings with `--help` for the user. 
E.g. Before:
```bash
positional arguments:
training_script       The full path to the script to be launched in parallel, followed by all the arguments for the training script.
training_script_args  Arguments of the training script.
optional arguments:
-h, --help            show this help message and exit
--config_file CONFIG_FILE
The …
```
> Refactor CLI to improve readability

- src/accelerate/hooks.py
This PR adds `recurse` argument in `remove_hook_from_module` to be able to remove the hooks of a module recursively. Useful in the context of https://github.com/huggingface/optimum/pull/423 
cc @sgugger 
Thanks!
> add `recurse` argument in `remove_hook_from_module`

- docs/source/package_reference/cli.mdx
- src/accelerate/commands/launch.py
We have the following naming convention for device vs training schema:
Device: 
- Use device name, such as `--tpu`, `--multi_gpu`, `--cpu`
Training Schema
- Use schema name with "use" in the front, such as `--use_megatron_lm` and `--use_deepspeed`
Since MPS is a torch device rather than a schema, this PR changes the flag to be `--mps` and adds in a future warning for `--use_mps` so we can be consistent 🤗 
Also updates the CLI docs to reflect the latest refactorization.
> Update CLI docs and use mps rather than mps_device

- setup.py
Should solve failing tests, needs to be `scikit-learn` not `sklearn`
> Rename sklearn to proper dep, solve failing tests

- docs/source/usage_guides/megatron_lm.mdx
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/megatron_lm.py
1. Enable returning logits for Megatron-LM GPT models
2. Enable specify custom Megatron-LM based model 
3. Enable specify any Megatron-LM arguments to support things such as ALiBi/ROPE positional embeddings, Multi-Query Attention, tokenizer files etc.
4. Enable `megatron_generate` method for Megatron-LM GPT model, this will use Tensor and Pipeline Parallelism to complete generations for a batch of `inputs` when using greedy with/without top_k/top_p sampling  and for individual prompt `inputs` when using beam search decoding. Only a subset of features of transformers `generate` is supported. This will help in using large models via tensor and pipeline parallelism  for generation (already does key-value caching and uses fused kernels by default). 
5. fixes #809
Below is the run of the …
> adding support to return logits and generate for Megatron-LM GPT models

- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
Should fix https://github.com/huggingface/accelerate/issues/817
> Isolate distrib_run

- examples/by_feature/deepspeed_with_config_support.py
I believe this example should be using gather_for_metrics here instead of gather to work correctly on distributed setups.
> Deepspeed example should use gather_for_metrics

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/test_distributed_data_loop.py
- src/accelerate/test_utils/scripts/test_script.py
- tests/test_accelerator.py
This PR adds a context manager which acts as a simple wrapper around [Join](https://pytorch.org/docs/stable/distributed.algorithms.join.html) to enable training with uneven inputs when using DDP.
This continues the work described in: https://github.com/huggingface/accelerate/issues/684
> Add `join_uneven_inputs` context manager to Accelerator

- docs/source/package_reference/logging.mdx
- src/accelerate/accelerator.py
- src/accelerate/logging.py
- src/accelerate/tracking.py
Fixes https://github.com/huggingface/accelerate/issues/835
Fixes https://github.com/huggingface/accelerate/issues/834
The first comes from the fact that there is a `logger.debug` that could get called in `filter_trackers` before `AccelerateState()` was created, leading to the error mentioned. This PR moves it down in `__init__` to where it should be to allow for this to work. 
The second was solved by introducing a convenience `log_level` parameter to `accelerator.logging.get_logger()`
> Fix log error and add log level to get_logger

- src/accelerate/scheduler.py
Fixes https://github.com/huggingface/accelerate/issues/843
The issue arises when using `OneCyclePolicy` and the `scheduler.step_count` > `scheduler.total_steps`. Current behavior is it will just move to the `else` statement and call `step()` regardless, which is not what we want. Instead this adds it in as a second if statement with no else.
> Fix if/else in AcceleratedScheduler

- docs/source/package_reference/cli.mdx
- setup.py
- src/accelerate/commands/accelerate_cli.py
- src/accelerate/commands/config/__init__.py
- src/accelerate/commands/config/config.py
- src/accelerate/commands/config/config_utils.py
- src/accelerate/commands/config/default.py
- src/accelerate/utils/other.py
As I'm focusing more on the CLI, eventually we wanted these three commands:
- `accelerate config`
- `accelerate default-config`
- `accelerate update-config` (from https://github.com/huggingface/accelerate/issues/832)
It did not quite make sense to have the CLI in this way, the actions should read start -> end. 
After doing a ton of digging I figured out that there's a neat way to add extra subparsers to existing subparsers by adding them as Argparsers directly. What does this mean? We can now do:
```bash
accelerate config -h
accelerate config default -h
```
And soon:
```bash
accelerate config update -h
```
This operates by having a single empty parent parser to start. This one has `add_help=False` and doesn't do much explicitly there.
`parent_parser = …
> Refactor Accelerate config and introduce a multi-argument CLI interface

- docs/source/package_reference/cli.mdx
- src/accelerate/commands/config/__init__.py
- src/accelerate/commands/config/config.py
- src/accelerate/commands/config/config_utils.py
- src/accelerate/commands/config/default.py
- src/accelerate/commands/config/update.py
Solves https://github.com/huggingface/accelerate/issues/832
Last of the CLI updates for now. This one refactors the current way that the CLI funcs are called to mimic `accelerate launch`. 
I also discovered with subcommands we just need to do `parser.add_parser`, we don't need to `add_subparsers` nor need as complex of a `SubcommandHelpFormatter`.
Now the help will just automatically show the subcommands in a list with their help:
```bash
usage: accelerate <command> [<args>] config [-h] [--config_file CONFIG_FILE] {default,update} ...
Launches a series of prompts to create and save a `default_config.yaml` configuration file for your training system. Should always be
ran first on your machine
optional arguments:
-h, --help            show this help message and exit
--config_file …
```
> Clean up, add update command

- src/accelerate/logging.py
Was noticing a bit more logs than expected post the log change, this is because by default the logging library uses WARN, not INFO (as stated down here: https://docs.python.org/3/howto/logging.html#when-to-use-logging)
> Switch default log to warn

- src/accelerate/accelerator.py
- src/accelerate/utils/other.py
Closes https://github.com/huggingface/accelerate/issues/858
Adds a new `remove_fp32_hook` param to `extract_model_from_parallel` and `unwrap_model` that will check to see if the forward pass is an instance of `ConvertOutputsToFp32` and if so then sets the forward pass back to the original forward pass
> Remove mixed precision hook as part of the unwrap_model

- src/accelerate/logging.py
Still not quite pleased with this implementation, learning more about the logging library + good practices. For example the transformers tests the output of `accelerator.state()` won't actually be logged unless the env var is set currently. 
So this PR makes us take a different approach of only filter *if we explicitly choose to filter* otherwise do nothing. This also limits it to the logger for the module, before it was setting the global log level which was leading to bloated traces
> Even more log level refined, leave alone if not explicitly set

- src/accelerate/accelerator.py
- src/accelerate/utils/operations.py
- src/accelerate/utils/other.py
- tests/test_utils.py
Fixes https://github.com/huggingface/accelerate/issues/866
In order to fully unwrap the amount of chaining done in https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L928-L936 and support pickling we have to explore each and every single `__wrapped__` that exists inside `model.forward` until we get back to the original forward implementation and present that. 
To know just when we've hit the original version, the model should store the original function somewhere so a `==` check works and we don't just remove all of the decorators in existence (say if someone wrapped `torch.no_grad` on the forward func)
This then lets you perform:
```python
torch.save(accelerator.unwrap_model(model))
```
Also changes the `test_pickle` because technically that test always …
> Solve pickling issues

- src/accelerate/accelerator.py
1. In torch 1.14.0.dev, LR Scheduler never gets prepared. PyTorch PR that will be impacting the LR schedulers: [#61232](https://github.com/pytorch/pytorch/commit/0a69c50a46d50ae265e2d1d826d0b4b69d4351fd) (2 weeks ago change)
2. This PR fixes the above issue
> fixing lr_scheduler prepare issue when using pytorch nightly

- src/accelerate/accelerator.py
- src/accelerate/commands/launch.py
This PR, replaces `logging.warn()` with `logging.warning()` as the former has been deprecated since Python 3.3.
> Update deprecated `logging.warn()`

- src/accelerate/big_modeling.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/offload.py
This PR reworks a bit the internals of the offload hooks to allow for the case where the checkpoint is saved with `safetensors`. In this case, there is no need to have a separate save of the weight as a Numpy memory-mapped array, as we can directly access the weight using `safe_open`.
Goes along with https://github.com/huggingface/transformers/pull/20321
> Allow safetensors offload

- src/accelerate/accelerator.py
- src/accelerate/commands/launch.py
- src/accelerate/launchers.py
- src/accelerate/state.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/launch.py
Closes https://github.com/huggingface/accelerate/issues/888 and follows the current pattern for `LOG_LEVEL` by prefixing all env variables Accelerate uses with `ACCELERATOR`
> Prefix all accelerate env vars with ACCELERATE

- src/accelerate/commands/menu/keymap.py
- src/accelerate/commands/menu/selection_menu.py
Closes https://github.com/huggingface/accelerate/issues/867
Mild fix for right now, need to eventually see why windows just prints the history of arrow keys such as:
```bash
Do you wish to use FP16 or BF16 (mixed precision)?
Please select a choice using the arrow or number keys, and selecting with enter
* no
fp16
bf16
[3A                                                                                                                    [1A                                                                                                                    [1A                                                                                                                    [1A …
```
> Fix windows cli selector

- src/accelerate/accelerator.py
Ties into https://github.com/huggingface/accelerate/issues/870, writes a more descriptive assert flag that states it must inherit `KwargHandler`
> Better description for improper kwargs

- src/accelerate/utils/modeling.py
Currently loading offloaded weights via `load_offloaded_weights` (as is done in Transformers in `from_pretrained` with `offload_state_dict=True`) does not work in bfloat16 because Numpy does not support that floating type.
This PR addresses that by reusing the function `load_offloaded_weight` which has the logic.
> Support bfloat16 in load_offloaded_weight

- docs/source/package_reference/utilities.mdx
- src/accelerate/utils/__init__.py
- src/accelerate/utils/torch_xla.py
The PR adds a function ```install_xla``` to install the correct version of XLA wheels based on the version of torch installed on the system. The function also takes in a boolean argument ```upgrade``` which allow the user to install the latest available version of torch and XLA.
Closes #586
> Adds a utility function to install correct version of torch XLA

- src/accelerate/commands/launch.py
Closes https://github.com/huggingface/accelerate/issues/903 by adding more sanity checks to `launch_command` including more compute type options with the latest ones and checking if we are doing `multi_gpu` num processes > 2
> Expand sanity checks

- src/accelerate/commands/launch.py
Changes the conditional in the sanity checks as `args.num_processes` could be `None` if using a config file. (Currently failing the multi-GPU tests on main)
> Fix conditional

- src/accelerate/accelerator.py
- src/accelerate/commands/launch.py
and num_cpu_threads_per_process is not reset for better performance in cpu only case
Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>
> fix issue that amp bf16 does not work for cpu in env with cuda.

- src/accelerate/accelerator.py
*failure occurs when testing FP16
*autocast fail to work for cpu bf16 in some gpu+cpu platform, no need to use is_bf16_available logic. because native_amp already contains such logic.
> fix accelerate test failure with cpu config

- docs/source/package_reference/utilities.mdx
- docs/source/quicktour.mdx
- docs/source/usage_guides/checkpoint.mdx
- docs/source/usage_guides/tracking.mdx
- src/accelerate/accelerator.py
- src/accelerate/tracking.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- tests/test_state_checkpointing.py
- tests/test_tracking.py
- Makes `logging_dir` optional and centralizes anything written to be saved to a `project_dir`
- Allows for a set limit to the number of saved checkpoints
- Introduces a `checkpoints` folder when saving with `Accelerator.save_state`
Closes https://github.com/huggingface/accelerate/issues/914
As more needs to customize directories with Accelerate arises, rather than having 2+ different folders a user can save things into it would be better to have a centralized "Project Directory" to work out of instead where the users checkpoints will always save to and loggers that require a directory will point to. 
- A `SaveConfiguration` dataclass has been made which will store customizations when saving states through `Accelerator.save_state`
- `save_state` will no longer require a `save_path`, …
> Introduce `project_dir` and limit the number of saved checkpoints

- docs/source/_toctree.yml
- docs/source/usage_guides/big_modeling.mdx
Users are very *very* confused as to why they can't combine Big Model Inference capability with the training capability of the library, and don't understand that they're two completely different sublibraries and that the current functionality to combine both does not exist (but actively being looked at). This PR adjusts the titles slightly so that it can be a bit more transparent, but also open to other ideas.
> Specify inference on Big Modeling

- src/accelerate/commands/launch.py
- src/accelerate/utils/dataclasses.py
> ds-z3-init and prepending ds env variables with `ACCELERATE_`

- src/accelerate/utils/modeling.py
This PR fixes a standing bug where we have a different behavior than PyTorch. In torch, loading a `state_dict` inside a model will never change the model's dtype:
```py
import torch
model = torch.nn.Linear(5, 6)
model_in_half = model.half()
state_dict_in_half = model.state_dict()
model = torch.nn.Linear(5, 6).to("meta")
model.load_state_dict(state_dict_in_half)
model.weight.dtype
```
Currently in Accelerate, `load_checkpoint` does the opposite and when loading a model, it converts it to the dtype of the state dict. This PR addresses that.
This PR only contains the fix for now, we have to discuss how to maybe maintain backward compatibility (even if this is a bug fix), because `diffusers` might be relying on this behavior, cc @patrickvonplaten
> Honor model dtype in `load_checkpoint`

- src/accelerate/utils/dataclasses.py
1. Adds DeepSpeed ZeRO-3 init context manager
1. context manager to enabled/disable `zero.Init`
2. util function to check if `zero.Init` is enabled
Sample accelerate config `ds_zero3.yaml` :
```yaml
command_file: null
commands: null
deepspeed_config:
gradient_accumulation_steps: 1
gradient_clipping: 1.0
offload_optimizer_device: 'cpu'
offload_param_device: 'cpu'
zero3_init_flag: true
zero3_save_16bit_model: true
zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
main_process_ip: null
main_process_port: null
megatron_lm_config: {}
mixed_precision: 'no'
num_processes: 2
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: …
```
> ds zero-3 init context manager

- src/accelerate/data_loader.py
There are a lot of cases, so I may be missing something, but I believe this is a bug.
I am setting batch_size=16 with num_processes=2 and using an IterableDataset.
My collator is receiving batches of size 8, and the dataloader is yielding batches of size 4 on each process.
The DataLoaderDispatcher has batch size 8 due to this line, which further gets split later on to 4.
This PR works in my case, but I am not sure it does not break another.
> fix batch size in prepare_dataloader for iterable datasets

- src/accelerate/tracking.py
Reported on Slack, basically some spaces have the following setup:
```
torch==1.12.1+cu113
torchvision==0.13.1+cu113
git+https://github.com/TheLastBen/diffusers
accelerate==0.12.0
OmegaConf
wget
pytorch_lightning
huggingface_hub
ftfy
transformers
pyfiglet
triton==2.0.0.dev20220701
bitsandbytes
python-slugify
requests 
```
As part of `pytorch_lighting` `tensorboardX` gets installed but `accelerate` doesn't properly import the `tensorboardX` import so this PR addresses it.
> Fix tensorboardX not being imported

- src/accelerate/utils/offload.py
This was reported in #938 and is a very small and easy fix: some checkpoints may have weights on the GPU and if the user does not pass along `map_location="cpu"` (which also our `load_checkpoint` function does not) we end with an error at this line.
> Fix offload when weights are on the GPU

- docs/source/quicktour.mdx
- docs/source/usage_guides/deepspeed.mdx
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/deepspeed.py
- tests/deepspeed/test_deepspeed.py
1. Fixes: #936 
Example:
1. accelerate config manually tweaked to have both `deepspeed_config_file` and other ds config entries that are available in the json config file:
```yaml
command_file: null
commands: null
deepspeed_config:
gradient_accumulation_steps: 1
gradient_clipping: 1.0
offload_optimizer_device: 'cpu'
offload_param_device: 'cpu'
zero3_init_flag: true
zero3_save_16bit_model: true
zero_stage: 3
deepspeed_config_file: 'ds_config.json'
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
main_process_ip: null
main_process_port: null
megatron_lm_config: {}
mixed_precision: 'bf16'
num_processes: 2
rdzv_backend: static
same_network: true …
```
> raise error for duplicate accelerate config  values when using `deepspeed_config_file`

- src/accelerate/state.py
This PR introduces a static `is_initialized` method which will check  if the state's dictionary is empty or not. It also refactors current methods to have `initialized` be a `@property` check of the same to increase code clarity towards what is happening under the hood.
Closes https://github.com/huggingface/accelerate/issues/933
The feature request asked for a similar API to what `torch` uses for `cuda`, i.e. `torch.cuda.is_initialized()` for `Accelerate`, so a user can do `import accelerate; accelerate.state.is_initialized()`
A new `is_initialized` method was added to the `accelerate.state` module
`initialized` was changed to be a dictionary check to mimic how the new `is_initialized()` function operates
```python
accelerate.state.is_initialized()
from accelerate import …
```
> Add is_initialized method and refactor

- tests/deepspeed/test_deepspeed.py
The `DeepSpeed` tests manually set `AcceleratorState.initialized` when trying to test the mixed precision types when it should use `_reset_state()`, leading to a failure on the recent API change introduced in #949.
IIUC this should be the proper fix, let me know if there was a specific reason for this particular setup @pacman100 when testing and I can modify this fix differently.
Proof tests pass can be seen here: https://github.com/huggingface/accelerate/actions/runs/3830884007
> Fix DeepSpeed tests

- src/accelerate/big_modeling.py
- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
This PR fixes an issue uncovered with the bug reported in #938. When loading a checkpoint with Accelerate big model inference, each weight is put on the device set in the `device_map`. In particular, all weights in the `state_dict` that should be offloaded to the disk according to the `device_map` are set on the meta device by `load_checkpoint_in_model`.
On the other hand, the hooks set by `dispatch_model` will by default no offload buffers on the disk (since they are usually small) and during their `init`, they move them to the execution `device`.
So the weights in the state dict that are buffers and inside modules offloaded to the disk end up on the meta device and are then moved to the execution device (which is GPU 0 usually). This crashes with the error reported in #938.
The fix is …
> Don't automatically offload buffers when loading checkpoints

- src/accelerate/utils/modeling.py
Simple string change (typo fix) I happened to notice and figured I should just fix while I'm looking at it.
> Typo fix in src/accelerate/utils/modeling.py

- src/accelerate/utils/deepspeed.py
DeepSpeed now allows deespeed configuration passed in as a base64 encoded string. This PR updates the check in accelerate to accommodate that change.
> Allowing encoded configuration for DeepSpeed

- README.md
In README.md file, explain "from accelerator import Accelerator, DeepSpeedPlugin"
But, Our package name is accelerate ( no accelerator )
When I use previous guidance, statement for this is failed.
> When use accelerator with deepspeed, We must import from accelerate package.

- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
Closes https://github.com/huggingface/accelerate/issues/847
TL;DR there was a neat bug in torch 1.9.0 where `torchrun` wouldn't always *actually run*. This PR changes the flag for checking to be 1.9.1, which I found *did* work after successfully recreating the 1.9.0 issue. 
It also modifies the `if/else` flag as it was always going to raise if the value was `<` 1.9.0 but gives it a much more clear answer as to what is truly happening here.
> Raise minimum version for distrib launch

- src/accelerate/utils/modeling.py
This PR fixes the test to determine tied parameters in `infer_auto_device_map`. The problem was discovered while investigating #958. When the module to treat contains both tied parameters (in the case of the issue, the module treated is `transformers` and the tied parameters are `'transformer.shared.weight'` and `'transformer.decoder.embed_tokens.weight'`) and it can fit on the current device, we get to an index error when the module treated is removed from the list of modules_to_treat.
The fix is to just ignore tied parameters in this case: this is only done to make sure they end up on the same device, but if we treat a module containing the tied parameters together, they will be put on the same device.
Fixes #958
> Fix tied parameters test in big model inference

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/external_deps/test_metrics.py
Solves https://github.com/huggingface/accelerate/issues/952 
TL;DR in a perfectly distributed batch setup (say dset 512, bs of 16), we need to ensure not to drop any samples and delegate to the `else` statement. Added a test to ensure this can get caught as well.
> Ensure that last batch doesn't get dropped if perfectly even in gather_for_metrics

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
I made a typo in #920 and forgot a `not` while copy-pasting some code :grimacing: 
This PR fixes that.
> Fix test for converting tensor to proper dtype

- src/accelerate/accelerator.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/memory.py
- tests/test_memory_utils.py
Helps https://github.com/huggingface/transformers/issues/21094 by introducing a lower-level convenience API for releasing memory. It's quite similar to `Accelerator.free_memory` but let's the user pass in a list of objects to remove.
Example usage:
```python
>>> import torch
>>> from accelerate.utils import release_memory
>>> a = torch.ones(1000, 1000).cuda()
>>> b = torch.ones(1000, 1000).cuda()
>>> a, b = release_memory(a, b)
```
Extracting it outside into a new util let's it be used by more usecases, such as big model inference
> Add new release_memory util

- src/accelerate/big_modeling.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
- tests/test_big_modeling.py
Currently `dispatch_model` breaks the tied parameters. This PR makes sure it does not.
Fixes #993
> Fix parameters tying in dispatch_model

- docs/README.md
Adds a styleguide under `docs/` matching relevant areas from the `transformers` style guide
> Add styleguide

- src/accelerate/accelerator.py
I noticed the `DeepSpeed` config was setting an environment variable of `ACCELERATE_GRADIENT_ACCUMULATION_STEPS`. This PR maintains consistency and lets the user have that specification when using the `Accelerator` if desired.
> Maintain accumulation steps environment variable

- src/accelerate/test_utils/testing.py
- tests/deepspeed/test_deepspeed.py
- tests/fsdp/test_fsdp.py
- tests/test_accelerator.py
Fixes test introduced in https://github.com/huggingface/accelerate/pull/991
It needed another call to `AcceleratorState._reset_state()` so I just moved it to the `tearDown` since every test in it reset the state. 
Also introduces an `AcceleratorTestCase` class to handle the `_reset_state()` for users since it's very easy to forget it happens and then a cryptic stack trace follows
> Fix test introduced in PR and introduce AcceleratorTestCase

- src/accelerate/state.py
- tests/test_accelerator.py
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>
Currently, `AccelerateState` will always use the Torch device corresponding to the local rank. This is fine in most cases, but may be limiting for advanced uses (eg. fractional GPUs) or compatibility with other libraries which manage resources themselves like Ray Train.
This PR adds logic to first derive the device from `ACCELERATE_TORCH_DEVICE` env var and falling back to local rank if that env var is not set. As this is an advanced use case, no documentation changes are introduced and there is no expectation that most users will make use of it.
I wasn't sure if this required tests and if so, what file they should be put into. Would appreciate some pointers here :)
This would make usage of Accelerate on Ray Train less error-prone.
> Allow the torch device to be set with an env var

- docs/source/_toctree.yml
- docs/source/index.mdx
- docs/source/usage_guides/explore.mdx
This PR introduces an interactive feature integrator tool into the Accelerate documentation. The space itself is hosted [here](https://huggingface.co/spaces/muellerzr/accelerate_examples). It operates by first having the user select a feature:
Then it will provide them with the code diff, an explanation, and a link to the docs for more information:
Ideally we use this for all of the items that exist in "Usage Guides" as fast visual tutorials, before linking to others. In the future this would include having an option to view CLI options as well as Big Model Inference, and other items with higher complexity's/diffs in a seperate interface category users can use (like select "Accelerator" vs "CLI" vs "Big Model Inference")
To add a new tutorial, please see the …
> Add in code exploration tool to docs

- src/accelerate/accelerator.py
As mentioned in #878 the current version of Accelerate breaks with the latest Nvidia PyTorch docker image (22.12) which doesn't have the change of class names for `LrScheduler`. Therefore, I switched the test to be replaced with a try except.
Fixes #1019
> Fix import of LrScheduler

- examples/by_feature/automatic_gradient_accumulation.py
- examples/by_feature/checkpointing.py
- examples/by_feature/cross_validation.py
- examples/by_feature/fsdp_with_peak_mem_tracking.py
- examples/by_feature/gradient_accumulation.py
- examples/by_feature/memory.py
- examples/by_feature/multi_process_metrics.py
- examples/by_feature/tracking.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- examples/cv_example.py
- examples/nlp_example.py
Currently all examples have a default of `mixed_precision="no"` when defining the `Accelerator`, which overrides whatever the user has in their config. This is a bit annoying, so this PR switches to `None` so that:
- the user can still force any mixed precision they want with `--mixed_precision`
- but otherwise the default value is read in the Accelerate config.
> Don't force mixed precision as no in examples

- docs/source/concept_guides/performance.mdx
Based on this [discussion](https://discuss.huggingface.co/t/learning-rate-scheduler-distributed-training/30453) writes a small note in the performance doc about how `accelerate` will step the scheduler multiple times and how the "batch size" is treated as a result
> Include steppage in performance docs

- src/accelerate/launchers.py
When adding the `ACCELERATE` prefix in https://github.com/huggingface/accelerate/pull/890, the `notebook_launcher` needs to check `ACCELERATE_USE_MPS_DEVICE`
Closes https://github.com/huggingface/accelerate/issues/1022
> Fix env var for MPS device on notebook_launcher

- src/accelerate/accelerator.py
- src/accelerate/utils/other.py
- tests/test_utils.py
> If a user does an evaluation loop at the end of each epoch, then they have to use unwrap_model with the keep_wrapper at True for FP16 integration. We made a breaking change with that when introducing the arg.
> For instance the no trainer translation and summarization scripts have stopped working with FP16.
Switches regression and makes the default `True`
> Change default for keep_fp32_wrapper

- examples/by_feature/checkpointing.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- src/accelerate/__init__.py
- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- tests/test_data_loader.py
This PR adds a new function to efficiently skip batches in a given DataLoader when the underlying dataset is not an `IterableDataset`. It works by replacing the `batch_sampler` with one that skips the first n batches, since iterating though the batch sampler is fast.
Missing tests and examples for now.
> Efficiently skip batches in a dataloader

- src/accelerate/accelerator.py
Over the next few days I will be adding more examples into the docstrings of major functions called within `accelerate` that are not there. This is to help in anticipation for the 1.0.0 release and to have a well-documented codebase along with a well-documented library as a whole.
> Start of adding examples

- docs/source/usage_guides/mps.mdx
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_utils.py
- src/accelerate/commands/launch.py
- src/accelerate/launchers.py
- src/accelerate/state.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
1. As `mps` and `cuda` won't be concurrently available/set, we can remove the `mps` config and have it enabled by default when it is available. To disable it use `--cpu` arg. This PR does that.
2. Supports backward compatibility till version 0.18.0. Post that `mps` related config will be removed.
> enabling `mps` device by default and removing related config

- src/accelerate/accelerator.py
`GradScaler` only makes sense in float16 mode and not for bf16 on the GPU. Removed block of code which did this for bf16.
> do not scale gradient in bf16 mode

- src/accelerate/utils/deepspeed.py
Hello. I tried to use DeepSpeed for my project and met a small bug. The problem was connected with backward function - i had to pass an argument 'retain_graph'. But we lose it by passing to internal DeepSpeed function.
I fixed it and these are my changes.
> Fixing of a bug connected with DeepSpeed

- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/utils/other.py
Based on conversation in slack, refactors the logic for process executors to be handled in the `AcceleratorState` and delegated to the `Accelerator` instead of in the `Accelerator` itself so that the `State` can be used by individuals that want to do process delegation without needing multiple `Accelerator` objects in their codebase. 
Still TODO is to move the decorators over, but those need some more improvements due to confusions in them and tests so that is a much later to-get-to
> Refactor process executors to be in AcceleratorState

- src/accelerate/big_modeling.py
- src/accelerate/hooks.py
As pointed out in #1041, one dispatching a model that has direct parameters, there is a device mismatch. This PR should fix it by adding the main execution device to the hook attached to whole model.
Fixes #1041
> Make sure direct parameters are properly set on device

- src/accelerate/__init__.py
- src/accelerate/big_modeling.py
- src/accelerate/hooks.py
- tests/test_big_modeling.py
This is a feature request for Diffusers. This PR adds a new `cpu_offload_with_hook` function that will offload the model to CPU, then put it back on the GPU once executed, but without offloading it just after the forward like `cpu_offload` does. Instead, it's up to the user to call the `hook.offload()` to offload it again.
Example:
```py
import torch
form accelerate import cpu_offload_with_hook
model = nn.Linear(4, 5)
model, hook = cpu_offload_with_hook(model)
print(model.weight.device) # Always cpu
outputs = model(inputs)
print(outputs.device) # Outputs are on GPU, execution was done on GPU
print(model.weight.device) # Stays on the GPU until hook.offload() is called
hook.offload()
print(model.weight.device) # Back to cpu
```
cc @pcuenca @patrickvonplaten
> Add `cpu_offload_with_hook`

- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
This PR refines `load_checkpoint_in_model` to directly load weights on the GPUs when the checkpoint file is a safetensors file, since `safetensors` can load very fast directly there. It also introduces a new `load_state_dict` function to do this loading.
@patrickvonplaten is this enough for your use case in `diffusers`?
> Load tensors directly on device

- src/accelerate/big_modeling.py
Minor fix in the code example for `cpu_offload_with_hook`
> Fix cpu_offload_with_hook code snippet

- src/accelerate/test_utils/testing.py
Gets rid of:
```
================================================================ warnings summary =================================================================
tests/test_cli.py::AccelerateLauncherTester::test_config_compatibility
tests/test_cli.py::AccelerateLauncherTester::test_config_compatibility
tests/test_cli.py::AccelerateLauncherTester::test_config_compatibility
tests/test_cli.py::AccelerateLauncherTester::test_no_config
/home/zach/accelerate/accelerate/src/accelerate/test_utils/testing.py:339: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
await asyncio.wait(
```
when running tests on py 3.9
> Use create_task when calling `_read_stream` during test_utils

- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
The post-filtered GPU params to `launch` need to maintain the script and arg parameters. This PR adds them in. 
Running on the nightly-ci to be sure before merging
> Fix args failure by adding in the defaults

- docs/source/package_reference/state.mdx
- src/accelerate/logging.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/external_deps/test_metrics.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/test_utils/testing.py
- tests/test_accelerator.py
- tests/test_scheduler.py
This PR introduces a `PartialState` class, which allows for process control while being *fully disconnected* from the `Accelerator` class. This allows users to utilize `print`, `on_main_process`, and more on their library integrations without needing to create an `Accelerator` object, and leave that to the user to create themselves. 
The `AcceleratorState` class does not inherit from this class, as otherwise the `__dict__`'s would be the same for `PartialState` and `AcceleratorState`, which we don't want. So it's referenced instead without explicit inheritance with passthroughs.
> Introduce PartialState

- src/accelerate/accelerator.py
- src/accelerate/state.py
As discussed in https://huggingface.slack.com/archives/C01Q6JPP6NA/p1676299264125009, flags `use_fp16` for deprecation once v1.0.0 of Accelerate is released.
> Flag use_fp16 for deprecation in 1.0

- src/accelerate/utils/operations.py
- src/accelerate/utils/other.py
- src/accelerate/utils/tqdm.py
Swaps over any utils that do not directly relate to the `Accelerator` object to use the `PartialState` instead (so utils on the optimizer, dataloader, etc all remain the same because they directly work with `accelerator.prepare`)
> Swap utils over to use PartialState

- docs/source/usage_guides/fsdp.mdx
- setup.py
1. Adds docs on correct way to save FSDP models as per the resolution of issue #1054 
2. Removes deepspeed version pinning
> update fsdp docs and removing deepspeed version pinning

- src/accelerate/__init__.py
- src/accelerate/accelerator.py
- src/accelerate/state.py
Refactors the `PartialState` and `Accelerator` to have the core decorator process-logic happen inside `PartialState` and then upstreams it to `AcceleratorState` and `Accelerator`, as `PartialState` should act as the main processes controller for users if they choose not to use the `Accelerator`. As a result, `PartialState` has complete docs for the functions while the `AcceleratorState` does not. I can also make a note on the version in `AcceleratorState` to point this out to users potentially.
> Refactor state and make `PartialState` first class citizen 

- src/accelerate/commands/config/config_args.py
As noted in https://github.com/huggingface/accelerate/issues/1073, the user tried to perform `accelerate launch --config_file MY_CONFIG.yaml ...` and if the file does not exist then a non-intuitive trace is given:
```python
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/accelerate/default_config.yaml'
```
Even though the user specified their own custom configuration.
This PR introduces a guard now instead of a magic-always-passing dropback when using `accelerate launch` that originally would then check if the default configuration could be used instead. 
New error message:
```python
(accelerate) zach@workstation:~/accelerate/accelerate$ accelerate launch --config_file "config.yml" test.py
File …
```
> Add error when trying to load non-existant config.yaml

- docs/source/usage_guides/sagemaker.mdx
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
The current implementation for SageMaker only allows a limited set of arguments, however the `Estimator` and `HuggingFace` Estimator support many additional arguments. With the current config wizard, this would be very hard to implement, hence I added a new field to `SageMakerConfig` to allow overrides to be set.
This e.g. allows the usage of Spot Instances.
> Allow custom SageMaker Estimator arguments

- docs/source/usage_guides/sagemaker.mdx
SageMaker supports local mode to test using the SageMaker DLC locally before starting the training job. This works out of the box, I added it to the configuration, I think it is valuable for users.
> Added SageMaker local mode doc section

- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
Closes https://github.com/huggingface/accelerate/issues/1083
Sadly to my knowledge there's not a decent way to test for the CLI use case without running some extensive test-check specific cases inside the config questionnaire logic. I think it'd be worth it later to do so but not right now.
> Fix config

- docs/source/usage_guides/big_modeling.mdx
The instructions suggested to use `git pull`, but the command to get the actual files from git-lfs is `git lfs pull`.
> Adds missing "lfs" in instructions for using git-lfs

- src/accelerate/utils/operations.py
Fixes #1058 
N.B. for consistency with existing code this always performs sum, ignoring the reduction kwarg (c.f. #745)
> add multi_cpu support to reduce

- README.md
From version 0.16.0, `mixed_precision='fp16'` must be given as a parameter when using accelerator fp16.
> Changed accelerator's fp16 parameter

- src/accelerate/accelerator.py
Just opening this PR for discussion, related to the changes in https://github.com/huggingface/accelerate/commit/38fd30e764ea87ef86e7d69fcba559c3605925b1
Observations:
- According to https://github.com/huggingface/accelerate/blob/38fd30e764ea87ef86e7d69fcba559c3605925b1/docs/source/usage_guides/tracking.mdx#accessing-the-internal-tracker, getting the tracker should expose that tracker's methods. In the example, the user is able to invoke `log_artifact`, which is specific to the `wandb` tracker. However, the same appears not to be working for us with the `tensorboard` tracker when we attempt to invoke `add_images`: https://github.com/huggingface/diffusers/issues/2468.
- The `unwrap` argument to `get_tracker()` appears not to be in use.
My question is, is the user expected to pass …
> Discussion: unwrap tracker

- src/accelerate/tracking.py
there is a small bug here:
```
$ python -c "import accelerate.tracking; x = accelerate.tracking.TensorBoardTracker('1')"
File "<string>", line 1, in <module>
File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/tracking.py", line 155, in __init__
self.logging_dir = os.path.join(logging_dir, run_name)
File "/home/stas/anaconda3/envs/py38-pt113/lib/python3.8/posixpath.py", line 76, in join
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
So the `logging_dir` arg can't be Optional, which this PR fixes, with it:
```
$ python -c "import accelerate.tracking; x = accelerate.tracking.TensorBoardTracker('1')"
File "<string>", line 1, in <module>
File …
```
> TensorBoardTracker: wrong arg def

- src/accelerate/test_utils/__init__.py
- src/accelerate/test_utils/scripts/test_ops.py
- src/accelerate/utils/operations.py
- tests/test_cpu.py
- tests/test_multigpu.py
Closes https://github.com/huggingface/accelerate/issues/1112
Fixes reduce to actually perform the mean operation, and adds a testing suite to the multigpu and cpu testfiles (TPU is a TODO once we have a runner)
> Add test for ops and fix reduce

- src/accelerate/commands/launch.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/launch.py
- tests/test_sagemaker.py
This PR refactors `commands.launch` to break up the logic into smaller functions, allowing for the environment preparation logic and actual launch logic to be decoupled. Therefore, a developer can now prepare an environment dict (and command list, where applicable) without having to launch any processes.
There have been no changes to the logic - this is purely a refactor of an existing structure.
As discussed offline, this will unblock Ray Train and other distributed frameworks which launch their own jobs.
> Refactor `launch` for greater extensibility

- src/accelerate/utils/modeling.py
- tests/test_modeling_utils.py
There was a bug when loading safetensors directly on GPU via `device_map="auto"` in `diffusers`.
The test shows the failure case.
> [Big model loading] Correct GPU only loading

- src/accelerate/commands/launch.py
Adds `--tee` and `--role` to `launch`, once https://github.com/huggingface/accelerate/pull/1108 is closed a better method will be used that doesn't require us to redefine each arg like this (and it can be done dynamically). 
Requested by @stas00
> Expose tee and role in Launch

- src/accelerate/commands/launch.py
Modifies the default for `launch` to grab all of the GPUs available if called without specifying anything. Will then also set `multi_gpu` to `True`.
> Expand warning and grab all GPUs available by default

- src/accelerate/accelerator.py
> fix lr scheduler issue

- src/accelerate/accelerator.py
- src/accelerate/test_utils/scripts/test_script.py
The decorators in the Accelerator object still were initialing the Accelerator on import, leading to issues when using the `notebook_launcher` (as seen in https://github.com/huggingface/accelerate/issues/1119). This PR fixes https://github.com/huggingface/accelerate/issues/1119 by rewriting the decorators again to follow the `_inner` pattern. Note that this is only needed on the `Accelerator`, for the self-decorators. This isn't needed for the `PartialState` elsewhere. 
(And this problem is mostly apparent on `notebook_launcher`, which takes a fork of the current process)
> Fix notebook_launcher

- src/accelerate/state.py
1. FSDP and Megatron-LM integrations are broken since the introduction of `PartialState` #1055. In prepare_data_loader , state obj is created again via `state = AcceleratorState()` . Now, it causes everything to go haywire, `self.__dict__.update(PartialState._shared_state)`  reverts FSDP  in AcceleratorState to `MULTI_GPU`  present in PartialState. This PR fixes it.
> fix partial state

- docs/source/basic_tutorials/notebook.mdx
Looks like a typo where `eval_split == train_split`.  The intend was most likely a 80%/20% split.
> Fixed typos in notebook

- docs/source/concept_guides/gradient_synchronization.mdx
Includes a new area in the docs based on my timing experiments performed on Friday, and published in an [article](https://muellerzr.github.io/blog/gradient_accumulation.html), mentioning how if users are not careful about gradient synchronization they can see a 2x+ slowdown when performing gradient accumulation.
> Include a note in the gradient synchronization docs on "what can go wrong" and show the timings

- src/accelerate/utils/modeling.py
Many diffusers checkpoint are sadly saved without `metadata["format"] = "pt"` which then creates the following issues: https://github.com/huggingface/diffusers/issues/2445
@sgugger could we maybe relax the constraint here a bit that if the metadata is missing we assume it's PT (also since accelerate is only made for PT)
> [Safetensors] Relax missing metadata constraint

- src/accelerate/checkpointing.py
The current implementation loads custom states to GPUs, leading to OOM. I add `map_location="cpu"` to the `torch.load` function, which is similar to the strategy in `load_accelerator_state`.
> Load custom state to cpu

- docs/source/package_reference/tracking.mdx
These two trackers seemed to be missing from the docs, so wanted to add them for folks to reference.
> Add Aim and MLFlow trackers to Reference Docs

- src/accelerate/data_loader.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_sync.py
Adjusts the `GradientState` so it can know:
- What dataloader is entered/exited on `__iter__`
- The total dataloader list that we are currently iterating over
- Changes the logic for setting the end of the dataloader to exist in `GradientState._add_dataloader` and `GradientState._remove_dataloader`
Solves https://github.com/huggingface/accelerate/issues/960 and https://github.com/huggingface/accelerate/issues/1050
> Let GradientState know active dataloaders and reset the remainder

- src/accelerate/utils/imports.py
- src/accelerate/utils/operations.py
When torch is build without distributed support (non pypi release), importing `accelerate` crashs because it tries to import `torch.distributed.ReduceOp`.
This PR attempts to only import when torch has support for distributed setups along with trying to not have too much impact on CCL call performances.
_I'm not quite sure how to test this setup as it, if you have any suggestion ..._
Root error stacktrace:
```python
File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 24, in <module>
from torch.distributed import ReduceOp
ImportError: cannot import name 'ReduceOp' from 'torch.distributed' (/usr/local/lib/python3.10/dist-packages/torch/distributed/__init__.py)
```
> Attempt to fix import error when PyTorch is build without `torch.distributed` module

- docs/source/usage_guides/checkpoint.mdx
Closes https://github.com/huggingface/accelerate/issues/1130
> Document skip_first_batches in the checkpoint usage guides

- README.md
- docs/source/quicktour.mdx
- examples/README.md
- examples/by_feature/README.md
- tests/test_kwargs_handlers.py
Since `torch.distributed.launch` is deprecated, finds all cases of `launch` and replaces with `run`/`torchrun`
> Remove outdated command directions and use in tests

- src/accelerate/commands/config/config_args.py
Currently if a user tries to load a config saved with 0.16.0, they will get
```
TypeError: __init__() got an unexpected keyword argument 'dynamo_backend'
```
This PR ensures backward compatibility.
> Fix backward compatibility in configs wrt dynamo backend

- src/accelerate/state.py
- tests/test_accelerator.py
Turns out I've discovered a neat behavior in the library, that was "broken" with the State rewrite. With how `Accelerate` will work, if the user defines `cpu=False` initially then goes `cpu=True`, then a value error will be raised and the state will be changed. *But* if `cpu=True` is passed first then `cpu=False`, nothing will change and no error will be raised. The reason for this is simply because its the default and its a way for `State` to not override the first choice, so we assume CPU all the time. 
Also brings back the `ACCELERATE_USE_CPU` env flag, as this was removed in the `State` refactor. 
This brings back this behavior and adds a test to the `AcceleratorTester` class. 
Closes https://github.com/huggingface/accelerate/issues/1174
> Fix CPU error always being raised

- src/accelerate/commands/launch.py
Fixed typo in tpu_pod_launcher src/accelerate/commands/launch.py that caused accelerate launch to crash on TPU pods by not reading config properly. Replaced  "--dynmo_backend" with  "--dynamo_backend",
> Fix typo in launch.py tpu_pod_launcher

- docs/source/usage_guides/fsdp.mdx
By default, `accelerator.get_state_dict` will call the underlying `model.state_dict` implementation.  With FSDP, this gathers all of the state onto the rank 0 device.  If the parameters don't fit, this can cause CUDA OOM errors.
This PR adds documentation around how to use the PyTorch state_dict_type context manager to configure the behavior of the state dict.
> Add documentation around FSDP state dict save behavior

- src/accelerate/utils/transformer_engine.py
In the FP8 integration, we don't want to convert linear layers that have weights that are not multiple of 16 (for instance the classifier head) as they won't work with transformer_engine.
> Only convert linear layers with weights multiple of 16

- src/accelerate/accelerator.py
In some training setups such as in `trl`: https://github.com/lvwerra/trl sometimes users create a new module that wraps modules that are loaded with `accelerate`. Check for example [this class](https://github.com/lvwerra/trl/blob/ddb6df367da4a7374287f35ae37d092f7c32a815/trl/models/modeling_value_head.py#L57)
I propose a simple fix in the accelerator to check if there is any immediate child module that has the `hf_device_map` attribute
cc @sgugger 
I can confirm all slow tests pass except the similar ones as in https://github.com/huggingface/accelerate/pull/1155 - which I believe are related to the way I am creating my env
> [`Accelerator`] We should not call `to` on modules that wraps `accelerate` loaded models

- src/accelerate/commands/accelerate_cli.py
- src/accelerate/commands/config/__init__.py
- src/accelerate/commands/launch.py
Solves https://github.com/huggingface/accelerate/issues/1195
TL;DR argparse has a behavior where by default if the passed args to the script align partially to the args in the parser, it will raise the error described in the issue
> Fixup passing overlapping args to the script

- docs/source/usage_guides/gradient_accumulation.mdx
- src/accelerate/accelerator.py
- src/accelerate/scheduler.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_sync.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- tests/test_scheduler.py
This PR adjusts the logic in the `AcceleratedScheduler` to take into account gradient accumulation steps. 
Closes https://github.com/huggingface/accelerate/issues/1170
Closes https://github.com/huggingface/accelerate/issues/1160
Currently a behavior does not exist that will automatically "cut" the LR scheduler of a user if they pass in `gradient_accumulation_steps`, so unless they are careful and adjust their LR scheduler beforehand, they're not actually stepping properly with the lr scheduler.
None, explicitly
`AcceleratedScheduler`'s `step` function now will run `n*num_processes` where `n==gradient_accumulation_steps` to account for the difference. 
To test performance, I ran the equivalent training of `gradient_accumulation_steps==2` on a bs of 16, and a regular batch size of 32, with …
> Make the Scheduler adjust the steps taken relative to the gradient accumulation steps

- docs/source/usage_guides/big_modeling.mdx
- src/accelerate/utils/modeling.py
This PR fixes the tied weights load. Since loading a checkpoint in a model that was instantiated on the meta device recreates the tensors, it breaks the connection between tied weights. This PR fixes that and also fixes the example in the doc to make sure weights are tied.
Fixes #1197
> Fix tied weights load

- src/accelerate/commands/launch.py
This PR closes https://github.com/huggingface/accelerate/issues/1199 and adds another sentence to the raised error telling the user to use `torch.distributed.launch` to start their script directly.
> Better error message when using multi-GPU and Accelerate on torch <1.9.1

- src/accelerate/accelerator.py
The accumulate method has an example of how to do gradient accumulation that has the context manager and the for loop in the wrong order.  The _do_sync method is called only when the context manager is entered, so it needs to go inside the loop.
(I was wondering why my model wasn't converging well!)
> Fix example in accumulate method documentation

- src/accelerate/accelerator.py
1. Use `DeepSpeedCPUAdam` when offloading optimizer to CPU/NVME
> ds offload optim fix to use CPUAdam

- src/accelerate/accelerator.py
Closes https://github.com/huggingface/accelerate/issues/1215
> Move when the GradientState test is performed so that it is not None

- src/accelerate/logging.py
The `get_logger` example's keyword argument is not aligned with the function, resulting in inconsistency. This pull request aims to fix this issue by adjusting the keyword argument used in the example to match the function.
> Fix get_logger kwarg documentation issue

- src/accelerate/commands/launch.py
Silences the warning if `dynamo_backend` uses the default value when launching a script
> Silence dynamo_backend

- src/accelerate/utils/other.py
This PR adds an additional check to ensure that an environment variable exists before deleting it when patching an environment. 
This prevents a `KeyError` being raised when training Multi-GPU using AzureML with the latest version of accelerate.
It would be awesome if this could be released quickly as a patch!
> Add additional check when patching env

- src/accelerate/accelerator.py
- tests/test_accelerator.py
Mild regression and expansion on the new gradient accumulation API change. 
Keeps all main areas of the `gradient_state` to be mutable if needed/wanted from the `Accelerator` object that users may wish to do (so `sync_gradients` and `gradient_accumulation_steps`)
Solves https://github.com/huggingface/accelerate/issues/1230
> Make grad accum steps mutable on the Accelerator object

- .devcontainer/devcontainer.json
"extensions" has been moved to "customizations/vscode"
```
"customizations": {
"vscode": {
"extensions": [
// Ensure we have IntelliSense in VSCode when running inside container
"ms-python.python"
]
}
}
```
> devcontainer: "extensions" has been removed and replaced by customizations

- README.md
Needs to be a full `raw.githubusercontent.com/*` for the image to show up on pypi, solves the logo not showing here: https://pypi.org/project/accelerate
> Fix pypi image

- src/accelerate/utils/deepspeed.py
This PR improves the handling of cases where users provide a non-existing deepspeed config path
- Parsing non-base64 strings with `base64.urlsafe_b64decode` raises `binascii.Error`, which is a subclass of `ValueError`. The previous error handling code won't catch it
- `config` is not defined if this piece of code errors out so we need to use `config_file_or_dict` instead in the error handling
> Handle missing deepspeed config

- src/accelerate/utils/modeling.py
- tests/test_big_modeling.py
Fixes https://github.com/huggingface/accelerate/issues/1228
Before this PR, if a user wants to call `dispatch_model` on a customly created model, the model remains unquantized and leads to some errors that are hard to understand and debug. This issue has been also observed several times on other libraries that uses `accelerate` + `bitsandbytes` such as in `PEFT` that calls `dispatch_model` under the hood as well.: https://github.com/huggingface/peft/issues/187 
Now with this PR, the script below returns the expected output: 
```python
import torch
from transformers import AutoConfig, AutoModel
from transformers.utils.bitsandbytes import replace_8bit_linear
from accelerate import init_empty_weights
from huggingface_hub import hf_hub_download
from accelerate import …
```
> [`core`] Add Quantization support for `dispatch_model`

- src/accelerate/utils/deepspeed.py
Dear contributers and maintainers.
- Include your OS type and version, the versions of Python and PyTorch.
```
> uname -a
Linux debian-cglab 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
> pip list
...
accelerate               0.12.0
...
deepspeed                0.8.3
...
open-clip-torch          2.7.0
pytorch-lightning        1.7.6
torch                    1.13.1
torchaudio               0.13.1
torchdiffeq              0.2.3
torchmetrics             0.11.4
torchsde                 0.2.5
torchvision              0.14.1
vector-quantize-pytorch  1.1.2
```
- A short, self-contained, code snippet that allows us to reproduce the bug in less than 30s;
When I use the deepspeed setting with single precision (fp32) data type,
I got an error message below
```
if …
```
> Check attribute 'overflow' exists in optimizer.

- .github/ISSUE_TEMPLATE/bug-report.yml
Expected behavior most likely is a normal text and not a code section
> fix issue template

- src/accelerate/utils/operations.py
There is something weird going on with `TypeError` not being properly raised in the PyTorch distributed launcher. This PR thus changes the type of the error raised when one tries to gather/reduce something that is not a Tensor.
> Change error raised to ValueError

- src/accelerate/utils/operations.py
Fixes #1266.
Fixes reduce to not change the input tensor if there's only one process.
Note: two tests failed even before I made any modifications. Other tests went fine. The short test summary info of `make test` is:
```
FAILED tests/test_grad_sync.py::SyncScheduler::test_gradient_sync_gpu_multi - RuntimeError: 'torchrun --nproc_per_node=2 /amax/xyf/accelerate/src/accelerate/test_utils/scripts/test_sync.py' failed with returncode 1
FAILED tests/test_memory_utils.py::MemoryTest::test_release_memory - AssertionError: 8519680 != 0
```
> Fix reduce operation

- src/accelerate/utils/transformer_engine.py
Solves https://github.com/huggingface/accelerate/issues/1276 by also including a check for `is_fp8_available`
> Raise import error if fp8 not available in `has_transfomer_engine_layers`

- docs/source/package_reference/accelerator.mdx
> Minor fix whitespace colon

- src/accelerate/state.py
Addresses https://github.com/huggingface/accelerate/issues/1276 by raising an error in `PartialState` when passing in `fp8` to the precision and its unsupported. I don't believe we should address this in `accelerate config` as well, since config files can be passed around. If you disagree @sgugger and it would be good to include that check during the CLI questionnaire, I can do so.
> Raise more explicit error when transformer_engine isn't installed

- src/accelerate/utils/operations.py
- tests/test_utils.py
Expands the error a bit more in `recursively_apply` to be more straightforward. Example:
```python
File "/home/zach_mueller_huggingface_co/test_distrib.py", line 6, in <module>
gathered_tensor, i = accelerator.gather((process_tensor, 1))
File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/accelerator.py", line 1869, in gather
return gather(tensor)
File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/utils/operations.py", line 243, in gather
return _gpu_gather(tensor)
File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/utils/operations.py", line 223, in _gpu_gather
return recursively_apply(_gpu_gather_one, tensor, error_on_other_type=True)
File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/utils/opera …
```
> Expound error on `recursively_apply`

- src/accelerate/accelerator.py
Partial solution to https://github.com/huggingface/accelerate/issues/1246 (I believe), which will always let the user pull the model, and we only check for fp16 if the state dict has the capability to do so
> Only check for dtype if it has it in get_state_dict

- tests/test_big_modeling.py
This PR fails the bnb slow tests that are currently failing. 
I was testing the tests on the `main` branch of `transformers` that included https://github.com/huggingface/transformers/pull/22238 . That fix was necessary to correctly call `replace_8bit_linear` that expects a list of strings as input for `modules_not_to_replace`, otherwise some checks will fail, leading to modules not being properly converted in int8
Afterwards I hit another issue where the device map missed the parameters of the model `*.SCB` (the quantization parameters) in `check_device_map`. Since these modules are not registered as a proper submodule the correct fix is to add a device_map that puts the entire model on a given device. 
This time ran the tests on the latest transformers release and they all pass
cc …
> [`bnb`] fix bnb slow test

- src/accelerate/launchers.py
Currently we rely on PyTorch's standard error message when the `notebook_launcher` has issues, and it is *exceedingly* cryptic how to continue when an import is causing issues. I specifically mean the `Cannot re-initialize CUDA in a forked subprocess...`. 
Especially for the user, it doesn't actually explain what is *truly* going on. As a result, this PR introduces a better error message.
Example trace:
```python
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
File ~/accelerate/src/accelerate/launchers.py:138, in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
137 try:
--> 138     start_processes(launcher, args=args, nprocs=num_processes, start_method="fork") …
```
> Raise better error on `notebook_launcher`

- docs/source/concept_guides/performance.mdx
Helps https://github.com/huggingface/accelerate/issues/1277 by adding a note based on my tests yesterday. tl;dr: When trying to compare performance you won't see a 1:1 if you use gradient accumulation or mixed precision due to averaging of the gradients and their overall precision, though the end result should be similar.
> Make note about grad accum and prec in performance documentation

- src/accelerate/big_modeling.py
The `load_checkpoint_and_dispatch` method has this kwarg type:
`device_map: Optional[Union[str, Dict[str, Union[int, str, torch.device]]]] = None,`
But if you pass `device_map=None` you get an error:
```
accelerate/big_modeling.py", line 477, in load_checkpoint_and_dispatch
if offload_state_dict is None and "disk" in device_map.values():
AttributeError: 'NoneType' object has no attribute 'values'
```
> fix for load_checkpoint_and_dispatch(device_map=None)

- src/accelerate/accelerator.py
- src/accelerate/checkpointing.py
- tests/test_state_checkpointing.py
Solves https://github.com/huggingface/accelerate/issues/1210 by setting the optimizer state to `accelerator.device` when `num_processes > 1` and calling `load_state`.
> Set the state device dependant to Accelerator on multigpu

- docs/source/package_reference/cli.mdx
- docs/source/usage_guides/megatron_lm.mdx
- src/accelerate/commands/launch.py
- src/accelerate/hooks.py
- src/accelerate/state.py
- src/accelerate/test_utils/testing.py
- src/accelerate/utils/launch.py
This PR simplifies the MPS implementation by removing all deprecated code (we did mention it would be good until v0.18). It also paves the way for an easier integration of other default devices later on by adding a `default_device` property on `PartialState`.
> Simplify MPS implementation

- src/accelerate/state.py
Defaults the `kwargs` to `nccl`, as the kwarg handler will sometimes not be used and we still need to use `nccl` as the default
> Default to nccl

- src/accelerate/utils/operations.py
- tests/test_utils.py
According to the PyTorch docs (and the error that comes up from https://github.com/huggingface/diffusers/issues/2775), we need to wrap around a function separately when doing a class decorator and applying torch.compile, rather than calling it directly. This PR solves this by creating the new function it requires, and then adding it to `__wrapped__` so that `unwrap_model` knows to pop it. (Basically manually creating a decorator).
Also added some tests to ensure it'll still work and does work.
> Ensure that dynamo is compatible with mixed precision

- .github/workflows/run_merge_tests.yml
- docker/accelerate-gpu/Dockerfile
After noticing https://github.com/huggingface/accelerate/pull/1322, the torch version ran on our merge tests isn't actually a high enough one to have `torch.compile`, so this PR makes sure that the latest torch/torchvision is always installed/upgraded
This PR also upgrades the CUDA docker python + CUDA versions, so that compile can be ran + installed
> Upgrade torch version on main tests

- src/accelerate/utils/modeling.py
Hi,
I found laboriously today that the prefix matching for identifying submodules in `modeling.py` will also match sibling modules with longer names, such as `model.layers.1` matching `model.layers.18`. This was producing broken structures preventing execution.
This patch mutates all uses of `.startswith()` in that file to ensure the model name is suffixed with a `.`. This resolved the immediate issue I encountered for me.
> ensure module prefixes only match that module

- src/accelerate/utils/modeling.py
I found when loading that each tensor for a device was reloaded for every layer in an `n**2` manner.
It seemed the device list in `load_state_dict` was loaded as device map keys, but then treated as a unique set despite having an element for every entry in the map, i.e. each device was in the list many times over.
I searched the file for `devices`, found two uses of lists as if they were sets, and added code to remove duplicate entries from both instances. I used a dict rather than a set so that order of entries is preserved, keeping the first device as the primary one.
EDIT: the other list I found already had unique entries and that change has been removed.
With this change, for me, the loading code no longer reloads every tensor for each map entry, instead loading them once for each …
> remove repetitive entries from device lists

- src/accelerate/test_utils/scripts/test_sync.py
This PR temporarily skips the gradient accumulation test on torch 2.0+ due to an active issue/investigation on it. The performance did not drop unreasonably and the API is still performing comparably in torch 2.0, so it may be a test-specific issue, however in terms of raw performance from our library the main implementation is fine.
> Skip failing torch 2.0+ test

- src/accelerate/utils/__init__.py
- src/accelerate/utils/imports.py
As Accelerate doesn't support `amp` anymore, removes last traces of it :)
> Remove unused amp import util

- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
This PR proposes a fix for #1303.
The bug seems to be in delegation from one context manager (for example from `Accelerator`) to another one (from `AccelerateState`). Currently, the following pattern is used:
```python
@contextmanager
def main_process_first(self):
yield self.state.main_process_first()
```
However, when executed, this context manager simply yields without entering `self.state.main_process_first()`, causing the bug. The solution is to correctly enter the inner context manager using `with`.
This was a very interesting bug. Since I haven't defined nested context managers like this before, I wanted to understand what the right way to do this is, and whether the current implementation in the library was correct. Like the cool kids I even asked ChatGPT, which explained what the …
> Fix nested context manager for main_process_first()

- src/accelerate/utils/modeling.py
Fixes an off-by-one appearance issue at 0% and 100% with the safetensors device_map loading progress bar.
I had this tacked onto my previous progress bar contribution but lost internet before the merge happened.
> Small progress bar fix

- src/accelerate/accelerator.py
As mentioned in [https://github.com/NVIDIA/TransformerEngine/issues/15#issuecomment-1515703357](https://github.com/NVIDIA/TransformerEngine/issues/15#issuecomment-1515703357)
> Today a CUDA Toolkit 12.1 update 1 was released. It contains cuBLAS 12.1.3.1 enabling FP8 kernels for Ada. With this version of cuBLAS together with Transformer Engine 0.7 which added Ada to the compilation targets, FP8 computation is now supported on Ada.
GPUs with computation capacity 8.9, (Ada Lovelace, includes RTX4xxx and RTX6000ada) can now benifit from FP8 acceleration with CUDA Toolkit 12.1 update 1 and Transformer Engine 0.7.
This pull request reflects the change.
> Support FP8 mixed precision training for Ada Lovelace GPUs

- src/accelerate/utils/imports.py
Following up on #379 
I have extended the check to other packages to ensure we are not picking up a folder that happens to be called as the package.
> Better check for packages availability

- README.md
- src/accelerate/accelerator.py
Fix typing issue in #1359 partially. For now, it only changes one file, but we'll need to gradually change all files to follow the new format.
> fix: typing issues, and replace deprecated python typing (Optional, Union) to `|`

- src/accelerate/commands/config/cluster.py
FSDP_MIN_NUM_PARAMS default changed from 1e8 to 100000000 (no floats allowed), see #1361
> Fix default FSDP_MIN_NUM_PARAMS so it's an int

- src/accelerate/state.py
`xpu_backend` can be `None`, and in the transformers integration we pass it to `PartialState` due to the fact that `no_cuda` is a toggleable option and can still be `True` on CPU. This PR makes it so that if the last case is hit in this block:
```python
if self.no_cuda:
self.distributed_state = PartialState(cpu=True)
self._n_gpu = 0
elif is_sagemaker_mp_enabled():
local_rank = smp.local_rank()
device = torch.device("cuda", local_rank)
self._n_gpu = 1
torch.cuda.set_device(device)
elif self.deepspeed:
os.environ["ACCELERATE_USE_DEEPSPEED"] = "true"
self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
del os.environ["ACCELERATE_USE_DEEPSPEED"]
self._n_gpu = 1
else:
self.distributed_state = PartialState(backend=self.xpu_backend)
self._n_gpu = 1
```
the …
> Special transformers case from args

- src/accelerate/commands/env.py
As we're getting more issues related to specific GPUs, and oftentimes with offloading it's good to know the user's system RAM, this PR modifies `accelerate env` to also report the GPU the user is using, along with the total system RAM that they have.
> Improve `accelerate env` reporting

- setup.py
- src/accelerate/test_utils/scripts/test_script.py
Should fix the thread issue with `pathlib.unlink()`, moves the removal under the first check that passes the conditional and waits for everyone, and has the main process only remove it. Going to rerun the CI multiple times to ensure it's no longer flaky
> Fix flakey thread issue

- src/accelerate/commands/config/config_args.py
I have used the below versions of packages for accelerate.
```
python==3.8.13
accelerate==0.18.0
PyYAML==6.0
```
And, I have used the below config files.
``` yaml
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
main_process_ip: null
main_process_port: null
mixed_precision: no
num_processes: 2
use_cpu: false
```
I wanted to use "fp32", I tried to train my model using **"mixed_precision"** as **"no"**, but I couldn't because of the error below.
${MY_PKG_PATH}/accelerate/utils/launch.py
``` python
mixed_precision = args.mixed_precision.lower()
```
**AttributeError: 'bool' object has no attribute 'lower'**
As a result of debugging, I found that the safe_load() function in the …
> fix config bug for 'mixed_precision' from 'yaml.safe_load()'

- setup.py
Per https://github.com/huggingface/accelerate/pull/638, it never actually bumped the minimal torch version to 1.6.0, which is the minimum we test on now and support.
> Bump torch version

- src/accelerate/test_utils/scripts/test_ops.py
- src/accelerate/utils/operations.py
- tests/test_multigpu.py
Solves https://github.com/huggingface/accelerate/issues/1383
Currently `gather_object` doesn't actually work properly, because pytorch will gather the whole object as a whole. As a result, using the nested execution that is currently there will force pytorch to not actually return what the user wants. This PR fixes the implementation, based on the suggestion in #1383, and adds tests for it as well.
I also noticed that occasionally just doing `torchrun` wouldn't force the tests to be ran with multiple GPUs/all gpus available, so this PR adds `--nproc_per_node` manually
> Fix gather_obj

- src/accelerate/accelerator.py
- src/accelerate/data_loader.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/utils/launch.py
- src/accelerate/utils/operations.py
- src/accelerate/utils/random.py
I've been working on migrating PyTorch/XLA from our legacy XRT runtime to PJRT. We have detailed documentation on the differences and changes here: https://github.com/pytorch/xla/blob/master/docs/pjrt.md
This PR collects all of the fixes that I've made so far to support XRT and PJRT interchangeably through Accelerate. In order of significance:
1. Update implementation of `synchronize_rng_types` to use `xm.collective_broadcast` to broadcast the RNG state tensor. Collective operations in general should be called from the main thread of each process to avoid unpredictable behaviors in XLA. But, our implementation of [`MpDeviceLoader` calls `accelerate.DataLoaderShard`'s `__iter__`](https://github.com/pytorch/xla/blob/f763d0d2a4dac0872e2e1670332fd490f524b8be/torch_xla/distributed/parallel_load …
> Support TPU v4 with new PyTorch/XLA TPU runtime

- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/test_utils/training.py
Depends on #1393
I've been working on migrating PyTorch/XLA from our legacy XRT runtime to PJRT. We have detailed documentation on the differences and changes here: https://github.com/pytorch/xla/blob/master/docs/pjrt.md
Due to TPU design constraints, PJRT must use multithreading on TPU v2 and v3 ([docs](https://github.com/pytorch/xla/blob/master/docs/pjrt.md#multithreading-on-tpu-v2v3)). 
- This means we cannot use global state for `AcceleratorState`, since two replicas would end up sharing the same `accelerator.device` and `accelerator.process_index`. I implemented a [descriptor](https://docs.python.org/3/howto/descriptor.html) that wraps the global `_shared_state` dicts in `state.py` and optionally makes it thread-local when using XLA.
- Use numpy `Generator`s in the `accelerate test` …
> Support TPU v2 and v3 on new PyTorch/XLA TPU runtime

- docs/source/_toctree.yml
- docs/source/usage_guides/local_sgd.mdx
- examples/by_feature/README.md
- examples/by_feature/local_sgd.py
- src/accelerate/local_sgd.py
- tests/test_examples.py
Hi,
As discussed with @muellerzr , I am adding a non-breaking functionality to support local SGD, which enables efficient multi-GPU training in the case when no fast interconnect is possible. 
This replaces a previous [pull request](https://github.com/huggingface/accelerate/pull/1350)
I incorporated recommendation to change the per device batch size (in the separate benchmark) and I also removed the erroneous code (borrowed from the examples) that reduced the size of the dataset (as well as code-related recommendations) and retested everything. There is still some unexplained behavior, but it looks quite reasonable now:
[Here is a link to the summary of results and benchmarking code.](https://github.com/searchivarius/BlogCode/blob/master/2023/test_accelerate_followup/README.md) …
> Adding support for local SGD.

- src/accelerate/tracking.py
If mlflow experiment already exists, we can re-use its id for tracking. (otherwise it will fail)
> use existing mlflow experiment if exists

- src/accelerate/tracking.py
If we use an already existing experiment, having to specify a logging directory doesn't make sense.
If we create a new experiment, the logging dir is optional too and is picked automatically by mlflow if not provided.
> Make mlflow logging dir optional

- .github/workflows/run_merge_tests.yml
The last step of the workflow doesn't do `source activate accelerate` so `tabulate` isn't installed. Ensures that when needed, tabulate is available.
> Ensure that tabulate gets installed on main tests

- src/accelerate/utils/__init__.py
- src/accelerate/utils/modeling.py
This PR adds a new utility class, termed as `CustomDtype` to handle custom dtypes that does not exists natively in PyTorch for future users that want to use `infer_auto_device_map` on exotic dtypes, such as FP8, int4, etc.
cc @sgugger
> [`core`] Introducing `CustomDtype` enum for custom dtypes

- src/accelerate/commands/config/default.py
Currently we have tests failing on transformers due to XPU, due to unsupported operations being performed. This PR makes it so that `write_basic_config` has an XPU flag, and sets it to `False` to not interfere with the plan CPU runners in transformers (also removes unused `dynamo_backend` option)
> Fix XPU being used in default config

- src/accelerate/utils/other.py
- tests/test_utils.py
When torch compile is used in addition to multi-GPU training the PyTorch module is wrapped twice and looks more or less as follows:
```
model: torch._dynamo.eval_frame.OptimizedModule(torch.nn.parallel.DistributedDataParallel(model))
```
The model is not unwrapped from distributed data parallel to just model. This PR adds more logic to `unwrap_model()` so that calling:
```py
accelerator.unwrap_model(model)
```
results in:
```
model: torch._dynamo.eval_frame.OptimizedModule(model)
```
which I think is a better fit here
> Make sure torch compiled model can also be unwrapped

- src/accelerate/logging.py
A user cannot call the logging utility in `Accelerate` without first building the state in some form. This PR introduces an error raising it as such and fixes https://github.com/huggingface/accelerate/issues/1445
> Raise error when logging improperly

- utils/log_reports.py
Small fix on the CI reporter where `files2failed` wasn't being made for the section on creating a list of messages on what failed, leading to an error and causing an all passing message to never be sent.
> Fix ci reporter

- docs/source/_toctree.yml
- docs/source/usage_guides/distributed_inference.mdx
- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
This PR introduces a new utility in `Accelerator`, `AcceleratorState`, and `PartialState`: `Accelerator.split_between_processes`.
It is often useful when performing distributed inference in applications such as stable diffusion to send one prompt to GPU A, another prompt to GPU B, and so forth. This PR introduces a new context manager that let's the user send some data in and split it evenly across all instances for them to use. An example application might look like such:
```python
from accelerate import PartialState
from diffusers import DiffusionPipeline
state = PartialState()
pipe= DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
with state.split_between_processes(["a dog", "a cat"]) as prompt:
pipe.to(state.device)
image = …
```
> Distributed prompting/inference utility

- docs/source/usage_guides/distributed_inference.mdx
I think `split_across_processes` should be [`split_between_processes`](https://huggingface.co/docs/accelerate/main/en/package_reference/state#accelerate.PartialState.split_between_processes) right?
> [docs] Minor typo in distributed inference

- docs/source/usage_guides/distributed_inference.mdx
I couldn't find a rank property in `PartialState`.
> [docs] Replace `state.rank` -> `process_index`

- src/accelerate/commands/launch.py
It was reported with an unexpected behavior (both on the forums [here](https://discuss.huggingface.co/t/num-processes-1-even-when-i-set-it-to-num-processes-2/40122) and in slack) where if a user specified `--num_processes` but didn't specify multi-gpu, multiple GPUs wouldn't be used by default.
This PR modifies the default checks when doing `accelerate launch` to see if `num_processes>1` and if multiple GPUs are available, specifies multi-gpu with a warning. cc @pcuenca
> Auto multigpu logic

- docs/source/basic_tutorials/launch.mdx
- docs/source/package_reference/cli.mdx
Documents how to use `python -m` when running launch instead of using the CLI. cc @stas00 
Also documents the other available module-calling option: `env`
> Document how to use commands with python module instead of argparse

- docs/source/usage_guides/checkpoint.mdx
- examples/by_feature/checkpointing.py
- examples/complete_cv_example.py
- examples/complete_nlp_example.py
- src/accelerate/accelerator.py
- tests/test_examples.py
Solves https://github.com/huggingface/accelerate/issues/1451 and adds tests
> Fix skip first batch being perminant

- src/accelerate/big_modeling.py
Fixes the following case
```python
import torch
from torch import nn
from accelerate import init_on_device
with init_on_device(device="meta", include_buffers=True):
dummy_module = nn.Module()
dummy_module.register_buffer("dummy_buffer", torch.tensor([1.0]), persistent=False)
```
cc @thomasw21
> Update `register_empty_buffer` to match torch args

- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
Solves https://github.com/huggingface/accelerate/issues/1400 by also letting the tensors be split if added. Note that similar to the list version, the tensors padded will have the value of the last item in the tensor being used. Such that on four processes:
```python
t = torch.tensor([[0,1,2,3], [4,5,6,7]])
with PartialState().split_between_processes(t) as t:
print(t)
tensor([[0,1,2,3]])
tensor([[4,5,6,7]])
tensor([[4,5,6,7]])
tensor([[4,5,6,7]])
```
> Split tensors as part of `split_between_processes`

- src/accelerate/data_loader.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_sync.py
1. Add `DataLoaderStateMixin`: Each dataloader should have it own states like `end_of_dataloader` and `remainder`
2. Changed `_remove_dataloader`: This should be called after last `yield`. Otherwise the active dataloader will be wrong in the last iteration.
3. Changed test: active_dataloader should be the current dataloader whether is the last iteration or not.
Solves #1050
@muellerzr
> Fix gradient state bugs in multiple dataloader

- src/accelerate/accelerator.py
Currently will fail with the transformers integration because IPEX is *always* used due to the presence of the plugin, when it should only exist when being used/actually available. 
<s>In a follow-up PR I will change this to use an env variable as well, as the "create a plugin by default" breaks our norm</s>
> Only use IPEX if available

- src/accelerate/utils/modeling.py
- tests/test_big_modeling.py
Fixes https://github.com/huggingface/accelerate/issues/1504
This PR applies the similar enhancement as #1228 for FP4 layers
Now the script below outputs the desired dtype:
```python
import torch
from transformers import AutoConfig, AutoModel, BitsAndBytesConfig
from transformers.utils.bitsandbytes import replace_8bit_linear
from accelerate import init_empty_weights
from huggingface_hub import hf_hub_download
from accelerate import load_checkpoint_and_dispatch
with init_empty_weights():
model = AutoModel.from_config(AutoConfig.from_pretrained("bigscience/bloom-560m"))
quantization_config = BitsAndBytesConfig(
load_in_4bit=True
)
model = replace_8bit_linear(model, quantization_config=quantization_config)
for p in model.parameters():
p.requires_grad = False
model_path = …
```
> [`bnb`] Add fp4 support for dispatch

- src/accelerate/accelerator.py
This small PR fixes the issue when the user prepare a 4-bit model on multiple devices. It will return an error just like for the 8-bit model. Furthermore, i have fixed how we get the device index as the device_map values can be of type torch.device.
> Fix 4bit model on multiple devices

- src/accelerate/accelerator.py
During ONNX Runtime optimization, the forward function's signature is inspected to perform downstream tasks. The current way of overriding the model's forward function results in the following error:
`AttributeError: 'function' object has no attribute '__func__'`
This PR improves the function signature override by using `types.MethodType` which doesn't impact the function signature for downstream tasks.
> adjust overriding of model's forward function

- docs/source/package_reference/cli.mdx
- src/accelerate/commands/config/cluster.py
- src/accelerate/commands/config/config_args.py
- src/accelerate/commands/launch.py
- src/accelerate/utils/launch.py
Keeps in line with the rest of Accelerate's env vars and CLI args to make it clear where it comes from and how to disable it:
* `IPEX_ENABLED` -> `ACCLERATE_USE_IPEX`
* `XPU_ENABLED` -> `ACCELERATE_USE_XPU`
Also cleans up CLI so we can properly do:
```bash
accelerate launch --ipex -h
```
CLI changes:
* `--ipex_enabled` -> `--ipex`
* `--xpu_enabled` -> `--use_xpu`
(And since `ipex` and `xpu` are enabled, unless I'm mistaken we should always do `--ipex` when doing `--use_xpu`
cc @sywangyi @abhilash1910 
I did not find any docs to update outside of this change, however the new CLI changes were added to the CLI documentation
> Swap env vars for XPU and IPEX + CLI

- .github/workflows/nightly.yml
- tests/test_cli.py
Adds check for print statement that deepspeed decided to add in the latest version causing a failure in our checking of the CLI outputs 🙃 Linked FR to hopefully make it a logger and not a print statement: https://github.com/microsoft/DeepSpeed/issues/3680
For now thought this can be merged w/o issue
> Fixup deepspeed/cli tests

- src/accelerate/data_loader.py
Replaces the following confusing error:
```python
../accelerate/src/accelerate/data_loader.py:564: in __iter__
observed_batch_size = find_batch_size(batch)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
data = None
def find_batch_size(data):
"""
Recursively finds the batch size in a nested list/tuple/dictionary of lists of tensors.
Args:
data (nested list/tuple/dictionary of `torch.Tensor`): The data from which to find the batch size.
Returns:
`int`: The batch size.
"""
if isinstance(data, (tuple, list)):
return find_batch_size(data[0])
elif isinstance(data, Mapping):
for k in data.keys():
return find_batch_size(data[k])
elif not …
```
> Raise ValueError on iterable dataset if we've hit the end and attempting to go beyond it

- src/accelerate/accelerator.py
- tests/test_accelerator.py
Fixes #1515 
Naive Pipeline Parallelism should be supported by accelerate and should work, if we properly educate users on how to use it. 
It is the simplest paradigm for running a model across multiple GPUs. It tries to evenly fit the model across all available GPUs (e.g. `device_map="auto"`)
Initially I added that check because I was afraid users will train 8bit models that are loaded across multiple GPUs **and** under multi-GPU distributed regime. In that case the model will be converted to DDP (which is fine if the model fits in a single GPU and duplicated across multiple GPUs (Data Parallelism)) - which can lead to many breaking behaviours such as https://github.com/huggingface/peft/issues/269#issuecomment-1498776567 . 
The fix is to relax the check constraint and to also check if we …
> Officially support naive PP for quantized models + PEFT

- docs/source/usage_guides/ipex.mdx
- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/test_utils/scripts/test_script.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/dataclasses.py
- src/accelerate/utils/imports.py
- src/accelerate/utils/launch.py
even we answer "NO" to "Do you want to use Intel PyTorch Extension (IPEX) to speed up training on CPU?" in accelerate config
> fix the issue that ipex is always imported if it's installed in python env.

- src/accelerate/big_modeling.py
When using `load_checkpoint_and_dispatch` with a user provided `device_map`, the function first computes the `max_memory` for each device. This has a side-effect of allocating one tensor, and thus cuda, on each available device, even if the device is not present in the values of the `device_map`.
Since this argument is not used with a user provided `device_map`, this PR simply move the `max_memory` computation out of the execution path, to prevent extra memory allocation on unused devices.
> Prevent using extra VRAM for static device_map

- docs/source/concept_guides/deferring_execution.mdx
These are just a few more minor grammar fixes in deferring_execution.mdx. They do not affect the ideas communicated in the documentation.
> [documentation] minor grammar fixes in deferring_execution.mdx

- src/accelerate/big_modeling.py
- src/accelerate/utils/modeling.py
- tests/test_big_modeling.py
This PR add the support for M1/M2 MacOS to big inference modeling. 
The main highlights of this PR are as follows:
- device_map = 'auto' will now detect mps device if available and set the device_map correctly. Since memory is shared between the GPU and CPU, modules are placed on the MPS device, and if necessary, offloaded to the disk.
- add tests for mps device
Reminder: mps backend can be slower than cpu in some cases.
Fix [#23916](https://github.com/huggingface/transformers/issues/23916)
> Add mps support to big inference modeling

- src/accelerate/accelerator.py
Sets an `evaluation_mode` instead under `prepare_model`, that will let `torch.compile` remain as well.
> Instead go with `evaluation_mode`

- src/accelerate/accelerator.py
- src/accelerate/optimizer.py
Solves double nested wrapping issues linked as a side-effect to https://github.com/huggingface/transformers/issues/24050.
Also resets step to 0 during free_memory
> Avoid double wrapping of all accelerate.prepare objects

- src/accelerate/utils/modeling.py
When there is one device + the disk, the state dict will return everything on the device (instead of putting the disk weights on the CPU). This PR addresses that.
> Fix load_state_dict when there is one device and disk

- .github/workflows/run_merge_tests.yml
- Makefile
It's still... *strange* that the workflows running `make test` (we have a number of them) didn't pick up on https://github.com/huggingface/accelerate/pull/1557... but at least this solves some of it...
> Fix tests not being ran on multi-GPU nightly

- src/accelerate/accelerator.py
Fixes the typo from #1555 (setattr and the corresponding getattr currently use different attribute names, which is a bug)
> fix the typo when setting the "_accelerator_prepared" attribute

- src/accelerate/accelerator.py
- tests/test_accelerator.py
Fixes https://github.com/lvwerra/trl/issues/413 and the current CI in TRL :D https://github.com/lvwerra/trl/actions/runs/5204023029/jobs/9387749684?pr=412 
Before https://github.com/huggingface/accelerate/pull/1555 it was possible to pass `NoneType` objects into prepare and that function would do nothing with it and return it. 
Adding a simple check `if item is not None:`  before setting the `_is_accelerate_prepare` attribute circumvents the bug
cc @sgugger @muellerzr
> [`core`] Fix possibility to pass`NoneType` objects in `prepare`

- src/accelerate/data_loader.py
- src/accelerate/state.py
- tests/test_data_loader.py
The `end_of_dataloader` from the `DataLoaderMixin` is set to `True` at the end of an iter, but never reset to False...
> Reset dataloader end_of_datalaoder at each iter

- tests/test_big_modeling.py
Fixes failing tests in https://github.com/huggingface/accelerate/actions/runs/5217618552/jobs/9417634363 
The new release of transformers includes the 4bit integration, therefore the behavior of `replace_8bit_linear` has been changed to support 4bit and replaced to `replace_with_bnb_linear` method. This PR addresses corresponding changes to properly call this method
cc @muellerzr @sgugger
> [`bnb`] Fix failing int8 tests

- README.md
Update the mixed precision integrations (FP16 with Apex is deprecated so removed it, and it was never actually requested).
> Update mixed precision integrations in README

- src/accelerate/tracking.py
- src/accelerate/utils/__init__.py
- src/accelerate/utils/operations.py
- tests/test_tracking.py
- tests/test_utils.py
Solves https://github.com/huggingface/accelerate/issues/1546 by introducing a utility which will recursively convert all tensors in a dictionary/list of dictionaries/etc/etc into pure lists of digits. This is needed for tensorboard to log, as it also can't take in numpy arrays either (tried this first, to just bring in `numpify` from `transformers`). Should be a useful util in the future however, which is why I decided to bring it out fully rather than just have it specific to tensorboard
> Introduce listify, fix tensorboard silently failing

- src/accelerate/accelerator.py
Solves second part of https://github.com/huggingface/accelerate/issues/1563 by expanding the docstring to `load_state` discussing what can be in the directory, and excludes backup files (`.bak`) when looking at what is loaded/saved in there.
> Check for bak and expand docs on directory structure

- src/accelerate/accelerator.py
- tests/test_accelerator.py
Another solution to our `_is_accelerator_prepared`, checking that the object must be in one of the `self._{type}` that is designated for storing
Solves https://github.com/huggingface/accelerate/issues/1574
> Make sure that we only set is_accelerator_prepared on items accelerate actually prepares

- src/accelerate/utils/torch_xla.py
This fixes the following warning:
> pkg_resources is deprecated as an API
See https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6750
> Get Torch version using  importlib instead of pkg_resources

- docs/source/concept_guides/training_tpu.mdx
> [documentation] grammatical fixes in training_tpu.mdx

- src/accelerate/utils/imports.py
Per discussion in google chat, the logic in the `is_tpu_available` check is incorrect and actually will not allow XLA to be ran at all. The proper check of just "is cuda available, if so return False" is used instead. This can be relied on as this is still a valid check even on a CPU-only build of torch.
> Fix TPU issues and actually initialize the device

- src/accelerate/logging.py
[#1178](https://github.com/huggingface/accelerate/issues/1178)
This pull request addresses an issue where the root logger's default level was set to WARNING, making `log_level` in get_logger out of work.
> fix logger level

- src/accelerate/utils/modeling.py
In current codes, there is a comma for `has_tied_encoder_decoder`, which makes it a tuple rather than bool. Therefore, the result of `check_tied_parameters_in_config` is always `True`.
For example, `has_tied_encoder_decoder = (False,)`
However, `any([False, (False, ), False]) == True`. We should make it a `bool` rather than `tuple[bool]`
> Bug fix for `check_tied_parameters_in_config`

- .github/workflows/integration_tests.yml
- .github/workflows/self_hosted_integration_tests.yml
- .github/workflows/test.yml
Adds integration CI's as we try to catch issues with accelerate breaking main or released versions for core libraries.
Currently just has `transformers`, will eventually add `skorch`.
Built in a way that lets us quickly add in more tests to run. (and whatever other libs we want to add along the way)
Will monitor the runner integration after it's been merged so I can manually run that afterwards, since it relies on our hosted runner.
> Integration tests

- src/accelerate/utils/offload.py
As pointed out by @Narsil , `safetensors` does not use that env variable anymore, so let's remove it and the log that goes with it.
> Remove GPU safetensors env variable

- src/accelerate/data_loader.py
- tests/test_data_loader.py
Reset `end_of_dataloader` to `False` at each iteration as in [PR#1562](https://github.com/huggingface/accelerate/pull/1562) but for the `DataLoaderDispatcher`.
> reset end_of_dataloader for dataloader_dispatcher

- src/accelerate/utils/modeling.py
When only one device is available, there is nothing we can really do to minimize the memory on device 0, so let's just ignore that flag.
Fixes #1614
> Ignore low_zero option when only device is available

- src/accelerate/test_utils/scripts/test_script.py
These particular tests shouldn't be ran on multinode, as the printing etc it relies on is not always able to be recreated well across nodes, and same with the split_between_processes.
Solves https://github.com/huggingface/accelerate/issues/1606
> Fix failing multinode tests

- src/accelerate/accelerator.py
- src/accelerate/utils/dataclasses.py
- tests/test_tracking.py
Fixes an issue where if you passed in a ProjectConfig and a `project_dir` but not a `logging_dir`, the logging_dir wouldn't be set due to th epost_init never being ran. This PR refactors that logic to be a bit more fullproof.
solves https://github.com/huggingface/accelerate/issues/1619
> Fix TensorBoard/logging dir issue

- .github/workflows/build_and_run_tests.yml
- .github/workflows/integration_tests.yml
- .github/workflows/self_hosted_integration_tests.yml
Fixes the nightly and merge workflows from not running.
Proof here: https://github.com/huggingface/accelerate/actions/runs/5338157693
Which also, we currently have a failure on multi-GPU on both main and pypi versions of accelerate, which I'll look at this week.
> Fix workflow

- src/accelerate/accelerator.py
- src/accelerate/state.py
- src/accelerate/utils/dataclasses.py
Adds a new `sync_with_dataloader` arg to the `GradientAccumulationPlugin`, to assist with using it across epochs via `total_batched_samples` (https://github.com/huggingface/transformers/issues/23935#issuecomment-1588134562)
> Fix transformers sync bug with accumulate

- src/accelerate/utils/modeling.py
This PR fixes a problem I had when I tried to offload a tensor to `meta` device using `set_module_tensor_to_device` with a specific dtype. The `dtype` of the meta tensor is not changed by the `dtype` arg. 
When we move back the meta tensor to `cpu` or `cuda`, if we don't indicate the `dtype` ,which is the case when we added the hook, it will take the `dtype` of the `meta` tensor. 
```python
if value is not None:
if dtype is None:
value = value.to(old_value.dtype)
```
> fixes offload dtype

- src/accelerate/accelerator.py
1. Fixes https://github.com/huggingface/transformers/issues/24431
Use `MethodType` to preserve the forward function's signature when the forward is a `method` else skip it if is a `function`.  For example, `model.foward` object is a function when using `device_map` and currently it is leading to `AttributeError: 'function' object has no attribute '__func__'`. This PR fixes it.
> fix autocasting bug

- src/accelerate/utils/modeling.py
#1607 
To fill GPU 0 , I think the remaining should be allocated as max(gpu:0 , remaining model memory) [L636 modeling.py]. (Since gpu:0 was initialized as 0, if we use min(), it will always be 0.). I am thinking this should resolve but want an expert opinion.
@sgugger  @muellerzr  need your review .
> fix modeling low zero

- src/accelerate/big_modeling.py
This PR changes the behavior of the `dispatch_model` function when the `device_map` have only one device. We don't attach the hooks anymore and the user will be able to move the model with `.to()`. This change breaks the case where the `device_map` is `{"":'cpu'}` or `{"":'disk'}` where the hooks will dispatch the weights to the `main_device`. However, this fix will lead to less issues from users who want to use `device_map` as a regular `device` parameter.
> Change dispatch_model when we have only one device

- docs/source/package_reference/utilities.md
- docs/source/quicktour.md
- src/accelerate/accelerator.py
This PR modifies the saving/loading section of Quicktour documentation. It replaces the `save` method by the `save_model` method from `Accelerator` class.
> Doc save model

- src/accelerate/utils/__init__.py
- src/accelerate/utils/launch.py
- src/accelerate/utils/other.py
Helps https://github.com/huggingface/accelerate/issues/1649 by checking under the following circumstances:
- If a user has multiple `accelerate launch` they wish to perform and is training on multi-GPU (or deepspeed)
- See if the connection port `torch.distributed` relies on for communication is already in use
- If so, direct them to specify a different communication port
This directly helps catch the following error before it occurs:
```python
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
```
And replaces it with:
```python
File …
```
> Check for port usage before launch
