examples/nlp_example.py
We are using `accelerator.distributed_type` in our `collate_fn` but the `accelerator` is defined later.
=> Fix TPU training in example

docs/source/quicktour.rst, examples/README.md, examples/cv_example.py, examples/nlp_example.py, src/accelerate/accelerator.py, src/accelerate/commands/launch.py, src/accelerate/data_loader.py, src/accelerate/optimizer.py, src/accelerate/test_utils/test_script.py, src/accelerate/utils.py
This PR adds a computer vision example, using timm and torchvision.
Some files are touched by the styling (forgot to do it in the last PRs and there is no CI to yell at me yet).
Tested on single process, multi-GPU and TPU.
=> Add CV example

README.md
I recently discovered you can have a \`\`\`diff, so trying it for a spin hear.
=> Alternate diff

docs/source/index.rst, docs/source/launcher.rst, docs/source/quicktour.rst, src/accelerate/__init__.py, src/accelerate/commands/launch.py, src/accelerate/notebook_launcher.py, src/accelerate/utils.py
This PR adds a notebook launcher function, to easily launch training in a Colab with TPUs.
having it properly launch distributed training in a Notebook on a machine with several GPUs seems a bit less straightforward, so support will be added later if there interest from the community.
Notebook examples will follow!
=> Notebook launcher

src/accelerate/data_loader.py
Possible fix for https://github.com/huggingface/accelerate/issues/61
=> Fix batch_sampler error for IterableDataset

examples/README.md
```diff
-pip install timm, torchvision
+pip install timm torchvision
```
=> Fix examples README

README.md
it would be nice if names of `torch.optim.Adam` instances in README.md are consistent.
=> Use `optimizer` for consistency

src/accelerate/accelerator.py
This PR adds a new method to the `Accelerator` class to unscale the gradients, which is necessary before doing some operations like gradient clipping (also supported in its own method currently, but some users might have more exotic strategies).
=> Add `unscale_gradients` method.

docs/source/quicktour.rst
This PR adds documentation on weight-tying on TPUs and the fact it gets broken.
=> Add caveat on weight-tying on TPUs

docs/source/index.rst, docs/source/quicktour.rst
This PR documents a little bit more the DeepSpeed experimental integration.
=> DeepSpeed documentation

src/accelerate/utils.py
Right now, using `accelerator.gather` on 0d tensors will fail since the tensors can't be concatenated from each process. This PR fixes that by adding a new dimension in that case.
=> Fix gather for 0d tensor

src/accelerate/data_loader.py
This PR puts back errors when warnings where set for a quick debug, with a better check.
=> Raise errors instead of warnings with better tests

README.md, src/accelerate/notebook_launcher.py
* Updates the README with a reference to a high-level API built on top of Accelerate
* Fixes a small type in the notebook launcher's log statement
=> Add high-level API reference to README

src/accelerate/data_loader.py
As pointed out in #209 the `drop_last` kwarg was not properly passed to the `DispatchDataLoader`. This PR fixes that.
Fixes #209
=> Pass along drop_last in DispatchDataLoader

src/accelerate/optimizer.py
#220 
This pull request tries to solve the abovementioned issue. It renames the original `state` attribute to `accelerator_state` and then have a property that returns the inner optimizer state when a user tries to access the state attribute.
=> Rename state to avoid name conflicts with pytorch's Optimizer class.

examples/nlp_example.py
This PR fixes the length of the LR scheduler in the NLP example, as pointed out in #225.
Fixes #225
=> Fix lr scheduler num samples

docs/source/installation.md
This PR fixes a small mistake in the installation docs.
=> Fix typo in installation docs

src/accelerate/utils.py
=> add support of gather_object

README.md
Hi guys, nice project!
After recent experiments with accelerate, I found it very close to my own "torch-backend" ideas, so... I decided to move a couple of frameworks to accelerate.
tl;dr
- Catalyst is based on Accelerate starting from [v22 edition](https://github.com/catalyst-team/catalyst/releases/tag/v22.02rc0)
- Animus - from [v0.0.1](https://github.com/Scitator/animus)
- Animus & Catalyst added to readme/frameworks section
- frameworks sorted alphabetically (it's easier to navigate)
✌️
=> Accelerate + Animus/Catalyst = 🚀 

src/accelerate/__init__.py, src/accelerate/launchers.py, src/accelerate/state.py, src/accelerate/utils.py, tests/test_cpu.py, tests/test_utils.py
This PR adds support for a `debug_launcher` will allows the user to launch a function in a distributed fashion on CPU for quick debugging. It will also let us test more extensively the library in the CI.
More tests will follow in subsequent PRs :-)
=> Add  `debug_launcher`

src/accelerate/utils.py
=> enhance compatibility of honor type

src/accelerate/accelerator.py, src/accelerate/utils.py
Closes https://github.com/huggingface/accelerate/issues/236
=> Ability to set the seed with randomness from inside Accelerate

docs/source/_toctree.yml, docs/source/checkpoint.mdx, docs/source/quicktour.mdx
Adds documentation to the new checkpointing capabilities
=> Document save/load state

src/accelerate/accelerator.py, src/accelerate/commands/launch.py, src/accelerate/launchers.py, src/accelerate/utils.py
Seperates out the precision types to its own enum for auto-complete and code simplicity
=> Refactor precisions to its own enum

examples/README.md, examples/complete_cv_example.py, examples/complete_nlp_example.py, examples/cv_example.py, examples/nlp_example.py
Start of updating the example scripts to use both the save/load_state and tracking
=> Update example scripts

src/accelerate/commands/config/cluster.py
cc @sgugger , let me know if I got this logic right/understanding this correctly. Should be a better solution than the previous PR
=> Better prompt for number of training devices

src/accelerate/commands/config/cluster.py
1. Fixes the placeholder in case of MULIT_GPU, MULTI_CPU and TPU.
2. Adds support of num_processes for FSDP and DeepSpeed.
=> Fix prompt for num_processes

examples/by_feature/fsdp_with_peak_mem_tracking.py, examples/by_feature/multi_process_metrics.py, examples/complete_cv_example.py, examples/complete_nlp_example.py
1. Fixing off by 1 issue during metric evaluation in distributed setup.
=> Fixing metric eval in distributed setup

src/accelerate/accelerator.py
=> deepspeed save model temp fix

src/accelerate/data_loader.py
fixes https://github.com/huggingface/accelerate/issues/375
cc @sgugger
=> fix shuffling for ShufflerIterDataPipe instances

.github/workflows/stale.yml, utils/stale.py
Adds a stalebot workflow mimicking the transformers one
=> Introduce stalebot 

.github/workflows/stale.yml
Small bugfix, also let's it be workflow_dispatch to let me run it manually
cc @sgugger
=> Small bugfix for the stalebot workflow

src/accelerate/utils/offload.py
This PR refactors the `offload_state_dict` function using the two new utils introduced in #380 and fixes a small bug in one of them.
=> Refactor offload_state_dict and fix in offload_weight

docker/accelerate-cpu/Dockerfile, docker/accelerate-gpu/Dockerfile
This PR makes the Dockerfile install git in the final user image, as it's currently not present and is needed for the CI. 
The CI operates on checking out the current commit and running the tests, as a result git was needed.
=> Fix CUDA Dockerfile

setup.py
This PR fixes issues with the installed version of tensorflow, missing tensorboard, and includes `psutil` in the base requirements.
I was noticing my Docker tests were failing due to missing dependencies or a mismatch of dependency versions, this PR fixes them.
=> Update requirements to pin tensorboard and include psutil

docker/accelerate-gpu/Dockerfile
Small bug in the Dockerfile I forgot to remove once I had finished testing.
=> Use main egg instead of old branch

examples/by_feature/README.md, examples/by_feature/gradient_accumulation.py, tests/test_examples.py
This PR introduces an example showcasing the new `Accelerator.no_sync` capability through using it on gradient accumulation
=> Create Gradient Accumulation Example

docs/source/accelerator.mdx, docs/source/big_modeling.mdx, docs/source/checkpoint.mdx, docs/source/fsdp.mdx, docs/source/index.mdx, docs/source/installation.mdx, docs/source/quicktour.mdx, docs/source/sagemaker.mdx, docs/source/tracking.mdx, docs/source/utilities.mdx
Had a look at the docs, and figured I might as well ;)
=> Some typos and cosmetic fixes to the docs

setup.py
Reverts huggingface/accelerate#477
=> Revert "Pin datasets for now"

docs/source/_toctree.yml, docs/source/gradient_accumulation.mdx
Adds a doc for gradient accumulation for the next release. It's a carbon copy of the one in #505.
=> Add gradient accumulation doc

src/accelerate/accelerator.py, src/accelerate/utils/operations.py
return reduced result of a tensor
=> Fix a bug when reduce a tensor.

src/accelerate/accelerator.py
I think this is a simple fix for #285 
I haven't test this. Just looking for feedback first.
=> Don't unwrap in save_state()

src/accelerate/commands/test.py
As the title indicates, fix `accelerate test` which tries to run a script that has moved :-)
=> Fix accelerate tests command

src/accelerate/big_modeling.py
After seeing many issues of users struggling with the `offload_state_dict` argument, I've decided to let it default to `None` and pick a default depending on the computed device map (`True` if there are weights offloaded to disk, `False` otherwise).
The same is being implemented in Transformers [here](https://github.com/huggingface/transformers/pull/18183).
=> Pick a better default for offload_state_dict

src/accelerate/utils/imports.py
=> Update new torch_ccl name in imports.py

.github/workflows/check_dependencies.yml, .github/workflows/nightly.yml
Renames the stages in the github actions to be a bit more accurate on what is being ran
=> Rename actions to be a bit more accurate

src/accelerate/state.py, src/accelerate/utils/__init__.py, src/accelerate/utils/imports.py
Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>
=> ccl version check and import different module according to version

examples/by_feature/checkpointing.py, examples/by_feature/fsdp_with_peak_mem_tracking.py, examples/by_feature/gradient_accumulation.py, examples/by_feature/memory.py, examples/by_feature/multi_process_metrics.py, examples/by_feature/tracking.py, src/accelerate/test_utils/examples.py, tests/test_examples.py
Duplicate of https://github.com/huggingface/accelerate/pull/548 with the right commit history + fixes the diff checker
=> Speed up main CI

tests/test_examples.py
=> Accidently broke multigpu tests

src/accelerate/utils/modeling.py
It turns out that `to` converts a parameter to a tensor, so the else branch that was added in #539 breaks a lot of things 😬 
This PR fixes that.
cc @younesbelkada
=> Fix `set_module_tensor_to_device`

src/accelerate/utils/modeling.py
Some tensors end up not being set with the recent changes in `set_module_tensor_to_device`. This should fix the issue.
=> Refine test in set_module_tensor_to_device

src/accelerate/commands/launch.py
1. FSDP launcher fix when not using a config file.
=> minor FSDP launcher fix

src/accelerate/accelerator.py
Makes the docstring aligned with the rest of the `on_*_process` docstrings
=> Improve docstring for on_local_process

setup.py
Pins deepspeed for now as their latest pypi release has broken the CI installation. 
Deepspeed issue: https://github.com/microsoft/DeepSpeed/issues/2166
=> Pin deepspeed

src/accelerate/commands/launch.py
Noticed that these didn't quite get fixed properly before the merge happened
=> Improve warning

docs/source/usage_guides/gradient_accumulation.mdx
Closes https://github.com/huggingface/accelerate/issues/616
=> Fix grad accum example in docs

src/accelerate/commands/launch.py, src/accelerate/utils/launch.py
Fixes the multi-gpu logic raised [here](https://github.com/huggingface/accelerate/pull/626/files) and also simplifies how args are setup for the namespace object
=> Fix multi-node issues and simplify param logic

docs/source/usage_guides/mps.mdx
=> update MPS support docs

src/accelerate/commands/launch.py
Puts back in the import guard for torchrun
=> Put back in place the guard

src/accelerate/utils/dataclasses.py
supported by https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html
This is particularly useful when using gradient checkpointing
See https://discuss.pytorch.org/t/ddp-and-gradient-checkpointing/132244/3 for more details
=> Add static_graph arg to DistributedDataParallelKwargs.

docs/source/concept_guides/gradient_synchronization.mdx, docs/source/usage_guides/gradient_accumulation.mdx
Emphases more on how you should use either of the two API's we provide, and links to the grad synchronization tutorial at the end of the grad accum to advertise learning about the magic it wraps around
=> Small nits to grad accum docs

README.md
1. Add bibtex for `Accelerate` so that folks can cite it.
2. Resolves #658
=> accelerate bibtex

docs/source/usage_guides/big_modeling.mdx, manim_animations/big_model_inference/stage_1.py, manim_animations/big_model_inference/stage_2.py, manim_animations/big_model_inference/stage_3.py, manim_animations/big_model_inference/stage_4.py, manim_animations/big_model_inference/stage_5.py
Adds an animation of big model inference directly to the docs, along with the code to create it. 
Animation is live [here](https://www.youtube.com/watch?v=MWCSGj9jEAo)
=> Manim animation of big model inference

setup.py, src/accelerate/__init__.py, src/accelerate/commands/launch.py, src/accelerate/utils/__init__.py, src/accelerate/utils/imports.py, src/accelerate/utils/rich.py
Moves rich out from a mandatory dep to an optional dep, as discussed offline
=> Make rich an optional dep

src/accelerate/commands/config/cluster.py
Specifies that answering "no" means that the computers are on the cloud and/or on different network hosts
=> Specify local network on multinode

src/accelerate/data_loader.py
As pointed out in #682 after its merge, there is a bit more code that can be cleaned up.
=> Clean up DispatchDataloader a bit more

src/accelerate/data_loader.py
It is possible to use a `DataLoader` with a batch sampler given as a sampler, to access dataset indices all together instead of one at a time. In this case, Accelerate should change this batch sampler and not the one on top of it.
Fixes #679
=> Fix DataLoader with samplers that are batch samplers

.github/workflows/test.yml, Makefile, src/accelerate/test_utils/scripts/test_script.py, utils/log_reports.py
Generates a report of failures when they occur on the job summary page. 
See an example here: https://github.com/huggingface/accelerate/actions/runs/3085436367/attempts/1#summary-8436903677
=> Add in report generation for test failures

examples/by_feature/cross_validation.py, examples/by_feature/deepspeed_with_config_support.py, examples/by_feature/memory.py
Some small readability fixups in `examples/by_feature`
=> docs: examples readability improvements

utils/style_doc.py
Small, one-off cleanups in `utils`
=> docs: `utils` readability fixups

docs/source/_toctree.yml, docs/source/concept_guides/deferring_execution.mdx, docs/source/concept_guides/performance.mdx
Given we've had **so many issues** about this topic, this adds a concept guide on the subject. Let me know if I seem to have missed any, but these are the main three I've observed
https://github.com/huggingface/accelerate/issues/526 https://github.com/huggingface/accelerate/issues/59#issuecomment-1167814595
=> Add a tutorial on proper benchmarking

docs/source/usage_guides/training_zoo.mdx
=> Add trlx to the zoo

.github/workflows/test.yml
Noticed that changing an example didn't run the CI, this fixes it
=> Include examples for CI

src/accelerate/commands/config/cluster.py
Would recommend a patch release on pypi, sorry!
=> Fix num_processes is not defined

src/accelerate/commands/launch.py
Adds a few more defaults for when reading in configs/args as stated in https://github.com/huggingface/accelerate/issues/770
=> Add defaults for launchers

docs/source/package_reference/cli.mdx, src/accelerate/commands/launch.py
Fulfills missing param not found in `launch` brought up in https://github.com/huggingface/accelerate/issues/770#issuecomment-1284295259, also working on a PR in with tests for checking that all possible args can be passed to the CLI manually soon
=> Add same_network to CLI args and update docs

src/accelerate/launchers.py
=> Kaggle + Notebook Launcher!

src/accelerate/big_modeling.py
This PR makes it possible to run `dispatch_model` with `device_map="auto"` on CPU-only envs. It has been tested for models that fit on the CPU, but not with offload to disk (which should work in theory, but there might still be bugs).
Making sure the offload to disk works on a CPU-only env is going to be further work however and go in another PR.
Fixes #796 
cc @patrickvonplaten
=> Fix device_map="auto" on CPU-only envs

src/accelerate/commands/launch.py
=> fix: add pdsh as default launcher

src/accelerate/accelerator.py
Details are in #801.
cc @sgugger
=> Deal with optimizer.differentiable in PyTorch 1.13.0

src/accelerate/optimizer.py, tests/test_optimizer.py
=> adding support to pickle and unpickle `AcceleratedOptimizer`

src/accelerate/accelerator.py, src/accelerate/commands/launch.py, src/accelerate/launchers.py
Acts on deprecations labelled to be removed in 0.13.0, and adds fp16 to be removed in 0.15.0 (one full `0.X.0` after the next)
=> Act on deprecations

docs/source/usage_guides/tracking.mdx, docs/source/usage_guides/training_zoo.mdx
A few missing doc portions that needed updating prior to 0.14.0
=> Some final doc nits before release

src/accelerate/commands/config/cluster.py, src/accelerate/commands/config/config_args.py, src/accelerate/commands/tpu.py, tests/test_configs/latest.yaml
Small change to let multiple commands be passed during config
=> Rename command to be commands and allow for multiple commands to be entered during setup

src/accelerate/accelerator.py, src/accelerate/commands/config/cluster.py, src/accelerate/commands/config/config_args.py, src/accelerate/commands/config/config_utils.py, src/accelerate/commands/config/sagemaker.py, src/accelerate/commands/launch.py, src/accelerate/state.py, src/accelerate/utils/__init__.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/other.py
This PR adds support for torch dynamo, which for now consists in wrapping the model in `dynamo.optimize`. So most of the PR is boilerplate to have everything setable with the config or args in the launcher.
Not adding any documentation yet as it's still very experimental and the underlying API might move a bit, this is mainly for internal use to be able to quickly benchmark things.
=> Add support for torch dynamo

src/accelerate/commands/config/cluster.py
1. FIx bugs in new CLI changes
=> FIx bugs in new CLI changes

src/accelerate/commands/menu/helpers.py, src/accelerate/commands/menu/selection_menu.py
Per request, highlights the selected choice in green like so:
=> Highlight selection with pretty colors

docs/source/package_reference/cli.mdx, setup.py, src/accelerate/commands/accelerate_cli.py, src/accelerate/commands/config/__init__.py, src/accelerate/commands/config/default.py
Brings in a `accelerate default-config` command to close https://github.com/huggingface/accelerate/issues/833.
=> Introduce `default-config` command

examples/complete_cv_example.py
Fixes https://github.com/huggingface/accelerate/issues/844
There was one regression in the examples that did not get trickled up between `cv_example` and `complete_cv_example` for calculating the metrics.
=> Fix complete_cv example regression

docs/source/package_reference/cli.mdx, src/accelerate/commands/config/__init__.py, src/accelerate/commands/config/config.py, src/accelerate/commands/config/config_utils.py, src/accelerate/commands/config/default.py, src/accelerate/commands/config/update.py
* Clean up, add update command
* Use args for all but default_config
* Call explicitly with args
* Update CLI docs
=> Clean up, add update command (#853)

src/accelerate/accelerator.py
Co-Authored-By: Stas Bekman <stas00@users.noreply.github.com>
1. address point 2 of comment https://github.com/huggingface/accelerate/pull/676#issuecomment-1317990966
=> update deepspeed error message wrt `batch_size`

src/accelerate/accelerator.py, tests/deepspeed/test_deepspeed.py
1. Fixes a failing deepspeed test, thanks to DeepSpeed team to bring this to our notice.
=> fix failing deepspeed test

src/accelerate/utils/dataclasses.py, tests/fsdp/test_fsdp.py
=> fix fsdp state_dict_config because of PyTorch changes

src/accelerate/accelerator.py
1. fixing remaining lr scheduler issues for pytorch nightly (1.14.0.dev)
=> fixing remaining lr scheduler issues for pytorch nightly

tests/deepspeed/test_deepspeed.py, tests/fsdp/test_fsdp.py
1. fix prefix issues in tests introduced #890
=> fix prefix issues in tests

src/accelerate/utils/dataclasses.py
Closes https://github.com/huggingface/accelerate/issues/870 by adding usage examples for each of the `KwargHandler` subclasses
=> Add usage examples

src/accelerate/accelerator.py, src/accelerate/utils/dataclasses.py
=> fsdp enhancements

src/accelerate/accelerator.py, src/accelerate/commands/launch.py, src/accelerate/launchers.py, src/accelerate/test_utils/scripts/test_script.py, tests/test_examples.py
- `--fp16` should be `--mixed_precision="fp16"`
- `Accelerator(fp16=True)` should be `Accelerator(mixed_precision="fp16")`
- `--use_mps_device` should be `--mps`
=> 🚨🚨🚨 Act on deprecations 🚨🚨🚨

src/accelerate/accelerator.py, src/accelerate/state.py
1. add `mixed_precision` property to `AcceleratorState`.
=> add `mixed_precision_type` property to `AcceleratorState`

src/accelerate/accelerator.py
1. Fixes bugs introduced in #935
=> fix mp related test fails

src/accelerate/commands/launch.py
=> support master port when using ds multi-node launcher

tests/test_tracking.py
Skips failing wandb test until they can help us analyze their new logs
=> Skip wandb test for now

src/accelerate/scheduler.py, src/accelerate/test_utils/scripts/test_sync.py
Fix https://github.com/huggingface/accelerate/issues/963 issue
=> Fix scheduler incorrect steps when gradient accumulation enabled

src/accelerate/accelerator.py, src/accelerate/utils/deepspeed.py
This PR
- improves the explanation of what happens during `engine.step` (deepspeed)
- fixes some typos
=> improve deepspeed notes

docs/source/usage_guides/explore.mdx
Makes dark or light theme work with the gradio demo
=> Light vs dark theme based on pick

src/accelerate/accelerator.py, src/accelerate/big_modeling.py, src/accelerate/hooks.py, src/accelerate/launchers.py, src/accelerate/utils/memory.py, src/accelerate/utils/modeling.py, src/accelerate/utils/offload.py, src/accelerate/utils/operations.py, src/accelerate/utils/other.py, src/accelerate/utils/random.py, src/accelerate/utils/torch_xla.py
Includes the rest of the docstring examples where needed on the major API parts of the codebase.
**Should not be merged until after** #1002
=> More improvements to docstrings + examples

src/accelerate/commands/launch.py
1. Fixes: #980 .
2. Specifically , the issue is mentioned in comment: https://github.com/huggingface/accelerate/issues/980#issuecomment-1407814122
=> sagemaker launcher fixes

.github/workflows/nightly.yml, utils/log_reports.py
Introduces a slackbot that posts in #accelerate-ci-daily with the status of how the nightly tests ran each day.
=> Add daily slack notifier for nightlies

src/accelerate/commands/launch.py
Closes https://github.com/huggingface/accelerate/issues/1078, and is reported that the solution works. Will merge after https://github.com/huggingface/accelerate/pull/1080 so that I get the merge-conflict headaches and not the community contributor 🤗
=> Fix tpu_cluster arg for sagemaker config

src/accelerate/commands/launch.py
Closes https://github.com/huggingface/accelerate/issues/996
=> Actually raise if exception

src/accelerate/commands/launch.py
Tentatively solves https://github.com/huggingface/accelerate/issues/1116
Arguably, would it be better to raise an assert here instead? It's mildly caught earlier via another check, however it may be better to do a full assert here instead.
=> Fix multinode with GPU ids when each node has 1

src/accelerate/accelerator.py
1. Fixes #1101 
2. Fixes #1136
=> deepspeed dataloader prepare fix

src/accelerate/state.py
=> fix ds dist init kwargs issue

src/accelerate/accelerator.py
1. Parity with https://github.com/huggingface/transformers/pull/21847
=> fsdp bf16 enable autocast

docs/source/usage_guides/fsdp.mdx, src/accelerate/accelerator.py, src/accelerate/commands/config/cluster.py, src/accelerate/utils/dataclasses.py
1. Adds support for multiple transformer class layer wrapping to be in sync with latest changes in Trainer FSDP support.
2. `limit_all_gathers` is supported from 1.13 torch version, fixing that to be backward compatible
=> FSDP enhancements and fixes

src/accelerate/accelerator.py, src/accelerate/commands/config/cluster.py, src/accelerate/commands/config/config_args.py, src/accelerate/commands/config/config_utils.py, src/accelerate/commands/config/default.py, src/accelerate/commands/config/sagemaker.py, src/accelerate/commands/launch.py, src/accelerate/state.py, src/accelerate/utils/__init__.py, src/accelerate/utils/constants.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/launch.py
1. update support for torch dynamo compile
=> update support for torch dynamo compile

src/accelerate/accelerator.py, tests/test_state_checkpointing.py
Closes https://github.com/huggingface/accelerate/issues/1163 by adding in a more explicit regex to help with sorting.
=> Fix what files get deleted through `total_limit`

src/accelerate/commands/test.py
`accelerate test` errors out on main, this fixes it.
=> Fix accelerate test with new config_file errors

src/accelerate/hooks.py
This PR adds a repr to AlignHook, which makes life easier for debugging issues with big model inference.
=> Add repr to AlignHook for easier debugging.

src/accelerate/utils/modeling.py
This PR will go along with [PR to come in Transformers] that fixes big model inference for T5 models. T5 models now have some weights that are kept in float32, which interferes with the computation done by `infer_auto_device_map`. On my setup, it gets me OOM when trying to load any big T5 model.
To fix that, on the Accelerate side we now accept a new argument `special_dtypes` which maps weight names to dtypes to use (and for the others we use the `dtype` provided).
=> Support special mapping of dtypes when preparing device map

src/accelerate/accelerator.py, src/accelerate/utils/dataclasses.py
=> add `use_orig_params` to FullyShardedDataParallelPlugin

src/accelerate/commands/launch.py
associated with issue #1217 
fix bug in loading custom config file in `accelerate launch` by adding 
```python
if (args.multi_gpu and args.num_machines is None):
args.num_machines = defaults.num_machines
```
in `/command/launch.py` line 805
=> Fix bug in loading launch config

src/accelerate/utils/dataclasses.py, tests/deepspeed/test_deepspeed.py
=> backfill ds plugin attributes when using ds_config

docs/source/basic_tutorials/notebook.mdx
Helps https://github.com/huggingface/accelerate/issues/1242
=> Change multinode to multigpu in notebook tutorial

src/accelerate/accelerator.py
=> raise error when dataloader with None as batch_size when using DS

src/accelerate/commands/config/default.py, src/accelerate/commands/config/sagemaker.py, src/accelerate/commands/launch.py
Solves https://github.com/huggingface/accelerate/issues/1275
=> Add missing FP8 options to CLI

src/accelerate/data_loader.py
Minor bug fix in def total_dataset_length()
=> Bug fix in setattr

src/accelerate/state.py
1. Uses DeepSpeed comm for initializing distributed setup when using DeepSpeed. This resolves the world size issues when using accelerate PartialState in Trainer with zero stage 3 + zero_init. This PR needs to be merged before https://github.com/huggingface/transformers/pull/22921
=> using deepspeed.comm for distrbiuted init

src/accelerate/test_utils/scripts/test_script.py
Found a lingering txt file from the process first tests, deletes it after the tests are done to not pollute the local git repo
=> delete textfile after tests are done

src/accelerate/accelerator.py
1. Changes to be made for integrating accelerate in Transformers
=> changes required for DS integration

src/accelerate/accelerator.py
1. Fixes https://github.com/huggingface/accelerate/pull/1406#issuecomment-1542848943
2. Changing the default of `zero_force_ds_cpu_optimizer` to True
3. Changing the max lr logic of the scheduler  in ds config
=> fix deepspeed failing tests

src/accelerate/accelerator.py
Fix for https://github.com/huggingface/diffusers/issues/3411 and #1420 owing to ipex changes for cpu.  (prelims seem ok )
cc for additional tests: @muellerzr
=> Fix bug on ipex for diffusers

src/accelerate/utils/modeling.py
fixed: ZeroDivisionError: division by zero
for: https://github.com/deep-floyd/IF/issues/104#issuecomment-1542613470
=> fixed: ZeroDivisionError: division by zero

src/accelerate/checkpointing.py
When resuming from a checkpoint, only the model will be loaded to different GPUs, which might cause OOM.
Background: 
I encounter an OOM error when attempting to resume training ControlNet from a checkpoint using 4 GPUs 12GB each. After making modifications to the code, this error (OOM) has been fixed.
=> fix potential OOM when resuming with multi-GPU training

src/accelerate/utils/modeling.py
This PR adds a few fixes for the issues mentioned in #1425.
=> Fixes in infer_auto_device_map

docs/source/usage_guides/distributed_inference.mdx
Someone pointed out to me I was missing moving the pipeline to the right device 😅 😓
=> Add to() on the pipeline (inference documentation)

docs/source/basic_tutorials/launch.mdx, docs/source/usage_guides/distributed_inference.mdx
Updates the distributed inference docs to a: show how to use `accelerate launch`, and b: update to include the change in #1452
=> Update with cli instructions

src/accelerate/logging.py
Ads `in_order` argument that defaults to `False`, to log in order.  It really helps with readability.  Defaults to false to not break backwards comp.
=> Adds `in_order` argument that defaults to False, to log in order.

src/accelerate/state.py
init_process_group() got multiple values for argument 'backend'
=> fix error for CPU DDP using trainer api.

src/accelerate/state.py
Simplify device selection in state for xpus & cpus  (also avoid certain boundary cases for xpu)
cc @muellerzr
=> Refactor and simplify xpu device in state

src/accelerate/state.py
Ensures sagemaker can be ran without environmental variables, as once the trainer gets involved this cannot be relied on
=> Imrpove sagemaker

src/accelerate/test_utils/scripts/test_script.py
Small oops, tensors need to be moved to device that we want to compare with.
=> Move to device during tests

docs/source/package_reference/cli.mdx, src/accelerate/commands/launch.py
Should solve https://github.com/huggingface/accelerate/issues/1489
=> Add rdzv-backend

README.md
Add torchkeras reference. Maybe someone will like this cute tool.
=> add torchkeras reference

src/accelerate/accelerator.py
This PR let's `gather_for_metrics` always run its check, so that if for any reason the user needs to calculate metrics or some other item and is in a situation where `distributed=False`, they can still cut-off the remainder/padding in the DataLoader automatically.
This directly fixes a failing test in the trainer dataloader integration (currently in progress):
Allows for this:
```python
if loss is not None:
losses = self._nested_gather(loss.repeat(batch_size))
losses_host = losses if losses_host is None else torch.cat((losses_host, losses), dim=0)
```
To become this:
```python
if loss is not None:
losses = self.accelerator.gather_for_metrics((loss.repeat(batch_size)))
```
(Note how the trainer uses `loss.repeat`, this was the issue at hand)
=> Let gather_for_metrics always run

src/accelerate/state.py, src/accelerate/utils/imports.py
also when cpu flag is set. should use cpu instead of XPU
=> fix crash when ipex is installed and torch has no xpu

docs/source/usage_guides/deepspeed.mdx
This pull request contains minor grammatical changes to a documentation file that do not effect the ideas communicated in the document.
=> [documentation] grammatical fixes for deepspeed.mdx

docs/source/concept_guides/performance.mdx
This pull request contains minor grammatical fixes for performance.mdx. There are also a couple misspelled words which have been corrected. The ideas communicated in the file have not changed.
=> [documentation] fixes for grammar & typos in performance.mdx

docs/source/concept_guides/deferring_execution.mdx, docs/source/concept_guides/gradient_synchronization.mdx
=> [documentation] grammar fixes in gradient_synchronization.mdx

docs/source/basic_tutorials/migration.mdx
=> [documentation] minor grammatical fixes in migration.mdx

docs/source/basic_tutorials/launch.mdx
=> [documentation] grammatical fixes to launch.mdx

README.md
=> [documentation] grammatical fixes in README.md

docs/source/usage_guides/big_modeling.mdx
=> [documentation] grammatical fixes in big_modeling.mdx

src/accelerate/test_utils/scripts/test_script.py
Solves https://github.com/huggingface/accelerate/issues/1573 by changing the test to:
- Properly give us an extra remainder/odd one
- Use `wait_for_everyone` for a clear trace on what happens if that test fails
- Properly convert the output to a list for the expected output when 4 GPUs are used
(Verified on 4x T4)
=> Solve failing test on 4 GPU

docs/source/usage_guides/checkpoint.mdx
=> [documentation] grammatical fixes to checkpoint.mdx

.github/workflows/build_and_run_tests.yml, .github/workflows/nightly.yml, .github/workflows/test.yml
Forgot to add the triggers, pretty sure the `RUN_SLOW=yes` will trickle down through the workflows, will see how the nightly does to check if they're being called.
=> Add triggers for CI workflow

src/accelerate/commands/config/cluster.py
This PR removes asking for XPU plugin when user does not choose xpu devices .
@sgugger @muellerzr
=> Remove asking xpu plugin for non xpu devices

src/accelerate/utils/modeling.py
Addresses #1612  for arc gpus . (Could not find any other arc specific invocation) 
@sgugger
=> Fix for arc gpus

src/accelerate/utils/imports.py
The megatron package name is mismatch with dist directory name.
Issue: [1635](https://github.com/huggingface/accelerate/issues/1635)
=> fix: Megatron is not installed. please build it from source.

src/accelerate/big_modeling.py
Fixes an issue reported [here](https://github.com/huggingface/accelerate/pull/1648#issuecomment-1610178618)
=> fix dispatch_model

.github/workflows/quality.yml, .github/workflows/stale.yml, .github/workflows/test.yml, README.md, setup.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/imports.py, src/accelerate/utils/torch_xla.py, src/accelerate/utils/versions.py
Updates the code to use python 3.8
=> 🚨🚨🚨 Spring cleaning: Python 3.8 🚨🚨🚨

.github/workflows/test.yml, README.md, docker/accelerate-cpu/Dockerfile, setup.py, src/accelerate/accelerator.py, src/accelerate/big_modeling.py, src/accelerate/commands/launch.py, src/accelerate/data_loader.py, src/accelerate/optimizer.py, src/accelerate/test_utils/scripts/test_ops.py, src/accelerate/test_utils/scripts/test_script.py, src/accelerate/utils/__init__.py, src/accelerate/utils/imports.py, src/accelerate/utils/launch.py, src/accelerate/utils/modeling.py, src/accelerate/utils/operations.py, tests/test_big_modeling.py, tests/test_grad_sync.py, tests/test_hooks.py, tests/test_kwargs_handlers.py, tests/test_metrics.py, tests/test_modeling_utils.py, tests/test_multigpu.py, tests/test_offload.py, tests/test_state_checkpointing.py
Removes a healthy chunk of code as we move to support a minimum of torch 1.10 from now on :)
(Set everyone to review so we're all aware!)
=> 🚨🚨🚨 Spring cleaning: PyTorch 1.10 🚨🚨🚨

docs/source/package_reference/accelerator.md
=> Add docs for saving Transformers models

.github/workflows/nightly.yml, tests/test_examples.py
Solves the issue of the failing nightly by checking for the right dictionary to be parsed, and ignoring other outputs (the cause of the issue)
=> Fix nightly tests

src/accelerate/commands/menu/selection_menu.py
Fixes for issue #1683: failed to run accelerate config in colab
=> Fixes for issue #1683: failed to run accelerate config in colab

src/accelerate/data_loader.py
Follow up to https://github.com/huggingface/accelerate/pull/1709, which did not include guards for when the torch version is `< 2.0.1`, which is the version that introduced this (see [here](https://github.com/pytorch/pytorch/commit/f1a6f32b72b7c2b73277f89bbf7e7459a400d80a))
=> Keep old behavior on dispatch dataloader

src/accelerate/data_loader.py
There's a failing multi-GPU test currently from the prior PR because after `stop_iteration` we need to set `self.remainder` to `observed_batch_size`, which is critical. Upon thinking about this more, I came to a conclusion that this logic is better suited to live inside the mixin, as its designed specifically for bits such as this. As a result `DataLoaderStateMixin` gets two new functions: `begin()` and `end()`, which replicate the same logic done in the `DataLoader` class, but as their more internal (such as using private functions), it makes more sense to keep them in here. If we want to keep the current behavior and un-isolate, do let me know.
=> Add `begin` and `end` setup/teardown to mixin, fix test

docs/source/usage_guides/training_zoo.md
1. add Comfy-UI to library zoo to showcase the usage of Accelerate
=> add Comfy-UI to library zoo to showcase the usage of Accelerate

src/accelerate/optimizer.py, tests/test_optimizer.py
Follow up of #1714 . This avoids constantly synchronization between cpu and gpu
=> Get rid of calling get_scale() by patching the step method of optimizer.

src/accelerate/utils/modeling.py, tests/test_modeling_utils.py
=> Adding a shape check for `set_module_tensor_to_device`.

src/accelerate/optimizer.py
https://github.com/huggingface/accelerate/pull/1720#issuecomment-1637219672
=> Fix errors when optimizer is not a Pytorch optimizer.

src/accelerate/accelerator.py, tests/test_state_checkpointing.py
Solves https://github.com/huggingface/accelerate/issues/1601 by having `Accelerator.load_state` grab the latest save folder and use it if no filename is passed.
=> Let load_state automatically grab the latest save

src/accelerate/utils/fsdp_utils.py
=> Fix import error when torch>=2.0.1 and torch.distributed is disabled

src/accelerate/utils/modeling.py, tests/test_modeling_utils.py
This PR add support for more flexible control of  memory size such as  "5.0GB, 0.5GB" . 
I also add some code to handle invalid memory size values.
Hope this is useful.
=> add support of float memory size in convert_file_size_to_int

examples/by_feature/fsdp_with_peak_mem_tracking.py, src/accelerate/commands/config/cluster.py, src/accelerate/state.py
This PR is for supporting fsdp plugins with xpu. 
@muellerzr @sgugger
=> Add FSDP for XPU

examples/by_feature/fsdp_with_peak_mem_tracking.py, src/accelerate/commands/config/cluster.py, src/accelerate/state.py, src/accelerate/test_utils/scripts/external_deps/test_peak_memory_usage.py
This PR enables FSDP for NPU. The passed test cases are as follows:
- `test_checkpointing.py`
- `test_peak_memory_usage.py`
- `test_performance.py`(without `DeepSpeed`)
@muellerzr @sgugger
=> Add FSDP for NPU

src/accelerate/utils/launch.py
[ the gpu_ids is not working #1848 ](https://github.com/huggingface/accelerate/issues/1848)
=> Fix the noneffective parameter: gpu_ids (Rel. Issue #1848)

src/accelerate/utils/modeling.py
This PR adds the possibility to load the safetensors checkpoint with just passing the folder containing the checkpoint in `load_checkpoint_in_model`.
=> Loading logic safetensors

src/accelerate/big_modeling.py
Fixes [#25448](https://github.com/huggingface/transformers/issues/25448) from transformers
cc: @sgugger
=> Add env variable for init_on_device

src/accelerate/accelerator.py, src/accelerate/data_loader.py, src/accelerate/utils/operations.py
@muellerzr I got a chance to work on this issue: #1816. Can you please review this PR? Happy to work on any suggestions.
=> support custom slice function in DataLoaderDispatcher

setup.py
This updates the release instructions to the latest (just followed those for v0.22.0 this morning).
=> Update release instructions

docs/source/_toctree.yml, docs/source/usage_guides/model_size_estimator.md
Doc write up on the model memory usage tool as a usage guide, which should help with overall visibility of the tool 🤗
=> Add doc on model memory usage

src/accelerate/utils/dataclasses.py
1. To be in sync with changes in PR https://github.com/huggingface/transformers/pull/25599
=> update import of deepspeed integration from transformers

src/accelerate/accelerator.py, src/accelerate/utils/dataclasses.py, tests/deepspeed/test_deepspeed.py
1. Fixes https://github.com/huggingface/accelerate/issues/1830
=> deepspeed grad_acc_steps fixes

src/accelerate/commands/config/sagemaker.py
=> fix: add debug argument to sagemaker configuration

src/accelerate/utils/imports.py
This is PR following the below issue found in trl.
https://github.com/huggingface/trl/issues/658#issuecomment-1687284028
=> support logging with mlflow in case of mlflow-skinny installed

src/accelerate/utils/dataclasses.py
Exposes auto in `DeepSpeedPlugin` docs and changes the default to `auto` (@pacman100 let me know if we should still keep it as `None`)
@pacman100
=> Expose auto in dataclass

src/accelerate/accelerator.py, src/accelerate/utils/operations.py
As the [comment](https://github.com/huggingface/transformers/pull/25702#discussion_r1313098895) says, we need to reduce the gradient first for XLA when unscaling the gradients in mixed precision training with AMP, and a better implementation is moving this part of the logic to Accelerate. That's why we have this PR :-)
background: https://github.com/huggingface/transformers/pull/25702
Anyone in the community is free to review the PR once the tests have passed.
=> reduce gradient first for XLA when unscaling the gradients in mixed precision training with AMP.

.github/workflows/integration_tests.yml, .github/workflows/self_hosted_integration_tests.yml
With v4.33 being out, time to bring them back and deal with the failures 😬 
@pacman100 @BenjaminBossan
=> Bring back pypi to runners

docs/source/basic_tutorials/notebook.md, src/accelerate/launchers.py, src/accelerate/utils/launch.py
Add num_nodes, master_addr, node_rank as arguments for notebook_launcher in order to support multi-node launching.
=> Support multi-node notebook launching

docs/source/usage_guides/fsdp.md
1. Fixes https://github.com/huggingface/accelerate/issues/1943
=> fix the fsdp docs

src/accelerate/accelerator.py, src/accelerate/utils/other.py, tests/test_accelerator.py
This PR fixes the `save_model` function for safetensors. It was never tested so it had a couple of problems.
=> fix safetensor saving

src/accelerate/accelerator.py, src/accelerate/test_utils/scripts/external_deps/test_metrics.py
#1925 
@muellerzr 
So, I wrote it as simple as I could. This is my first contribution here, so some good points are:
should we extract `check_input` function to a more general function on utils?
should we extract the dedup part for a utils function? I did not found the call mentioned in the issue. Also I'm a little lost as to testing. Did not find unit tests for functions, maybe I missed that. Style passing, and tests passing (without adding new cases).
Looking forward for suggestions and improvements. Thanks in advance.
=> [WIP] Implementing gather_for_metrics with dedup for non tensor objects

src/accelerate/big_modeling.py, tests/test_big_modeling.py
Fixes #1888 by adding a `force_hooks` flag to `dispatch_model` that let's a user ensure that align device hooks will be attached to their model even if all layers are mapped to a single device.
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag members/contributors who may be interested in your PR.
@SunMarc
=> Add `force_hooks` to `dispatch_model`

docs/source/usage_guides/deepspeed.md, docs/source/usage_guides/fsdp.md
1. Updates FSDP and DeepSpeed docs to clarify https://github.com/huggingface/accelerate/issues/1970 and https://github.com/huggingface/accelerate/pull/1947#issuecomment-1712019113
=> update FSDP and DeepSpeed docs

src/accelerate/accelerator.py
Fix for flex: https://github.com/huggingface/transformers/pull/26135
cc @muellerzr
=> Flex fix patch for accelerate

docs/source/_toctree.yml, docs/source/concept_guides/internal_mechanism.md, docs/source/quicktour.md
This PR refactors the Quick tour to make navigating it easier. It does so via rewriting some sections for simpler readability, restructuring the doc, and updating the headers. It also moves the "Internal mechanism" section into a separate conceptual guide.
=> [docs] Quick tour refactor

docs/source/basic_tutorials/launch.md
Adds some basic documentation for multi-node training with 🤗 Accelerate. I've also added a small comment on running code on CPU, which I think is helpful but is not talked about in the tutorials. 
cc @muellerzr
=> Add basic documentation for multi node training

docs/source/usage_guides/fsdp.md
1. Fixes https://github.com/huggingface/accelerate/issues/2025
=> update fsdp docs

src/accelerate/accelerator.py, src/accelerate/checkpointing.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/other.py
Lets `save` and `save_state` rely on a similar system to deepspeed, and to ensure we're not overloading the `Accelerator` with arguments delegating it to the `ProjectConfiguration`
Solves https://github.com/huggingface/accelerate/issues/1950
@BenjaminBossan @pacman100
=> Enable shared file system with `save` and `save_state` via ProjectConfiguration

setup.py
Fix DeepSpeed version to make CI pass, see #2042 for reference.
=> Fix DeepSpeed version to <0.11

setup.py
=> Unpin deepspeed

src/accelerate/utils/modeling.py
=> fix docstring

utils/stale.py
Fixes broken stalebot (ref: https://github.com/huggingface/peft/pull/1016)
@BenjaminBossan @LysandreJik
=> Fix stalebot

docs/source/usage_guides/model_size_estimator.md
Adds the model estimator tool gradio space directly to the docs, and links to "Can You Run It?": https://huggingface.co/spaces/Vokturz/can-it-run-llm
@BenjaminBossan @LysandreJik
=> Add space to docs

src/accelerate/utils/dataclasses.py
When my deepspeed config does not have `train_batch_size `, this error will occur
```
KeyError: 'train_batch_size'
```
=> Fix the error when the "train_batch_size" is absent in DeepSpeed config

tests/deepspeed/test_deepspeed.py
as title.
cc @muellerzr @BenjaminBossan
=> remove unused constants

docs/source/usage_guides/big_modeling.md
There is a typo in the link, which is fixed by this PR.
@muellerzr
=> DOC: Fix broken link to designing a device map

src/accelerate/data_loader.py
=> Fix docstring typo

docs/source/package_reference/cli.md
Doc fix for flag typo
- [ X ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
@pacman100 @muellerzr
=> Fix flag typo

examples/multigpu_remote_launcher.py, src/accelerate/launchers.py
Just fixed a typo in localhost ip address
=> fixed ip address typo

src/accelerate/big_modeling.py
This PR fixes the issue related to the offload warning that was introduced in this [PR](https://github.com/huggingface/accelerate/pull/2075).
=> fix warning when offload

src/accelerate/test_utils/scripts/test_script.py
We changed the logic on when to run a chunk of the code during https://github.com/huggingface/accelerate/pull/2110, but I did not update the test, oops
@SunMarc
=> Fix issue with tests

README.md
Use "and" instead of comma, otherwise you get 
```
Too many commas in name 1 of "Sylvain Gugger, Lysandre Debut, Thomas Wolf, Philipp Schmid, Zachary Mueller, Sourab Mangrulkar, Marc Sun, Benjamin Bossan" for entry sylvain_gugger2022accelerate
```
@muellerzr
=> Use "and" instead of comma in Bibtex citation

src/accelerate/commands/config/cluster.py, src/accelerate/state.py, src/accelerate/utils/launch.py
Deepspeed has exposed support for different backends, including Ascend NPU. This PR make accelerate-deepspeed available on Ascend NPU.
cc @muellerzr @pacman100
=> add DeepSpeed support for NPU

docs/source/concept_guides/big_model_inference.md, docs/source/concept_guides/gradient_synchronization.md, docs/source/usage_guides/distributed_inference.md, docs/source/usage_guides/explore.md, docs/source/usage_guides/megatron_lm.md, docs/source/usage_guides/training_zoo.md, src/accelerate/commands/config/cluster.py
=> [Docs] fix doc typos

.github/workflows/build-docker-images-release.yml, .github/workflows/quality.yml, .github/workflows/stale.yml
Noticed some logs about deprecation in the actions, solves them
@SunMarc
=> Deprecated runner stuff

.github/workflows/build-docker-images-release.yml, .github/workflows/build_docker_images.yml, .github/workflows/nightly.yml, .github/workflows/run_merge_tests.yml, .github/workflows/self_hosted_integration_tests.yml
Reverts huggingface/accelerate#2087
=> Revert "New CI Runners"

docker/accelerate-gpu/Dockerfile
Updates docker image to use latest CUDA version. 
cc @pacman100 still one test failure:
```
FAILED tests/deepspeed/test_deepspeed.py::DeepSpeedConfigIntegration::test_prepare_deepspeed_custom_optimizer_custom_scheduler - AssertionError: False is not true
```
@SunMarc
=> Update docker images

docs/source/concept_guides/big_model_inference.md, docs/source/package_reference/big_modeling.md
=> [Docs] Add doc for cpu/disk offload

tests/deepspeed/test_deepspeed.py
1. Fixes the failing DeepSpeed test in CI.
=> fix the DS failing test

src/accelerate/utils/offload.py
Fixes BFloat16 is not supported on MPS # (2226)
=> fix BFloat16 is not supported on MPS (#2226)

src/accelerate/accelerator.py, tests/deepspeed/test_deepspeed.py
1. Refactors DeepSpeed dataloader prepare logic as per the suggestions in https://github.com/huggingface/accelerate/pull/2207. This should resolve the concern raised in the mentioned PR.
=> refactor deepspeed dataloader prepare logic

setup.py
The latest DVCLive is causing failures on main + nightlies due to a key error. Removing from test reqs until @dberenbaum can take a look. 
@SunMarc
=> Rm DVCLive from test reqs as latest version causes failures

docs/source/usage_guides/fsdp.md, src/accelerate/commands/config/cluster.py, src/accelerate/commands/launch.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/launch.py, tests/fsdp/test_fsdp.py
1. Fixes https://github.com/huggingface/accelerate/issues/2275 and https://github.com/huggingface/accelerate/issues/2273 while being backwards compatible.
=> Improve FSDP config usability

src/accelerate/utils/dataclasses.py
A follow up to https://github.com/huggingface/accelerate/pull/2288 improving language issues.
@pacman100
=> [doc] language fixes

setup.py, src/accelerate/tracking.py, tests/test_tracking.py
Reverts/fixes #2279
@muellerzr PTAL. DVCLive 3.5.1 was released with a fix for this issue.
=> add back dvclive to tests

tests/test_state_checkpointing.py
Part of https://github.com/huggingface/accelerate/issues/2122
=> make test_state_checkpointing device agnostic

docs/source/usage_guides/deepspeed.md, src/accelerate/utils/dataclasses.py
This PR improves Deepspeed bits
- fixes a typo
- expands the doc on auto values for comms related to the fixes in https://github.com/huggingface/accelerate/pull/2295
@pacman100
=> [deepspeed] documentation

docs/source/package_reference/utilities.md
This PR adds a number of items in `accelerate.utils` into the appropriate documentation. 
@SunMarc
=> Add more missing items

src/accelerate/accelerator.py
Currently, if the model doesn't have `model.config` or `model.config.hidden` and auto values are used for comms buffers Accelerate silently ignores the issue and then subsequently fails with:
```
[:0]:    ) = self.accelerator.prepare(
[:0]:  File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/accelerator.py", line 1212, in prepare
[:0]:    result = self._prepare_deepspeed(*args)
[:0]:  File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/accelerator.py", line 1560, in _prepare_deepspeed
[:0]:    deepspeed_plugin.deepspeed_config_process(must_match=False, **config_kwargs)
[:0]:  File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/utils/dataclasses.py", line 754, in deepspeed_config_process
[:0]:    self.deepspeed_config_process(
[:0]:  File …
```
=> [deepspeed] fix setting `auto` values for comm buffers

src/accelerate/accelerator.py, src/accelerate/utils/dataclasses.py, tests/deepspeed/test_deepspeed.py
1. Addresses comments of https://github.com/huggingface/accelerate/pull/2295
=> DeepSpeed refactoring

src/accelerate/data_loader.py
Fixes #2285
The `dataloader.batch_size` is set to `None` in `DataLoader.__init__` if `batch_sampler` is given.
I made the `split_batches` sanity check depend on `dataloader.batch_sampler.batch_size` if `dataloader.batch_size` is `None`
I have pass passed `pytest tests/test_data_loader.py`, `make style` and `make quality` on my linux GPU server.
@muellerzr
=> Fix batch_size sanity check in `prepare_data_loader`

docs/source/basic_tutorials/notebook.md, docs/source/concept_guides/low_precision_training.md, docs/source/package_reference/cli.md, docs/source/package_reference/utilities.md, docs/source/usage_guides/big_modeling.md, docs/source/usage_guides/deepspeed.md, docs/source/usage_guides/fsdp.md, docs/source/usage_guides/low_precision_training.md, docs/source/usage_guides/megatron_lm.md
Fixes all the typos of the readme files in the docs folder
Fixed typos in the following files:
1. `docs/source/basic_tutorials/notebook.md`
1. `docs/source/concept_guides/low_precision_training.md`
1. `docs/source/package_reference/cli.md`
1. `docs/source/package_reference/utilities.md`
1. `docs/source/usage_guides/big_modeling.md`
1. `docs/source/usage_guides/deepspeed.md`
1. `docs/source/usage_guides/fsdp.md`
1. `docs/source/usage_guides/low_precision_training.md`
1. `docs/source/usage_guides/megatron_lm.md`
[here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specific …
=> Fixed typos in readme files of docs folder.

tests/test_accelerator.py, tests/test_multigpu.py
=> device agnostic test_accelerator/test_multigpu

tests/test_big_modeling.py
Running on T4 GPU now passes for me
```
CUDA_VISIBLE_DEVICES="0" pytest tests/test_big_modeling.py -k "test_dispatch" -s -vvvvv
```
Note: using torch 2.1.2 with CUDA 12+ and NOT running tests in parallel, maybe can still fail otherwise, let's see
=> Fix dispatch_model with tied weights test on T4

src/accelerate/hooks.py
Introduced in https://github.com/huggingface/accelerate/pull/2330 but it is quite unnecessary
The test
```
FAILED tests/test_accelerator.py::AcceleratorTester::test_accelerator_bnb_cpu_error - TypeError: init_hook() got an unexpected keyword argument 'tied_params_map'
```
now passes
=> Remove init_hook_kwargs

tests/test_optimizer.py
Part of https://github.com/huggingface/accelerate/issues/2122
cc @muellerzr
=> device agnostic optimizer testing

src/accelerate/big_modeling.py
=> Adding `requires_grad` to `kwargs` when registering empty parameters.

src/accelerate/test_utils/__init__.py, src/accelerate/test_utils/testing.py, src/accelerate/utils/operations.py, tests/test_cli.py, tests/test_grad_sync.py, tests/test_kwargs_handlers.py, tests/test_memory_utils.py
Part of #2122 
@muellerzr @statelesshz
=> device agnostic cli/data_loader/grad_sync/kwargs_handlers/memory_utils testing

setup.py
Revert #2394 as torch 2.2 (with corresponding torchvision/torchaudio) works now in `transformers` and we will unpin those - however, this requires `accelerate` to unpin too) 🙏
=> [don't merge yet] unpin torch

setup.py
Reverts huggingface/accelerate#2406
=> Revert "[don't merge yet] unpin torch"

examples/README.md
Clarification of the activateEnviroment.sh script in the examples working on a cluster with Slurm&Enviroment Modules
Clarification of the activateEnviroment.sh script in the examples working on a cluster with Slurm&Enviroment Modules
Fixes #2370
cc @muellerzr
=> Added activateEnviroment.sh to readme

examples/by_feature/local_sgd.py, src/accelerate/local_sgd.py
=> Adding Local SGD support for NPU

setup.py
=> Unpin torch

tests/test_multigpu.py
=> Include pippy_file_path

src/accelerate/accelerator.py, src/accelerate/state.py
Solves https://github.com/huggingface/transformers/issues/29042 by allowing `xm.mark_step` to occur if we're running on XLA specifically. 
@SunMarc
=> Use grad-accum on TPU

docs/source/_toctree.yml
Separate training and inference docs for easier navigation.
=> [docs] Divide training and inference

src/accelerate/utils/launch.py
=> fix typo in launch.py (`----main_process_port` to `--main_process_port`)

src/accelerate/state.py, src/accelerate/test_utils/scripts/test_script.py
make `split_between_processes` handle a `datasets.Dataset`
Fixes https://github.com/huggingface/accelerate/issues/2220
=> split_between_processes for Dataset

.github/workflows/test.yml
Tired of installs failing on PR ci, due to hitting it so often. We can maybe look at docker images or something but UV can't handle our 10 workers running at once
@BenjaminBossan (merge after review please 🙏 )
=> Rm uv install

src/accelerate/commands/launch.py
Deepspeed allows for configuring the deepspeed env file it uses through https://github.com/microsoft/DeepSpeed/pull/4006.
A user must set `DS_ENV_FILE` to configure it.
This PR upstreams this
@pacman100
=> Allow for custom deepspeed env files

src/accelerate/data_loader.py, src/accelerate/test_utils/scripts/test_script.py, tests/test_data_loader.py
This pull request addresses an oversight in the current implementation of `prepare_data_loader` function, related to the assignment of `SeedableRandomSampler` within nested sampler structures. Specifically, when employing `BatchSamplerShard`, it is possible for its encapsulated `batch_sampler` to possess its own sampler. The existing codebase does not account for this potential nesting, failing to apply `SeedableRandomSampler` to the innermost sampler when it is of type `RandomSampler`. This adjustment ensures consistent and expected behavior across all sampler layers, promoting enhanced control and predictability in sample selection processes.
Fixes #2574
to it if that's the case. **The 7th comment of [this …
=> Update data_loader.py to Ensure Reproducibility in Multi-Process Environments with Dataloader Shuffle

src/accelerate/commands/estimate.py, tests/test_cli.py
This PR, while on the surface changes no values, will work towards improving the estimator tool by allowing us to explicitly state the various types of memory one could expect. 
Specifically we can now differentiate on the four memory workloads during training:
1. Model + Optimizer
2. Gradients
3. Backward pass
4. Optimizer step
@SunMarc
=> Refactor and improve model estimator tool

src/accelerate/data_loader.py, src/accelerate/tracking.py, src/accelerate/utils/deepspeed.py, src/accelerate/utils/megatron_lm.py, src/accelerate/utils/operations.py
Fixes the format of the `kwargs` docstrings.
=> [docs] Fix kwarg docstring

src/accelerate/utils/modeling.py
As per title, small typo in https://github.com/huggingface/accelerate/pull/2588
=> Fix warning log for unused checkpoint keys

setup.py
Pins the hub for the time being while our CI fails. Relevant slack message: https://huggingface.slack.com/archives/C02V5EA0A95/p1712064349607939
@SunMarc
=> Pin hub for tests

src/accelerate/commands/estimate.py
For some reason, this is needed now and having `None` no longer works
Fixes some of the failing tests
@SunMarc
=> Default false for trust_remote_code

examples/inference/llama.py, tests/test_examples.py
This PR fixes the llama example for pippy. I removed the llama test since we are unable to download the gated model.
Fixes https://github.com/huggingface/accelerate/issues/2575
=> fix llama example for pippy

docs/source/quicktour.md
Fixes some links in the quicktour docs that were redirecting bad
@SunMarc
=> Fix links in Quick Tour

src/accelerate/commands/env.py
This PR adds some more information to `accelerate env` to help with knowing *what* `accelerate launch` is being ran, to help solve issues like https://github.com/huggingface/accelerate/issues/2622 faster
For example, here is the new output:
```
Copy-and-paste the text below in your GitHub issue
- `Accelerate` version: 0.29.0.dev0
- Platform: Linux-6.5.0-25-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /home/zach/miniconda3/envs/accelerate/bin/accelerate
- Python version: 3.9.15
- Numpy version: 1.24.0
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 62.50 GB
- GPU type: NVIDIA GeForce RTX 3070 Laptop GPU
- `Accelerate` default config:
- compute_environment: LOCAL_MACHINE
- …
```
=> Link to bash in env reporting

tests/test_big_modeling.py, tests/test_hooks.py, tests/test_utils.py
part of https://github.com/huggingface/accelerate/pull/2602#issue-2217828783
=> device agnostic testing for hooks&utils&big_modeling

docs/source/usage_guides/tracking.md
=> Docs fix for using internal trackers

src/accelerate/utils/modeling.py
This test is to test the change in the memory size occupied by model loading when low_cpu_mem_usage is used. Therefore, the default device used is cpu. However, when judging whether other devices are available, for example xpu, new packages ipex will be introduced, causing memory changes and interfering with the test results.
Fix the test_from_pretrained_low_cpu_mem_usage_measured failure when ipex is installed.
```
pytest tests/test_modeling_utils.py::ModelUtilsTest::test_from_pretrained_low_cpu_mem_usage_measured
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.9.18, pytest-7.4.4, pluggy-1.3.0
rootdir: …
```
=> Fix test_from_pretrained_low_cpu_mem_usage_measured failure

src/accelerate/utils/random.py
This PR adds a (probably) missing `torch.mlu.set_rng_state` to ensure sync rng state is set correctly.
I don't have a suitable MLU environment to checkout whether this method `torch.mlu.set_rng_state` really exists, but I believe it's meaningless to synchronize rng state without re-set it :)
cc @muellerzr
=> Add MLU rng state setter

src/accelerate/state.py
Reverts huggingface/accelerate#2652
=> Revert "fix backend check"

tests/deepspeed/test_deepspeed.py
1. Fix deepspeed moe test with version check
=> Fix deepspeed moe test with version check

setup.py
Another patch release DeepSpeed issue... pins it again...
Fixes failing tests on main
@pacman100
=> Pin DS...again..

src/accelerate/test_utils/scripts/test_distributed_data_loop.py
=> Simplify test logic

manim_animations/big_model_inference/stage_1.py, manim_animations/dataloaders/stage_0.py, manim_animations/dataloaders/stage_1.py, manim_animations/dataloaders/stage_2.py, manim_animations/dataloaders/stage_3.py, manim_animations/dataloaders/stage_4.py, manim_animations/dataloaders/stage_5.py, manim_animations/dataloaders/stage_6.py, manim_animations/dataloaders/stage_7.py
Adds source code for the new manim animation going live on 4/23/2024
@SunMarc
=> Add source code for DataLoader Animation

src/accelerate/utils/dataclasses.py, tests/deepspeed/test_deepspeed.py
1. Add version checks for the import of DeepSpeed moe utils.
=> Add version checks for the import of DeepSpeed moe utils

setup.py
We need diffusers as a test dep with the new examples.
@SunMarc
=> Add diffusers to req

src/accelerate/data_loader.py
This PR fixes a bug that this [PR](https://github.com/huggingface/accelerate/pull/2723) introduced. I removed a line by mistake. The failing test pass with this PR.
=> Fix sampler failing test

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml
This PR fixes the docbuilder workflow. 
cc @mishig25  @Wauplin
=> Docs: Fix build main documentation

src/accelerate/commands/config/cluster.py
Fixes https://github.com/huggingface/accelerate/issues/2747
cc @@muellerzr
=> Fixed the problem of incorrect conditional judgment statement when configuring enable_cpu_affinity

src/accelerate/utils/modeling.py
#What does this PR do ?
This PR fixes a bug that was introduced in this [PR](https://github.com/huggingface/accelerate/pull/2681). max_memory is a dict so that can't use append 🤦. I've checked that this should fix the failing CI.
=> Fix max_memory assignment

src/accelerate/accelerator.py
Fixes https://github.com/huggingface/accelerate/issues/2766
=> fix minor typo

src/accelerate/commands/config/cluster.py, src/accelerate/utils/launch.py
The fsdp_activation_checkpointing config does not currently take effect. The fsdp_plugin still get `fsdp_activation_checkpointing = False` for the following config
```
fsdp_config:                                                                                                                        
fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP                                                                                     
fsdp_backward_prefetch: BACKWARD_PRE                                                                                              
fsdp_cpu_ram_efficient_loading: true                                                                                              
fsdp_forward_prefetch: false …
```
=> Enable config for fsdp activation checkpointing

src/accelerate/commands/launch.py
Fixes failing test introduced in https://github.com/huggingface/accelerate/pull/2779
TL;DR needed to also be a CLI argument :)
@SunMarc
=> Add arg from CLI to fix failing test

src/accelerate/state.py, src/accelerate/test_utils/scripts/test_script.py
=> fix duplicate elements in split_between_processes

src/accelerate/accelerator.py
=> Fix type in accelerator.py

src/accelerate/utils/modeling.py
Supersedes https://github.com/huggingface/accelerate/pull/2743
Fixes https://github.com/huggingface/accelerate/issues/2742
=> 4-bit quantization meta device bias loading bug

tests/test_accelerator.py
This PR fixes a test that was missing a cuda dependency from this [PR](https://github.com/huggingface/accelerate/pull/2619).
=> add cuda dep for a test

src/accelerate/commands/launch.py, src/accelerate/test_utils/testing.py
Aligns accelerate <-> torch args for monitor interval, as confirmed here: https://github.com/pytorch/pytorch/pull/124692
h/t to @BenjaminBossan for confirming for us
cc @stas00, should just be OOTB faster now
=> monitor-interval, take 2

docs/source/usage_guides/megatron_lm.md, src/accelerate/accelerator.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/imports.py, src/accelerate/utils/megatron_lm.py
Optimize the megatron plugin, and make the megatron's version to r0.5.0.
https://github.com/huggingface/accelerate/pull/2501#issuecomment-2126931526
https://github.com/huggingface/accelerate/issues/2390#issuecomment-2136834517
=> Optimize the megatron plugin

src/accelerate/accelerator.py, src/accelerate/state.py
=> fix fstr format

README.md
=> Remove underlines between badges

src/accelerate/big_modeling.py
Hey team, I've made a small fix in the `dispatch_model` function . Updated `logging.warning("xxx")` to `logger.warning("xxx")` for consistent logging practices throughout the codebase. I believe this was a minor typo.
Additionally, this is the only similar issue I've found throughout the entire project.
=> Refactor logging to use logger in `dispatch_model`

setup.py
<s>We've found out who didn't prepare for numpy v2.0.0: `wandb` :)</s>
Jk it's deepspeed, numpy, and a few more. We'll pin for now sadly 😢 
@SunMarc
=> Potentially fix tests

src/accelerate/commands/config/config_utils.py, src/accelerate/utils/dataclasses.py
This PR introduces the [TorchDynamo integration with PyTorch XLA](https://github.com/pytorch/xla/blob/r2.0/docs/dynamo.md). Though I haven't thorougly benchmarked the code, it works on the [CLM example](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py) from the Transformers library, when spawned using the `accelerate launch` command on a v5e TPU VM with 8 TPUs running on Ubuntu 22.04. It also passes all tests I ran on the TPU. 
Fixes #2870 
Anyone in the community is …
=> Add XLA Dynamo backends for training and inference

tests/test_modeling_utils.py
Fix the bug introduced in #https://github.com/huggingface/accelerate/pull/2879/files. I reverted the change I made in that PR because once our PyTorch PR is merged, it will work. 
@muellerzr
=> [tests] fix bug in torch_device

src/accelerate/utils/megatron_lm.py, tests/test_imports.py
Import tests are failing on main, seems to be from an external library, best I could find different/slow is the transformers import. 
We'll see what this shows however.
I've also tweaked the threshold to give us a few more datapoints in the tree. 
@SunMarc
=> Fix import test

src/accelerate/utils/imports.py
This PR will enable detection of the `pynvml` package when installed via [`nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py/).
@muellerzr
=> Consider pynvml available when installed through the nvidia-ml-py distribution

tests/test_accelerator.py
As discussed on Slack, this PR is intended to improve the reliability of a flaky unit test in `accelerate/tests/test_accelerator.py` @ `AcceleratorTester.test_free_memory_dereferences_prepared_components`.
@muellerzr
=> Improve test reliability for Accelerator.free_memory()

.github/workflows/integration_tests.yml, .github/workflows/quality.yml, .github/workflows/stale.yml, .github/workflows/test.yml, .github/workflows/test_imports.yml
This PR aims to enable `pip` caching in CI thereby enabling faster CI times.
Request for Review: @muellerzr
=> feat(ci): add `pip` caching in CI

docs/source/concept_guides/low_precision_training.md, docs/source/usage_guides/deepspeed.md, docs/source/usage_guides/fsdp.md, docs/source/usage_guides/low_precision_training.md
Some links in the docs were broken because the url ended in .md
@muellerzr
=> remove .md to allow proper linking

src/accelerate/accelerator.py
Fixes bug of clip_grad_norm_ for xla fsdp.
=> Fix bug of clip_grad_norm_ for xla fsdp

src/accelerate/commands/estimate.py, tests/test_cli.py
`huggingface_hub` swapped to a new error raising... need to adjust
@SunMarc
=> Fix gated test

setup.py, src/accelerate/__init__.py
=> update version to 0.34.dev0

src/accelerate/accelerator.py
is_msamp_available -> is_te_available.
(My env has both hence wasn't flagged)
=> Wrong import check for TE

benchmarks/fp8/fp8_utils.py
Santosh noted that I missed a declaration for `references` when running on single GPU, fixes it
=> Fix fp8 benchmark on single GPU

src/accelerate/data_loader.py
Fix three typos in src/accelerate/data_loader.py
Fix three typos in src/accelerate/data_loader.py
Fixes https://github.com/huggingface/accelerate/issues/3081
=> Fix three typos in src/accelerate/data_loader.py

tests/test_examples.py
Removes t5 pippy test, since it's no longer applicable
@SunMarc
=> No more t5

src/accelerate/test_utils/scripts/test_sync.py
Should be the last fix needed (but isn't really needed for the pre-release), last sneaky parts of the deprecation
Fixes main
@SunMarc
=> Fixup test_sync w/ deprecated stuff

src/accelerate/launchers.py, src/accelerate/utils/dataclasses.py
This PR deprecates TPU distributed type and we switch to XLA since we are moving to v1. 
Fixes https://github.com/huggingface/accelerate/issues/3115
cc @muellerzr for vis
=> Switch to XLA instead of TPU

docs/source/usage_guides/big_modeling.md
fix typo in docs
- Documentation: @muellerzr
=> fix tip brackets typo

src/accelerate/utils/dataclasses.py, tests/deepspeed/test_deepspeed.py
@stas00 discovered that because we constantly create the transformers weakref (not just under zero3 now), we need to always set the "auto" values (such as batch size etc) if passed in by the user. Else we can hit an issue where it's still set as `'auto'` and DS will yell at us:
```python
stderr: [rank0]: Traceback (most recent call last):
stderr: [rank0]:   File "/root/dawn/dawn/train/causal/run.py", line 83, in <module>
stderr: [rank0]:     model = getattr(model_class, from_config)(
stderr: [rank0]:   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 440, in from_config
stderr: [rank0]:     return model_class._from_config(config, **kwargs)
stderr: [rank0]:   File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line …
```
=> Fixup DS issue with weakref

tests/deepspeed/test_deepspeed_multiple_model.py
As part of fixing the auto parts, the values in the plugin need to be adjusted to their non-auto parts (aka set to 1 and a value dropped). 
Eventually Stas and I discussed adding a util to auto-fix these after the values have been adjusted (or a util). For now this is manual though (and is a known manual thing)
@SunMarc
=> DS fix, continued

tests/deepspeed/test_deepspeed.py
Test introduced in https://github.com/huggingface/accelerate/pull/3069 is not working and is failing in trunk CI.
This PR remove them and maybe try to add some working test.
Feel free to close this if you want to replace this with a working test @SunMarc
=> Remove broken dynamo test

.github/workflows/integration_tests.yml, .github/workflows/quality.yml, .github/workflows/stale.yml, .github/workflows/test.yml, .github/workflows/test_imports.yml, docker/accelerate-cpu/Dockerfile, setup.py
Updates our failing tests by bringing in python 3.9 as a minimum! 
@SunMarc
=> 🚨 🚨 🚨 Goodbye Python 3.8! 🚨 🚨 🚨 

src/accelerate/utils/modeling.py
I noticed that the minimum version of `safetensors` that `accelerate` depends on is `0.4.3` https://github.com/huggingface/accelerate/blob/ba7ab93f5e688466ea56908ea3b056fae2f9a023/setup.py#L80
cc @muellerzr
=> eliminate dead code

src/accelerate/big_modeling.py
=> typo fix in big_modeling.py

docs/source/usage_guides/tracking.md, src/accelerate/accelerator.py
This PR is to fix 1 typo and 1 bug in the example code. 
@muellerzr
=> [docs] update code in tracking documentation 

examples/by_feature/megatron_lm_gpt_pretraining.py
=> Fix: Resolve #3257

docs/source/concept_guides/deferring_execution.md
Small typo fix in the title 
@muellerzr
=> [docs] fix typo

docs/source/basic_tutorials/migration.md, docs/source/basic_tutorials/notebook.md, docs/source/usage_guides/quantization.md, docs/source/usage_guides/tracking.md
Fixes typos in the following docs:
- Minor typos
- **Add Accelerate to your code**
- **Launching distributed training from Jupyter Notebooks**
- **Model quantization**
- Incorrect code examples & minor typos
- **Experiment trackers**
@muellerzr
=> Fixed multiple typos for Tutorials and Guides docs

docs/source/usage_guides/big_modeling.md
This PR adds xpu besides cuda and replaces the hard-coded cuda with device-agnostic device. 
@muellerzr
=> [docs] no hard-coding cuda

.github/workflows/build_docker_images.yml
We migrated the path for the FP8 docker image, the workflow needed to be updated
@SunMarc
=> Fixup docker build err

src/accelerate/utils/dataclasses.py
=> [docs] fix typo, change "backoff_filter" to "backoff_factor"

Makefile, setup.py
Consolidates the most annoying part of this workflow to `make prepare_release`
@SunMarc
=> [Dev] Update release directions

src/accelerate/commands/launch.py, src/accelerate/commands/utils.py, tests/test_cli.py, tests/test_configs/validate_launch_cmd.yaml
Reapply this PR (https://github.com/huggingface/accelerate/pull/2757) with some fixes.
@muellerzr @lain-S
=> fix: ensure CLI args take precedence over config file.

examples/inference/distributed/llava_next_video.py
Add distributed inference example for LLaVA-NeXT-Video-7B-hf. Changes were already approved but staled: https://github.com/huggingface/accelerate/pull/3179
to it if that's the case. Link: https://github.com/huggingface/accelerate/issues/3078
@muellerzr @a-r-r-o-w @SunMarc
=> Distributed inference example for llava_next

src/accelerate/data_loader.py, src/accelerate/test_utils/testing.py
Fixes an issue caused by https://github.com/huggingface/accelerate/pull/3420 where said code only works if we're on torch 2.6+. Used a `hasattr` check instead here to make it work. 
Fixes https://github.com/huggingface/accelerate/issues/3438
(Did a new PR since the old one had outdated main).
I'll do a secondary patch with these fixes once merged
@SunMarc @BenjaminBossan …
=> Fix prod issues

src/accelerate/accelerator.py
This PR fixes https://github.com/huggingface/accelerate/pull/3390#issuecomment-2722005648. deepspeed_config don't necessarily have the `tensor_parallel` key
=> Fix attribute issue with deepspeed tp

src/accelerate/utils/ao.py
We modified how we pass in the layers but I didn't actually update the call in the case of the default being used
@SunMarc
cc @s1ro1
=> Fixup ao module filter func

src/accelerate/accelerator.py
Fixes a small bug in `clip_grad_norm` that was introduced in #3394.
cc @muellerzr
=> Fix: clip grad norm in fsdp2

tests/test_big_modeling.py
From PyTorch 2.5.0, we don't need platform-dependent OutOfMemoryError API, there is a unified one `torch.OutOfMemoryError`.
=> use device agnostic torch.OutOfMemoryError from pytorch 2.5.0

.github/workflows/pr_style_bot.yml
Adds @sayakpaul's style bot to the accelerate repo. 
To run, in a PR call `@bot /style`
@sayakpaul @SunMarc @ydshieh
=> Adds style bot

src/accelerate/commands/merge.py
straightforward
@SunMarc @zach-huggingface
=> [bug] unsafe_serialization option in "merge-weights" doesn't work

src/accelerate/commands/config/cluster.py, src/accelerate/commands/config/config_utils.py
=> Add the HPU into accelerate config

src/accelerate/optimizer.py, src/accelerate/state.py
PyTorch/XLA has deprecated bunch of APIs (https://github.com/pytorch/xla/issues/8915) for the upcoming 2.7 release. This PR integrates the change into accelerate package.
=> Remove deprecated PyTorch/XLA APIs

src/accelerate/utils/fsdp_utils.py
This PR fixes three issues in FSDP2's wrap policy and mixed precision preparations.
@SunMarc @zach-huggingface @S1ro1
=> [FSDP2] Issues in Wrap Policy and Mixed Precision

docker/accelerate-gpu-deepspeed/Dockerfile, docker/accelerate-gpu/Dockerfile
This PR updates the Dockerfiles which are used to for CI purposes. In CI, we're now testing against PyTorch 2.7.0 with its default CUDA 12.6 build. In order to align with this, we will now start with the CUDA 12.6.3 image, on Ubuntu 22.04.
to it if that's the case. 
[Internal Slack discussion](https://huggingface.slack.com/archives/C04N7QL0KBL/p1745489417967679)
@SunMarc @BenjaminBossan
=> Update Docker builds to align with CI requirements

src/accelerate/utils/fsdp_utils.py
Sometimes, the infer logic fails when we use LORA, this fixes it
See mentioned PR in trl for *test*
=> [FSDP2] Fix: "..." is not a buffer or a paremeter

src/accelerate/data_loader.py
When training for multiple epochs, the set_epoch defined in the Sampler does not work because set_epoch in DataLoaderShard is missing a further level call.
@SunMarc @zach-huggingface
=> Fix the issue where `set_epoch` does not take effect.

src/accelerate/utils/bnb.py
@SunMarc @faaany , pls help review, thx.
=> simplify model.to logic

src/accelerate/commands/env.py
@SunMarc, pls help review, thx very much.
=> tune env command output

docs/source/usage_guides/compilation.md, docs/source/usage_guides/gaudi.md, src/accelerate/commands/config/cluster.py, src/accelerate/commands/config/sagemaker.py, src/accelerate/commands/launch.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/launch.py, src/accelerate/utils/other.py, tests/test_launch.py
This is to allow enabling regional compilation without passing TorchDynamoPlugin in (Gaudi)Trainer.
@regisss I also added a section in gaudi docs wdyt ?
This PR allows us to further slim down the custom accelerator in optimum-habana https://github.com/huggingface/optimum-habana/pull/1979
=> Add regional compilation to cli tools and env vars

src/accelerate/utils/fsdp_utils.py
=> reenable FSDP2+qlora support

src/accelerate/state.py, src/accelerate/test_utils/scripts/test_script.py
same PR as last time added test 
```python
from accelerate import PartialState
from accelerate.utils import gather_object
import os
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
print(f"Number of CUDA devices: {torch.cuda.device_count()}")
print(f"Current CUDA device: {torch.cuda.current_device()}")
print(f"CUDA device name: {torch.cuda.get_device_name()}")
distributed_state = PartialState()
prompts = [str(i) for i in range(4)]  # ["0", "1", "2", "3"]
batch_size = 2
tokenized_prompts = [prompts[i : i + batch_size] for i in range(0, len(prompts), batch_size)]
completions_per_process = []
with distributed_state.split_between_processes(tokenized_prompts, apply_padding=True) as batched_prompts:
for batch in batched_prompts:
generated_text = …
```
=> Fix prevent duplicate GPU usage in distributed processing

tests/test_load_checkpoint_and_dispatch_with_broadcast.py
All 3 cases passed, @SunMarc , pls help review, thx.
=> enable test_load_checkpoint_and_dispatch_with_broadcast cases on XPU

examples/inference/pippy/bert.py, examples/inference/pippy/gpt2.py, src/accelerate/test_utils/scripts/test_cli.py, src/accelerate/utils/memory.py, tests/test_cli.py, tests/test_examples.py
all passed. @SunMarc , pls help review, thx very much.
=> enable test_cli & test_example cases on XPU

benchmarks/torch.compile/regional_compilation.py
@SunMarc @IlyasMoutawwakil , pls help review.
XPU shows similar trends w/ CUDA, like
=> enable regional_compilation benchmark on xpu

src/accelerate/checkpointing.py, src/accelerate/optimizer.py, src/accelerate/utils/dataclasses.py, src/accelerate/utils/imports.py
@SunMarc @IlyasMoutawwakil , pls help review, thx.
=> add device-agnostic GradScaler

benchmarks/fsdp2/main.py, benchmarks/fsdp2/measure_utils.py, benchmarks/fsdp2/utils.py
@SunMarc @IlyasMoutawwakil , pls help review and comment, thx very much.
=> enable fsdp2 benchmark on XPU

src/accelerate/utils/transformer_engine.py
=> Fix missing te.LayerNorm in intel_transformer_engine

src/accelerate/utils/fsdp_utils.py
`device_type` is accessible from device mesh
=> Remove hardcoded cuda from fsdpv2

src/accelerate/accelerator.py
Syncs the gradient_accumulation_steps from the deepspeed plugin to the GradientAccumulationPlugin
=> [DeepSpeed] sync gradient accum steps from deepspeed plugin

src/accelerate/data_loader.py
I've make a typo in this [PR](https://github.com/huggingface/accelerate/pull/3635#issuecomment-2990330360). Fixing this here.
=> [typo] shards instead of shard 

examples/fsdp2/README.md
- Fix typo in the fsdp2-fp8 example 
@SunMarc @zach-huggingface
=> Fix fsdp2 example typo

src/accelerate/utils/memory.py, tests/test_memory_utils.py
Supersedes [3650](https://github.com/huggingface/accelerate/pull/3650) to trigger the github actions
=> “Stop Halving My Batch!” · Default back-off 0.5 → 0.9

src/accelerate/accelerator.py, src/accelerate/data_loader.py
`submesh_tp_size` wasn't initialized before, so if I'm manually handling device meshes, this would trigger a local variable error.
@SunMarc @S1ro1 
=> set default submesh_tp_size to prevent unset local variable error

tests/fsdp/test_fsdp.py
=> TST Add test for FSDP ignored_modules as str

examples/config_yaml_templates/deepspeed.yaml, examples/config_yaml_templates/fsdp.yaml, examples/config_yaml_templates/multi_xpu.yaml, examples/config_yaml_templates/single_accelerator.yaml, examples/nlp_example.py, src/accelerate/utils/operations.py
1. xpu INT64 all_gather issue fixed in 2.9(reported by this PR https://github.com/huggingface/accelerate/pull/3563,validated in pytorch 0902 nightly wheel), so skip the WA since 2.9
2. validated config_yamls on XPU
@SunMarc , pls help review, thx very much.
=> xpu INT64 all_gather issue fixed in 2.9

src/accelerate/accelerator.py
=> fix: specify device for process_tensor in example usage

src/accelerate/utils/imports.py
Importing `torch_npu` may fail in some envs (e.g. inside cpu-only container with torch-npu installed)
Fixes #3754 
=> fix: torch_npu import error in some envs
